### ISSUE TITLE
Service Binding

### ISSUE THREAD

**Issue by ImSingee** [cloudflare/wrangler2#1004]
Is there any way to set up a service binding? I tried in website but it told me to setup in wrangler, however I can't find any related things in both the wrangler document and code base.

https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/

https://blog.cloudflare.com/service-bindings-ga/

**Comment by ImSingee** [comment]
I found the undocumented `[experimental_services]` and `[[unsafe.bindings]]`, it works well!

Looking forward to an non-experimental config👀

**Comment by threepointone** [comment]
Hello! We're working on service bindings integration in wrangler at the moment, you can follow the PR here https://github.com/cloudflare/wrangler2/issues/1004 Please pay attention to the "Current critical drawbacks" section. 

Closing this issue, but happy to discuss further.
