### ISSUE TITLE
[Pages] Ability to delete branch when using direct-uploads

### ISSUE THREAD

**Issue by bardouni** [cloudflare/wrangler2#1007]
When deploying to a pages project using direct-uploads and --branch argument, U can't delete that deployment/branch from the project as it shows this error:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/11160251/168442954-9db72898-2d40-4572-9ce0-d03bade351e5.png">

**Comment by GregBrimble** [comment]
Hi @bardouni ,

This is a feature request for the Pages product rather than an issue with wrangler. I'll close this issue and pass on your request to the team, but in the future, please send feature requests to #feature-suggestions in [Discord](https://discord.gg/cloudflaredev).

**Comment by bardouni** [comment]
Got it, thanks
