### ISSUE TITLE
implement `--polyfill-node` / `config.polyfill_node`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#101]
Lots of libraries in the ecosystem assume a node.js environment. Those modules just aren't available in Workers, but some can be polyfilled (e.g - `path`, `url`, etc). I made an attempt at landing this in https://github.com/cloudflare/wrangler2/pull/72, but removed it in https://github.com/cloudflare/wrangler2/pull/100 because the polyfills are made for the browser, not Workers (eg - the `http` polyfill assumes the presence of `XMLHTTPRequest`). Some polyfills just don't exist (eg - `crypto`). It's all quite bad really, and it's not good enough even as a prototype. 

So this issue tracks the proper implementation of this feature. We'll have to implement some of them scratch, and have proper messaging around the ones that do get used.

**Comment by mangs** [comment]
I had an interesting thought, not sure if this is useful or not. Workers APIs seem to follow much more closely to modern browser APIs than Node.js ones which got me thinking of Deno (which also does so) and how it would be nice if wrangler could have its own built-in runtime with said polyfills. Then I remembered the [`deno compile` command](https://deno.land/manual/tools/compiler) wherein you could essentially build a custom runtime into its own executable then ship it as part of `wrangler2` perhaps? A zero additional dependency way to emulate workers would be great (not having to also have Node.js installed)

**Comment by mangs** [comment]
Wow. I'm so looking forward to having an open-sourced Workers runtime and trying it with wrangler2. Great job to everyone at Cloudflare and beyond who made that happen!!

**Comment by threepointone** [comment]
We landed initial support for this in 2.0 (as `config.node_compat` / `--node-compat`). We'll continue working on this, and file fresh issues for it. Closing this one. Personally very excited about this myself!
