### ISSUE TITLE
Wrangler fails to publish a folder to pages

### ISSUE THREAD

**Issue by bardouni** [cloudflare/wrangler2#1015]
Fails with this error, btw, it was working fine before.

Select an account from below:
❯ ****

✘ [ERROR] fetch failed

If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
🌎  Uploading... (10/36)

**Comment by GregBrimble** [comment]
Likely a dupe of #960 , but we'll take a look, thank you!

**Comment by bardouni** [comment]
@GregBrimble I don't think so.
I just found that my issue only happens in slow networks.
i can publish using 4g but not able on ADSL.

**Comment by bardouni** [comment]
I'm kind of sure that it's a network issue
4G upload speed is >= 2 Mbps
ADSL ~= 0.6 Mbps
I repeated the process multiple times on both networks and always get the same results, works on 4G and fails on ADSL.
Thank you

**Comment by GregBrimble** [comment]
Ah, okay, we'll add retries and a better error message for client disconnections. That'll hopefully help in most cases.

**Comment by martinfojtik** [comment]
@bardouni my upload speed is around 16 Mbps, but I can not upload files. I'm trying to upload almost 260 files the size of my files is between 4K and 500K.

**Comment by martinfojtik** [comment]
Is there any way how find out which files fail to fetch? Is there an option to show more debug information?

**Comment by sidharthachatterjee** [comment]
Hey @martinfojtik 

Can you perhaps try `wrangler@2.0.7`? We rewrote much of this to use bulk uploads instead of uploading a file at a time and I suppose that will affect what you're seeing. Let me know if it fixes it? 

Cheers.

**Comment by bardouni** [comment]
This was fixed for me in the latest versions.
