### ISSUE TITLE
🐛 BUG: `wranglerjs-compat-webpack-plugin` not published?

### ISSUE THREAD

**Issue by psyked** [cloudflare/wrangler2#1020]
### What version of `Wrangler` are you using?

2.0.5

### What operating system are you using?

Mac

### Describe the Bug

I am trying to migrate my existing config to Wrangler 2, using the `wranglerjs-compat-webpack-plugin` package for compatibility. However the published `wranglerjs-compat-webpack-plugin` appears to be empty - the published package only contains the following information:

```json
{
  "name": "wranglerjs-compat-webpack-plugin",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by threepointone** [comment]
Oops sorry about that!

**Comment by threepointone** [comment]
This is now published, let me know if you face any issues!
