### ISSUE TITLE
🐛 BUG: SSL/HTTPS issues and websocket issue with wrangler dev

### ISSUE THREAD

**Issue by pbowyer** [cloudflare/wrangler2#1021]
### What version of `Wrangler` are you using?

2.0.5

### What operating system are you using?

Windows 10 Professional 64-bit

### What browser opens the URLs below?
Google Chrome 101.0.4951.54 (Official Build) (64-bit)

### Describe the Bug

When I create a new TypeScript project using `wrangler init` project and run `wrangler dev` it defaults to using `https://localhost` for the oAuth callback.

Editing the browser URL to `http://127.0.0.1` made authentication work. But now when I do `wrangler dev` and open a browser it's back to using HTTPS, even if I use `--local-protocol`:

```
wrangler dev --local-protocol http
 ⛅️ wrangler 2.0.5
-------------------
Select an account from below:
...
⬣ Listening at http://localhost:8787
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn on local mode, [c] clear console, [x] to exit                   │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
Pressing *b* opens https://localhost:8787/, and pressing *d* opens https://built-devtools.pages.dev/js_app?experiments=true&v8only=true&ws=localhost:9229/ws and I cannot get past 
![image](https://user-images.githubusercontent.com/89852/168574656-3bdf2e2a-7eef-47b2-9328-aee4ea036193.png)

If I click "Reconnect DevTools" it hides the modal, thinks for a second, then redisplays the modal.

The `wrangler.toml` generated during init is:
```
name = "mytestproject"
main = "src/index.ts"
compatibility_date = "2022-05-16"
```

Running in local mode makes no difference - it still tries https.

**Comment by pbowyer** [comment]
On my Mac the same project works fine, so looks to be a platform issue?

**Comment by petebacondarwin** [comment]
The OAuth callback URL is http://localhost:8976/oauth/callback, yes? Why is this not working on your Windows machine? Is `localhost` not setup to route to the local machine?

The `--local-protocol` argument only affects the URL that you go to in order to access the preview of the Worker itself, and is not used for creating the OAuth callback URL.

When you browse to `https://localhost:8787/` is the Worker displayed? If not then the DevTools view has nothing to connect to, I believe.

**Comment by pbowyer** [comment]
> The OAuth callback URL is http://localhost:8976/oauth/callback, yes? Why is this not working on your Windows machine? Is localhost not setup to route to the local machine?

The OAuth callback was defaulting to https:// - and in Chrome, editing the protocol defaults immediately back to https. Localhost works great here, it's used for serving everything from Jupyter to node dev envs.

> When you browse to https://localhost:8787/ is the Worker displayed? If not then the DevTools view has nothing to connect to, I believe.

No, the worker isn't displayed because of the https issue. If I use Firefox and type in http://localhost:8787/ then it displays

**UPDATE:** From something I've run on this machine Chrome had got stuck with a HSTS policy for localhost.

Going to chrome://net-internals/#hsts, entering localhost in the box below and deleting fixed the problem.
![image](https://user-images.githubusercontent.com/89852/168586520-a2d3a6f3-10c3-4bda-a7b3-189daf48fead.png)
I have no idea what caused that, and couldn't find a way to get Chrome to tell me.

**Comment by threepointone** [comment]
This is good to know if we face this issue again in the future, thank you for investigating!
