### ISSUE TITLE
`wrangler init` throws an error if `git` is not available 

### ISSUE THREAD

**Issue by shehiramkamal** [cloudflare/wrangler2#1022]
while using this command, i get this error

npx wrangler init my-worker
 ⛅️ wrangler 2.0.5
-------------------
Using npm as package manager.
✨ Created my-worker\wrangler.toml

X [ERROR] Command failed with exit code 1: git --version

  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by petebacondarwin** [comment]
Hmm, strange. That should have been fixed by https://github.com/cloudflare/wrangler2/commit/1caa5f764100156a8d8e25347036b05e2b0210f6
