### ISSUE TITLE
feat: implement support for service bindings 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1026]
As announced in https://blog.cloudflare.com/service-bindings-ga/, this issue tracks first class integration in wrangler.

**Comment by sodabrew** [comment]
Hi! I want to call out that this API remains undocumented at api.cloudflare.com, which is ostensibly blocking my PR to cloudflare-go: https://github.com/cloudflare/cloudflare-go/pull/849

Would greatly appreciate API docs for use cases where a customer is not using wrangler.
