### ISSUE TITLE
bug: publishing to routes has assorted issues 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1030]
We're noticing some issues with developing/publishing to routes with wrangler 2. Using this as an umbrella issue because some of them may be related, but we can investigate them all together. 

- https://github.com/cloudflare/wrangler2/issues/1003
- https://github.com/cloudflare/wrangler2/issues/652 
- https://github.com/cloudflare/wrangler2/issues/651
- https://github.com/cloudflare/wrangler2/issues/603

**Comment by petebacondarwin** [comment]
Assigning this to @caass as she is working on the last issue in this list.

**Comment by threepointone** [comment]
All the sub issues have been fixed, so I'm closing this parent issue. Great work everyone!
