### ISSUE TITLE
feat: upload/download/delete objects from r2

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1031]
(tbd, placeholder issue. cc @vlovich)

**Comment by jgentes** [comment]
@JacobMGEvans could you link your PR here?

**Comment by IgorMinar** [comment]
I belive it's this one: https://github.com/cloudflare/wrangler2/pull/1486

**Comment by JacobMGEvans** [comment]
> I believe it's this one: #1486

That's the one. 

@jgentes  I linked it here as well, though it is still a draft with no description or changeset.
