### ISSUE TITLE
🐛 BUG: Require to esm conversion

### ISSUE THREAD

**Issue by BurkeDesigns** [cloudflare/wrangler2#1046]
### What version of `Wrangler` are you using?

2.0.5

### What operating system are you using?

Windows

### Describe the Bug

After updating to wrangler 2, I tried using the npm Stripe library and am unable to import it even when I used the http client. I was able to use Stripe no problem in wrangler v1. Anyway, here are the steps to reproduce:

1. Create a new Wrangler 2 JavaScript project
2. Run these commands
`yarn add hono` and `yarn add stripe`
3. Copy the following working code into your "src/index.js":
```
import { Hono } from 'hono'
import { cors } from 'hono/cors'
// const Stripe = require("stripe");

const app = new Hono()
app.use('*', cors())

app.get('/', async (c) => {
  return c.text('hello world!');
})

app.fire()

```
4. If you uncomment the stripe import, you will get the following error:
`Converting "require" to "esm" is currently not supported`

**Please note:** even when using the esm import, it doesn't work. Is there a way to properly use npm packages like Stripe in Wrangler 2?

**Comment by threepointone** [comment]
Could you try this - use the `import Stripe from "stripe"` form, and add `node_compat = true` to your `wrangler.toml`
