### ISSUE TITLE
🐛 BUG: Cannot use node builtin polyfill "crypto"

### ISSUE THREAD

**Issue by yakovmanshin** [cloudflare/wrangler2#1047]
### What version of `Wrangler` are you using?

2.0.5

### What operating system are you using?

macOS 12.4

### Describe the Bug

In my worker’s code, I make use of Node’s built-in `crypto` package. Before upgrading to `wrangler` 2, it more or less worked (I had to use the `crypto-browserify` workaround). `wrangler` 2 refuses to build the code outright, even though `tsc` compiles it without a problem.

```
bash-3.2$ wrangler dev
 ⛅️ wrangler 2.0.5 
-------------------
Running custom build: npm run build

> <REDACTED>@<REDACTED> build
> tsc

⬣ Listening at http://localhost:8787
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn on local mode, [c] clear console, [x] to exit                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
✘ [ERROR] Could not resolve "crypto"

    ../<REDACTED>.js:26:36:
      26 │ const Crypto = __importStar(require("crypto"));
         ╵                                     ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Build failed with 1 error:

  ../<REDACTED>.js:26:36: ERROR: Could not resolve "crypto"


If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
```

Does `wrangler` actually need to build the code for the browser? Can it be customized to build for Node instead?

**Comment by threepointone** [comment]
Can you add `node_compat = true` to your `wrangler.toml` and try again?

**Comment by yakovmanshin** [comment]
Hi @threepointone! Thanks for the suggestion!

Setting `node_compat` to `true` makes it possible to build the project, but the `crypto` module *specifically* does not work as expected (it doesn’t work at all, throwing errors like `Crypto.createHash is not a function`).

With this option enabled, `wrangler` displays the following warning:
```
▲ [WARNING] Enabling node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.
```

…and the linked repo’s `README` [says](https://github.com/ionic-team/rollup-plugin-node-polyfills/blob/master/readme.md?plain=1#L56), “Crypto is not shimmed and and we just provide the commonjs one from browserify and it will likely not work, if you really want it please pass `{crypto: true}` as an option.”

So it seems there’s still a need for further customization options in `wrangler` config.

**Comment by threepointone** [comment]
Oh hmm, ok we should just add the browserify one with `{crypto: true}`. 

Some immediate options for you here - 

- enhance your custom build step to add the crypto polyfill yourself 
- replace usage of node's crypto with the web crypto api 
- Stick with wrangler 1 while we solve this on our end. 

The module we use for this doesn't have options for enabling crypto right now. We want to replace that module with our own, and that would make enabling that much simpler. Overall, we plan on making `node_compat` better, but work on that might not start for a couple of weeks, we're in the middle of planning at the moment. 

I'll leave this issue till we can fix your situation, happy to keep discussing options. Extremely sorry about this experience.

**Comment by yakovmanshin** [comment]
Thank you!

**Comment by lrapoport-cf** [comment]
let's continue the discussion in https://github.com/cloudflare/wrangler2/issues/1345
