### ISSUE TITLE
🐛 BUG: Unable to `wrangler pages publish` to production env

### ISSUE THREAD

**Issue by Barre** [cloudflare/wrangler2#1050]
### What version of `Wrangler` are you using?

2.0.5

### What operating system are you using?

Macos

### Describe the Bug

It does not seem possible to run wrangler pages publish against the production environment.

```
wrangler pages publish --env production
```

returns 

```
 [ERROR] Unknown argument: env
```

Looking at the dashboard, running `wrangler pages publish --env production` seems to deploy in the "preview" environment

<img width="393" alt="image" src="https://user-images.githubusercontent.com/45085843/169003662-84ca0267-07bd-4041-9f57-aa143fea06c5.png">

**Comment by GregBrimble** [comment]
Hi @Barre ,

The environment for a Pages deployment is determined by the branch used. By default this will pick up from your git workspace if you're in one, but you can also specify this manually with the `wrangler pages publish ./dir --branch=foo` argument. When the branch name matches that of your project's production branch, you'll create a production deployment.
