### ISSUE TITLE
wrangler doesn't follow XDG spec for config files

### ISSUE THREAD

**Issue by UtkarshVerma** [cloudflare/wrangler2#1053]
#### Describe the bug

wrangler creates a `~/.wrangler` folder even though I have `$XDG_CONFIG_HOME` set in my environment. There has been an issue([#180](https://github.com/cloudflare/wrangler/issues/180)) for this which was closed a year ago, but it seems it has surfaced again.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Install wrangler (wrangler 1.19.8 in my case)
2. Watch wrangler login create `~/.wrangler`.

#### Expected behavior

`$XDG_CONFIG_HOME/wrangler` should be used instead.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Arch Linux (Kernel v5.15.8 x86_64)
* output of `wrangler -V`: wrangler 1.19.8
* output of `node -v`: v17.3.0
* content of `wrangler.toml`: (Irrelevant)

**Comment by YaBoiBurner** [comment]
small addition to this - the old version of wrangler had a `$WRANGLER_HOME` environment variable which you could use to get around this for the most part (I had it set to `~/.config/wrangler`), while wrangler 2 doesn't.

[relevant code](https://github.com/cloudflare/wrangler/blob/master/src/settings/global_config.rs#L6-L16=)

Still, not a particularly high priority thing right now - Symlinking `~/.wrangler` to `~/.config/wrangler` works fine enough as a temporary workaround
