### ISSUE TITLE
Documentation: Add r2 and Pages commands to reference docu

### ISSUE THREAD

**Issue by jkup** [cloudflare/wrangler2#1059]
### What version of `Wrangler` are you using?

2.0.2

### What operating system are you using?

Mac

### Describe the Bug

We should add the `wrangler pages` and `wrangler r2` reference documentation to https://developers.cloudflare.com/workers/wrangler/commands/

**Comment by cameron-robey** [comment]
Looks like this should have been closed with https://github.com/cloudflare/cloudflare-docs/pull/4627
