### ISSUE TITLE
feat: Implement `wrangler delete`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1065]
We should be able to delete a Worker from the CLI, potentially include all its environments, and linked Durable Objects and other resources. Probably needs to be interactive, but we could also add a `--force` flag. We'd taken an initial attempt at it for wrangler 1 but it never landed https://github.com/cloudflare/wrangler/pull/2086

**Comment by threepointone** [comment]
Landed a basic version in https://github.com/cloudflare/wrangler2/pull/2045. My usecase is pushing a new worker for every PR in my project (named by branch), and deleting it when the PR closes. It works well for now!

**Comment by jfsiii** [comment]
yes, please re: the `maybe delete sites/assets kv namespace as well?` [comment in that PR](https://github.com/threepointone/wrangler2/blob/c2d3286fab527042eca76fd3626d1be0f79612cf/packages/wrangler/src/delete.ts#L85)

We're doing same worker-per-PR [you describe](https://github.com/cloudflare/wrangler2/issues/1065#issuecomment-1282861140) and we need to delete assets namespace for the same reason.

It didn't take long to learn there's a limit of 100 workers and 200 KV namespaces. Once you hit either limit the new deploys (API requests) start failing

**Comment by threepointone** [comment]
I'll try to send a PR that does site/assets namespace deletion this weekend. 

Re: the 100/200 limit, my 2c

for workers: I wonder if cloudflare could provide a new kind of publish here. We don't need these to be globally distributed, or even particularly long lived. It could use the same infra as `wrangler dev`. 

Alternately, there's now opportunity to just run workerd on something like fly.io (but making it 'work' with/mock every other cf service would be a pita 

for site namespaces: really, kv was only a temporary solution for static assets. the pages upload api should mature, and replace kv as the primitive for static assets.

**Comment by threepointone** [comment]
I got a PR up for deleting sites/assets namespaces https://github.com/cloudflare/wrangler2/pull/2098

**Comment by rozenmd** [comment]
@threepointone we good to close this one?

**Comment by threepointone** [comment]
Yeah. You'll have to revisit it in the future when (if?) service environments become a thing, but this issue should be good to close for now.
