### ISSUE TITLE
Ambiguous instructions

### ISSUE THREAD

**Issue by tgunr** [cloudflare/wrangler2#1092]
https://capture.dropbox.com/lcYVFnJ9y3ipmVKt

Exactly where does one go to at the "open Browser" instruction?

**Comment by petebacondarwin** [comment]
Hi @tgunr - the browser should have opened up automatically as part of the OAuth flow. Did that not happen in your case?

**Comment by rozenmd** [comment]
We could probably clarify that "When prompted, open your browser and click the **Authorize Wrangler** button" line to say something like: "When wrangler automatically opens your browser, click the **Authorize Wrangler** button"

**Comment by tgunr** [comment]
My misunderstanding, I was anticipating going to somewhere on CF web site to authorize. I was doing this from CLI on Linux. When I moved to my Mac and installed wrangler and issued 'nix wrangler dev' to my surprise the browser on my Mac opened to the proper URL. 

You might make it clearer that the CLI environment needs to be on a system which has a GUI interface.

**Comment by petebacondarwin** [comment]
@tgunr when you say

> I was doing this from CLI on Linux.

What is the setup there?

- Was it over SSH or something so that no browser was available? In that case, I think we should have shown an error.
- Or was it that you couldn't see the browser because it was opened elsewhere?

**Comment by petebacondarwin** [comment]
Also, @tgunr, can you tell me where you go that screenshot? I can't find that in our current docs.

**Comment by tgunr** [comment]
I was ssh into my Debian server using CLI.  The screenshot is from the website somewhere, I was using to illustrate the instructions for login, namely `"When prompted, open your browser and click the Authorize Wrangler button. This will send an API Token to Wrangler." 
`
Which prompted my initial question, open my browser where? No URL was given and I was assuming I needed to open my browser to some URL not realizing the login was trying to open a GUI browser on the host I was plugged into via ssh (which was headless therefor no GUI).

**Comment by petebacondarwin** [comment]
OK - so I assume that the Debian server had a browser available locally, which it opened, but you couldn't see it?

Regarding the instructions. I asked where you found them, because I can't find this in any of the Cloudflare docs. If you can point me to it, then I can get it updated.

**Comment by tgunr** [comment]
No, the server is headless, no terminal, no GUI. 

I'll look later for that set of instructions.

**Comment by rozenmd** [comment]
@petebacondarwin it's displayed at dash.cloudflare.com, the strings can be found in our internal stratus repo

**Comment by rozenmd** [comment]
Just letting you know I've updated the instructions @tgunr: 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/3822106/172579883-251deaa3-7ef7-4deb-a732-a0be67436b13.png">

Thanks for the report!
