### ISSUE TITLE
BUG: wrangler publish fails with error about control characters

### ISSUE THREAD

**Issue by timabb031** [cloudflare/wrangler2#1094]
I've been following the instructions on the Workers Chat Demo repo (https://github.com/cloudflare/workers-chat-demo) and when I run `wrangler publish` an error is returned - "Control characters (codes < 0x1f and 0x7f) are not allowed in comments, use \u000d instead".

Steps to reproduce (on Windows 10):

1. Clone https://github.com/cloudflare/workers-chat-demo to c:\projects\workers-chat-demo
2. Open up cmd.
3. `npm install -g wrangler` (I'm running 2.0.6)
4. `cd \projects\workers-chat-demo`
5. `wrangler login`
6. `wrangler publish`

**Comment by petebacondarwin** [comment]
Hmm, I thought I had fixed this with https://github.com/cloudflare/wrangler2/pull/936

**Comment by petebacondarwin** [comment]
Can you just check that it is picking up the correct global version of wrangler by running `wrangler -v`?

**Comment by timabb031** [comment]
`wrangler -v` returns `2.0.6`

**Comment by petebacondarwin** [comment]
Hmm. Let me see if I can reproduce this locally.

**Comment by petebacondarwin** [comment]
I just followed these steps this on my Windows machine and it worked:

```
> wrangler publish
 ⛅️ wrangler 2.0.6
-------------------
▲ [WARNING] Processing wrangler.toml configuration:

    - 😶 Ignored: "type":
      Most common features now work out of the box with wrangler, including modules, jsx,
  typescript, etc. If you need anything more, use a custom build.
    - Deprecation: "build.upload.format":
      The format is inferred automatically from the code.
    - Deprecation: "build.upload.main":
      Delete the `build.upload.main` and `build.upload.dir` fields.
      Then add the top level `main` field to your configuration file:
      ```
      main = "src\chat.mjs"
      ```
    - Deprecation: "build.upload.dir":
      Use the top level "main" field or a command-line argument to specify the entry-point for the
  Worker.
    - Deprecation: The `build.upload.rules` config field is no longer used, the rules should be
  specified via the `rules` config field. Delete the `build.upload` field from the configuration
  file, and add this:
      ```
      [[rules]]
      type = "Data"
      globs = [ "**/*.html" ]
      ```


▲ [WARNING] The default module rule {"type":"Data","globs":["**/*.bin"]} has the same type as a previous rule (at position 0, {"type":"Data","globs":["**/*.html"]}). This rule will be ignored. To the previous rule, add `fallthrough = true` to allow the default one to also be used, or `fallthrough = false` to silence this warning.


▲ [WARNING] Deprecation: detected a legacy module import in "./src\chat.mjs". This will stop working in the future. Replace references to "chat.html" with "./chat.html";


Uploaded edge-chat-demo (4.60 sec)
Published edge-chat-demo (6.55 sec)
  edge-chat-demo.petebd.workers.dev
```

I think it might be that the wrong version of Wrangler must be running in your case...

**Comment by timabb031** [comment]
I've uninstalled wrangler globally, rebooted, installed it again with `npm install -g wrangler` and I still get the same error message.  `wrangler -v` reports 2.0.6.  If there's anything else I can try let me know.

**Comment by petebacondarwin** [comment]
Ahah! On my Windows machine, git was setup to convert CRLF combos to just LF. So I was not seeing the problem. I can reproduce now.

**Comment by petebacondarwin** [comment]
And the unit test I wrote for that only had a single line, so of course it passed!
I'll fix this up right away.
