### ISSUE TITLE
Can't upload pages from CLI - "upstream connect error or disconnect/reset before headers. reset reason: connection termination"

### ISSUE THREAD

**Issue by tomdee** [cloudflare/wrangler2#1104]
I've tried this several times, each time it fails with the same message sometime during the upload of the last 10 or so file.

```
 wrangler pages deployment create dist/staging --project-name <REDACTED> --commit-dirty=true
Using cached values in 'node_modules/.cache/wrangler'. This is used as a temporary store to improve the developer experience for some commands. It may be purged at any time. It doesn't contain any sensitive information, but it should not be commited into source control.

✘ [ERROR] ✘ [ERROR] Received a malformed response from the API

  
    upstream connect error or disconnect/reset before headers. reset reason: connection termination
    POST /accounts/8b9657f9c0af3fe061cda883091b7cc4/pages/projects/vanta/file -> 503 Service
    Unavailable
  
    If you think this is a bug, please open an issue at:
    https://github.com/cloudflare/wrangler2/issues/new
  
  


🌎  Uploading... (240/245)
```

**Comment by anndro** [comment]
Getting same error.

✘ [ERROR] ✘ [ERROR] Received a malformed response from the API
  
    upstream connect error or disconnect/reset before headers. reset reason: connection termination
    POST /accounts/57bdf1c9f3689d136ce98442ed4fd2e1/pages/projects/market-oceanland/file -> 503 Service Unavailable
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new
  
  
🌎  Uploading... (260/441)

**Comment by anndro** [comment]
I can confirm it is solved. 

>🌎  Uploading... (439/439)
>✨ Success! Uploaded 439 files (24.25 sec)
>Using cached values in 'node_modules/.cache/wrangler'. This is used as a temporary store to improve the developer experience for some commands. It may be purged at any time. It doesn't contain any sensitive information, but it should not be commited into source control.

**Comment by petebacondarwin** [comment]
Thanks for the update - @tomdee can you check if it is resolved for you too?

**Comment by tomdee** [comment]
Yep, working for me too. Thanks for your help

**Comment by petebacondarwin** [comment]
Thanks both for confirming.
