### ISSUE TITLE
 npx wrangler pages publish build

### ISSUE THREAD

**Issue by bis0072** [cloudflare/wrangler2#1108]
$ npx wrangler pages publish build
Using cached values in 'node_modules/.cache/wrangler'. This is used as a temporary store to improve the developer experience for some commands. It may be purged at any time. It doesn't contain any sensitive information, but it should not be commited into source control.

X [ERROR] X [ERROR] Received a malformed response from the API

    <html>
    <head><title>502 Bad Gateway</title></head>
    <body>
    <center><h1>502 Bad Gateway</h1></cente... (length = 155)

    POST /accounts/*********************/pages/projects/admin/file -> 502 Bad Gateway

    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new

🌏  Uploading... (17/25)

**Comment by leviwolfe** [comment]
It seems like this might also be related to #960. I was able to publish fine earlier, however using `wrangler pages publish` now I also see a combination of the error above or this:

```🌎  Uploading... (95/95)
✨ Success! Uploaded 95 files (6.83 sec)

✘ [ERROR] ✘ [ERROR] Received a bad response from the API  
    An unknown error occurred [code: 8000000]    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new```

**Comment by jahands** [comment]
Thank you for reporting this - we are working on stability improvements for publishing Pages projects through Wrangler

**Comment by mergesort** [comment]
I'm running into this as well with no feedback other than this.
```
🌍  Uploading... (82/82)

✨ Success! Uploaded 82 files (10.28 sec)


✘ [ERROR] ✘ [ERROR] Received a bad response from the API

  
    An unknown error occurred [code: 8000000]
  
    If you think this is a bug, please open an issue at:
    https://github.com/cloudflare/wrangler2/issues/new
```

**Comment by RobertBroersma** [comment]
I'm receiving a similar error:

```
Compiled Worker successfully.
🌍  Uploading... (188/188)

✨ Success! Uploaded 0 files (188 already uploaded) (0.58 sec)


✘ [ERROR] A request to the Cloudflare API (/accounts/********************************/pages/projects/website/deployments) failed.

  An unknown error occurred [code: 8000000]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
  ```
  
  I receive this error pretty consistently both locally and in CI. Occasionally it flakes and succeeds. 
  
  It seems to have gotten worse after adding a `_redirects` file, not sure if that is related.

**Comment by fidgety** [comment]
We see an error when we're trying to redeploy a previously deployed version (when we want to revert a live defect from our CI tool)

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/4701093/173873665-5e0c15ef-53aa-4d79-a323-e796024a45d4.png">

our assumption is that cloudflare recognises it as a previously deployed version and throws an error. How would you suggest we handle triggering a re-release of an older version from a CI pipeline?

**Comment by RobertBroersma** [comment]
I did some logging in the Wrangler code hoping to find some more info about the error, but it seems to be a Internal Server Error.

Let me know if there's anything I can do to help!

**Comment by leviwolfe** [comment]
Updating to wrangler 2.0.14 has had no effect on success rates. Today for example, using the CLI in a GitHub Action succeeded only 3 times out of 12 attempts. Wrangler does seem smarter about not re-uploading files, which at least makes it fail faster with the "unknown error" afterwards:

```
> wrangler pages publish dist --project-name XXXXX --branch "main"
🌍  Uploading... (215/215)
✨ Success! Uploaded 0 files (215 already uploaded) (0.40 sec)
✘ [ERROR]A request to the Cloudflare API (/accounts/***/pages/projects/XXXXX/deployments) failed.
  An unknown error occurred [code: 8000000]
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
Error: Process completed with exit code 1.
```

**Comment by RobertBroersma** [comment]
I'm not 100% sure if it is, but for me this issue appears to be fixed 😁

**Comment by sidharthachatterjee** [comment]
Hiya! Sorry for the issues. We have since fixed these so I'm closing it for now. Please do update `wrangler` to optin. 

If you'll still see instances of this, please feel free to open or reopen this one. Cheers!
