### ISSUE TITLE
🚀 Feature Request: Enhance wrangler init with template selection

### ISSUE THREAD

**Issue by timabb031** [cloudflare/wrangler2#1113]
### Describe the solution

When using `wrangler init` there is an option to create a worker which adds src\index.ts when selected.

The worker that is created is specifically for `fetch`, which I guess is the most common use case.

It would however be great if I could choose a different template, for example a `scheduled` worker so that I don't have to read through the docs and figure out how to set up the function / TS types / etc.

In future it seems there will be other specialised workers such as `email` (https://blog.cloudflare.com/announcing-route-to-workers/) and it would be cool to have the option to bootstrap one of those in future too.

Having the option to bootstrap a Durable Object in either JS or TS would also be a plus.

**Comment by petebacondarwin** [comment]
I like the idea of having a list of checkboxes where we can choose one or more handler types (with `fetch` being selected already by default) would be a good improvement. Feel free to send in a PR!

**Comment by timabb031** [comment]
@petebacondarwin I'll have a look at tackling this once #1112 has been done.

**Comment by timabb031** [comment]
@petebacondarwin Would a single select instead of a list of checkboxes suffice? i.e. offer the user a choice between a fetch/scheduled handler.  I've got an implementation that produces the result below with the `ink-select-input` package that is already in use elsewhere in the project.  I had a look at the `ink-multi-select` package but it's got a low number of downloads and was last published 2 years ago. 

![image](https://user-images.githubusercontent.com/51492403/170889519-dd811c76-f2c4-4998-a540-ed774aef600d.png)

**Comment by petebacondarwin** [comment]
I think that would be OK to start with. We can discuss making it more sophisticated later.
How about, rather than the two questions: "Would you like to create a Worker..." and "Which type of handler...", we change it to:

```
Would you like to create a Worker at ...?
[ ] - None
[ ] - Fetch handler
[ ] - Scheduled handler
```
```

**Comment by timabb031** [comment]
Ok, that would work well.  Leave it with me and I'll see if I can work on it later this week.
