### ISSUE TITLE
🚀 Feature Request: Expose `--no-cf-fetch` in `pages dev`

### ISSUE THREAD

**Issue by kotx** [cloudflare/wrangler2#1114]
### Describe the solution

`wrangler pages dev [...]` doesn't expose miniflare's `--no-cf-fetch` flag.

**Comment by GregBrimble** [comment]
If we do #1115, is there reason why you'd want to use `--no-cf-fetch`?

**Comment by GregBrimble** [comment]
Now that we're using `wrangler dev`'s server, I think we'll just conform to whatever they do. Doesn't look like there was much interest in this feature unfortunately, so I'll close it out. Happy to revisit if there is a surge of interest in the future :)
