### ISSUE TITLE
🚀 Feature Request: Load values from wrangler.toml

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#1117]
### Describe the solution

A lot of times, I'd like my worker code to depend on some values I have in my `wrangler.toml` (e.g. getting the worker name, getting the routes it can be deployed to, etc.)

While I can duplicate this information in JS, it'd be easier if I could just import my `wrangler.toml` the same way I can import my `package.json`.

We should include a plugin to parse `.toml` files with `esbuild` (such as [`esbuild-plugin-toml`](https://github.com/SilentVoid13/esbuild-plugin-toml) so that `wrangler publish` can include imports from `toml` files.

**Comment by petebacondarwin** [comment]
Interesting idea...

**Comment by JacobMGEvans** [comment]
Even from a internal Wrangler standpoint I think there is value for it being very available, using something like https://github.com/npm/config or https://github.com/davidtheclark/cosmiconfig

**Comment by GregBrimble** [comment]
Pages exposes certain things (e.g. the branch name) as environment variables: https://developers.cloudflare.com/pages/platform/build-configuration/#environment-variables. They're available on `env.`. I imagine you probably don't want to do that, but bringing it up just in case it's a useful reference point.

**Comment by petebacondarwin** [comment]
We can currently achieve this via a custom build step, so I'm going to close this as not something we should implement in core Wrangler.
