### ISSUE TITLE
Possible API response bug

### ISSUE THREAD

**Issue by DSSTrading** [cloudflare/wrangler2#1118]
I have encountered an issue with the end of our circleCI pipeline throwing an authentication error [code: 10000]. It seems this could possibly be an issue with either client or server side. Thankfully on our end the pipeline seems to function properly despite throwing this error and failing. Any ideas why this might happen?

```
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

added 56 packages, and audited 57 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
 ⛅️ wrangler 2.0.6 
-------------------
🌀 Creating the secret for script dev-sheet 
✨ Success! Uploaded secret psk
 ⛅️ wrangler 2.0.6 
-------------------
🌀 Creating the secret for script dev-sheet 
✨ Success! Uploaded secret google_api_key
 ⛅️ wrangler 2.0.6 
-------------------
Uploaded dev-sheet (1.42 sec)

✘ [ERROR] ✘ [ERROR] Received a bad response from the API

  
    Authentication error [code: 10000]
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new
  
  



Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by petebacondarwin** [comment]
Since you are running this in CircleCI, I assume you are using CLOUDFLARE_API_TOKEN to authenticate.
Could you say what permissions that token has been granted? We have seen some other auth issues recently where the token is only granted Zone rights and not full Account rights...

**Comment by teebszet** [comment]
@petebacondarwin is there any clarification on which permissions are required when running

`wrangler pages publish` ?

I'm using a CLOUDFLARE_API_TOKEN generated from my personal account which doesn't have super admin privileges, so would be useful in finding out the minimum required permissions.

thanks!

**Comment by petebacondarwin** [comment]
I'm not sure what perms are required for `pages publish`. cc @sidharthachatterjee ?

**Comment by teebszet** [comment]
Thanks!

It's probably a combination of token permissions and user privileges right? 

e.g. user must have API write or soemthing? (I can't see my user permissions so don't know the exact names)

**Comment by GregBrimble** [comment]
The API token created must have rights for the account and project you're trying to edit to. But this is a bit of a digression from the originally reported issue for `wrangler secret put`, so please create another issue to discuss `wrangler pages publish` if you're having problems.

**Comment by threepointone** [comment]
@DSSTrading I suspect your token expired, or it was just misconfigured. I'm going to close this issue, but feel free to drop any info if you want to discuss further and/or if we need to reopen this issue. . Further, do try with latest versions of wrangler, it may just have been fixed.
