### ISSUE TITLE
🐛 BUG: `pages publish .` uploads the contents of `.git` into the root of the deployment

### ISSUE THREAD

**Issue by Erisa** [cloudflare/wrangler2#1119]
### What version of `Wrangler` are you using?

0.0.0-b7a9ce6

### What operating system are you using?

Ubuntu 22.04 in WSL on Windows 11

### Describe the Bug

Repo steps:
- Clone a git repository
- Run through `npx wrangler@beta pages publish .`

You will notice that it uploads the contents of `.git` to the root of the resulting project (Not even in the `.git` directory which makes this weird)

For example: `.git/config` becomes https://d02d80d8.erisa-uk-test.pages.dev/config

The expectation I would have is that the `.git` directory would be [ignored](https://github.com/cloudflare/wrangler2/blob/b7a9ce60244e18b74533aaeeff6ae282a82892f1/packages/wrangler/src/pages.tsx#L1052) the same as others like `node_modules`.

While this is not inherently a security issue and is not being reported as one, it does have the potential to become a security issue in a number of isolated scenarios.

This has been tested on both the current stable and beta versions of wrangler.

**Comment by sidharthachatterjee** [comment]
This is a great callout. Thank you so much @Erisa! Not sure how we missed this.

**Comment by sidharthachatterjee** [comment]
We've shipped a fix. Expect a release soon-ish. Thank you for the report again!
