### ISSUE TITLE
🐛 BUG: You are not entitled to use r2. [code: 10042]

### ISSUE THREAD

**Issue by Yoo-DongGyun** [cloudflare/wrangler2#1124]
### What version of `Wrangler` are you using?

2.0.6

### What operating system are you using?

Mac

### Describe the Bug

I signed up to test R2. But I can't test R2 Because of I got this message 'You are not entitled to use r2. [code: 10042]'
![스크린샷 2022-05-27 오후 3 49 46](https://user-images.githubusercontent.com/97266282/170646625-cd899187-f764-4c39-8e62-e37dc46b1ed6.png)
<img width="458" alt="스크린샷 2022-05-27 오후 3 50 15" src="https://user-images.githubusercontent.com/97266282/170646642-55e4b6fd-7089-4cb4-a58f-4166037c5a41.png">

Please fix this problem.

Thank you!

**Comment by petebacondarwin** [comment]
Hi @Yoo-DongGyun - please could you provide some more information about how you are authenticating?
Are you using the OAuth login approach (e.g. using `wrangler login`) or are you using a `CLOUDFLARE_API_TOKEN`?
Does the authenticated user definitely have access to the R2 feature? Can you login via the same user and see the R2 functionality in the Cloudflare dashboard?

**Comment by DongGyun-Yoo** [comment]
Hi @petebacondarwin, I am sorry for the late your reply. 
I've had problems with both of them.
First picture is what happend in OAuth login and Second picture is Cloudflare what happend in Cloudflare dashboard too.
I can use another Cloudflare service, but I can't use only R2 service because of message
Thank you for answering my question and i will appreciate it., if you can check it again.

**Comment by petebacondarwin** [comment]
I have asked in the R2 team to find out more about what might be wrong here.
Do you have a paid support arrangement with Cloudflare? You might be able to get a more direct response through your customer support agent? Alternatively, there might be someone on the [Cloudflare discord](https://discord.com/invite/cloudflaredev) that can look into this for you?

**Comment by petebacondarwin** [comment]
Closing for now, since this is not specifically a bug with Wrangler. Apparently there may have been some propagation issues with auth. Please try again and come back if it's still a problem.
