### ISSUE TITLE
🚀 Feature Request: Use `ExportedHandler` type in `wrangler init`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1128]
### Describe the solution

```typescript
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    return new Response("Hello World!");
  },
};
```

vs

```typescript
export default {
  async fetch(request, env, ctx) {
    return new Response("Hello World!");
  },
} as ExportedHandler<Env>;
```

https://github.com/cloudflare/workers-types/blob/3012f263fb1239825e5f0061b267c8650d01b717/index.d.ts#L604

This'll let people easily add `scheduled` or `email` types as well if they want, and is just cleaner anyway, imo.

**Comment by petebacondarwin** [comment]
I thought about this when we just landed the change that introduced these additional arguments.
But I thought that adding the `as ...` type cast would look a bit magical; and that the original PR with explicit types was clearer for new developers.

**Comment by GregBrimble** [comment]
Fair enough—feel free to close if you're happy leaving things as-is!

**Comment by threepointone** [comment]
I'm pretty sympathetic to this, and in general we need to have a fresh look at this. Another sorta related thing I'd like to do is autogenerate the type for Env based on wrangler.toml. Another thing that could help this specific situation is https://github.com/cloudflare/wrangler2/issues/1113 One thing at a time...

I'm going to close this for now, but it's on our minds, and I'm happy to continue discussing.
