### ISSUE TITLE
Detected a Node builtin module import while Node compatibility is disabled. Add node_compat = true to your wrangler.toml file to enable Node compatibility.

### ISSUE THREAD

**Issue by tyurin-ilya** [cloudflare/wrangler2#1130]
I want connect to postglesql db via knex library. But after installation of knex, I receiving an error:
**Detected a Node builtin module import while Node compatibility is disabled. Add node_compat = true to your wrangler.toml file to enable Node compatibility.**
If in wrangler.toml I write **node_compat = true** worker fails with other errors. How can I use knex orm in cloudlfare workers?
https://www.npmjs.com/package/knex

**Comment by ashwinv11** [comment]
Hello @tyurin-ilya, were you able to use knex successfully within a worker connected to postgres? If so do you mind adding some example steps on how you were able to get this to work? I'm having issues with Typescript, Knex, and the pg client and was wondering if you had a working example
