### ISSUE TITLE
🚀 Feature Request: wrangler types

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1132]
### Describe the solution

Declare modules for all the various loaders that wrangler has implemented.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/8484333/170793053-aebc2c4f-1030-40c5-a5ee-20a969bbb2a8.png">

```typescript
declare module "*.html" {
  const content: string;
  export default content;
}
```

**Comment by petebacondarwin** [comment]
I like it - although I am not sure where this should live. I don't think it should go in the `wrangler-types` package, since it is specific to the Wrangler bundling approach.

**Comment by GregBrimble** [comment]
We put Pages Functions types into `@cloudflare/workers-types` package 🤷‍♀️ Technically they're just a compile-time thing too.

**Comment by threepointone** [comment]
One problem here (I think?) is that it'll be hard to override if someone wants to import it differently (say, as `Data`) Correct me if I'm wrong? We should probably do it for `.wasm` anyway, I doubt that'll change for a while.

**Comment by penalosa** [comment]
@JacobMGEvans I believe this is solved by the `wrangler types` command?
