### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by jamalgillis** [cloudflare/wrangler2#1138]
i'm getting loader configuration errors with my python file.  Can someone please give me a good step by step on how to get python to run in cloudflare workers?  Thanks

**Comment by petebacondarwin** [comment]
This template is rather outdated but appears to be the only documentation we have on writing a Worker in Python: https://github.com/cloudflare/python-worker-hello-world

**Comment by petebacondarwin** [comment]
This issue tracker is not really for support requests, I would recommend joining the Cloudflare Discord server and seeing if you can get help there: https://discord.com/invite/cloudflaredev
