### ISSUE TITLE
feat: show information about how user is authenticating

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#1148]
It is helpful for the user to know whether we are authenticating them via an API token or OAuth etc.

**Comment by fbritoferreira** [comment]
@petebacondarwin Maybe add a debug log line when using commands that logs which authentication is using

**Comment by rozenmd** [comment]
`wrangler whoami` prints whether the user is using OAuth or an API token - are we good to close this @petebacondarwin?

**Comment by petebacondarwin** [comment]
Yeah, I think that is enough for debugging scenarios.
