### ISSUE TITLE
🐛 BUG: Wrangler rebundles code that was already bundled with a custom build command.

### ISSUE THREAD

**Issue by evaera** [cloudflare/wrangler2#1149]
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

Windows

### Describe the Bug

A Worker of mine uses esbuild as a bundler and generates source maps that I then use to upload to Sentry for error reporting. When I use Wrangler 2, it does invoke my custom build script, but then it also runs esbuild *again* over the output of my own build command. While the uploaded code functions, the source maps that my bundler generated are no longer useful.

I'm submitting this issue as a bug because I think it is unintentional that Wrangler would run esbuild again after it invokes my custom build specified with `build.command`.

Here is a repo with a small repro of the issue: https://github.com/evaera/w2-double-build

You'll notice that after building, the index.mjs file is:

<details>
<summary>After build</summary>

```js
var a,g=new Uint8Array(16);function s(){if(!a&&(a=typeof crypto<"u"&&crypto.getRandomValues&&crypto.getRandomValues.bind(crypto)||typeof msCrypto<"u"&&typeof msCrypto.getRandomValues=="function"&&msCrypto.getRandomValues.bind(msCrypto),!a))throw new Error("crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported");return a(g)}var p=/^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000)$/i;function x(t){return typeof t=="string"&&p.test(t)}var m=x;var o=[];for(u=0;u<256;++u)o.push((u+256).toString(16).substr(1));var u;function v(t){var e=arguments.length>1&&arguments[1]!==void 0?arguments[1]:0,r=(o[t[e+0]]+o[t[e+1]]+o[t[e+2]]+o[t[e+3]]+"-"+o[t[e+4]]+o[t[e+5]]+"-"+o[t[e+6]]+o[t[e+7]]+"-"+o[t[e+8]]+o[t[e+9]]+"-"+o[t[e+10]]+o[t[e+11]]+o[t[e+12]]+o[t[e+13]]+o[t[e+14]]+o[t[e+15]]).toLowerCase();if(!m(r))throw TypeError("Stringified UUID is invalid");return r}var i=v;function y(t,e,r){t=t||{};var n=t.random||(t.rng||s)();if(n[6]=n[6]&15|64,n[8]=n[8]&63|128,e){r=r||0;for(var f=0;f<16;++f)e[r+f]=n[f];return e}return i(n)}var d=y;function l(){return new Response(d())}var j={async fetch(t){return l()}};export{j as default};
//# sourceMappingURL=index.mjs.map
```
</details>

However, after publishing to Cloudflare via Wrangler:
<details>
<summary>After publish</summary>

```js
// dist/index.mjs
var a;
var g = new Uint8Array(16);
function s() {
  if (!a && (a = typeof crypto < "u" && crypto.getRandomValues && crypto.getRandomValues.bind(crypto) || typeof msCrypto < "u" && typeof msCrypto.getRandomValues == "function" && msCrypto.getRandomValues.bind(msCrypto), !a))
    throw new Error("crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported");
  return a(g);
}
var p = /^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000)$/i;
function x(t) {
  return typeof t == "string" && p.test(t);
}
var m = x;
var o = [];
for (u = 0; u < 256; ++u)
  o.push((u + 256).toString(16).substr(1));
var u;
function v(t) {
  var e = arguments.length > 1 && arguments[1] !== void 0 ? arguments[1] : 0, r = (o[t[e + 0]] + o[t[e + 1]] + o[t[e + 2]] + o[t[e + 3]] + "-" + o[t[e + 4]] + o[t[e + 5]] + "-" + o[t[e + 6]] + o[t[e + 7]] + "-" + o[t[e + 8]] + o[t[e + 9]] + "-" + o[t[e + 10]] + o[t[e + 11]] + o[t[e + 12]] + o[t[e + 13]] + o[t[e + 14]] + o[t[e + 15]]).toLowerCase();
  if (!m(r))
    throw TypeError("Stringified UUID is invalid");
  return r;
}
var i = v;
function y(t, e, r) {
  t = t || {};
  var n = t.random || (t.rng || s)();
  if (n[6] = n[6] & 15 | 64, n[8] = n[8] & 63 | 128, e) {
    r = r || 0;
    for (var f = 0; f < 16; ++f)
      e[r + f] = n[f];
    return e;
  }
  return i(n);
}
var d = y;
function l() {
  return new Response(d());
}
var j = { async fetch(t) {
  return l();
} };
export {
  j as default
};
//# sourceMappingURL=index.js.map
```
</details>

It is clear that Wrangler is rebundling the code an additional time.

**Comment by petebacondarwin** [comment]
This is indeed how Wrangler 2.0.0+ works.

The bundling of the code is now built-in to Wrangler, so in most cases you do not even need to run a custom pre-build step. If you are bundling yourself in a custom pre-build step then mostly the only difference between the before and after is whitespace, which will not affect the behaviour of your code.

**Comment by evaera** [comment]
> This is indeed how Wrangler 2.0.0+ works.
> 
> The bundling of the code is now built-in to Wrangler, so in most cases you do not even need to run a custom pre-build step. If you are bundling yourself in a custom pre-build step then mostly the only difference between the before and after is whitespace, which will not affect the behaviour of your code.

Please re-read - The root of the issue is not about behavior difference in the code. I need to generate source maps so that I can upload them to Sentry for proper error reporting. If Wrangler 2 rebundles my code, the source maps are no longer accurate to the source code that is actually running on the Worker, rendering them useless.

**Comment by evaera** [comment]
> You probably need the sourcemaps to upload to a service like sentry to associate with your errors. You can get this by running `wrangler publish --dry-run --outdir dist`, and you'll find the sourcemap under `dist/<entry>.map`. This consumes your original sourcemap and will still work with services like sentry.

I have other things configured in my ESBuild script, so source maps are not the only issue. I define a global called `SENTRY_RELEASE` using esbuild's `define` feature, which lets me reference the current release commit that the bundle was generated with. I also use esbuild's ignore plugin to ignore certain dependencies that reference Node native modules, e.g. things that use `require("util")`.

**Comment by threepointone** [comment]
No worry, You can still use your custom build as you currently do. `wrangler publish --dry-run --outdir dist` will still run your custom build command, and then run our compilation on top of that, consuming your original sourcemap as well.

**Comment by petebacondarwin** [comment]
I think you do not need the `--dry-run` option either. So you could do it in one step with only two esbuild runs.
You might also try `--minify` which might even result in identical output from Wrangler.

As @threepointone says, we have now had a couple of requests for skipping the esbuild step in Wrangler. But this is a bit tricky. Wrangler often needs to send additional files as part of the bundle that are only discoverable by running esbuild. Two possible approaches to solving this would be to a) allow developers a bit more access to configure the Wrangler esbuild step or b) allow developers to skip the last bundling step. In the first case, we make it much more difficult to evolve the underlying bundling, since we would have to support this extra API surface. In the second case, the developer would be restricted in the kind of Worker that they could generate.

Perhaps a longer term solution may come from Wrangler providing a programmatic API to its features, which would allow more flexibility in wiring up the bundling?

**Comment by petebacondarwin** [comment]
Sorry for being vague 😄 Primarily we have this esbuild plugin, which captures and includes certain kinds of modules in the final upload:

https://github.com/cloudflare/wrangler2/blob/a8c509a200027bea212d461e8d67f7e1940cc71b/packages/wrangler/src/module-collection.ts
