### ISSUE TITLE
🐛 BUG: Unable to load Cloudflare CA certificate(s)

### ISSUE THREAD

**Issue by koistya** [cloudflare/wrangler2#1164]
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

`macOS` \w `Cloudflare WARP`, `Node v18.2.0`, `Yarn v4.0.0-rc`

### Describe the Bug

The following warning appears when running any Wrangler CLI commands:

`Warning: Ignoring extra certs from ".yarn/berry/cache/wrangler-npm-2.0.7-05d4fc41d3-9.zip/node_modules/wrangler/Cloudflare_CA.pem", load failed: error:02001014:system library:fopen:Not a directory`

**UPDATE**: Fixed in https://github.com/cloudflare/wrangler2/pull/1154

**Comment by threepointone** [comment]
Yeah I think we've fixed this, but would love some confirmation. Could you try with `wrangler@beta`? Thank you!

**Comment by threepointone** [comment]
Wonderful! Closing this for now, but lemme know if you have any problems.
