### ISSUE TITLE
🐛 BUG:Tries to init with `main` branch but fails on older git versions

### ISSUE THREAD

**Issue by polybuildr** [cloudflare/wrangler2#1168]
Hello! :wave: 

**Wrangler version**: 2.0.7
**OS**: Linux/Ubuntu

I just tried my first `wrangler init` and it asked me if I wanted to use git to manage this Worker. I said yes but unfortunately the command failed because it did a `git init --initial-branch=main` and that's not a valid option for my git version of 2.25. Based on this [StackOverflow answer](https://stackoverflow.com/a/64787736/2141058), the option was only added in v2.28.

I'll look into updating my git version, but maybe wrangler can avoid using this option for older git versions? If you'd like to still call the branch `main` with older git versions, maybe that can be achieved with a `git branch -m`?

**Comment by petebacondarwin** [comment]
Looking into this `git branch -m`, which renames the current branch seems like a very reasonable backward compatible way to achieve this.
