### ISSUE TITLE
🐛 BUG: Secrets don't seem to exist with wrangler dev?

### ISSUE THREAD

**Issue by mwisner** [cloudflare/wrangler2#1172]
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

Mac

### Describe the Bug

Honestly, I'm not sure if this is a bug or a user error... Maybe I'm doing something wrong here, but for the life of me I cannot figure out how to correctly handle secrets. I'm wondering if maybe there is a bug?

When I run: `wrangler secret list -e staging` I see the secrets in question listed.

Dev command: `wrangler dev -e staging` 

I have a test secret named `MATT` 

The index file looks like this: 

```
import type { Env } from './types';

const worker = {
  /**
   *
   * @param request
   * @param env
   * @param ctx
   */
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    console.log(env);
    console.log(env.MATT);
    return new Response("HELLO");
  },
};

export default worker;
```

When I run `wrangler dev -e staging` `env.MATT` is always undefined. Even though it is showing up w/ `wrangler secret list -e staging` 

Does anyone have any recommendations on how to best manage secrets during local development?

**Comment by petebacondarwin** [comment]
I wonder if this is the same as https://github.com/cloudflare/wrangler2/issues/1003?
Are you using `routes` in your `wrangler.toml`?

**Comment by mwisner** [comment]
Hi @petebacondarwin ,

It might be? I am using routes but I've tried the workaround described in #1003 and still can't see any secrets. I could totally be doing the workaround incorrectly though... Maybe I'll hold off until #1003 and try again.
