### ISSUE TITLE
🐛 BUG: Wrangler init fails if git is used and git version is < 2.28.0

### ISSUE THREAD

**Issue by jgentes** [cloudflare/wrangler2#1174]
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

WSL

### Describe the Bug

The `initial-branch` option was introduced in Git v2.28.0, which is later than the standard Git install on Ubuntu 18 & 20:

```
 ~ - [] $ wrangler init test
 ⛅️ wrangler 2.0.7
-------------------
Using npm as package manager.
✨ Created test/wrangler.toml
Would you like to use git to manage this Worker? (y/n)

✘ [ERROR] Command failed with exit code 129: git init --initial-branch=main

  error: unknown option `initial-branch=main'
```

The feature was introduce here: https://github.com/git/git/commit/32ba12dab2acf1ad11836a627956d1473f6b851a

We should check the version and just initialize the repo without setting the initial branch name if Git isn't up to date.

**Comment by petebacondarwin** [comment]
Sorry James you were just beaten to it by a few hours: https://github.com/cloudflare/wrangler2/issues/1168
Closing as a duplicate.
