### ISSUE TITLE
Can't publish to Cloudflare pages using API token.

### ISSUE THREAD

**Issue by lemniskett** [cloudflare/wrangler2#1186]
Hi, The title says about it.

I wanted to deploy my Jekyll website using an automation tool, I created an API token using the Worker template. but it doesn't seem to work when publishing the page. It works when using `wrangler login`

Using API token (Edit Cloudflare Worker template):
```
$ export CLOUDFLARE_API_TOKEN=<insert_api_token_here>
$ wrangler whoami                                        
 ⛅️ wrangler 2.0.7 
-------------------
Getting User settings...
👋 You are logged in with an OAuth Token, associated with the email 'lemniskett@gmail.com'!
┌────────────────────────────────┬──────────────────────────────────┐
│ Account Name                   │ Account ID                       │
├────────────────────────────────┼──────────────────────────────────┤
│ Lemniskett@gmail.com's Account │ <insert_account_id_here>         │
└────────────────────────────────┴──────────────────────────────────┘

$ wrangler pages publish _site/ --project-name lemniskett

✘ [ERROR] ✘ [ERROR] Received a bad response from the API

  
    Authentication error [code: 10000]
  
    If you think this is a bug, please open an issue at:
    https://github.com/cloudflare/wrangler2/issues/new
```

Using `wrangler login`:
```
$ wrangler login                                         
 ⛅️ wrangler 2.0.7 
-------------------
Attempting to login via OAuth...
Successfully logged in.
$ wrangler pages publish _site/ --project-name lemniskett
🌍  Uploading... (23/23)

✨ Success! Uploaded 23 files (5.51 sec)

✨ Deployment complete! Take a peek over at https://some.url.here
```

My wrangler version: 
```
$ wrangler --version
2.0.7
```

**Comment by Cherry** [comment]
What permissions have you given the API token? You may be running into https://github.com/cloudflare/wrangler2/issues/651 if you're trying to publish to a custom route.

**Comment by threepointone** [comment]
This is pages, so it may not be related to the routes issue

**Comment by lemniskett** [comment]
I used the Cloudflare Worker template for generating the API token:
- Lemniskett@gmail.com's Account - Workers KV Storage:Edit, Workers Scripts:Edit, Account Settings:Read, Workers Tail:Read, Workers R2 Storage:Edit
  - All zones - Workers Routes:Edit
- All users - User Details:Read

**Comment by helsus** [comment]
@lemniskett Just add  `Account - Cloudflare Pages - Edit` permission

**Comment by GregBrimble** [comment]
@helsus is correct — you just need to add that permission. Thanks!

**Comment by lemniskett** [comment]
Thank you @helsus !
