### ISSUE TITLE
🐛 BUG: wrangler publish - 413 Request Entity Too Large

### ISSUE THREAD

**Issue by EatonZ** [cloudflare/wrangler2#1187]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Windows

### Describe the Bug

I upgraded my Workers Sites project from Wrangler v1 to v2(.0.8). I replaced my .toml file with an all command line implementation:

`wrangler publish "workers-site\index.js" --name="dev-site" --compatibility-date="2022-06-05" --routes="www.dev-site.dev/*" --routes="dev-site.dev/*" --site="dist" --minify`

Wrangler starts up and starts reading/uploading many files without issue. Then it hangs at a particular file every time, and a 413 Request Entity Too Large HTTP error is encountered:

![413](https://user-images.githubusercontent.com/3020941/172064405-b3493fd3-a523-41ed-b4fb-d1cbc7468ba4.png)

That version\index.html file is only 32 bytes.

This site uploaded without issue using Wranger v1. It is only after upgrading to v2 that this problem has started occurring.

**Comment by threepointone** [comment]
Oh darn sorry about that. Could you tell me what the size of the folder you're uploading is?

**Comment by EatonZ** [comment]
@threepointone 151 MB (349 files, 61 folders)
I am aware of the KV value size limits and I do not go past that, hence Wrangler v1 having no issues.

**Comment by threepointone** [comment]
Ok this is probably something we should fix on our side, looks like the bulk upload endpoint might have a limit, so we might have to split and batch this into multiple calls. Sorry!

**Comment by EatonZ** [comment]
@threepointone I figured that's what it was. I'm surprised that no one has run into this yet!

**Comment by threepointone** [comment]
I'm surprised too!! I'll verify it during the week.

**Comment by EatonZ** [comment]
@threepointone On a side note, did I specify the routes correctly in the command line? Couldn't find an example of specifying a string array.
Additionally, is `--minify` needed or is that the default?

**Comment by threepointone** [comment]
You've specified multiple routes correctly, that is indeed the right way to do it. And minify isn't the default (yet), so you're good. 

I'm working on configuration / flags docs soon, and I'll make it a point to specify this.

**Comment by threepointone** [comment]
This is released in wrangler@2.0.11, let us know if you see any further issues! And thank you for your patience!

**Comment by EatonZ** [comment]
It does work for me now in 2.0.11, thanks!
