### ISSUE TITLE
🐛 BUG: dev --local fails when Worker fetches origin

### ISSUE THREAD

**Issue by sbquinlan** [cloudflare/wrangler2#1196]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Mac

### Describe the Bug

The following simple Worker works without --local but recurses with --local. 

```ts
export interface Env {}

export default {
  async fetch(
    request: Request,
    _env: Env,
    _ctx: ExecutionContext
  ): Promise<Response> {
    return await fetch(request.url)
  }
}
```

Running `wrangler dev` will work and correctly fetch from the origin server. Running this with `--local` will fail. On failure, Miniflare suggests setting the option `upstream` in its config, but there is no way to do that using either CLI options or changing the TOML as the 'miniflare' TOML option is deprecated and ignored.

**Comment by threepointone** [comment]
Quick question: Do you have routes in your wrangler.toml? I'm asking because I wonder if by default we should simply use the domain specified in your routes automatically as the upstream (unless of course it's proxying to totally different domain, which may require extra config).

**Comment by sbquinlan** [comment]
@threepointone yeah, I think either using dev.host in the toml or from route would be a reasonable default / fix for this, but one of the main perks of using miniflare is to run fully local (including origin) so having a CLI option to override "upstream" for miniflare would be clutch for those using --local.

**Comment by threepointone** [comment]
Yeah I can't think of a way to make this fully inferable for a clearly valid usecase, so I think we'll have to introduce config for this. Thanks for reporting!

**Comment by threepointone** [comment]
Fixed via https://github.com/cloudflare/wrangler2/pull/1207#issuecomment-1165310921
