### ISSUE TITLE
Documentation: Configuration page should include information about optional fields and default values

### ISSUE THREAD

**Issue by jkup** [cloudflare/wrangler2#1205]
### What version of `Wrangler` are you using?

2.0.2

### What operating system are you using?

Mac

### Describe the Bug

Happy to discuss more about this but I think it would be nice if https://developers.cloudflare.com/workers/wrangler/configuration/ showed subfields that are optional and/or what the default value would be?

I don't mean for top-level fields necessarily but where we take objects and they have optional sub-fields? Like `preview_id` for `kv_namespaces` or `environment` under `services`?

**Comment by sbquinlan** [comment]
probably should be reported against the docs repo: [cloudflare/cloudflare-docs](https://github.com/cloudflare/cloudflare-docs)

**Comment by KianNH** [comment]
A WIP concept: https://kian-wrangler-configuration.cloudflare-docs-github.pages.dev/workers/wrangler/configuration/

**Comment by cameron-robey** [comment]
I think we can now close this with:
- https://github.com/cloudflare/cloudflare-docs/pull/5150

Thanks @KianNH !
