### ISSUE TITLE
🐛 BUG: wrangler init fails to initialize git

### ISSUE THREAD

**Issue by nexxeln** [cloudflare/wrangler2#1208]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

WSL Ubuntu

### Describe the Bug

When I ran `wrangler init my-worker`, there was a prompt for if I would like to use `git` or not. I selected `y` and it threw the following error:

```
Command failed with exit code 129: git init --initial-branch=main

  error: unknown option `initial-branch=main'
  usage: git init [-q | --quiet] [--bare] [--template=<template-directory>]
  [--shared[=<permissions>]] [<directory>]

      --template <template-directory>
                            directory from which templates will be used
      --bare                create a bare repository
      --shared[=<permissions>]
                            specify that the git repository is to be shared amongst several users
      -q, --quiet           be quiet
      --separate-git-dir <gitdir>
                            separate git dir from working tree
```

My git version is `2.25.1`

![demo](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/WindowsTerminal_voMrSCpfoh.gif)

**Comment by nexxeln** [comment]
Nevermind, turns out I just need to update git. Sorry for wasting your time.

**Comment by threepointone** [comment]
It's not a waste of time, it's a valid bug! We want to fix it, tracking here https://github.com/cloudflare/wrangler2/issues/1168

**Comment by petebacondarwin** [comment]
And fixed here https://github.com/cloudflare/wrangler2/pull/1209 !!

**Comment by nexxeln** [comment]
Great! Glad I was of some help! 
PS: @threepointone great talk with Theo today, loved it!
