### ISSUE TITLE
🐛 BUG: `wrangler pages dev` allows local/unbundled imports (js/mjs) from _worker.js

### ISSUE THREAD

**Issue by theprojectsomething** [cloudflare/wrangler2#1214]
### What version of `Wrangler` are you using?

2.0.6

### What operating system are you using?

Mac

### Describe the Bug

More like an oversight than a bug .. 

When developing pages locally you are able to import files directly from an unbundled `_worker.js`. As a pages noob it took a not insignificant amount of time to debug why my super clever setup, which was all good and dandy in workers (it's in the name), fell over spectacularly in pages. Heads up to the discord.

If it's not an easy fix (or is intentional), then a warning in dev that *"imports aren't supported in prod"* or somesuch would totally suffice I think. Cheers for a great product!

**Demo _worker.js:**
```js
import { ahoy } from './module.mjs'
import hoy from './script.js'

export default {
  async fetch(request, env, ctx) {
    console.log({ ahoy, hoy });
    return new Response(ahoy);
  }
}

```
Previewing works fine:
```
$ wrangler pages dev ./ 
Serving at http://localhost:8788/
{ ahoy: true, hoy: true }
GET / 200 OK (59.93ms)
```

... Wrangler deployment then proceeds without a hitch:

```sh
$ ls
_worker.js	index.html	module.mjs	script.js
$ wrangler pages publish ./
🌎  Uploading... (3/3)

✨ Success! Uploaded 3 files (1.29 sec)

✨ Deployment complete! Take a peek over at https://ahoy-hoy
```

... but of course everything has actually exploded:

```
$ wrangler pages deployment list
┌─────────────┬────────┬─────────┬──────────────────┬────────────────┬──────────────────────────────────┐
│ Environment │ Branch │ Source  │ Deployment       │ Status         │ Build                            │
├─────────────┼────────┼─────────┼──────────────────┼────────────────┼──────────────────────────────────┤
│ Production  │ master │ 0c2044f │ https://ahoy-hoy │ Failure        │ https://dash.cloudflare.com/ahoy │
└─────────────┴────────┴─────────┴──────────────────┴────────────────┴──────────────────────────────────┘
```

**Comment by theprojectsomething** [comment]
Hey thanks so much for looking into this @Skye-31 (and @GregBrimble) .. Small thing, but I've noticed that I'm getting your error the first time I run `wrangler pages dev ./` regardless of whether there are imports or not:

```error
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
✘ [ERROR] _worker.js is importing from another file. This will throw an error if deployed.

  You should bundle your Worker or remove the import if it is
  unused.
```

Could it be something to do with this [catchall filter](https://github.com/cloudflare/wrangler2/blob/687170d71d1e072a3708ef42aef58d5cdef67394/packages/wrangler/src/pages/dev.tsx#L457)? No idea how the build/plugin system works but thought I would flag it. 

Thanks again.

**Comment by mglikesbikes** [comment]
+1 from me
