### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by SimonyanG** [cloudflare/wrangler2#1221]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Mac,Linux

### Describe the Bug

publishing static assets returns error 500, started today 10 Jun 2022 
`wrangler pages publish build --project-name some-test --branch test`

```
✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
  <!--[if I... (length = 3796)

  POST /pages/assets/check-missing -> 500 Internal Server Error

```

**Comment by UnlimitedBytes** [comment]
Having the same issue on **Wrangler v2.0.8 operating on Windows**

**Comment by WalshyDev** [comment]
This should be fixed now, thanks for the report :)
