### ISSUE TITLE
🐛 BUG: Received a malformed response from the API

### ISSUE THREAD

**Issue by arggh** [cloudflare/wrangler2#1222]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Mac

### Describe the Bug

I can't publish my project anymore (which I could publish yesterday just fine).

```
❯ wrangler publish --env staging
 ⛅️ wrangler 2.0.8
-------------------
Your worker has access to the following bindings:
- Vars:
  - ENVIRONMENT: "staging"

✘ [ERROR] Received a malformed response from the API

  {
    "result": {
      "id": "front-staging",
      "etag": "c2bc4c316edc5f156011be2cafb1a0ba8e2e6584c277... (length = 2809573)

  PUT /accounts/d7c7e62dcb0e66.......7b90d86b10/workers/scripts/front-staging -> 200 OK

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

**EDIT:** Correction, it seems the project was published, even though Wrangler gives me an error.

**Comment by 0x15f** [comment]
I am encountering this issue as well. All was fine yesterday, attempting to redeploy (the same code that worked yesterday) yields a malformed response error.

**Comment by petebacondarwin** [comment]
Is the size of the Worker script particularly large?
It looks like the response is very large (~ 2809573) but it looks like it is valid JSON.
Perhaps we are failing to parse it because it is too large.
I wonder if the backend has changed to return the script contents in the response object?

Can you try running Wrangler in a debugger, pausing at the point this error is thrown and checking what the `err` value is?

The relevant code is: 

https://github.com/cloudflare/wrangler2/blob/6b44822b1742e2b84e6b38c383e78043db922b67/packages/wrangler/src/cfetch/internal.ts#L46-L61

**Comment by 0x15f** [comment]
> Is the size of the Worker script particularly large? It looks like the response is very large (~ 2809573) but it looks like it is valid JSON. Perhaps we are failing to parse it because it is too large. I wonder if the backend has changed to return the script contents in the response object?
> 
> Can you try running Wrangler in a debugger, pausing at the point this error is thrown and checking what the `err` value is?
> 
> The relevant code is:
> 
> https://github.com/cloudflare/wrangler2/blob/6b44822b1742e2b84e6b38c383e78043db922b67/packages/wrangler/src/cfetch/internal.ts#L46-L61

In my case, it is quite large. The API is returning the entire script content, it is a parse error within the `script` property on the response. 

**Error:**
```
ParseError: Unexpected token <
```

**Comment by petebacondarwin** [comment]
I wonder if this is related to https://github.com/cloudflare/wrangler2/issues/1219?
Can you say whether you have "orange clouded" the domain you are publishing to?

**Comment by 0x15f** [comment]
I do have an orange cloud, this is a worker-only domain, not a worker proxy.

**Comment by 0x15f** [comment]
> 

Yes, custom domains, my apologies for the miswording.

**Comment by petebacondarwin** [comment]
When you say:

> When saving the output to a JSON file, the script contents arent properly escaped.

can you describe what exactly is not being escaped correctly? For example is it the quotation marks or something?

**Comment by 0x15f** [comment]
> When you say:
> 
> > When saving the output to a JSON file, the script contents arent properly escaped.
> 
> can you describe what exactly is not being escaped correctly? For example is it the quotation marks or something?

I cannot precisely tell what is not being escaped, the payload is too large for VSCode to syntax highlight it all. Below is the link to a gist with the response. When copying it into jsonformatter.org it yields

```
Parse error on line 15:
...   ],    "script": "(() => {\n  // dist
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

https://gist.github.com/0x15f/48014b9c09416ca2940d8275bfeb39ee

**Comment by threepointone** [comment]
I'll keep this issue open until the api fix rolls out

**Comment by threepointone** [comment]
I believe the escaping bug has been fixed on the api end, and the additional fix to not include it given the excludeScript query params will be rolled out soon. So I'm going to close this. Thanks everyone for reporting!
