### ISSUE TITLE
🐛 BUG: Wrangler is loading the wrong content for certain files

### ISSUE THREAD

**Issue by lorenzo** [cloudflare/wrangler2#1225]
### What version of `Wrangler` are you using?

2.0.2

### What operating system are you using?

Mac

### Describe the Bug

I have a site built with sphinx. Deployed using this command

```
 wrangler pages publish --project-name docs build/html
```

All the assets under the `_static` folder are served by Cloudflare with the contents of `index.html` in the root of the `build/html` folder. This results in the site have no CSS styling.

If I upload the same folder using the web interface, things work as expected.

**Comment by lorenzo** [comment]
probably related to https://github.com/cloudflare/wrangler2/issues/1087

**Comment by Vladi-ed** [comment]
> probably related to #1087

yes, same issue

**Comment by GregBrimble** [comment]
This should be fixed in [2.0.15](https://github.com/cloudflare/wrangler2/pull/1284).
