### ISSUE TITLE
🐛 BUG: `wrangler dev --local` occasionally emits 'Waiting for connection...' continuously

### ISSUE THREAD

**Issue by timabb031** [cloudflare/wrangler2#1226]
### What version of `Wrangler` are you using?

2.0.9

### What operating system are you using?

Windows 10

### Describe the Bug

When I run `wrangler dev --local` in Powershell or cmd, sometimes it'll just emit 'Waiting for connection...' continuously until I force close via Ctrl+C.  Other times it works fine. 

e.g.

```
 ⛅️ wrangler 2.0.8
-------------------
⎔ Starting a local server...
Waiting for connection...
Waiting for connection...
Waiting for connection...
Waiting for connection...
(line above repeats forever)
```

https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/inspect.ts#L290

I've logged the websocket URL being used for the connection in the function above and when the issue occurs it appears the URL is a partial one (e.g. ws://127.0.0.1:9229/91fedb) instead of the full URL returned by `node --inspect` (e.g. ws://127.0.0.1:9229/91fedbcf-52c1-421c-9228-146631a3717b).  Opening a websocket with the partial URL causes the `"unexpected-response"` event to fire (due to the server returning 400 Bad Request) which then results in an endless loop as the connection is retried (see `retryRemoteWebSocketConnection`).

The source of the websocket URL appears to be parsed in:
https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/dev/local.tsx#L255

On my machine this handler typically receives data in two chunks (i.e. the event fires twice).  If a chunk contains a partial URL then the regex matches and `setInspectorUrl` is called with the invalid partial URL (which causes the issue).  If none of the chunks match the regex then `setInspectorUrl` is never called and the issue doesn't occur. 

I've managed to fix this locally by accumulating the chunks and then testing the accumulated data with a modified regex that requires a 36 character UUID in the URL for a match. 

Hope this helps / I'll open a PR with a fix shortly.

**Comment by petebacondarwin** [comment]
Awesome stuff @timabb031
