### ISSUE TITLE
🐛 BUG: Pages `next()` headers mutable in local dev, but not in production

### ISSUE THREAD

**Issue by Cherry** [cloudflare/wrangler2#1244]
### What version of `Wrangler` are you using?

2.0.9

### What operating system are you using?

Windows 10

### Describe the Bug

The Pages Functions docs has [this example](https://developers.cloudflare.com/pages/platform/functions/#exporting-middleware):

```js
const hello = async ({ next }) => {
  const response = await next();
  response.headers.set('X-Hello', 'Hello from functions Middleware!');
  return response;
};
```

This works perfectly fine in local dev with `pages dev`, but fails in production due to the `next()` response having immutable headers there. This leads to frequent frustration for folks since there's no way to get function error logs to debug this inconsistency.

To make this work in prod, you have to do something like this:
```js
const hello = async ({ next }) => {
  const rawResponse = await next();
  const response = new Response(rawResponse.body, rawResponse); // clone response to create mutable headers
  response.headers.set('X-Hello', 'Hello from functions Middleware!');
  return response;
};
```

Related: https://github.com/cloudflare/cloudflare-docs/pull/4773

**Comment by Cherry** [comment]
The change in #1325 appears to work great, thanks very much! I ran the follow:
```js
export async function onRequestGet({next}){
	const response = await next();
	response.headers.set('x-test', 'hello')
	return response;
}
```
and was able to see the `x-test` header when using the new wrangler version both in prod and dev, and an exception in prod when using the current release version, as expected. Woot! 🎉

**Comment by sidharthachatterjee** [comment]
No, thank _you_ very much! We appreciate you. I'll give you a heads up when we have a released version!

**Comment by sidharthachatterjee** [comment]
@Cherry It's now out in `wrangler@2.0.15` 🎉

**Comment by Cherry** [comment]
> @Cherry It's now out in `wrangler@2.0.15` 🎉

Awesome, thank you!!
