### ISSUE TITLE
console logs from imported modules

### ISSUE THREAD

**Issue by sirganya** [cloudflare/wrangler2#1257]
### Describe the solution

When I have a `console.log` in a module I've imported into my wrangler module it appears in `wrangler tail` but not in the terminal  or dev tools in `wrangler dev` mode. 

Would it be possible to have `wrangler tail` show logs from `wrangler dev` or have all console logs from imported modules appear in the dev tools.

**Comment by sirganya** [comment]
oh, now it works. Obviously I needed to waste your time first.

**Comment by threepointone** [comment]
Lol no worries https://en.wikipedia.org/wiki/Heisenbug
