### ISSUE TITLE
multiple accounts + dev = Silent Crash in `dev` mode

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/wrangler2#1258]
#### Describe the bug

When running `dev` mode in wrangler, service will run for a second, prompt for an account, and then silently crash.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run `wrangler dev` with project that previously worked.
2. Wait a second while the `dev` instance boots up.
3. Select Account from list.

#### Expected behavior

After running `wrangler dev`, `wrangler` should prompt for your account **BEFORE** starting up, and then should not crash unexpectedly.

#### Environment and versions

Fill out the following information about your environment.

* operating system: macOS Monterey v12.4
* output of `wrangler -V`: `2.0.9`
* output of `node -v`: `v18.2.0`
* content of `wrangler.toml`:
```toml
name = "gitdiffbot"
compatibility_date = "2022-05-25"
main = "dist/index.js"

kv_namespaces = [
  {binding = "KV", id = KVID, preview_id = KVID}
]

[triggers]
crons = ["0 */6 * * *"]

**Comment by threepointone** [comment]
Could you try running `wrangler login` before starting `wrangler dev` and tell if the problem persists?

**Comment by andon** [comment]
@threepointone I'm experiencing the same bug. It happens from `wrangler@2.0.9`. The problem persists when I run `wrangler login` before `wrangler dev`.

**Comment by threepointone** [comment]
Can you confirm that you have multiple account ids?

**Comment by andon** [comment]
@threepointone Yes I do. 3 accounts.

**Comment by threepointone** [comment]
Yeah I think we have a bug here, sorry about that. This is probably a blocker for anyone with multiple accounts. We'll discuss it today and figure out a fix/workaround. Sorry! Please downgrade to 2.0.9 for now.

**Comment by threepointone** [comment]
A workaround could be to enter `account_id = "your account is"` in wrangler.toml (or as an env var like `CLOUDFLARE_ACCOUNT_ID=your account wrangler dev`)

**Comment by andon** [comment]
> Yeah I think we have a bug here, sorry about that. This is probably a blocker for anyone with multiple accounts. We'll discuss it today and figure out a fix/workaround. Sorry! Please downgrade to 2.0.9 for now.

Downgrade to 2.0.8 ;)

The workaround with adding the account-id in wrangler.toml does the trick. Thanks.

**Comment by threepointone** [comment]
I suspect it's because we have 2 things listening for input, the hotkeys bar, and the dropdown select in multiple accounts.

**Comment by petebacondarwin** [comment]
Oh! Right. Maybe even the fact that we are trying to call Ink.js `render()` for the dropdown from within an Ink.js component that is already being rendered :-/

**Comment by threepointone** [comment]
That's probably it!

**Comment by petebacondarwin** [comment]
The fix is up for review...

**Comment by novincode** [comment]
I've made a CLI tool on top of Wrangler for myself. but It's open source and you can use it too. It lets you manage mutliple wrangler accounts easily using api tokens 
[CFman](https://github.com/novincode/cfman)
`npx cfman --help`
