### ISSUE TITLE
Actions items before merging v2+v1 repositories 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1262]
(well maybe not merging, but definitely making this the primary one). 

- [ ] We should probably implement `wrangler generate` as a layer on top of `npm init cloudflare`. We need to review all the templates, as well all the older v1 templates, and come up with a cohesive plan for it all. 
- [ ] Generate prebuilt binaries OR make a call to what we're going to do here for folks who need that workflow
- [ ] Evaluate the github action and make sure it works correctly with wrangler 2, or fox the things that don't 
- [ ] We need to review the docs to make sure they're at apr with v1. Specifically we need to expand the config page, finish up all the other unfinished pages, and make sure references to the pages from everywhere are pointing at the right pages 
- [ ] There are 70 open issues on https://github.com/cloudflare/wrangler/issues, and I think issues there should either be closed, or moved here, or resolved in some way 

This is a moving target, this list may change a bit unto it settle

**Comment by IgorMinar** [comment]
I'm in favor of not offering standalone binaries unless we have a strong signal that this would be a significant issue for a large group of our customers. Standalone binaries are non-trivial to maintain and offer incomplete DX (only a subset of functionality would work without npm dependencies, e.g. typescript, or worker-types, so we'll be able to provide a better experience if we expect that node support just works.

The docs have been increasingly getting better thanks to contributions from Kate. Maybe we could organize a doc hackathon to do a pass through all the content.

As for the old issues, I recommend closing them with a pointer to wrangler v2 as the replacement of v1.

The remaining items lgtm.

**Comment by threepointone** [comment]
Thanks for the feedback, we'll discuss it and take a call.

**Comment by lrapoport-cf** [comment]
overall, wrangler v1 deprecation is being tracked internally, so closing this issue in favor of that. specifically for each item noted: 
- wrangler generate has been implemented: https://github.com/cloudflare/wrangler2/issues/1402 / https://github.com/cloudflare/wrangler2/pull/1438
- per @IgorMinar 's suggestion we will not offer standalone binaries
- an internal ticket has been created to evaluate the github action and address if necessary
- docs changes are being tracked internally, but the current list of PRs include: https://github.com/cloudflare/cloudflare-docs/pull/6934, https://github.com/cloudflare/cloudflare-docs/pull/6141, https://github.com/cloudflare/cloudflare-docs/pull/6905, https://github.com/cloudflare/cloudflare-docs/pull/6925
- we plan to close issues and PRs in the wrangler v1 repo per the suggestions here and there is an internal ticket to track this
