### ISSUE TITLE
🚀 Enable debug log reporting

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#1266]
Currently our logger can receive messages for "debug", "info", "warn" and "error". But only the "info" and higher logs are actually rendered.

We should allow developers to specify the log-level when running Wrangler. Two approaches (we could do one or both):

- look for an environment variable: WRANGLER_LOG_LEVEL=debug
- look for a command line arg: --log-level=debug

**Comment by petebacondarwin** [comment]
This will be useful to Pages projects and internal Cloudflare Workers projects.

**Comment by threepointone** [comment]
Completed in https://github.com/cloudflare/wrangler2/pull/1275
