### ISSUE TITLE
🐛 BUG: blake3_js.js is missing from modules. 

### ISSUE THREAD

**Issue by toomanylogins** [cloudflare/wrangler2#1268]
### What version of `Wrangler` are you using?

2.0.12

### What operating system are you using?

Windows

### Describe the Bug

Clean install of wrangler. File node_modules\blake3-wasm\dist\wasm\nodejs\blake3_js.js is missing from package. This only applies if the node-modules folder is on a network drive. Ok on local drive.

Uninstall does not update package.json.

{
  "name": "blake3-js",
  "version": "0.1.0",
  "files": [
    "blake3_js_bg.wasm",
    "blake3_js.js",
    "blake3_js_bg.js",
    "blake3_js.d.ts"
  ],
  "main": "blake3_js.js",
  "types": "blake3_js.d.ts"
}

**Comment by threepointone** [comment]
Closing this, happy to investigate if you can provide a reproduction or more details.
