### ISSUE TITLE
🐛 BUG: kv commands do not roundtrip binary data correctly

### ISSUE THREAD

**Issue by koeninger** [cloudflare/wrangler2#1273]
### What version of `Wrangler` are you using?

2.0.12

### What operating system are you using?

Mac

### Describe the Bug

Regression compared to wrangler1, raised by customers in discord. Even if https://github.com/cloudflare/wrangler2/pull/1255 fixes puts, it looks like reads don't work correctly.

bash-3.2$ dd if=/dev/urandom of=/tmp/random-binary bs=1 count=4096
4096+0 records in
4096+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.031555 s, 130 kB/s
bash-3.2$ wrangler1 kv:key put --binding="NEWKV" "a-random-key" "/tmp/random-binary" --path
✨  Success
bash-3.2$ wrangler1 kv:key get --binding="NEWKV" "a-random-key" > /tmp/random-binary-roundtrip
bash-3.2$ wrangler2 kv:key get --binding="NEWKV" "a-random-key" > /tmp/random-binary-roundtrip2
bash-3.2$ md5sum /tmp/random-binary
35f2320ed7c5c8ad4fd8056c6773c365  /tmp/random-binary
bash-3.2$ md5sum /tmp/random-binary-roundtrip
35f2320ed7c5c8ad4fd8056c6773c365  /tmp/random-binary-roundtrip
bash-3.2$ md5sum /tmp/random-binary-roundtrip2
2c8bb93dd8bd9c3a22e0158195365bda  /tmp/random-binary-roundtrip2

**Comment by threepointone** [comment]
Thank you for reporting! We should fix this

**Comment by threepointone** [comment]
We've currently reverted https://github.com/cloudflare/wrangler2/pull/1255 and will land it back as soon as we have a fix for `kv:key read` as well. Thank you for reporting this!
