### ISSUE TITLE
🚀 Feature Request: Remove or update dependencies on NPM packages with security vulnerabilities

### ISSUE THREAD

**Issue by wiredprairie** [cloudflare/wrangler2#1291]
### Describe the solution

For brand new explorers/developers of Cloudflare Workers using Wrangler, the install experience for Wrangler should be free of any warnings or errors. It's an unpleasant welcome experience for example if one were to install Wrangler for the first time and see something like this:

**`> npm install -g wrangler`**
```
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

added 59 packages, and audited 60 packages in 6s

1 package is looking for funding
  run `npm fund` for details

9 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

The install experience should install Wrangler without errors or warnings.

**Comment by petebacondarwin** [comment]
Thanks for reporting this. It is a duplicate of https://github.com/cloudflare/wrangler2/issues/1232. Let's track it there.

**Comment by wiredprairie** [comment]
Ok—as long as that other issue is covering the suggested security vulnerabilities. I didn’t look further.
________________________________
