### ISSUE TITLE
Releases 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#13]
This issue tracks how we should probably do releases. 

- I'm a fan of [changesets](https://github.com/atlassian/changesets), let's do that.
  - That solves a number of process problems at once: changelogs, waiting for people to cut a release, permissions, etc 
- Additionally, every commit should be published on to npm as an alpha (or some other tag). This should make experimentation a little easy too.
- Finally, it would be nice if we could publish PRs to a separate temporary registry. Open to ideas here.

**Comment by JacobMGEvans** [comment]
> It would be nice if we could publish PRs to a separate temporary registry. Open to ideas here. 

I could create a publish on every PR that uses commit hash `npm publish --tag HASH`

**Comment by threepointone** [comment]
No, we don't want hundreds and thousands of tags, and we don't want other people's unverified code on our package.

**Comment by JacobMGEvans** [comment]
> No, we don't want hundreds and thousands of tags, and we don't want other people's unverified code on our package.

Hmm... 🤔  we should talk on this more then. I totally get what you're saying and will look into this a little more

**Comment by JacobMGEvans** [comment]
Also pointing out the first two bullets have been done for the repo now 😄

**Comment by petebacondarwin** [comment]
After the work to publish PR artifacts has completed, this can be closed.
