### ISSUE TITLE
🚀 Feature Request: A way to specify custom polyfills

### ISSUE THREAD

**Issue by kensnyder** [cloudflare/wrangler2#1304]
### Describe the solution

In wrangler 1, I could add a custom webpack.config.js and specify aliases under `resolve.alias`. This allowed me create small shims to support npm packages that currently only work on node (such as `@elastic/elasticsearch` and `express`).

So for example, when express calls `require('net')` I can provide my own `net.js` file with my own functionality.

Looking at miniflare, it appears that I could use a custom build with webpack or the esbuild plugin `esbuild-plugin-alias`, but that requires me to create a custom build process.

I noticed that the request in ticket #1011 and others would be satisfied by this way to specify a custom polyfill to use on `require` or `import`.

**Comment by threepointone** [comment]
I don't think we have plans just yet to enable overriding of polyfills in a granular fashion as you're describing. The reason we have a `node_compat` flag is so that we can now start working on them internally, with better polyfills that we'll provide, and potentially runtime support. So for example, in the future, we'll provide our own version of 'net' that actually works without modifications. 

That said, I'm sympathetic to the idea of having aliasing functionality. It's just a hard decision to provide at the wrangler level because it can mess with other assumptions across other dependencies, and probably should be at a higher level of abstraction like a custom build. We'll keep discussing it. I think custom builds are a good workaround here for now for your current usecase. Thank you for filing this issue!

**Comment by kensnyder** [comment]
Thanks for considering.

A downside of improving the `node_compat` polyfills is that some libraries may want something stubbed one way and and some another.

I saw that there was a `rules` section in wrangler.toml which does does allow some esbuild configuration. This one.

```toml
[[rules]]
  type = "Text"
  globs = ["**/*.md"]
  fallthrough = true

```

Anyhow, I'll probably look next at a code change at the miniflare level that would allow adding  plugins to esbuild. Maybe a change to miniflare's [build.mjs file](https://github.com/cloudflare/miniflare/blob/master/scripts/build.mjs).

@threepointone, I see that you are a contributor to miniflare as well. Would such a PR be welcome? 

I think my approach would be to allow package.json specify one or more files that should be executed to get additional options for `pkgBuildOptions`. Or is there a better approach you could recommend?

**Comment by threepointone** [comment]
Even if we own the polyfills with node_compat, you'll have the opportunity to override it with a custom build. So it's still a good solution. 

I don't think we'd accept this functionality in miniflare either tbh. 

Could you you explain why a custom build isn't a good solution for you? It feels perfectly right for a poweruser usecase like the one you're describing, where you'll have full control over how to alias and replace modules.

**Comment by kensnyder** [comment]
@threepointone In my personal use case, I wanted to write code that worked on both on NodeJS and Cloudflare Workers. Why? I don't like the risk of writing an entire app, not knowing if I could fit it into the max build size and max execution time. With Wrangler 1, it was surprisingly easy to make stubs that worked cross platform.

But the bigger draw is potentially for the reverse situation: apps written for NodeJS that can work with minimal changes; perhaps none if you can control the imports. I'd argue that Webpack's providing import aliasing without a plugin shows how common the use case is.

I look at the [Works on Workers](https://workers.cloudflare.com/works) page and it is hard to convince my peers that they should write apps for a platform where most npm libraries don't work. I'd love to see a place where most npm libraries DO work, even though many will need some sort of companion shim.

As far as why I'm hesitant to make a custom build:
1. It appears that I need to create a copy of [build.mjs](https://github.com/cloudflare/miniflare/blob/master/scripts/build.mjs), all to add just one line to insert a plugin (Or maybe I only need a 5-line equivalent of build.mjs, I don't know)
1. When Miniflare updates build.mjs, I may need to update my file to take advantage of new features.
1. I can't find any documentation about what Wrangler 2 features I lose if I use a custom build (maybe there aren't any)

Maybe you can clear up those points.
