### ISSUE TITLE
🚀 Feature Request: Report bundle/gzip size even on wrangler publish error

### ISSUE THREAD

**Issue by wallslide** [cloudflare/wrangler2#1328]
### Describe the solution

Currently, when there is an error such as:
```
Script startup timed out. This could be due to script exceeding size limits or expensive code in
  the global scope.
```
The bundle and gzipped sizes that would normally be shown are omitted (even on `wrangler@beta`). This makes it difficult to know if bundle size was the source of the error. I propose to show the bundle and gzip sizes even when the publish command fails.

FYI: if you have this issue and add `--dry-run` then you can see the bundle/gzipped sizes.

**Comment by threepointone** [comment]
Good catch!
