### ISSUE TITLE
Can't work with `jsc8` 

### ISSUE THREAD

**Issue by YUFENGWANG** [cloudflare/wrangler2#133]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Issue Description

Can't work with `jsc8` in cloudflare pages and functions

## Steps to Reproduce

1. clone this repo https://github.com/YUFENGWANG/sticker.ink
2. install deps and run `npm run dev`
3. install wrangler beta `npm install -g wrangler@beta`
4. Open a new terminal run ` wrangler pages dev ./dist --proxy=3000`
## Current Behavior

Build failed, and it says 

![image](https://user-images.githubusercontent.com/12859005/146634410-aafa4377-a532-4775-9b93-8b99dd1bd02c.png)

## Expected Behavior
worker scripts in function folder built correctly
## Failure Logs
```bash
Compiling worker to "/var/folders/hh/2zx_j24n4z7gntlh9yq3z4b00000gn/T/functionsWorker.js"
✘ [ERROR] Could not resolve "path"

    node_modules/.pnpm/jsc8@0.16.3/node_modules/jsc8/lib/cjs/util/joinPath.web.js:3:21:
      3 │ var path_1 = require("path");
        ╵                      ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

/Users/wenhu/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1493
  let error = new Error(`${text}${summary}`);
```

## Context

* C8 Version: ^0.16.3

**Comment by threepointone** [comment]
We have an issue tracking polyfilling libraries that assume a node environment (#101) which we'll get to in q1.

**Comment by YUFENGWANG** [comment]
Great job, looking forward to it.

**Comment by threepointone** [comment]
We landed initial support for node compatibility, either by adding `node_compat = true` in `wrangler.toml`, or by passing `--node-compat` in the command line, which should resolve this specific issue. Closing this issue, but lemme know if you face any further problems.
