### ISSUE TITLE
🐛 BUG: `wrangler pages dev` throws 404 for URL with unicode character

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/wrangler2#1338]
### What version of `Wrangler` are you using?

2.0.15

(**edit**: issue persists in 2.0.24)

### What operating system are you using?

Linux

### Describe the Bug

A directory with name `ń` (`%C5%84`) is served correctly with `wrangler pages publish`,
but throws a 404 when accessed with `wrangler pages dev`.

**Comment by kotx** [comment]
This issue seems to be present for ALL filenames that are url-encoded? Even files with spaces in the names 404.

**Comment by dgokcin** [comment]
I am having the same issue.

**Comment by dgokcin** [comment]
@Hexstream do you have a workaround for a temporary fix? In my next static export website, I have dynamic routes + functions and I am not able to run my function locally because of this.

**Comment by dgokcin** [comment]
@Hexstream I want to use wrangler pages dev in local development so I dont think I want a preview environment or anything that is not on the local pc.

**Comment by dgokcin** [comment]
also @Hexstream do you agree thet #1437 is related eith this?

**Comment by Hexstream** [comment]
> I want to use wrangler pages dev in local development so I dont think I want a preview environment or anything that is not on the local pc.

Right now I think your options would be not using encoded URLs, using preview deployments, or wait until this issue is fixed.

I'm not sure why you wouldn't want to use preview deployments, since they can even be secured if you like.

-------------------

I'm not sure why you would want to use brackets in URLs in the context of #1437, but I certainly don't expect brackets in URLs to work in local dev before this issue is fixed.

**Comment by dgokcin** [comment]
> > I want to use wrangler pages dev in local development so I dont think I want a preview environment or anything that is not on the local pc.
> 
> Right now I think your options would be not using encoded URLs, using preview deployments, or wait until this issue is fixed.
> 
> I'm not sure why you wouldn't want to use preview deployments, since they can even be secured if you like.
> 
> -------------------
> 
> I'm not sure why you would want to use brackets in URLs in the context of #1437, but I certainly don't expect brackets in URLs to work in local dev before this issue is fixed.

I am using nextjs and I have a /pages/orders/[id].js which throws a 404 because of failing to decode brackets. this works if published but not with wrangler pages dev.

**Comment by sidharthachatterjee** [comment]
Closing this in favour of https://github.com/cloudflare/wrangler2/issues/1437

Thanks!

**Comment by Hexstream** [comment]
I think my earlier issue was more concise and to the point, but whatever. ;P

**Comment by Hexstream** [comment]
Surprisingly not fixed by #1552 in 2.0.24.

**Comment by Hexstream** [comment]
Since #1437 is fixed but not this issue, I believe these are separate issues after all, hence this issue should be reopened.

**Comment by Hexstream** [comment]
Thank you for reopening and looking into this! ❤️

**Comment by Skye-31** [comment]
After some testing, this is not a wrangler issue, but instead a miniflare issue.
I have created an [issue on their repo](https://github.com/cloudflare/miniflare/issues/326), and would recommend you follow that instead 🙂

**Comment by Hexstream** [comment]
Awesome, thanks!!

**Comment by Hexstream** [comment]
I can confirm this is fixed as of wrangler 2.0.28.
