### ISSUE TITLE
🐛 BUG: `URLPattern` incorrectly throws an error when constructed with a valid URL pattern string

### ISSUE THREAD

**Issue by samlaycock** [cloudflare/wrangler2#1339]
### What version of `Wrangler` are you using?

2.0.15

### What operating system are you using?

Mac

### Describe the Bug

When passing a valid (according to Chrome's implementation at least) URL pattern string to the `URLPattern` constructor, it will incorrectly throw saying the string is invalid.

Reproduction (this line anywhere in executing worker code):

`new URLPattern("http{s}?://test.something.local/*");`

This will throw the error `Failed to construct 'URLPattern': invalid pathname pattern 'http{s}?://test.something.local/*'.`. It appears to be a problem with the [`URLPattern` polyfill](https://github.com/kenchris/urlpattern-polyfill) being used.

**Comment by petebacondarwin** [comment]
I cannot reproduce this problem.
Here is a repository you can try: https://github.com/petebacondarwin/test-url-pattern

Run

```
git clone https://github.com/petebacondarwin/test-url-pattern
cd test-url-pattern
npm i
npx wrangler dev
```

When I run that I see that the URLPattern instantiates correctly and then matches the URL I pass to it.

**Comment by threepointone** [comment]
Quick question - are you using Pages?

**Comment by samlaycock** [comment]
Sorry, completely my fault, I was not paying attention to how the `URLPattern` was being constructed. All working fine. Thanks for the quick response!
