### ISSUE TITLE
🐛 BUG:  Uncaught TypeError: Cannot read properties of undefined (reading 'memory')

### ISSUE THREAD

**Issue by mettke** [cloudflare/wrangler2#1341]
### What version of `Wrangler` are you using?

2.0.15

### What operating system are you using?

Linux

### Describe the Bug

We're using wrangler2 in combination with rust. Our stack is:
```
worker-rs: 0.0.10
worker-build: 0.10.3
```

When we try to `wrangler publish` we get the error:
```
✘ [ERROR]A request to the Cloudflare API (/accounts/xxxx/workers/scripts/xx-worker-name-xx) failed.
  Uncaught TypeError: Cannot read properties of undefined (reading 'memory')
    at line 0
   [code: 10021]
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
```

The same worker worked with `worker-rs: 0.0.9`

I'm happy to provide more information, but I'm not sure what you need to get a better grip of this error.

**Comment by petebacondarwin** [comment]
I believe the error appears to be from inside undici (the library providing `fetch`): https://github.com/nodejs/undici/blob/c8e4f3c670b368442e5ab040ab00af50a5319eb5/lib/client.js#L501

which would indicate that the llhttp object is `undefined`.

That object is created by instantiating a Wasm module: https://github.com/nodejs/undici/blob/c8e4f3c670b368442e5ab040ab00af50a5319eb5/lib/client.js#L324-L388

**Comment by mettke** [comment]
I was able to create a minimal repo. At least I hope that you now will have the same problem as I have.

### Reproduce

1. Check out https://github.com/mettke/worker-0.10-test
2. Check that worker-build 0.0.6 is installed `cargo install worker-build --version 0.0.6`
3. Check wasm-pack version 
```
wasm-pack --version
wasm-pack 0.10.3`
```
4. Check wrangler version
```
wrangler2 --version
2.0.15
```
5. Run `worker-build --release`
6. Run `wrangler2 dev`
7. Turn on local mode by using `l`
8. Result is `[ERROR] Miniflare process exited with code 1`

## Repo creation

To create the repo I did the following two things:
1. npm init cloudflare test worker-rust
2. Update worker-rs from `0.0.9` to `0.0.10`

**Comment by petebacondarwin** [comment]
Awesome reproduction @mettke! Thanks. I can confirm that I see the error.
It appears that there is a problem in the shim.mjs.  These lines:

```
cachedInt32Memory0 = new Int32Array(wasm.memory.buffer);
cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
```

execute before

```
wasm = new WebAssembly.Instance(_wasm, importsObject).exports;
```

causing the error.
I think that those lines above are being hoisted too high for some reason.
We need to dig into `worker-build` I think.

**Comment by petebacondarwin** [comment]
@caass any ideas what changes in `workers-rs` might have caused this?

**Comment by jakubadamw** [comment]
Seems related to https://github.com/cloudflare/workers-rs/issues/204.
