### ISSUE TITLE
RFC: `wrangler pull <name>` (and alternatives)

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1346]
When developers use Workers, they're commonly onboarded by creating a new Worker in the dashboard itself (by clicking on the "Create a Service" button). The browser-based editor is pretty good, it even has autocomplete, and the sheer efficiency of going from code to production in seconds is honestly amazing. Indeed, some folks use the dashboard editor as their _primary_ development experience. 

However, there comes a time when they want to _graduate_ to a more traditional development experience; using their own editor, splitting code up into modules, using third party dependencies from npm, and so on. Right now, they can achieve this by creating a new project (with `wrangler init <name>`), then copying over the script contents from the dashboard editor to created `index.ts`/`index.js`, then further copying over environment variables and other bindings into `wrangler.toml`. (iiuc, it's the vars/bindings part that's actually annoying to copy off since it's laborious and spread out in the dashboard.)

The proposal here is to implement a command (tentatively `wrangler pull <name>`, but we can bikeshed that) that will automate the above steps. It will take the name of the project, and then it will create a new project in the current directory, and then it will copy over the contents of the script to the new project, as well as populate `wrangler.toml` with vars/bindings.

Some notes that come to mind here - 

- We should _not_ be able to run this command that was previously published with wrangler, or any other tooling. It _has_ to have been a worker created in the dashboard. Otherwise we stand to confuse the user with multiple sources of the worker.
- We should also _not_ be able to run this command inside an existing project, since we could corrupt the project. We can workaround this, but we have to be careful.
- As an alternative, we could also have a "download as project" button in the dashboard that creates a zip file on-the-fly of a project that includes this worker. This option is nice because they don't have to have previously installed wrangler, it'll come bundled with dependencies, and we don't don't risk corrupting an exisiting project.
- Another alternative is to simply implement a command that can download only environment variables and bindings to be copy pasted into wrangler.toml. This would be useful in other scenarios too (like when vars have been edited in the dashboard and folks want to sync it to their project before doing a wrangler publish)

This is an open topic, we're not sure yet of the shape of the solution, and are even trying to understand the problem itself, but please feel free to contribute your thoughts and ideas.

**Comment by rozenmd** [comment]
I love this idea, almost reminds me of create-react-app's `eject`. 

> As an alternative, we could also have a "download as project" button in the dashboard

IMO we should start here. Someone comes along that has only been developing in the dashboard, hits "download as project", it becomes an on-ramp to getting started with using wrangler for developing their workers.

> Another alternative is to simply implement a command that can download only environment variables and bindings to be copy pasted into wrangler.toml.

(I'm not fully across how env vars work atm) am I right in thinking that it's possible to have a situation where environment variables locally don't match what's in dashboard? Like, you have vars locally, hit publish - does that not update the vars stored in dash atm?

**Comment by JacobMGEvans** [comment]
> Focusing on project initialization rather than "pulling" which suggests a potential sync which could be invoked on an existing project would clearly communicate the intent of the command.

I like the idea on focusing on initializing for this implementation. It could potentially in the future be worked into other potential sources like StackBlitz or personal template repos. 

> In any case, I prefer the wrangler based workflow over dashboard button, because by implementing this via dashboard, we'd set us up for a continuous maintenance of this feature as wrangler and wrangler.toml changes over time. The wrangler-based approach seems on to be less maintenance heavy, but I'd love to hear if others think otherwise.

I think, we shouldn't handle source control in any form or seemingly do so, which is how the dashboard code is treated. Think much like how similar tooling will pass that responsibility to remote source control tools like GitHub, BitBucket, etc... Example of a tooling that did something like what I am referring to is CodeSandbox with the Zeit (now Vercel) deploy but you could also initialize a GitHub with that code. That would separate source control and Worker tooling, so that we are not creating or competing with a quasi-source control tool against things like `git`, `gh` cli and other tooling specifically focused on source control.

**Comment by IgorMinar** [comment]
@JacobMGEvans apologies if I was not clear, but I think we are thinking of different things. What I had in mind was that `wrangler init` already has very nice DX for generating projects and customizing them to developer's needs via interactive prompts that impact the output.

I think it would be awesome if we could leverage this by enabling developers to scaffolding projects as they can today and then populating the index.js/index.ts and wrangler.toml with content pulled from an existing deployed worker (presumably created via the dash).

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans apologies if I was not clear, but I think we are thinking of different things. What I had in mind was that `wrangler init` already has very nice DX for generating projects and customizing them to developer's needs via interactive prompts that impact the output.
> 
> I think it would be awesome if we could leverage this by enabling developers to scaffolding projects as they can today and then populating the index.js/index.ts and wrangler.toml with content pulled from an existing deployed worker (presumably created via the dash).

No, I understood. If anything I stated previously was unclear I would be happy to clarify what I mean.

**Comment by JacobMGEvans** [comment]
This is meant to be a follow up for public transparency in planning and discussions pertaining to this happening internally and will be followed up with a spec (which I would be willing to share if people are interested).  

> What I had in mind was that wrangler init already has very nice DX for generating projects and customizing them to developer's needs via interactive prompts that impact the output.

In regards to this and based on additional internal discussions, particularly addressing my concerns around anything resembling source control or source management. I agree that the `wrangler init` is a good place for this to live, alternatively `wrangler generate` might have potential, however, `wrangler init` does have features that can be utilized to augment to project being pulled from Cloudflare Dashboard. 

 > I think it would be awesome if we could leverage this by enabling developers to scaffolding projects as they can today and then populating the index.js/index.ts and wrangler.toml with content pulled from an existing deployed worker (presumably created via the dash).
 
This highlights another good point mentioned internally in regards to agnostic of source control & storage  while providing the DX of local Cloudflare tooling like Wrangler and potentially improving the user ecosystem with options like TypeScript, GitHub initialization (could consider adding others). 

Cc: @IgorMinar

**Comment by IgorMinar** [comment]
Thanks for the update @JacobMGEvans!

**Comment by JacobMGEvans** [comment]
Please see #1538 for continuation of discussion and planning.
