### ISSUE TITLE
🐛 BUG: A request to the Cloudflare API failed [code: 10021] 

### ISSUE THREAD

**Issue by Aprillion** [cloudflare/wrangler2#1362]
### What version of `Wrangler` are you using?

2.0.15

### What operating system are you using?

Mac

### Describe the Bug

When I run `wrangler publish` for my Remix project at commit https://github.com/Aprillion/stampy-ui/tree/d043537b673cb10f6618ecc9fca4606a8e7750bc I see following error message:

```sh
...
Skipping - already uploaded.
↗️  Done syncing assets
Your worker has access to the following bindings:
- KV Namespaces:
  - STAMPY_KV: 37c6b989d87f403ca8b430669a33f671

✘ [ERROR] A request to the Cloudflare API (/accounts/f0374a5183ab1561eb2439f397ba7de9/workers/scripts/stampy-ui) failed.

  Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and generating random
  values, can only be performed while handling a request.
    at line 39971
    at line 40043
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

No idea how to investigate what exactly went wrong and how to fix / workaround the problem, thanks for any advice what to do.

**Comment by threepointone** [comment]
If you run `npx wrangler build`, it'll output the bundle that gets uploaded into `./dist'. Can you inspect that see what's happening on lines 39971, 40043?

**Comment by Aprillion** [comment]
thanks for the tip!

```js
  var UW = new AbortController(); // 39971
  ...
})(); // 40043 - closing bracket for IFFE starting at line 1
```

this code would get executed in `useEffect` => only inside the browser and not during server side rendering in a cloudflare worker

I will try a workaround using custom object `{abort: false}` instead of the real `AbortController`

is `wrangler publish` trying to run the code or is this error from some static analysis (that could be turned off or not)?

**Comment by threepointone** [comment]
Odd error. While we do "run" a worker when we upload it, we definitely don't send it any requests. (And I assume the code you have / remix runs doesn't run outside of a request). But more importantly, react shouldn't be running code inside effects on the server anyway, so I suspect their server detection logic might be buggy here (they might be detecting a worker environment as a "browser"). I'll investigate that some more myself, but closing this issue for now. Thank you so much for filing this issue and bringing it to our attention!
