### ISSUE TITLE
🐛 BUG: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by kuno989** [cloudflare/wrangler2#1367]
### What version of `Wrangler` are you using?

2.0.15

### What operating system are you using?

Mac

### Describe the Bug

Wrangler dev works fine, but returns 413 error when deploying.

✘ [ERROR] Received a malformed response from the API

  <html>
  <head><title>413 Request Entity Too Large</title></head>
  <body>
  <center><h1>413 Request En... (length = 184)

**Comment by kuno989** [comment]
> ### What version of `Wrangler` are you using?
> 2.0.15
> 
> ### What operating system are you using?
> Mac
> 
> ### Describe the Bug
> Wrangler dev works fine, but returns 413 error when deploying.
> 
✘ [ERROR] Received a malformed response from the API

  <html>
  <head><title>413 Request Entity Too Large</title></head>
  <body>
  <center><h1>413 Request En... (length = 184)

**Comment by petebacondarwin** [comment]
What is the size of deployed bundle? It should be shown in the console when you run `wrangler publish`.

**Comment by threepointone** [comment]
The bundle size we log in the terminal is only for the worker, whereas this error that OP is seeing refers to the bulk upload of assets. I have a (probable) fix up here https://github.com/cloudflare/wrangler2/pull/1392

**Comment by kuno989** [comment]
I found the reason for the bug.
When wrangler builds, the build file name is newly created, so the bundle size continues to grow.
[origin] index-JDIVOPHU.js 630kb
[new] index-UO3TSDNU.js 630kb ... total 1260kb

Eventually, this will add duplicate files, which will increase the bundle size.

Deleting the build file and creating a new one solved the problem.
In the end it was my mistake. sorry.
