### ISSUE TITLE
local dev server for remix sends scripts with invalid mime type

### ISSUE THREAD

**Issue by kyeotic** [cloudflare/wrangler2#137]
#### Describe the bug

When running the `create-remix` template in local dev (`npm run dev`) all bundled scripts are missing a MIME type, blocking them from execution.

#### Reproduce the bug

I'm unsure of the cause here. Several users in Discord did not encounter this issue, so ymmv

1. run `npx create-remix@latest`
2. add a `<button>` to your index route with an onClick that does _anything_ (.e.g `onClick={() => console.log('hello')}`)
3. run `npm run dev`
4. check the console

#### Expected behavior

Local dev server should return scripts with valid MIME types

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS 12.0.1, M1 PRO
* output of `wrangler -V`: `0.0.0-9ca1315`
* output of `node -v`: `v16.13.1`
* content of `wrangler.toml`: none

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1187432/146659671-b9ea535e-ad77-4d40-8998-7526247e508b.png">

Greg Brimble requested I add [this](https://stackoverflow.com/questions/29555290/what-is-the-difference-between-res-end-and-res-send/49242271#49242271) to the ticket

**Comment by loonfly** [comment]
On Windows 10, index page has no button, has no onClick. Still receiving the same `server responded with a MIME type of ""`.

When i tried to redirect to a non existence page, I finally receive `💿 Hey developer👋, ......`

**Comment by pinko64** [comment]
![image](https://user-images.githubusercontent.com/6287989/147932398-a1e4a740-bfd3-46b0-96e3-848fb82822e7.png)
With  "wrangler": "^0.0.6" vite/solidjs also fails. Local dev complains about the MIME issue.
On cloudflare(not local) the pages won't work either: Uncaught TypeError: Error resolving module specifier “solid-js/web”. Relative module specifiers must start with “./”, “../” or “/”.

With version ^0.0.0-beta.6 it works in local and in cloudflare.
