### ISSUE TITLE
🚀 Feature Request: Don't open a browser tab automatically on `wrangler pages dev`

### ISSUE THREAD

**Issue by jazoom** [cloudflare/wrangler2#1376]
### Describe the solution

I want `wranger` to serve up a `functions` directory. I don't want it to do anything else. The framework (Svelte) is handling the hot-reloading of code.

Obviously I don't want a browser tab to open to a pointless location that has no content (http://localhost:8788). The `--headless` option that exists elsewhere in `wrangler` doesn't work here.

As a side note, it was unintuitive that I had to do `wrangler pages dev ./functions` to get it to serve up the functions without serving up some other arbitrary page (the application pages aren't yet built by the framework since we're just using hot reload). Perhaps `wrangler pages dev` should have done the job?

Yes, I'm aware Svelte has an adapter for cloudflare, but I want to separate concerns a bit and use the built-in routing for the `functions` directory.

**Comment by petebacondarwin** [comment]
You can prevent `wrangler pages dev` from opening a browser by setting the `BROWSER` environment variable to `none`.

**Comment by rozenmd** [comment]
We should probably document that 😬 - https://developers.cloudflare.com/workers/wrangler/commands/
