### ISSUE TITLE
🐛 BUG:[ERROR] Processing wrangler.toml configuration:

### ISSUE THREAD

**Issue by ghgrafos** [cloudflare/wrangler2#1390]
### What version of `Wrangler` are you using?

2.0.15

### What operating system are you using?

Linux

### Describe the Bug

    - 😶 Ignored: "type":
      Most common features now work out of the box with wrangler, including modules, jsx,
  typescript, etc. If you need anything more, use a custom build.
    - Deprecation: "zone_id":
      This is unnecessary since we can deduce this from routes directly.
    - Deprecation: "build.upload.format":
      The format is inferred automatically from the code.

    - Expected "route" to be either a string, or an object with shape { pattern, custom_domain,
  zone_id | zone_name }, but got "".

**Comment by threepointone** [comment]
It's not clear from your issue what command you ran, and what the error is. Could you share some more details about what happened?
