### ISSUE TITLE
v1 » v2 migration

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#14]
This issue is for tracking details on how to migrate a project from v1 to v2. Roughly, the difference between the features that look the same, what features are deprecated and how to replace their functionality, and maybe how to take advantage of newer features.

**Comment by petebacondarwin** [comment]
Closing as this issue has nothing specifically actionable and we have pretty much covered migration from W1.
Any specific migration concerns should be captured in a new issue.
