### ISSUE TITLE
`node_modules` caching in the github actions doesn't appear to work

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#140]
`npm install` consistently takes about 30 seconds, which implies it's downloading all the packages everytime. This probably means the caching (defined here https://github.com/cloudflare/wrangler2/blob/973b8f2dd93a1d5976e650fa5228bf605dd9326d/.github/workflows/prereleases.yml#L25-L30) isn't working.

**Comment by JacobMGEvans** [comment]
I will take a look and fix that tomorrow.

**Comment by threepointone** [comment]
fixed in #146, thanks @JacobMGEvans
