### ISSUE TITLE
chore: write docs for commands/config in repo

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1400]
Our main, user facing reference for documentation is at https://developers.cloudflare.com/workers/wrangler/. This is good, and will still remain the primary interface. 

However, we face a bit of a problem in that we're not actively updating those docs ourselves, and as such those docs are lagging. Further, those docs are a little light on details, and we'd like a richer reference for superusers, and ourselves. 

So the proposal is to make a docs folder, where we have engineering specific docs. We may expand the scope in the future, but let's keep it as a technical reference for now. 

Further, it now becomes the responsibility of this team to update these docs whenever they land new features (or make changes o existing ones). So the docs/content team can use this as a reference when they're updating docs in the user facing site. 

Let's start with `commands.md` and `configuration.md`.

**Comment by rozenmd** [comment]
> we're not actively updating those docs ourselves, and as such those docs are lagging

Closing this issue as we're now updating these docs ourselves
