### ISSUE TITLE
🐛 BUG: secret is not defined in local dev

### ISSUE THREAD

**Issue by tibotiber** [cloudflare/wrangler2#1412]
### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

Mac

### Describe the Bug

Hello, I'm facing an issue where wrangler in local dev tells me that my secret is undefined. Checking the Cloudflare dashboard confirms the secret its set, and `wrangler secret list` lists it as well. I believe the same code used to work, but it doesn't anymore. Any idea?

PS: this is my first issue, is this the right place vs the community site to request for help like this?

**Comment by tibotiber** [comment]
Update: I got this solved using the (thus far) undocumented `.dev.vars` file as pointed to me [in the forum](https://community.cloudflare.com/t/help-secret-is-not-defined-in-local-dev/397005). Docs is on the way also so I'll close this - https://github.com/cloudflare/cloudflare-docs/issues/4770.

I'm understanding the first round of help request would be better in the forum or discord and move here if devs are required.

**Comment by threepointone** [comment]
Glad you were unblocked!
