### ISSUE TITLE
🐛 BUG: Unexpected fields found in top-level field: "kv-namespaces"

### ISSUE THREAD

**Issue by jahands** [cloudflare/wrangler2#1421]
### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

WSL (Ubuntu 20.04)

### Describe the Bug

I'm upgrading an old project from Wrangler 1 to Wrangler 2, and got the following error:
```
▲ [WARNING] Processing wrangler.toml configuration:
    - Unexpected fields found in top-level field: "kv-namespaces"
```
Looks like `kv-namespaces` got renamed to `kv_namespaces`, but there's no notice for this other than the error.

It would be helpful if we had a warning or error saying something to the effect of: "hey we renamed kv-namespaces to kv_namespaces, please rename it in your wrangler.toml"

Thanks!

**Comment by threepointone** [comment]
To clarify, looks like wrangler 1 supported `kv-namespaces` in addition to `kv_namespaces` https://github.com/cloudflare/wrangler/search?q=kv-namespaces, but it was never documented anywhere. We haven't renamed anything here. https://developers.cloudflare.com/workers/wrangler/cli-wrangler/configuration/#kv_namespaces We could add a specific warning for this.

**Comment by threepointone** [comment]
Ah, here it is https://github.com/cloudflare/wrangler/blob/746f8de5f1a015c15e9a91374e0156853a2f6ce7/CHANGELOG.md#L1393

quote: 
  
  When KV namespace support was initially added to Wrangler, we documented using `kv-namespaces` in `wrangler.toml`. Unfortunately, the `-` was not consistent with other fields such as `zone_id` and `account_id`, so the decision was made to allow both `kv-namespaces` and `kv_namespaces`. When this change was introduced, it worked with top level `kv_namespaces` entries, but not in environments. This is now fixed! You can now use `kv_namespaces` everywhere you can use `kv-namespaces`.

**Comment by JacobMGEvans** [comment]
> Ah! That makes sense. A specific warning would be helpful, as I had to google how to declare kv namespaces to figure out the correct way to declare them

We should discuss backwards compatibility
