### ISSUE TITLE
How to migrate pre-existing tsconfig.json set-ups

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#143]
- [x] whether to explicitly ask whether to install @cloudflare/workers-types, even if they have a tsconfig.
- [ ] whether we need to tweak the compilerOptions in a current tsconfig.json to match what we require.
- [ ] whether to only touch tsconfig.json in the current working directory, since changing a higher up one might break other projects in a monorepo.
- [ ] whether to check if the correct version of TS is installed.
- [ ] whether to create a new tsconfig.json in the current directory even if there is a higher up one, which we then extend.

Taken from https://github.com/cloudflare/wrangler2/pull/141#discussion_r771986201

**Comment by threepointone** [comment]
No one's asked for this, let's close this one and do something more targeted in the future
