### ISSUE TITLE
🐛 BUG: Devtools does not receive console logs

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/wrangler2#1436]
### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

Windows

### Describe the Bug

Write a basic worker which uses some console logs, and open the devtools.
When it's loaded, make a request to your worker, and observe that the logs will be shown in the terminal, but not shown on the Devtool's console tab.

**Comment by threepointone** [comment]
I can't reproduce this behaviour locally. I think we may have fixed this recently. @Skye-31 could you please confirm you see this behaviour in the latest version of wrangler?

**Comment by threepointone** [comment]
No, just a regular worker apparently.

**Comment by Skye-31** [comment]
On 2.0.17 this is still applicable in local mode, however works as expected when using remote mode
![image](https://user-images.githubusercontent.com/46286597/178470899-df7ec0b5-06e2-42f9-ae09-6e72400ac7ae.png)

**Comment by threepointone** [comment]
good catch! looks like we lost it for local mode during a refactor
