### ISSUE TITLE
🐛 BUG: Unclear error message when Node is too old

### ISSUE THREAD

**Issue by kentonv** [cloudflare/wrangler2#1443]
### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

Debian Linux

### Describe the Bug

The most recent Debian -- v11, "bullseye" -- ships Node 12 as its `nodejs` package.

Using this version, attempting to install and use Wrangler results in a weird error:

```
$ npm install wrangler --save-dev
(... succeeds ...)
$ npx wrangler --help
Unexpected token '.'
$
```

It turns out this is because Wrangler requires Node 16. In fact, the `package.json` even says so:

```
	"engines": {
		"node": ">=16.7.0"
	},
```

For whatever reason, though, this requirement did not lead to any useful error message from `npm`. It might be worth Wrangler itself checking, at startup, whether the version of Node is too old, and if so, writing a more useful error.

**Comment by petebacondarwin** [comment]
That strange because there is literally code to do this check: https://github.com/cloudflare/wrangler2/blob/238b546cc84bc7583f6668be25b7746c48d1a3fb/packages/wrangler/bin/wrangler.js#L24-L26

**Comment by threepointone** [comment]
Because this specific file isn't transpiled, we have to be careful not to use any newer syntax. I think adding the ...args code recently broke this from running on older versions of node/js. 

Alternately, we should just transpile this file as well. So we won't risk this kind of failure.

**Comment by petebacondarwin** [comment]
Ahah! It is because the binary contains the `?.` operator, which node 12 does not understand. So it cannot even parse the file let alone run it.

**Comment by kentonv** [comment]
Yes, it's the use of `?.`

**Comment by petebacondarwin** [comment]
See https://github.com/cloudflare/wrangler2/blob/238b546cc84bc7583f6668be25b7746c48d1a3fb/packages/wrangler/bin/wrangler.js#L130-L135

**Comment by kentonv** [comment]
I should probably have included this more complete error in my bug report...

```
$ node_modules/.bin/wrangler --help
/home/kenton/src/kvite/node_modules/wrangler/bin/wrangler.js:128
	wranglerProcess?.kill();
	                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
