### ISSUE TITLE
🚀 Feature Request: Work around 25MB Pages filesize limit by automatically serving bigger files from R2 instead

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/wrangler2#1452]
### Describe the solution

I have a mere 57 files across my 25 subdomains that are larger than Pages' 25MB filesize limit (dictated by Workers KV limitations).

I am preparing to manually work around the problem by manually serving those files from R2 instead, but there would surely be tremendous value for users in automatically serving files bigger than 25MB from R2 instead.

(This seems like a pretty obvious idea that I assume has already been discussed internally, but if there are good reasons not to implement this, I'd like to know...)

**Comment by sidharthachatterjee** [comment]
> I am preparing to manually work around the problem by manually serving those files from R2 instead, but there would surely be tremendous value for users in automatically serving files bigger than 25MB from R2 instead.

This is totally okay to do and I don't see an issue serving them from R2 via a worker or function that you write. 

We have discussed this internally but don't have anything else at the moment to share.

**Comment by nprogers** [comment]
Serving assets from R2 is on the Pages roadmap, so we will not prioritize any workaround issues. Thanks!

**Comment by Hexstream** [comment]
Amazing!! Thank you!!
