### ISSUE TITLE
🚀 Feature Request: Add support for easy proxying to R2 using Pages _redirects file

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/wrangler2#1453]
### Describe the solution

[The Pages documentation for redirects](https://developers.cloudflare.com/pages/platform/redirects/) seems to say that easy proxying will be supported later, with syntax such as:

`/blog/* https://blog.my.domain/:splat 200`

I'm very excited for that feature, but even more exciting would be to also add easy read-only proxying of private R2 buckets with syntax such as:

`/blog/* r2://my-bucket/:splat 200`

This would notably be very useful to work around Page's 25MB filesize limit.

**Comment by sidharthachatterjee** [comment]
Hey there! Thanks for the feature request. What if this was a plugin? 

Have you thought about putting files in a R2 bucket and use a Pages function to serve them?

**Comment by sidharthachatterjee** [comment]
Closing this in favour of https://github.com/cloudflare/wrangler2/issues/1453 since they are both trying to solve the same issue really

**Comment by Hexstream** [comment]
> Closing this in favour of https://github.com/cloudflare/wrangler2/issues/1453 since they are both trying to solve the same issue really

I assume you meant #1452, but I disagree, since working around the 25MB filesize limit is simply NOT the only valid use-case for this feature. This would be a great feature to have even if #1452 were to be implemented.

For instance, I often like to have a `/tmp/` directory in my websites for quickly sharing files.
Proxying this directory from R2 would make much more sense than rebuilding and republishing.
There are surely a ton of other valid use-cases for such easy R2 proxying.

I don't think this issue should be closed at all.

**Comment by Hexstream** [comment]
> Hey there! Thanks for the feature request. What if this was a plugin?
>
> Have you thought about putting files in a R2 bucket and use a Pages function to serve them?

[Pages Functions does not appear to support R2 bindings yet](https://developers.cloudflare.com/pages/platform/functions/#adding-bindings), so I was planning to just use a Worker to proxy R2.

**Comment by Mexican-Man** [comment]
> [Pages Functions does not appear to support R2 bindings yet](https://developers.cloudflare.com/pages/platform/functions/#adding-bindings), so I was planning to just use a Worker to proxy R2.

Same here. I was hoping to wait until bindings get added, but I know the R2 beta has been around for a while, so I just assuming it wasn't on the table.

**Comment by Skye-31** [comment]
Fwiw, R2 is supported on pages now

**Comment by Hexstream** [comment]
That's great, but note that ultimately, all `_redirects` and `_headers` file features can be emulated with Functions/Workers anyway, yet the extra convenience is clearly worth it.
