### ISSUE TITLE
🐛 BUG: Possibly missing R2 Persist

### ISSUE THREAD

**Issue by CraigglesO** [cloudflare/wrangler2#1454]
### What version of `Wrangler` are you using?

latest

### What operating system are you using?

Mac

### Describe the Bug

Might be wrong here, but I noticed the R2 update and from my limited understanding of the wrangler codebase,
https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/dev/local.tsx#L198
Shouldn't this include [r2persist](https://github.com/cloudflare/miniflare/blob/master/packages/r2/src/plugin.ts#L35)?

**Comment by rozenmd** [comment]
Thanks for reporting this @CraigglesO! It'll be part of our next release.
