### ISSUE TITLE
RFC: internal middleware for "wrapping" workers

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1466]
We're coming across multiple usecases where it's useful to "wrap" a worker with some functionality before running `dev`/`publish`. 

- `--assets`/`config.assets` uses a [facade](https://github.com/cloudflare/wrangler2/blob/501cb6a13623e353e0b7a9f1a4386448ac2492e6/packages/wrangler/templates/static-asset-facade.js) to add the boilerplate for serving static assets from kv 
- d1 uses a facade to inject D1 bindings that abstract over the underlying Durable Object (until the runtime native supports it, at which point we will remove the facade)
- We can capture errors in dev to give a more user friendly experience for errors (tracking at https://github.com/cloudflare/wrangler2/issues/441)
- We can use it to expose special routes that trigger scheduled workers 
- We could wrap a worker and inspect requests in dev to add live reload functionality (tracking in https://github.com/cloudflare/wrangler2/issues/1167)
- We can use it in dev to inject bindings to override service bindings and implement zero config multiworker development (tracking https://github.com/cloudflare/wrangler2/issues/1182)
- We use this in the `wrangler@wasm` builds to wrap `.wasm` files with a worker facade that makes it amendable to the Workers runtime 
- We could use it to detect missing favico responses in dev mode 

There are probably a bunch more usecases, but this list should be sufficient to convince of it's usefulness. 

The proposal here is to formalise this internally in the codebase so we can add/remove these facades/"middleware" based on conditions, so that we can add more than one for a worker if and when required.

**Comment by Electroid** [comment]
One thing to keep in mind is this will (probably?) affect source maps.

**Comment by threepointone** [comment]
Landed this in https://github.com/cloudflare/wrangler2/pull/1551, works well, sourcemaps included. Closing this.
