### ISSUE TITLE
`wrangler dev` for a script in a subfolder doesn't work with prefix `./` in the script name

### ISSUE THREAD

**Issue by ImPlotzes** [cloudflare/wrangler2#147]
When your want to run a script in a subfolder, for example when you're in a project root folder and your worker's script is in an `src` folder, then you can't do that if you write the command like this: `wrangler dev ./src/worker.js`. It works when you do `wrangler dev src/worker.js`, but not when `./` is added in the beginning.

**Comment by threepointone** [comment]
good catch. I'll fix this.
