### ISSUE TITLE
🚀 Feature Request: Detect whether code is being run in Cloudflare Workers (or Node.js)

### ISSUE THREAD

**Issue by brillout** [cloudflare/wrangler2#1481]
### Describe the solution

Add some kind of macro to detect whether the code, that is currently being run, is running in Cloudflare Workers.

For example with `esbuild`:

```js
return esbuild.build({
  define: {
    IS_CLOUDFLARE_WORKER: 'true'
  }
})
```

I've been using this for my custom Cloudflare Worker bundling (see [github.com/brillout/build-worker/tree/build-worker.mjs#L20-L22](https://github.com/brillout/build-worker/blob/2cd7b6ddd6b2625887e07d209d7c4c1ffd120520/build-worker.mjs#L20-L22)).

**Comment by brillout** [comment]
In the meantime: this https://community.cloudflare.com/t/how-to-detect-the-cloudflare-worker-runtime/293715 works.

**Comment by WalshyDev** [comment]
I believe the Navigator API is the preferred way to do this

```js
if (navigator.userAgent === 'Cloudflare-Workers') {
  // logic
}
```

**Comment by threepointone** [comment]
I don't think wrangler would inject any compile time value that would indicate a workers environment. @WalshyDev's suggestion would be like the right way to do this. Closing this issue.

**Comment by brillout** [comment]
It doesn't seem to work: I get `typeof navigator === "undefined"`.

**Comment by petebacondarwin** [comment]
I just tried this in a worker:

```ts
export default {
  async fetch() {) {
    return new Response(JSON.stringify(navigator));
  }
}
```

and in the browser, I see:

```
{"userAgent":"Cloudflare-Workers"}
```

**Comment by brillout** [comment]
I just tried again using `wrangler@2.9.1` and by inserting `console.log(typeof navigator)` somewhere in the worker code and I still get `typeof navigator === "undefined"`. Maybe it's because I'm using `wrangler.toml#node_compat`?

**Comment by alanshaw** [comment]
For anyone else that comes across this, the navigator useragent method appears to be the Cloudflare recommended way of determining cloudflare worker runtime: https://developers.cloudflare.com/workers/runtime-apis/web-standards/#navigatoruseragent

**Comment by penalosa** [comment]
For future readers, `navigator.userAgent` requires the `global-navigator` compatibility flag, or a compatibility date after 2022-03-21: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#global-navigator
