### ISSUE TITLE
🐛 BUG: wrangler pages dev + SvelteKit + KV, locally

### ISSUE THREAD

**Issue by mglikesbikes** [cloudflare/wrangler2#1490]
### What version of `Wrangler` are you using?

2.0.22

### What operating system are you using?

Mac

### Describe the Bug

Seeing an empty KV store when binding to it with `wrangler pages dev --kv MY_NAMESPACE`. E.g., `platform.env.MY_NAMESPACE.list()` does not show what's in the actual store in the cloudflare dash.

What am I missing? My `package.json`, the relevant script being `dev:wrangler`:

```package.json
{
  "name": "mgissad",
  "version": "0.0.1",
  "watch": {
    "build": "src/**"
  },
  "scripts": {
    "dev:watch": "npm-watch build",
    "dev:wrangler": "BROWSER=none npx wrangler pages dev .svelte-kit/cloudflare/ --kv MY_NAMESPACE",
    "build": "vite build"
}
```

Note: haven't tested with DOs yet.

**Comment by mglikesbikes** [comment]
Closing as apparently I totally misunderstood how this works haha

**Comment by 4levels** [comment]
Would love to understand as well why this is not working as I personally expected.
Is this related to the fact that `wrangler pages dev` triggers somehow the `--local` flag of the `wrangler dev` command, resulting in an ephemeral store being used instead of the actual one?
