### ISSUE TITLE
🚀 Feature Request: Log whether new versions are available as a part of `wrangler --version`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1492]
### Describe the solution

If I'm checking my version, I'm probably also interested in seeing if there are new versions available. The only reason I can think to _not_ do this is if we ever encourage something like `node --version > .nvmrc` or `node --version > .node-version` for other tools to pick it up or for us to read that in some CI environment or whatever.

**Comment by threepointone** [comment]
SOunds good. Happy to output newer available versions when `!isTTY`

**Comment by threepointone** [comment]
In fact, we should just use `printWranglerBanner()` when !isTTY, it includes this information and looks nice

**Comment by threepointone** [comment]
Assigning to @cameron-robey
