### ISSUE TITLE
🐛 BUG: No feedback given on `wrangler kv:namespace delete`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1494]
### What version of `Wrangler` are you using?

2.0.18

### What operating system are you using?

macOS

### Describe the Bug

`wrangler kv:namespace delete` doesn't give any feedback to suggest whether the operation was successful or failed. It should print some message confirming.

e.g.

> Successfully deleted KV namespace (ID: `xyz`)

`wrangler r2 create bucket` does it nicely.

**Comment by threepointone** [comment]
good catch, yes.
