### ISSUE TITLE
🐛 BUG: Invalid regular expression

### ISSUE THREAD

**Issue by chris-kruining** [cloudflare/wrangler2#1504]
### What version of `Wrangler` are you using?

beta

### What operating system are you using?

Windows 11

### Describe the Bug

- install remix with `npx create-remix@latest`
- choose a folder
- choose "Just the basics"
- choose "Cloudflare Pages"
- choose "Typescript"
- run `npm run dev`

**Comment by chris-kruining** [comment]
problem does not exist in 2.0.22

**Comment by threepointone** [comment]
@GregBrimble @Skye-31 this might be related to the pages dev refactor?

**Comment by chris-kruining** [comment]
weird, I've set the version back to beta in my package.json and ran `npm i` again, but I don't have the error anymore. Would it be worth to remove my node_modules and do a 100% fresh install? Or is it more preferable to just close this issue under the conclusion of: don't use beta?

**Comment by GregBrimble** [comment]
Definitely we'd rather you use stable versions. But it sounds like it _probably_ wasn't an issue with the current beta release, so I'll close this out. Let us know if it comes up again!

**Comment by petrusgomes** [comment]
I had a similar issue on Wrangler 2.0.23 stable.
Using 2.0.22 solved it.

**Comment by Skye-31** [comment]
Can confirm this is an issue in 2.0.23

**Comment by Skye-31** [comment]
@petrusgomes, would you be able to see if [this version of wrangler](https://github.com/cloudflare/wrangler2/pull/1552#issuecomment-1195770084) fixes it?
