### ISSUE TITLE
🐛 BUG: D1 shim hides other things on `env`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1512]
### What version of `Wrangler` are you using?

d1

### What operating system are you using?

macOS

### Describe the Bug

```ts
export default {
  fetch(request, env) {
    return new Response(JSON.stringify(env))
  }
}
```

When other bindings exist (env vars, service bindings etc.), using D1 obscures them in the above script. They're still accessible if I know their binding, but they don't list out/JSON-stringify.

**Comment by Skye-31** [comment]
Cannot reproduce this on wrangler 2.6.1

**Comment by rozenmd** [comment]
Looks like it's fixed
