### ISSUE TITLE
Everyone that’s. Messed with my codes and tried to make me think I’m not god at what I do. Wiki may pay y’all back

### ISSUE THREAD

**Issue by satoshi022** [cloudflare/wrangler2#1522]
Everyone that’s. Messed with my codes and tried to make me think I’m not god at what I do. Wiki may pay y’all back

_Originally posted by @satoshi022 in https://github.com/cloudflare/wrangler2/issues/1521#issuecomment-1192050871_

**Comment by Hexstream** [comment]
I reported this bizarre spam account to GitHub.

**Comment by petebacondarwin** [comment]
Thanks @Hexstream
