### ISSUE TITLE
🚀 Feature Request: Print full URL on `wrangler publish`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1530]
### Describe the solution

RIght now we just output something like:

```
foo.bar.workers.dev
```

It would be nice to prefix with a protocol so that it's recognized as a URL so I can just Cmd+Click to go straight there. I realize that it's maybe not always `https` though, and maybe Wrangler doesn't know the protocol? Maybe just assume `https`? Or can we pull it from the zone settings somehow?

**Comment by threepointone** [comment]
There are a bunch of edgecases here, especially if it's also a route, or even a service that's bound, or a script that's only used as  DO, etc. 

Let's skip all that and keep it simple. If we know it's a workers.dev worker, then let's print the url with https. If it's on a route, then let's not.
