### ISSUE TITLE
🐛 BUG: Miniflare `D1Plugin` is not enabled

### ISSUE THREAD

**Issue by yusukebe** [cloudflare/wrangler2#1531]
### What version of `Wrangler` are you using?

2.0.22 (d1 branch)

### What operating system are you using?

Mac

### Describe the Bug

Hi! Thank you for your great work!

I want to run the script with D1 locally. I've followed the instruction below:

https://github.com/cloudflare/templates/tree/main/worker-d1

But, I got the error:

```
[mf:err] GET /: TypeError: Cannot read properties of undefined (reading 'fetch')
```

<img width="1139" alt="スクリーンショット 2022-07-25 12 32 49" src="https://user-images.githubusercontent.com/10682/180693850-db5c1f7a-a3a8-456e-8a7c-00c47d0652ca.png">

So, I've investigated the cause of the error, and I found that the `D1Plugin` in `miniflare-dist` is not enabled in [the D1 branch](https://github.com/cloudflare/wrangler2/tree/d1):

<img width="1034" alt="スクリーンショット 2022-07-25 12 24 32" src="https://user-images.githubusercontent.com/10682/180694112-32729beb-5860-44cf-84a5-d1afdc39bd00.png">

I ran the command to re-install `miniflare@d1`:

```
npm install -w packages/wrangler --save miniflare@d1
```

Then, the `D1Plugin` has been enabled:

<img width="1109" alt="スクリーンショット 2022-07-25 12 25 34" src="https://user-images.githubusercontent.com/10682/180694023-88668e13-8d31-4c1e-ba2a-4049679f8889.png">

It seems that the `package-lock.json` does not have `minidlare@d1` modules correctly. Can you fix it?

**Comment by GregBrimble** [comment]
We probably need to cherry-pick this onto the d1 branch: https://github.com/cloudflare/wrangler2/pull/1511/commits/9b173774b2c19260c982d479bc2eedbad087458a

**Comment by yusukebe** [comment]
@GregBrimble 

You are right! I've cherry-picked it into d1 branch, built it, ran it with the command that was built, and it's successful. Could you release this as wrangler@d1?

**Comment by yusukebe** [comment]
Hi!

In this PR #1579 by @geelen, D1 works! Thanks!
