### ISSUE TITLE
🐛 BUG: (docs) `npx wranger init` unexpected results 

### ISSUE THREAD

**Issue by ptim** [cloudflare/wrangler2#1532]
### What version of `Wrangler` are you using?

1 & 2

### What operating system are you using?

Mac

### Describe the Bug

This is all user confusion / PEBCAC - but more explicit instructions in the readme would be helpful whilst two versions of wrangler are current 🙏.

I have previously mostly used wrangler1, which is installed globally via npm.

`npx wrangler init my-package' used the old version of wrangler, and created a wrangler.toml in the pwd using v1, rather than creating a new subdir, etc via v2.

Npx doesn't like `npx @cloudflare/wrangler2`; `npx wrangler@2.0.22 init my-package` worked as expected. 

Additional confusion: [package.json states that his package is `"version": "0.0.0",`](https://github.com/cloudflare/wrangler2/blob/main/package.json#L3), although the latest release is 2.0.22.

Cheers, ptim

**Comment by JacobMGEvans** [comment]
> Additional confusion: [package.json states that his package is "version": "0.0.0",](https://github.com/cloudflare/wrangler2/blob/main/package.json#L3), although the latest release is 2.0.22.

That is the monorepo version. You can find the Wrangler package version [here](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/package.json#L3)

**Comment by ptim** [comment]
Ah, silly me, thanks @JacobMGEvans 👍
