### ISSUE TITLE
🐛 BUG: d1 `first()` errors if no results are found

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1536]
### What version of `Wrangler` are you using?

d1

### What operating system are you using?

macOS

### Describe the Bug

At least in local mode, `result` is returned, rather than `results`, so the logic in the facade `results.length` crashes.

**Comment by isaac-mcfadyen** [comment]
According to the docs an `D1_NORESULTS` error should be thrown if this is the case (not the generic error that's being produced here).
