### ISSUE TITLE
🐛 BUG: It's not clear how `wrangler pages dev` proxy is supposed to work

### ISSUE THREAD

**Issue by bebraw** [cloudflare/wrangler2#1547]
### What version of `Wrangler` are you using?

2.0.023

### What operating system are you using?

MacOS 12.5

### Describe the Bug

I'm currently trying to add a couple of dynamic routes to my static site using CF functions. The recently added Functions feature that was added to CF Pages fits my use case perfectly.

To try out the functionality, I set it up as follows:

1. Repository: https://github.com/jsterlibs/website-v2/tree/feat/use-extended-data
2. Command: `wrangler pages dev . -- deno task start` (run after checking out at the repository root. This depends on Deno 1.23.3)

After running the server, I can access my test function at http://localhost:8788/ping as expected. However, it doesn't seem to run my static development server (`deno task start`) at all although based on the current documentation it should.

It's entirely possible I misunderstood something as it's my first steps with the tool. As a temporary solution, I could proxy wrangler through my development server but I can see the benefit of having wrangler CLI as a shell. Now that I think of it, it could easily be some port thing as it's not clear how the proxy is supposed to work (how does wrangler know where my dev server is running?).

**Comment by Martin-Eriksson** [comment]
Wrangler silently ignores your proxy command when you specify a directory. I actually created an issue (#1543) and a PR (#1545) for this yesterday :)

Remove the `.` and it should proxy.

**Comment by bebraw** [comment]
Yeah, that's it. Thanks a lot.

Now there's some other error to debug but that's separate from this and might be related to my personal setup and Deno somehow.
