### ISSUE TITLE
🚀 Feature Request: `pages dev --proxy=3000` doesn't do anything alone

### ISSUE THREAD

**Issue by bebraw** [cloudflare/wrangler2#1549]
### Describe the solution

In order to debug proxy behavior, I'm trying to run my development server in another terminal instead of using `wrangler pages dev --proxy=3000 -- deno task start` kind of command. The problem with this type of invocation seems to be that it's removing any console output coming from my development server (`deno task start`).

To overcome the issue, I would expect `wrangler pages dev --proxy=3000 .` to proxy the port 3000 when running Wrangler but it feels like the proxy option is simply discarded. If that's by design, maybe it would be good to at least warn about the behavior and suggest correct usage.

**Comment by Skye-31** [comment]
A warning for when both directory and port are specified was added in <https://github.com/cloudflare/wrangler2/pull/1545>.

Additionally, there's a PR for allowing no command to be specified when a port is provided, at #1694
