### ISSUE TITLE
🐛 BUG: `pages dev` only listens on `localhost` now (2.0.23)

### ISSUE THREAD

**Issue by awthwathje** [cloudflare/wrangler2#1554]
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Windows

### Describe the Bug

Up until version 2.0.23, Wrangler was listening on all available local IPs, but since then only on `localhost`.  This broke my development environment where I develop in a VM guest and test the app in VM host.

I see you introduced a new option `--local-protocol`, but for some reason not `--ip`, but it's better to bring the old behavior back to bind to all available local IPs (or `0.0.0.0`?) automatically.

**Comment by threepointone** [comment]
Are you referring to pages?

**Comment by threepointone** [comment]
Ok I see you're referring to pages. Thanks for filing this issue, we'll investigate it!

**Comment by GregBrimble** [comment]
We've decided to default to `0.0.0.0` for `wrangler dev` and `wrangler pages dev` by default. This issue tracks that work.

**Comment by awthwathje** [comment]
Yay, thanks a lot guys, you're the best!
