### ISSUE TITLE
🚀 Feature Request: Print OAuth2 authorize URL

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1563]
### Describe the solution

Right now, it just opens the browser. Sometimes I want to open it in a different browser, or maybe it failed to open. Wrangler should print the authorization URL to the terminal as well so I can use it as I please.

**Comment by threepointone** [comment]
I think we already do this? 
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/18808/181300681-2a136b28-b1ff-4a1d-b2af-240bd9ed17f2.png">

**Comment by threepointone** [comment]
Closing this, but happy to reopen if I've misunderstood
