### ISSUE TITLE
🐛 BUG: Wrangler2 does not load `dist/_worker.js` unless you are running wrangler directly in `dist` directory

### ISSUE THREAD

**Issue by CMCDragonkai** [cloudflare/wrangler2#1570]
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Linux

### Describe the Bug

I copied the documentation `_worker.js` into a `dist` directory:

```
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname.startsWith('/api/')) {
      // TODO: Add your custom /api/* logic here.
      return new Response('Ok');
    }
    // Otherwise, serve the static assets.
    // Without this, the Worker will error and no assets will be served.
    return env.ASSETS.fetch(request);
  },
};
```

When running `wrangler pages publish ./dist --project-name polykey-docs`, the worker does not get uploaded.

Whne running `wrangler pages dev ./dist` the worker also does not work.

However if I run `cd dist && wrangler pages publish ./ --project-name polykey-docs` or `cd dist && wrangler pages dev ./` then the `_worker.js` actually does work.

**Comment by Skye-31** [comment]
Hi there. Trying this on the latest version of wrangler (2.0.24), I am unable to reproduce this.

Could you provide a minimal reproducible sample if you still experience this on the latest version?

**Comment by CMCDragonkai** [comment]
Stopped using pages and went back to workers.
