### ISSUE TITLE
🐛 BUG: [pages + windows] Could not automatically determine proxy port

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/wrangler2#1587]
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Windows

### Describe the Bug

This specifically occurs when the directory which wrangler is being run in is in a different disk than the directory that netstat is located.

For example, in this case, netstat is located on my C: drive, whereas my code is located on my F: drive. It incorrectly searches the F drive for the file, which does not exist. Creating a symlink or copying the executable into the correct path does resolve this for me, however that's obviously not a real solution.

```
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Running npm run dev...
Sleeping 5 seconds to allow proxy process to start before attempting to automatically determine port...
To skip, specify the proxy port with --proxy.
[proxy]: 
> link-site@0.0.1 dev
> svelte-kit dev --host


No Instance(s) Available.
The system cannot find the path specified.
X [ERROR] Error scanning for ports of process with PID 5252: Error: Command failed: \windows\system32\netstat.exe -nao

  The system cannot find the path specified
```

**Comment by Skye-31** [comment]
Found this which may be of use? https://github.com/balena-io-modules/drivelist, as it includes which is the system drive (where netstat is located) 
I imagine this issue may actually be present across all operating systems, but have no way of testing currently.

**Comment by WalshyDev** [comment]
Ok, so the issue for this lies here:
https://github.com/cloudflare/wrangler2/blob/d4fbd0be5f5801c331a76709cb375a9386117361/packages/wrangler/src/pages/dev.tsx#L322

Looks like Wrangler already has logic to see if a port is in use and wait for it to be available/error. We may be best just using this logic:
https://github.com/cloudflare/wrangler2/blob/d4fbd0be5f5801c331a76709cb375a9386117361/packages/wrangler/src/proxy.ts#L420

Looks like this would have correctly errored for the port in use here.

**Comment by Skye-31** [comment]
The purpose of this is to automatically determine which port to proxy, not to check if a port has been proxied
