### ISSUE TITLE
bug: service bindings + wrangler dev ignores pathname when making a request 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#1598]
https://github.com/cloudflare/wrangler2/blob/d4fbd0be5f5801c331a76709cb375a9386117361/packages/wrangler/templates/service-bindings-module-facade.js#L29-L31

We don't construct the full url, so only the root gets called

**Comment by JacobMGEvans** [comment]
🏖️

**Comment by JacobMGEvans** [comment]
So rather than an empty string as a default we can have a port?

**Comment by threepointone** [comment]
You need to pass on pathname from the original request appended to the protocol://host:port/
