### ISSUE TITLE
🐛 BUG: _worker.js file not in file counter

### ISSUE THREAD

**Issue by thibault-deriv** [cloudflare/wrangler2#1599]
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Linux

### Describe the Bug

I have a directory with one `index.html` file, one `redirected.html` and one `_worker.js` file like the following:
```
$ tree
.
├── index.html
├── redirected.html
└── _worker.js

0 directories, 3 files
```

I'm using wrangler 2.0.24: 
```
$ npx wrangler --version
 ⛅️ wrangler 2.0.24 
--------------------
```

When I upload the files, `_worker.js` seems not uploaded `Uploading... (2/2)` (but it is):
```
$ CLOUDFLARE_ACCOUNT_ID=d97daaaaaaaabbbbbbbbbcccccccca054 CLOUDFLARE_API_TOKEN=T0k3n npx wrangler pages publish . --project-name=workr --branch=up
🌍  Uploading... (2/2)

✨ Success! Uploaded 0 files (2 already uploaded) (0.25 sec)

✨ Deployment complete! Take a peek over at https://b33be5fd.workr.pages.dev
```

Same in UI, `_worker.js` does not appear:
![no_worker_ui](https://user-images.githubusercontent.com/104425314/182345378-c15c0e6a-56bd-40dc-8485-62ba295c0aab.png)

## Upload via UI
When uploading via UI, you can see the `_worker.js` well listed during "upload step":
![upload_step](https://user-images.githubusercontent.com/104425314/182344775-ea88e9b8-9003-473b-b114-a5a223011815.png)

But later, as with wrangler, it does not appear in "Deployment details":
![ui_no_worker](https://user-images.githubusercontent.com/104425314/182346022-64ee7c15-dcdb-4292-ad68-2a7db25f1eb6.png)

It's minor... but confusing :sweat_smile:

**Comment by nprogers** [comment]
We should add a line in the CLI output indicating that the functions file was uploaded.

**Comment by thibault-deriv** [comment]
Thank you a lot @Skye-31 :tada:
