### ISSUE TITLE
🐛 BUG: Unbound workers don’t respect subrequest limit in `--local` mode

### ISSUE THREAD

**Issue by huw** [cloudflare/wrangler2#1601]
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Linux

### Describe the Bug

Miniflare recently updated to support new subrequest limits for Unbound workers (cloudflare/miniflare#274), but it requires the caller to pass `usageModel`. In `--local` mode, `wrangler dev` doesn’t support the new subrequest limits because it’s not passing the parameter.

I tested this locally, and passing `unbound` to the compiled Miniflare CLI results in the correct behaviour. 

I’ll put together a PR to read this from `wrangler.toml` and pass it through.

**Comment by JacobMGEvans** [comment]
Appreciate the work!! 🎉
