### ISSUE TITLE
🚀 Feature Request: Mass Secrets Management

### ISSUE THREAD

**Issue by Cherry** [cloudflare/wrangler2#1610]
This pairs with https://github.com/cloudflare/wrangler-action/issues/79.

It would be good to have a way to set mass secrets within `wrangler`, so within `wrangler-action`, you aren't met with repetitive output, which can look very much like an error to an unsuspecting user.

Given the TTY nature of `wrangler secret put` I'm not entirely sure how this could work, other than maybe some kind of `wrangler secret mass-put 10` which prompts for key, then value, 10 times? Hopefully y'all have a better idea. 😅

**Comment by JacobMGEvans** [comment]
Thanks for the suggestion! I will put it up for discussion with the team 😄

**Comment by JacobMGEvans** [comment]
Considering an approach involving piping in a file.
