### ISSUE TITLE
🐛 BUG: define is not defined

### ISSUE THREAD

**Issue by knyzorg** [cloudflare/wrangler2#1613]
### What version of `Wrangler` are you using?

latest

### What operating system are you using?

WSL

### Describe the Bug

The following happens when I try to publish OR dev:

```
▶ npx wrangler dev src/index.ts
 ⛅️ wrangler 2.0.24 
--------------------
Retrieving cached values for userId from node_modules/.cache/wrangler
⬣ Listening at http://localhost:8787
Total Upload: 144.92 KiB / gzip: 21.72 KiB
✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/3ef6bdbd5647b3f05c7b4d95bda51111/workers/scripts/mailer-worker/edge-preview) failed.

      at throwFetchError
  (/home/slava/mailer-worker/node_modules/wrangler/wrangler-dist/cli.js:136497:17)
      at fetchResult (/home/slava/mailer-worker/node_modules/wrangler/wrangler-dist/cli.js:136466:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/home/slava/mailer-worker/node_modules/wrangler/wrangler-dist/cli.js:136758:29)
      at async createWorkerPreview
  (/home/slava/mailer-worker/node_modules/wrangler/wrangler-dist/cli.js:136778:17)
      at async start
  (/home/slava/mailer-worker/node_modules/wrangler/wrangler-dist/cli.js:137471:34) {
    text: 'A request to the Cloudflare API
  (/accounts/3ef6bdbd5647b3f05c7b4d95bda51111/workers/scripts/mailer-worker/edge-preview) failed.',
    notes: [
      {
        text: 'Uncaught ReferenceError: define is not defined\n' +
          '  at line 0\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }

```

**Comment by JacobMGEvans** [comment]
Are you still having this issue?

**Comment by knyzorg** [comment]
@JacobMGEvans I found the error to be looking as if it were a wrangler issue, but if I remove all my code it works. This is a minimal reproducible example:

```ts
import Mailgun from "mailgun.js";
import formData from "form-data";

export interface Env {
  BANNED_IPs: KVNamespace;
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    const mailgun = new Mailgun(formData);

    return new Response("Hello World!");
  },
};
```

Mailgun is just a REST wrapper, but it seems like it is at the root of the issue. Why would this happen?

**Comment by JacobMGEvans** [comment]
Try running your wrangler command with this flag `--node-compat`

**Comment by nosovk** [comment]
@vezaynk were you able to fix the issue?

**Comment by superjose** [comment]
> @JacobMGEvans I found the error to be looking as if it were a wrangler issue, but if I remove all my code it works. This is a minimal reproducible example:
> 
> ```ts
> import Mailgun from "mailgun.js";
> import formData from "form-data";
> 
> export interface Env {
>   BANNED_IPs: KVNamespace;
> }
> 
> export default {
>   async fetch(
>     request: Request,
>     env: Env,
>     ctx: ExecutionContext
>   ): Promise<Response> {
>     const mailgun = new Mailgun(formData);
> 
>     return new Response("Hello World!");
>   },
> };
> ```
> 
> Mailgun is just a REST wrapper, but it seems like it is at the root of the issue. Why would this happen?

I know this has been closed, but coincidentally I'm also using Mailgun, which seems to be the root of the issue. 

I guess the solution is to create a client for it using REST
https://community.cloudflare.com/t/import-mailgun-from-mailgun-js/395597
