### ISSUE TITLE
🚀 Feature: Source code `wrangler init --from-dash`

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#1624]
### Describe the solution

Implement the first phase of `--from-dash`, getting the source code into an initialized project replacing the boilerplate code. 

Additional discussion: https://github.com/cloudflare/wrangler2/discussions/1623
- This implementation should be agnostic from any source control & storage.
- Encourage augmenting projects, i.e. TypeScript, and source storage (we currently provide GitHub repo creation).
- The flag should only be done in empty projects.

**Comment by lrapoport-cf** [comment]
for posterity, leaving a note after chatting with @JacobMGEvans : would be awesome to have [multipart parsing](https://github.com/nodejs/undici/issues/974) support in undici
