### ISSUE TITLE
🐛 BUG: `__STATIC_CONTENT_MANIFEST` is undefined or empty in local mode

### ISSUE THREAD

**Issue by PolariTOON** [cloudflare/wrangler2#1632]
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Linux

### Describe the Bug

I have a worker that uses `kv-asset-handler` and reads the `__STATIC_CONTENT_MANIFEST` global variable to do some checks.

When previewing the project with `wrangler dev`, everything is fine, but with `wrangler dev --local` the variable appears to be undefined or an empty object depending on whether I use a service worker or a module worker.

That's what currently prevents me from using the local mode, but perhaps I'm doing it wrong.

Here is a repository to reproduce the issue: https://github.com/PolariTOON/no-static-content-manifest-in-miniflare

**Comment by JacobMGEvans** [comment]
Reference: https://github.com/cloudflare/miniflare/issues/233
