### ISSUE TITLE
🚀 Feature Request: Export script bundle for interop with the Cloudflare terraform provider

### ISSUE THREAD

**Issue by m0ar** [cloudflare/wrangler2#1646]
### Describe the solution

There should be a way of outputting the script bundle created with `wrangler`, so it's possible to develop with Wrangler while provisioning with the [Cloudflare Terraform provider](https://github.com/cloudflare/terraform-provider-cloudflare).

Background: We want to manage as much as possible with infrastructure as code. When moving to wranger2, we could drop a lot of mess from our worker node projects, which is awesome. But since bundling is now done inside of wrangler on `publish`, we don't have a built artefact to use for deployment. It seems logical these two tools support each other since they complement each other very well.

**Comment by JacobMGEvans** [comment]
Have you tried utilizing the `--dry-run --outdir=dist`  for this purpose?

**Comment by m0ar** [comment]
@JacobMGEvans It does! Fantastic, thanks :cupcake:
