### ISSUE TITLE
🐛 BUG: wrangler dev wasm not working

### ISSUE THREAD

**Issue by kesavkolla** [cloudflare/wrangler2#1672]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Linux

### Describe the Bug

I have installed the wrangler2 using the following command:

```shell
npm --location=global i wrangler@latest
```

I got the latest version of wrangler 

```
wrangler -v
```
 ⛅️ wrangler 2.0.25 

When I try to run my wasm module using wrangler dev I get the following error:

```
✘ [ERROR] No loader is configured for ".wasm" files: target/wasm32-wasi/release/hello-world.wasm

```

**Comment by kpietraszko** [comment]
Yeah, it's broken. Same thing on Windows, and when trying to `publish`

**Comment by penalosa** [comment]
To help us diagnose this further, would you be able to provide some more information about your environment? Specifically, the contents of your `wrangler.toml` would be really useful!

**Comment by cameron-robey** [comment]
Hey 👋 !
We haven't heard from you about this so we are going to close this. If you have further clarification on this please feel free to reopen this, or open another issue with some more details

**Comment by estk** [comment]
I hit the exact same issue when following the steps in this [blog post](https://blog.cloudflare.com/announcing-wasi-on-workers/)

Seems like everything in that blog post _just doesn't work_:tm:

For instance also: https://hexly.examples.workers.dev/ 404's

fwiw here's my wrangler.toml
```
name = "cf-workers-test"
compatibility_date = "2022-09-30"
```

And how I got there:
```
> wrangler2 dev target/wasm32-wasi/release/hello_world.wasm
```

But also, did this ever work?
https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/entry.ts#L156

**Comment by estk** [comment]
@cameron-robey @penalosa

**Comment by bebraw** [comment]
It looks like one way to work around the problem is to set up a rollup build and treat the wasm bundle as an external. I found an example of that here: https://github.com/ssssota/svg2png-worker .

That said, it would be great if wasm worked out of the box.
