### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Mindfulplays** [cloudflare/wrangler2#1673]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

WSL

### Describe the Bug

Wrangler publish fails with 

```
✘ [ERROR] fetch failed
```

I am not sure how https://github.com/cloudflare/wrangler2/issues/834 works with latest wrangler.

**Comment by JacobMGEvans** [comment]
Could you provide additional logging, stacktrace and context on the issue you are having? Thank you 😄

**Comment by Mindfulplays** [comment]
Let's say I have 1000+ files under some directories.
Total bucket size <=450MB, each file <=25MB all within KV limits.

wrangler publish either hangs or just fails with fetch failed.
There is no other error message nor logs.

I tried to do partial uploads (10 files at a time), the first few went through, but the others got stuck with the same problem as before.
Same thing happens with the web-based Drop files or even if I try to migrate to Sites (someone in Discord said Pages is no longer supported, so I tried using Sites). All of them hit this same hiccup.

**Comment by Mindfulplays** [comment]
Posting my comment from Discord here, as I would hate to lose it. The documentation cross-referencing along with code samples all have a myriad of Wrangler 1.0 vs 2.0 syntax, Modules vs non-Modules Workers, Pages vs Sites (so many of them don't work or just plain wrong) with many of the recommended approaches still in Beta label, so the old approach is deprecated, the new approach is just not there yet. Even the simplest getAssetsFromKV has no working example with the new module approach.

**Comment by penalosa** [comment]
There are definitely some documentation issues that we've got on our roadmap to fix! If you could point out some specific areas we can make sure those get fixed quickly.

It sounds like for your use-case, [Pages](https://developers.cloudflare.com/pages), or [R2](https://developers.cloudflare.com/r2/) would be a good fit (Pages is definitely not being depreciated in favour of Sites). I'll close this issue for now, but feel free to post with more details of the specific situation causing `✘ [ERROR] fetch failed` and we can look into it further!

**Comment by Mindfulplays** [comment]
FWIW, moving to Wrangler 2, Modules+TS, R2 was painful, but well worth it at the end. The platform seems to work well, pretty smooth after the initial snafu. R2 + Workers in particular is really great, no issues at all. 

Hopefully this is the last of the migrations.

Documentation is still lacking/incorrect/plain-wrong, but you are already aware of it.

**Comment by penalosa** [comment]
Yeah, documentation in general is definitely on our roadmap to fix. If there's anything you notice that's incorrect though, do definitely point it out--that'd be really helpful!
