### ISSUE TITLE
Windows development experience

### ISSUE THREAD

**Issue by Cherry** [cloudflare/wrangler2#1674]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Windows 10

### Describe the Bug

Currently, the development experience with wrangler on Windows isn't really functional. Running through the CONTRIBUTING guide:

## Starting

- Run `npm install` - lots of deprecation warnings, but success
- Run `npm start -w wrangler`

Here, you're met with the first issue:
```
> wrangler@2.0.25 bundle
> node -r esbuild-register scripts/bundle.ts

'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
```

This appears to be due to the `start` script of 

```
"start": "npm run bundle && NODE_OPTIONS=--enable-source-maps ./bin/wrangler.js"
```

so if I change that to the following, using [`cross-env`](https://www.npmjs.com/package/cross-env):
```
"start": "npm run bundle && cross-env NODE_OPTIONS=--enable-source-maps ./bin/wrangler.js"
```

This now works, and I can start wrangler using `npm start -w wrangler`.

## Building

Let's say I want to run the build script though. Following the CONTRIBUTING guide again:

- `npm run build -w wrangler`

You'll then get hit with this:
```
> wrangler@2.0.25 clean
> rm -rf wrangler-dist miniflare-dist emitted-types

'rm' is not recognized as an internal or external command,ted in 2ms
operable program or batch file.
```

This appears to be due to the wrangler clean script:

```
"clean": "rm -rf wrangler-dist miniflare-dist emitted-types",
```

so if I then add something like [`rimraf`](https://www.npmjs.com/package/rimraf) and use that instead:

```
"clean": "rimraf -rf wrangler-dist miniflare-dist emitted-types",
```

I am then able to complete the `npm run build -w wrangler` command without issue.

## Testing

- `npm run check:type` - works fine, no issues
- `npm run check:lint` - works fine, no issues
- `npm run check:format` - works fine, no issues

- `npm run test`

This seems to kinda "work", but the _spew_ of output and errors all over the place makes it near to impossible to see what's going on. This seems to be the case in CI too, looking at recent Actions runs: https://github.com/cloudflare/wrangler2/runs/7819352422?check_suite_focus=true#step:6:1521

This never actually finished running on my machine and was just hung at the end with a seemingly infinite loop of trying to stop/start `dev` servers, but that may just be my environment. Even after leaving it for about 30 minutes. 🤷‍♀️. I pretty much gave up at this point.  Here's a test log that I killed after about 30 minutes, if someone wants to look through it: https://up.jross.me/kc5ncla3

---

Can we get some Windows development love please? 🧡

**Comment by Skye-31** [comment]
Dropped a basic PR to fix the first 2 issues, tests are a larger one however 😅

**Comment by JacobMGEvans** [comment]
Did #1675 resolve this @Cherry ?

**Comment by Cherry** [comment]
> Did #1675 resolve this @Cherry ?

It resolves the "starting" and "building" sections, yep, thanks! The "Testing" section is a much larger one though.

**Comment by JacobMGEvans** [comment]
> > Did #1675 resolve this @Cherry ?
> 
> It resolves the "starting" and "building" sections, yep, thanks! The "Testing" section is a much larger one though.

This might be resolved with the testing story with creating the Wrangler core API.
