### ISSUE TITLE
🐛 BUG: wrangler kv:key put value is requited and doesn't accept empty string

### ISSUE THREAD

**Issue by Vladi-ed** [cloudflare/wrangler2#1676]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Windows

### Describe the Bug

If you run any of these commands:
`wrangler kv:key put --namespace-id=my-id "11@22.com"`
`wrangler kv:key put --namespace-id=my-id "11@22.com" ""`

you will see an error:

> X [ERROR] Exactly one of the arguments value and path is required

But value parameter is optional, so the error doesn't make sense.

**Comment by JacobMGEvans** [comment]
Reference fix in PR: #1667
