### ISSUE TITLE
🐛 BUG: wrangler kv:bulk put fails to load JSON with additional keys

### ISSUE THREAD

**Issue by Vladi-ed** [cloudflare/wrangler2#1677]
### What version of Wrangler are you using?
2.0.25

### What operating system are you using?
Windows

### Describe the Bug

When you run bulk upload of big JSON file (>20000 records) that contains keys other then 'key' and 'value' the wrangler freezes showing no output.
`wrangler kv:bulk put --namespace-id=my-id "C:\records-to-upload.json"`

You see it just hanging out with this message:
```
 ⛅️ wrangler 2.0.25
--------------------
```
Also there is no checkup for how many records you going to upload (I see a 10000 records limit in docs).

**Comment by JacobMGEvans** [comment]
Potentially 2 issues, the check could be a quick win.

**Comment by cameron-robey** [comment]
Hey 👋! Thanks for raising this issue. Sorry it's been a while till we got around to looking at it.

I've done some testing today to try and reproduce it and I wasn't able to. I believe the behaviour I got below is the intended behaviour. Indeed, we do have checks in place for both additional keys, where we `warn` the user, and wrong keys where we throw an error.

Could you provide some extra clarification on how to reproduce the issue?

- Does `kv:bulk put` work with smaller json files?
- Does `kv:bulk put` work with large json files with the correct keys and no additional keys? 

Here are the outputs from `kv:bulk put` that I got when I tried to reproduce this:

**Bulk upload with >20000 records:**
```sh
$ npx wrangler@latest kv:bulk put data.json --namespace-id xyz
 ⛅️ wrangler 2.1.7 
-------------------
Uploaded 0% (0 out of 21,000)
Uploaded 23% (5,000 out of 21,000)
Uploaded 47% (10,000 out of 21,000)
Uploaded 71% (15,000 out of 21,000)
Uploaded 95% (20,000 out of 21,000)
Uploaded 100% (21,000 out of 21,000)
Success!
```

**Bulk upload with >20000 records, with extra keys:**
```sh
$ npx wrangler@latest kv:bulk put data_extra_key.json --namespace-id xyz
 ⛅️ wrangler 2.1.7 
-------------------
▲ [WARNING] Unexpected key-value properties in "data.json".

  The item at index 20995 contains unexpected properties: ["extra_key"].


Uploaded 0% (0 out of 21,000)
Uploaded 23% (5,000 out of 21,000)
Uploaded 47% (10,000 out of 21,000)
Uploaded 71% (15,000 out of 21,000)
Uploaded 95% (20,000 out of 21,000)
Uploaded 100% (21,000 out of 21,000)
Success!
```

**Bulk upload with >20000 records, without `key` and `value`:**
```sh
$ npx wrangler@latest kv:bulk put data_wrong_key.json --namespace-id xyz
 ⛅️ wrangler 2.1.7 
-------------------

✘ [ERROR] Unexpected JSON input from "data.json".

  Each item in the array should be an object that matches:
  
  interface KeyValue {
    key: string;
    value: string;
    expiration?: number;
    expiration_ttl?: number;
    metadata?: object;
    base64?: boolean;
  }
  
  The item at index 20995 is
  {"different_key":"test_key20995","different_value":"test_value20995","expiration_ttl":3600}


If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
```

**Comment by lrapoport-cf** [comment]
we haven't heard back in a while regarding repro steps so we'll close this out. feel free to re-open if it's still an issue and more detail is available :)
