### ISSUE TITLE
Add error message for a workaround 

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#1683]
A workaround to this issue is to add an account_id in your wrangler.toml, or set it as an environment variable with CLOUDFLARE_ACCOUNT_ID. We could probably add this tip in the error message itself.

_Originally posted by @threepointone in https://github.com/cloudflare/wrangler2/issues/1422#issuecomment-1189496401_
resolves #1422

**Comment by penalosa** [comment]
@JacobMGEvans At a quick glance, this _seems_ like it's solved by https://github.com/cloudflare/wrangler2/pull/1502—what's remaining on this ticket?

**Comment by JacobMGEvans** [comment]
Ah nice! Looks like it didn't auto close that ticket. Feel free to pick up another quick win ticket 😄

**Comment by shaozhijuan** [comment]
useful
