### ISSUE TITLE
🐛 BUG: Path duplicated

### ISSUE THREAD

**Issue by zigazajc007** [cloudflare/wrangler2#1688]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Linux - Fedora 36

### Describe the Bug

I ran:
```
wrangler generate passky-server https://github.com/cloudflare/worker-template-router
```
inside  this directory:
``` 
/home/ziga/Documents/Projects/Passky/Passky-Server-Worker
```
and it created folders / files:
``` 
/home/ziga/Documents/Projects/Passky/Passky-Server-Worker/home/ziga/Documents/Projects/Passky/Passky-Server-Worker/passky-server
```
Like it duplicated the path

**Comment by rozenmd** [comment]
I was able to reproduce this issue on macOS, will start working on a fix tomorrow morning
