### ISSUE TITLE
Feature Request: specify pages dev proxy port manually

### ISSUE THREAD

**Issue by yjl9903** [cloudflare/wrangler2#1693]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Window 10 Pro 21H1

### Describe the Bug

I want to manually run my web dev server and `wrangler pages dev` server separately. I start my web dev server first, get the assets port, and then specify the proxy port, run `wrangler pages dev --proxy ...`. Wrangler still tell me to give some commands, so I must provide some fake commands to start wrangler dev.

I think we can just return the port when it is not undefined.

https://github.com/cloudflare/wrangler2/blob/a0a3ffde4a2388cfa2c6d2fa13b4c0ee94a172ba/packages/wrangler/src/pages/dev.tsx#L453-L466

**Comment by GregBrimble** [comment]
Hi! Thanks for filing this request. We'll keep this ticket open to see if others are interested in it, but in the meantime, you could do something like:

```
npx wrangler pages dev --proxy=3000 -- echo "hi"
```
