### ISSUE TITLE
🐛 BUG: Login Failed

### ISSUE THREAD

**Issue by d0j1a1701** [cloudflare/wrangler2#1699]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Windows 11 21H2(22000.856)

### Describe the Bug

When I type `wrangler login` in the terminal, the OAuth authentication window pops up normally in the browser, but when I click Allow, the web page reports the error "ERR_CONNECTION_REFUSED: localhost has rejected our connection request" and the terminal displays the following.
```
PS D:\Coding\VSCodeWorkSpace\website> wrangler login
 ⛅️ wrangler 2.0.26 
--------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=54d11594-84e4-41aa-b438-e81b8fa78ee7&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20pages%3Awrite%20zone%3Aread%20offline_access&state=Leq-4X9L9HjVXE4N~.Gzsz31_PiHD5pG&code_challenge=Qs69wwlhVtajCNM9Jj0kSo7utCyt9qijl0Zyt0AYHSs&code_challenge_method=S256
C:\Users\Administrator\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:12110
            throw ex;
            ^

TypeError: fetch failed
    at Object.processResponse (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:70321:27)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:70654:42
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: [Error: 25624:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
  ] {
    library: 'SSL routines',
    function: 'ssl3_get_record',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

Sorry, my English is not good, so I use DeepL to translate.

**Comment by dajia-1701** [comment]
I am located in China, so I am using the V2Ray proxy software, but it reports an error whether the proxy software is turned on or not.

The environment variables `http_proxy`, `https_proxy` and `socks_proxy` are not set.

**Comment by zicklag** [comment]
I am behind a proxy and I have my proxy environment variables set, so that most applications work fine, and I'm running into the same issue.

I've also set the `npm config` proxy settings and I'm still having the same issue.

**Comment by rozenmd** [comment]
@zicklag just to confirm, is it `wrangler login` for you too?

**Comment by zicklag** [comment]
Yep. :+1:

**Comment by jspspike** [comment]
We're having problems recreating the issue but you could use the [`CLOUDFLARE_API_TOKEN`](https://developers.cloudflare.com/workers/wrangler/ci-cd/) environment variable to authenticate wrangler as a workaround.

If anyone can provide further insight into the problem or reproducing the issue, feel free to re-open this issue.
