### ISSUE TITLE
Trying to configure secret yield an "Raw mode not supported" from vadimdemdes/ink package

### ISSUE THREAD

**Issue by grenierdev** [cloudflare/wrangler2#170]
Today I was trying to configure my first secret variable with `echo "SECRET VALUE" | wrangler secret put SECRET_KEY` and I was getting the following error :

```sh
  ERROR  Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
        Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported

 - Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
```

The command works with wrangler1.

Tested on Win10 Pro 19043.1415, node v16.9.0, npm v7.21.1, wrangler 0.0.6 and 1.19.6.

**Comment by petebacondarwin** [comment]
Thanks for submitting this issue report @grenierdev.

Wrangler2 does not currently support piping values into the CLI.

I think we need to intercept the situation where stdin is not in TTY mode and avoid sending processing to Ink components...
