### ISSUE TITLE
🐛 BUG: wrangler get stuck running proxy command

### ISSUE THREAD

**Issue by DevinWinata** [cloudflare/wrangler2#1702]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Pop!_OS 22.04 LTS

### Describe the Bug

run `wrangler pages dev -- next dev` in next.js project folder.
it will stuck at `Running next dev...` with high cpu usage (1 of my cpu cores always run at 100% for this process).
no error message.
need to close my terminal to terminate the process, `CTRL+C` in the terminal doesn't work.
with `pnpm wrangler pages dev -- next dev` (pnpm in the front), `wrangler pages dev -- pnpm dev` (change next to pnpm for proxy command), and `pnpm wrangler pages dev -- pnpm dev` (pnpm in the front and next to pnpm for proxy command), it will not get stuck.

other software version details:
node 16.17.0 with nvm 0.39.1
pnpm 7.9.3

**Comment by WalshyDev** [comment]
Hey,

This may have been resolved since due to a lot of the work we have done around `pages dev`. Please let us know if this is still an issue!
