### ISSUE TITLE
🐛 BUG: wrangler doesn't terminate proxied process

### ISSUE THREAD

**Issue by DevinWinata** [cloudflare/wrangler2#1704]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Pop!_OS 22.04 LTS

### Describe the Bug

run `wrangler pages dev -- pnpm dev` or `pnpm wrangler pages dev -- pnpm dev` (both use pnpm dev as proxy command) in next.js project folder.
exit wrangler with `[x] to exit` in terminal.
wrangler did exit, but `pnpm dev` still running.
![Screenshot from 2022-08-18 19-36-43](https://user-images.githubusercontent.com/39239937/185396371-80e2719b-efd1-4290-b918-89e0f9ef26aa.png)
using `next dev` as proxy command did terminate the process when wrangler exit.

other software version details:
node 16.17.0 with nvm 0.39.1
pnpm 7.9.3

**Comment by Skye-31** [comment]
Possible that #1628 fixes this?

**Comment by DevinWinata** [comment]
I'm not so sure. from what I read from #1628, it's like the other way around.
I will try wrangler prerelease in #1628 to see if it fixes the issue.

**Comment by DevinWinata** [comment]
Unfortunately, wrangler prerelease in #1628 doesn't fixes the issue.

**Comment by Skye-31** [comment]
It does it both ways, when the main process exits, it now cleans up the child process properly, and vice versa.

If that doesn't fix it, can you create a minimal reproducible repo please 🙂

**Comment by DevinWinata** [comment]
is this sufficient? [wrangler-1704](https://github.com/DevinWinata/wrangler-1704)

**Comment by Skye-31** [comment]
Interestingly enough, I can reproduce on your next app, but can't on a sveltekit app (where it wasn't successful before that PR landed).

**Comment by GregBrimble** [comment]
Thanks for the report! This seems to be limited to `pnpm` and is reported on their repo. We ask the process to terminate with a `SIGTERM` which `pnpm` doesn't seem to handle perfectly right now.

https://github.com/pnpm/pnpm/issues/2653
