### ISSUE TITLE
🚀 Feature Request: r2-persist flag for Pages

### ISSUE THREAD

**Issue by davemurphysf** [cloudflare/wrangler2#1707]
### Describe the solution

It looks like the ability to persist r2 data locally only made it into functions in #1457.  It would be great to be able to use this with Pages as well, since Pages doesn't have the option to tunnel yet either.

**Comment by WalshyDev** [comment]
Persistence is done through the `--experimental-enable-local-persistence`. R2 should be persisting already with this, please let me know if it isn't.

**Comment by davemurphysf** [comment]
Confirmed persistence works with this flag; thanks!
