### ISSUE TITLE
🐛 BUG: bundle problem when using googleapis 

### ISSUE THREAD

**Issue by daimalou** [cloudflare/wrangler2#1709]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Windows

### Describe the Bug

I am using two google official libraries to develope some features. 

"google-auth-library": "^8.2.0",
https://github.com/googleapis/google-auth-library-nodejs

"googleapis": "^105.0.0",
https://github.com/googleapis/google-api-nodejs-client

I  wirite `node_compat = true` on `wrangler.toml`, and then I run `npm run start` It says:

```
X [ERROR] Could not resolve "http2"
 node_modules/googleapis-common/build/src/http2.js:16:22:
    16 │ const http2 = require("http2");
         │                       ~~~~~~~
         ╵                       "./http2"

  The package "http2" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

**Comment by JacobMGEvans** [comment]
Found a similar issue on Clerk here: https://github.com/clerkinc/javascript/issues/127#issuecomment-1104419384
and Fauna here: https://github.com/fauna/faunadb-js/issues/649

**Comment by Infinitay** [comment]
Has anyone found a solution to this issue? Facing this myself when trying to use the got (https://github.com/sindresorhus/got) package

**Comment by JacobMGEvans** [comment]
> Has anyone found a solution to this issue? Facing this myself when trying to use the got (https://github.com/sindresorhus/got) package

Are you utilizing the `--node-compat` flag or in wrangler.toml using `node_compat = true`?

**Comment by Infinitay** [comment]
Yes I have tried adding `node_compat = true` but it resulted in the same issue as OP. Actually, with the same package too of `http2`.

Node Version: `v16.13.1`

**Comment by jspspike** [comment]
We won't be able to fix this within wrangler but we've created an internal issue to try to improve `node_compat` within the workers runtime. We'll be closing this ticket for now

**Comment by pbteja1998** [comment]
Hi, is there any update on this? 

I am trying to use `wrangler2` with fauna and getting the same error saying `Could not resolve "http2"`

**Comment by MuhammedAO** [comment]
Hi, I'm experiencing this bug at the moment. was there any resolution to this?

**Comment by sbussard** [comment]
Same issue

**Comment by MujeebullahKalwar** [comment]
Same issue, I am using wrangler `3.13.1`

**Comment by flyinvscode** [comment]
Same issue

**Comment by elizabethsiegle** [comment]
Same issue

**Comment by shonubijerry** [comment]
I have written a gist here to authenticate with GCP and query via API rather than the npm packages.

https://gist.github.com/shonubijerry/1c0a1deff5c74d42602ab726017da0ad
