### ISSUE TITLE
🐛 BUG: Wrangler dev  - 504 Gateway Time-out error

### ISSUE THREAD

**Issue by yudax42** [cloudflare/wrangler2#1711]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Linux

### Describe the Bug

When there are environment variables in the wrangler.toml file, it just hangs for a while and gives a 504 Gateway Timeout

Steps for replication:
1 - Create a new wrangler project 
2 - Add a random environment variable to the wrangler.toml file 
3 - Start the project using the `wrangler dev` command

**Comment by Sharkgamedev** [comment]
I'm experiencing this as well. Same steps to repro.

**Comment by yudax42** [comment]
The problem was resolved 

https://www.cloudflarestatus.com/incidents/75d0lh053887
