### ISSUE TITLE
🐛 BUG: wrangler dev doesn't use [dev] ip = '127.0.0.1' in wrangler.toml

### ISSUE THREAD

**Issue by jamiesteven** [cloudflare/wrangler2#1714]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Mac

### Describe the Bug

New Wrangler dev defaults to 0.0.0.0.

As a result, I added the following to my wrangler.toml.
```
[dev]
  ip = '127.0.0.1'
```

However, running `npx wrangler dev` still runs at 0.0.0. Also tried `npx wrangler dev --config wrangler.toml`.

`npx wrangler dev --ip 127.0.0.1` does work as expected.

**Comment by threepointone** [comment]
Nice catch! Fix up in https://github.com/cloudflare/wrangler2/pull/1718
