### ISSUE TITLE
🐛 BUG: [D1] ArrayBuffer inputs aren't handled

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#1716]
### What version of `Wrangler` are you using?

d1

### What operating system are you using?

macOS

### Describe the Bug

The docs say ArrayBuffer inputs should be transformed to SQLite BLOBs, but right now they are just dropped.

**Comment by rozenmd** [comment]
@GregBrimble do you mind posting a small repo that reproduces the issue?

**Comment by Skye-31** [comment]
I believe this bug has been fixed as of ~a month ago? Related to <https://github.com/Skye-31/d1-null-bug> - all inputs (numbers, arraybuffers, null etc.) were becoming stringified
