### ISSUE TITLE
🐛 BUG: Support http proxies for `wrangler dev`

### ISSUE THREAD

**Issue by tianluanchen** [cloudflare/wrangler2#1738]
### What version of `Wrangler` are you using?

2.0.22

### What operating system are you using?

windows 10

### Describe the Bug

```powershell
wrangler pages publish public --project-name xxxx              

X [ERROR] fetch failed

If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose 
```
Logging in is fine, but when posting a project it fails to capture, setting the http proxy is useless, even though the http proxy allows the browser to open all websites normally

**Comment by kckeiks** [comment]
I'm having the same problem with wrangler 2.0.26 but I can't even log in.

**Comment by rozenmd** [comment]
Hi @tianluanchen, could you please clarify what you mean by "setting the http proxy is useless"? Is there an error message?

What steps did you take to setup the http proxy?

**Comment by rozenmd** [comment]
@Lifeni - do you mind trying something for me?

Does it work if you try run:

```
cross-env HTTPS_PROXY=http://127.0.0.1:7890 wrangler dev
```
?

**Comment by Lifeni** [comment]
@rozenmd 
It still doesn't work, the error message is the same as before (ERR_SSL_WRONG_VERSION_NUMBER).

But the error message sometimes becomes `Error: read ECONNRESET` or `Error: Client network socket disconnected before secure TLS connection was established`. This may be related to my bad network, I will try again after a while.

**Comment by rozenmd** [comment]
@Lifeni - so it's a bug, `wrangler dev` doesn't handle proxies correctly, `wrangler dev --local` should work though

Can you confirm whether other wrangler commands work, like `wrangler publish` and `wrangler whoami`?

**Comment by Lifeni** [comment]
@rozenmd 

Two days ago, neither `wrangler dev` nor `wrangler publish` worked properly, only `wrangler dev` would give detailed error messages.

After that, I changed my proxy software. `wrangler whoami` and `wrangler whoami` seem to work fine, but `wrangler dev` still doesn't work. Unlike before, it prompts that the upload is complete, but fails to load the page. Below is the new error message.

<details>
<summary> Run `wrangler dev` </summary>


```
>  wrangler dev                                                  

⛅️ wrangler 2.0.28 
--------------------
Retrieving cached values for userId from ..\..\node_modules\.cache\wrangler
Your worker has access to the following bindings:
- KV Namespaces:
  - urls: xxx
⬣ Listening at http://0.0.0.0:8787
Total Upload: 15.82 KiB / gzip: 2.88 KiB
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn on local mode, [c] clear console, [x] to exit                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
C:\Users\Liang\AppData\Roaming\fnm\node-versions\v16.16.0\installation\node_modules\wrangler\wrangler-dist\cli.js:12110
            throw ex;
            ^

Error: connect ETIMEDOUT 199.59.148.9:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on WebSocket3 instance at:
    at emitErrorAndClose (C:\Users\Liang\AppData\Roaming\fnm\node-versions\v16.16.0\installation\node_modules\wrangler\wrangler-dist\cli.js:116659:17)
    at ClientRequest.<anonymous> (C:\Users\Liang\AppData\Roaming\fnm\node-versions\v16.16.0\installation\node_modules\wrangler\wrangler-dist\cli.js:116565:9)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '199.59.148.9',
  port: 443
}


> curl -I 7653e5587bba444793d44fadfd7d0c7a.lifeni.workers.dev  
HTTP/1.1 404 Not Found
Content-Length: 16
Alt-Svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Ray: 74363a6ddb9f8eff-HKG
Connection: keep-alive
Content-Type: text/plain; charset=UTF-8
Date: Wed, 31 Aug 2022 13:49:13 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Referrer-Policy: same-origin
Server: cloudflare
X-Frame-Options: SAMEORIGIN
```
</details>

I checked the url for the connection timeout and it is this: `https://7653e5587bba444793d44fadfd7d0c7a.<name>.workers.dev/` (it changes every time). I can load it in the browser or curl.

So I think the previous problem is more likely a network problem. And there are still some issues with `wrangler dev`.

**Comment by Lifeni** [comment]
@rozenmd   `wrangler dev --local` works fine, thank you!

**Comment by tianluanchen** [comment]
> Hi @tianluanchen, could you please clarify what you mean by "setting the http proxy is useless"? Is there an error message?
> 
> What steps did you take to setup the http proxy?

I set the environment variables by executing the following command

```powershell
$env:HTTP_PROXY="http://127.0.0.1:10809"
```

The error message before and after setting is as follows

```powershell
wrangler pages publish public --project-name xxxx              

X [ERROR] fetch failed

If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose 
```
