### ISSUE TITLE
🐛 BUG: Incorrect error message suggested when publishing pages while multiple accounts available

### ISSUE THREAD

**Issue by Plausible0Bug** [cloudflare/wrangler2#1741]
### What version of `Wrangler` are you using?

wrangler-action@2.0.0

### What operating system are you using?

GitHub actions

### Describe the Bug

Got following error:
```
$ Running: wrangler pages publish ./dist --project-name=angryracoon

✘ [ERROR] More than one account available but unable to select one in non-interactive mode.

  Please set the appropriate `account_id` in your `wrangler.toml` file.
  Available accounts are ("<name>" - "<id>"):
    "Alice@cloudflare.com's Account" - "000f666ff22e22e2ee2c55e22c88a888")
    "Bob@cloudflare.com's Account" - "000f666ff22e22e2ee2c55e22c88a444")
```
When publishing using GitHub actions.
However as far as I'm concerned pages don't support `wrangler.toml`

**Comment by threepointone** [comment]
Try setting the CLOUDFLARE_ACCOUNT_ID environment variable (corresponding to one of those IDs)

**Comment by Plausible0Bug** [comment]
I guess I can already solve my issue by using following config in GitHub action:
```
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=example
```

Where the accountId can be set manually.

I mean the error message itself is buggy, it **should not** suggest user to set account_id in wrangler.toml as it is useless when publishing pages.

**Comment by GregBrimble** [comment]
Thanks for filing the issue. We support an `accountId` input to the [official Pages GitHub Action](https://github.com/cloudflare/pages-action), so hopefully that or the wrangler Action will let you use tokens scoped to multiple accounts.
