### ISSUE TITLE
Support correct asset paths in Jest

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#1755]
In production, the Wrangler source code is bundled into a single file that is stored in the `packages/wrangler/wrangler-dist` directory. Therefore any use of `__dirname` or similar in the source code is relative to this `wrangler-dist` directory. In particular we access template files for `wrangler init` functionality, and also the miniflare binary for `wrangler dev`.

In testing, Jest does not bundle the source code, but instead just strips the TypeScript typings and converts it to CommonJS format. Therefore, any use of `__dirname` will be relative to the source file rather than `wrangler-dist`.  This is mitigated by only using `__dirname` in the top level source files and then using relative paths that start with `..`. Since the source is in `packages/wrangler/src` then `path.resolve(__dirname, '..')` would always result in `packages/wrangler`. But we run into trouble if the source file is one or more directories below `src`.

We should fix this by providing an API that is used to get the "base-path" of the package that is consistent whether in production or testing, and then to have an eslint rule that warns (or errors) if things like `__dirname` are used in everyday code.

(A previous attempt to solve this was at https://github.com/petebacondarwin/wrangler2/commit/e6c3c60f67e252fdad4fab68d13ec96b0c55934e but this was decided against as it adds unwanted counterintuitive complexity.)

**Comment by rozenmd** [comment]
It's also not as easy as this:
```
	typeof jest === "undefined"
				? "../miniflare-dist/index.mjs"
				: "../../miniflare-dist/index.mjs"
```

As we run `local-mode-tests` against wrangler from a different directory again
