### ISSUE TITLE
🚀 Feature Request: Report exception to users

### ISSUE THREAD

**Issue by aseure** [cloudflare/wrangler2#1759]
### Describe the solution

Hello team,

Today, we've spent quite some time trying to guess why `wrangler` was correctly starting (as we were seeing the Wrangler version header being displayed) but silently failing with an exit code of 1 when running from inside some of our build scripts in our CI.

Turns out, the exception thrown in [`cli.ts` here](https://github.com/cloudflare/wrangler2/blob/3904ee40e0de645b3898f7dcf033d3f9ed3b5717/packages/wrangler/src/cli.ts#L13-L18) is not reporting at all. The comment mentions some handling by something called `yargs.fail()` handler, which I'm not knowledgeable about, but nothing is displayed. We found out about the issue by inserting a `console.log()` in the generated JS files in our project to find the root cause of our problem.

Possible solutions that we had in mind:
- add a logging statement to display the thrown exception before exiting the process
- see if the `yargs.fail()` handler is capable of displaying the thrown exception before exiting the process

Thank you for taking the time to consider this feature.

**Comment by JacobMGEvans** [comment]
Is there any reproduction you can provide so I can recreate the same silent error. There seems to be Error handling in place for the `yargs.fail()` and right before it gets to the `cli.ts` code. 
So something is getting lost right before or somehow bypassing all the error checks in the catch.

**Comment by cameron-robey** [comment]
Hey 👋 !
We haven't heard from you about this so we are going to close this. If you have further clarification on this please feel free to reopen this, or open another issue with some more details
