### ISSUE TITLE
How to call functions in proxy

### ISSUE THREAD

**Issue by Swimburger** [cloudflare/wrangler2#177]
I'm trying to run Wrangler with functions and Blazor WASM. Blazor WASM is a front-end framework similar to Angular etc.
The proxy successfully proxies the front-end application, but I am not able to invoke the Cloudflare function, or do not know how to.
This is the command I'm running:
```bash
npx wrangler@alpha pages dev --proxy 7054 -- dotnet watch run
```
There's a function at _functions\sample-weather.js_ that returns some JSON, but calling _https://localhost:7054/sample-weather_ does not return the JSON.
Requesting the function via _http://127.0.0.1:8788/sample-weather_ does work, but I'd have to fetch across origins and set CORS headers to do that. I'm trying to use the proxy functionality to avoid this.

How can I call the function inside of the proxy origin?

**Comment by GregBrimble** [comment]
You should be able to use http://127.0.0.1:8788/ for everything. The `/sample-weather` path will be handled by your function, and static assets will fall back to your proxy process.

**Comment by Swimburger** [comment]
Thank you for the reply. I've been an idiot and got confused about which port is which.
I thought 8788 was where the functions were hosted without proxying the frontend, but it is where the proxy is hosted (functions+frontend).
I disregarded 8788 because I was proxying to and HTTPS address and that didn't seem to work.
After proxying the HTTP host, it started working.
