### ISSUE TITLE
🐛 BUG: Calling wrangler publish will remove KV bindings

### ISSUE THREAD

**Issue by davemurphysf** [cloudflare/wrangler2#1771]
### What version of `Wrangler` are you using?

2.0.28

### What operating system are you using?

Mac

### Describe the Bug

(copied from https://github.com/cloudflare/wrangler/issues/2301)
#### Describe the bug

On wrangler 2.0.28 (and possibly 2.0.26), after I call `wrangler publish` without a wrangler.toml file, my KV bindings are removed from my worker.  My full publish command in case its relevant: `wrangler publish dist/index.mjs --name auth --tsconfig ./tsconfig.json --latest`

#### Reproduce the bug

1. `wrangler login`
2. `wrangler init wrangTest --yes`
3. `cd wrangTest && rm wrangler.toml`
4. `wrangler publish src/index.ts --name wrangtest --latest`
5. [Add KV binding to worker in dashboard.  Name and which KV namespace does not matter]
6. Run `wrangler publish src/index.ts --name wrangtest --latest` again
7. KV binding will be gone :-( 

#### Expected behavior

Existing KV binding should not be removed on `wrangler publish`

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS Monterey 12.5.1
* output of `wrangler -V`:  ⛅️ wrangler 2.0.28
* output of `node -v`: v18.7.0
* content of `wrangler.toml`: no wrangler.toml

**Comment by rozenmd** [comment]
Hey @davemurphysf if you add `--keep-vars` to your wrangler publish command (as of `wrangler@2.1.6`), it'll keep your bindings - there's also a wrangler.toml config for it: https://developers.cloudflare.com/workers/wrangler/configuration/#source-of-truth

**Comment by caass** [comment]
Ok so I've looked into this a little.

When going to add a KV binding to a worker, there's this little warning:

![Image](https://user-images.githubusercontent.com/25358963/195705299-8354b17e-8a90-4d5d-88dc-a24a1f769a7d.png)

And then once you add the binding, you get a popup giving you the code you need to put in your `wrangler.toml`:

![Image](https://user-images.githubusercontent.com/25358963/195705491-698cb899-43c8-40ac-b4f8-53ac2aa1e7b9.png)

And then when you go to publish the worker from wrangler afterwards, you get another warning:

![Image](https://user-images.githubusercontent.com/25358963/195705642-0d7f50c6-7e3d-460b-8287-763149de730a.png)

I suppose we could...provide a diff of the bindings and recommend users add them to their `wrangler.toml` and retry publishing.

**Comment by penalosa** [comment]
@caass Worth noting that all of those warnings were implemented after this issue was filed

**Comment by caass** [comment]
Ah okay fair enough, I'll close this out then.
