### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by davidmartos96** [cloudflare/wrangler2#179]
Hello! It would be great to have a way to run the tool without it opening a new tab in the browser.
I'm using Vite, so in my case it's annoying to keep closing the extra tab that gets opened.

I'm using: `npx wrangler pages dev -- yarn dev` (yarn dev simply calls `vite`)

**Comment by GregBrimble** [comment]
Hi! If you set the env var `BROWSER=none`, e.g. `BROWSER=none npx wrangler pages dev -- yarn dev`, we won't automatically open a browser window for you.

**Comment by davidmartos96** [comment]
@GregBrimble  Thank you! I didn't think about that.

**Comment by Cyb3r-Jak3** [comment]
@GregBrimble Running into this on Windows, and it is harder to work around because windows doesn't let you set an environment variable for just a command. You set it for the entire system and is harder to go back and forth.

**Comment by petebacondarwin** [comment]
I don't suppose you could use one of these ideas https://superuser.com/a/1049433

**Comment by Cyb3r-Jak3** [comment]
I skimmed through the code and found wrangler loads [from .env](https://github.com/cloudflare/wrangler2/blob/02a2cae2c9810a3e7062843907fabcd050c4ae2c/packages/wrangler/src/cli.ts#L1), so added `BROWSER=none` to mine.

**Comment by petebacondarwin** [comment]
Yes that is an option, as long as you don't want to quickly toggle between opening and not opening the browser.
