### ISSUE TITLE
Cannot create binding for class DurableChat that is not exported by the script [API code: 10061]

### ISSUE THREAD

**Issue by Inrixia** [cloudflare/wrangler2#1792]
### What version of `Wrangler` are you using?

1.19.12

### What operating system are you using?

Windows

### Describe the Bug

When trying to deploy a worker with a new DurableObject binding.

For example:
```
[durable_objects]
bindings = [{name = “DurableChat”, class_name = “DurableChat”}]
```

Attempting to `wrangler publish` results in the following error:

```
Cannot create binding for class DurableChat that is not exported by the script [API code: 10061]
```

This error suggests that said class is not exported by the script, however even if the class is not exported it is still given.

The actual issue is new objects require the first publish to include `--new-class DurableChat`. I'm not sure if this is mentioned in the documentation, I didn't see it when checking.

Regardless this error is very misleading, the above error is fine for when the class is actually not exported, but for the actual issue there should be a different error prompting the user to include the `--new-class` flag.

**Comment by petebacondarwin** [comment]
I see you are using 1.19.12. This is a deprecated version of Wrangler (which has its own repository (https://github.com/cloudflare/wrangler).

This repository is for Wrangler versions 2 and upward. This is a complete rewrite and should not have the problem you are reporting. Please can you try upgrading to the new version of Wrangler. Uninstall Wrangler 1, however you installed it. And then run:

```
npm -g install wrangler
```

**Comment by Inrixia** [comment]
Ah, I was under the impression I had already updated. Thankyou

Will close this with the presumption updating fixes this issue

**Comment by zehawki** [comment]
Just wanted to note that I had the same error on 2.9.1. 

Upon investigation, I believe this was my scenario:

Published a DO with class X - all OK
Made lots of changes in local, and then tried to publish with new class Y, and class X deleted - got error

Resolved by deleting the service in the CF console and then republishing. In my case since I'm testing, this approach was fine. In production case, perhaps the right way to handle this would be via a migration?

**Comment by petebacondarwin** [comment]
Yes, @zehawki, in production you need to provide migrations whenever you add, "or delete", a Durable Object class. So in your case you would ave needed to have a migration that told Cloudflare that class X is no longer a Durable Object. If I remember correctly, there is a slight pain in that the class must still exist in the bundle when you first run that migration. But then after that it can be safely removed.
