### ISSUE TITLE
🐛 BUG: Interrupted wrangler pages publish resets wrangler auth state and project selection

### ISSUE THREAD

**Issue by scaleoutsean** [cloudflare/wrangler2#1793]
### What version of `Wrangler` are you using?

2.0.29

### What operating system are you using?

Linux 

### Describe the Bug

I ran this command and pressed CTRL+C while it was getting cache (because I had forgotten to build, so I thought to stop it):

```
$ wrangler pages publish .build
Retrieving cached values for account_id and project_name from node_modules/.cache/wrangler
^C%
```

After I built the project with `npm` I executed the same command again but Wrangler now asked me to login and then to select a project.

```
$ wrangler pages publish .build
Retrieving cached values for account_id and project_name from node_modules/.cache/wrangler
Attempting to login via OAuth...
```

Expected behavior for me would be that stopped cache retrieval wouldn't require OAuth and project selection.

**Comment by GregBrimble** [comment]
Hi @scaleoutsean , thanks for filing this issue. I am unfortunately unable to reproduce this. Are you able to consistency cause this logout behavior?

**Comment by WalshyDev** [comment]
Hey,

This does not seem to be a real problem since the repro is hard and it just requires a re-auth.
