### ISSUE TITLE
🐛 BUG: api.error.service_not_found when publishing a development worker

### ISSUE THREAD

**Issue by poespas** [cloudflare/wrangler2#1824]
### What version of `Wrangler` are you using?

2.1.0

### What operating system are you using?

Linux + Github Actions

### Describe the Bug

It appears `wrangler publish` broke in the recent version. 

The error I'm getting is:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/ACCOUNTID/workers/services/githubrepo-feature-refs-pull-46-merge) failed.

  workers.api.error.service_not_found [code: 10090]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

I'm getting this from just running the command `npx wrangler@2 publish --name=test123` too.

When this happens the error is being thrown from [this line](https://github.com/cloudflare/wrangler2/compare/wrangler%402.0.29...wrangler%402.1.0#diff-fa9a52007c2b6571335f75c75e00cf783306b826a082fe144ac0337b3bfff9fcR522). I'm trying to understand the difference between a script and a service (and it's API counterparts), but I can't really seem to figure out what I'm doing wrong

**Comment by derekps** [comment]
Also experiencing this issue with v2.1.0

**Comment by threepointone** [comment]
@JacobMGEvans i think the unit from dash thing broke publishes

**Comment by JacobMGEvans** [comment]
How is publish even hitting that line...

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans i think the init from dash thing broke publishes

Did a bit of a sanity check, I pulled down the `test-worker2` and published it immediately and it worked. The GitHub Action might be doing something odd, but I am uncertain how functionality in `init` would impact `publish` 
<img width="1106" alt="Screen Shot 2022-09-12 at 1 45 42 PM" src="https://user-images.githubusercontent.com/27247160/189732022-141d7365-8356-438b-8114-8ad775869d0e.png">

**Comment by poespas** [comment]
@JacobMGEvans Hi, just confirming. I am experiencing this on both Github Actions, and manually running this to a non-production (dot_workers) environment. Publishing to a production-env works just fine.

**Comment by threepointone** [comment]
My guess is it's coming from here https://github.com/cloudflare/wrangler2/blob/1553eb3db6712e4eeb82e087bfc25e8fe0916fb4/packages/wrangler/src/publish.ts#L223-L225 

can you try doing a publish on a script that's not been published before?

(I'm afk so can't test this myself)

**Comment by JacobMGEvans** [comment]
I will give it a try.

**Comment by poespas** [comment]
![image](https://user-images.githubusercontent.com/10142882/189735567-83f248e2-1b03-4821-a549-bbc32bd78e6f.png)

**Comment by JacobMGEvans** [comment]
> My guess is it's coming from here
> 
> https://github.com/cloudflare/wrangler2/blob/1553eb3db6712e4eeb82e087bfc25e8fe0916fb4/packages/wrangler/src/publish.ts#L223-L225
> 
> can you try doing a publish on a script that's not been published before?
> 
> (I'm afk so can't test this myself)

Got the same error.

**Comment by petebacondarwin** [comment]
Hmm, maybe if the Worker has never been published before, we can't ask for its previous publish metadata.
Perhaps we just need to wrap this request in a try-catch block?

**Comment by JacobMGEvans** [comment]
> Hmm, maybe if the Worker has never been published before, we can't ask for its previous publish metadata. Perhaps we just need to wrap this request in a try-catch block?

Already made the PR @petebacondarwin 😄
