### ISSUE TITLE
🐛 BUG: A request to the Cloudflare API failed

### ISSUE THREAD

**Issue by lorenbrichter** [cloudflare/wrangler2#1829]
### What version of `Wrangler` are you using?

⛅️ wrangler 2.1.0

### What operating system are you using?

Mac

### Describe the Bug

Got this error when I tried to publish a new worker:

% npm run deploy

> website@0.0.0 deploy
> wrangler publish

 ⛅️ wrangler 2.1.0 
-------------------
Retrieving cached values for userId from node_modules/.cache/wrangler

✘ [ERROR] A request to the Cloudflare API (/accounts/7ec8fc331fa0934755a004c2aab1562b/workers/services/website) failed.

  workers.api.error.service_not_found [code: 10090]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose

Not sure what I did wrong or how to troubleshoot.

Thanks,

**Comment by petebacondarwin** [comment]
We just released 2.1.1, which I believe should resolve this issue.

**Comment by rozenmd** [comment]
Fixed in wrangler@2.1.1

**Comment by lorenbrichter** [comment]
Thank you!
