### ISSUE TITLE
🐛 BUG: wrangler pages dev public errors when public/_headers exists

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#1831]
### What version of `Wrangler` are you using?

2.1.1

### What operating system are you using?

Mac

### Describe the Bug

On 2.1.1 wrangler pages dev public errors with:

```
✘ [ERROR] Miniflare process exited with code 1 
```

if public/_headers exists.  

Removing the file or downgrading to 2.0.29 and it starts fine.

**Comment by mrmcc3** [comment]
Looks like this is fixed in 2.1.2

**Comment by rozenmd** [comment]
Closing as fixed in 2.1.2.

Thanks @mrmcc3!
