### ISSUE TITLE
Cannot assume 127.0.0.1 with ipv6 origins

### ISSUE THREAD

**Issue by maraisr** [cloudflare/wrangler2#184]
Sometimes when using a proxy command, the host actually runs on a ipv6 host `::1` — so cannot proxy that.

https://github.com/cloudflare/wrangler2/blob/562d3adf908541e52be6e463a120f7acbc6ef8ee/packages/wrangler/src/pages.tsx#L786

Might I suggest:

```diff
- url.host = `127.0.0.1:${proxyPort}`;
+ url.host = `localhost:${proxyPort}`; 
```

On all POSIX (unsure about windows) `localhost` is aliased to both ipv6 and v4.

```sh
$ cat /etc/hosts

127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

With your blessing more than happy to raise this as a PR.

For reference:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/599459/147893554-51aee529-85cb-4971-9e02-1e8cc9f7f37f.png">

**Comment by GregBrimble** [comment]
Hi, thanks for flagging this. We've started a related discussion in #181. We had just discussed `0.0.0.0` vs. `localhost`, but this is issue maybe another strong vote for `localhost`.

**Comment by GregBrimble** [comment]
This should be fixed with #181 when we set everything to use `localhost`, but let us know if you're still seeing any quirky behavior.

**Comment by maraisr** [comment]
Nope @GregBrimble that pr was about what host wrangler uses for its dev server, my issue is about which host wrangler uses when proxying the pages dev server port. Please reconsider opening this issue 👍🏻

**Comment by GregBrimble** [comment]
@maraisr , we updated the proxy to localhost as well :) https://github.com/cloudflare/wrangler2/pull/181/files#diff-671053f3ecffd0e36229ae8b3c6090a2becd125b2c3247a41de85836dca29884L900

**Comment by maraisr** [comment]
Good man! Was mega worried for a moment 😧
