### ISSUE TITLE
Non verbose proxy

### ISSUE THREAD

**Issue by davidmartos96** [cloudflare/wrangler2#185]
Is there a way to launch the `wrangler pages dev` proxy in a way that doesn't log every single GET request? I would like it to show only console logs from the worker code during development.

**Comment by Electroid** [comment]
We should consider this for `wrangler dev` as well, same idea.

**Comment by GregBrimble** [comment]
Now that we're using `wrangler dev`'s server, I'll remove the `pages` label as, like @Electroid says, this could be a feature for `wrangler dev` in general.

**Comment by JacobMGEvans** [comment]
Discuss internally about how we want to proceed with a possible `--quiet` mode

**Comment by Helix-DB3** [comment]
![Image](https://user-images.githubusercontent.com/96703991/184793954-cdbc748b-7a20-4726-af3a-9ffdcfba8104.jpg)
Digital Ocean
[https://support.google.com/youtube/contact/ypc2_trans_survey?caseid=AGFLTD275dkF3RYksCvnF0R9KPxpiFUKmWRzt-HF7GcdNKHi0RQgSbok2Qw=&hl=en](app onl)
Youtu.be/pewdiepie.gg/#mine

**Comment by rozenmd** [comment]
Pretty sure I accidentally implemented this as part of https://github.com/cloudflare/wrangler2/pull/1538 - once it's merged we just need a flag/setting to expose it as an option for regular dev.

**Comment by JacobMGEvans** [comment]
> Pretty sure I accidentally implemented this as part of #1538 - once it's merged we just need a flag/setting to expose it as an option for regular dev.

"accidental feature" should be a new PR tag lol

**Comment by JacobMGEvans** [comment]
@rozenmd with that PR merged is this issue resolved?

**Comment by rozenmd** [comment]
We still need to add a flag @JacobMGEvans - but the miniflare-cli now disables logging if `logLevel === "none"`

in api/dev.tsx I call `startDev` with `logLevel: "none",` to disable miniflare's route logging.

**Comment by JacobMGEvans** [comment]
I'm on it 😁
