### ISSUE TITLE
🐛 BUG: A worker set up with `init --from-dash` fails to publish due to empty migrations

### ISSUE THREAD

**Issue by penalosa** [cloudflare/wrangler2#1854]
### What version of `Wrangler` are you using?

2.1.3

### What operating system are you using?

Mac

### Describe the Bug

Running `npm run deploy` in a newly set up `init --from-dash` worker fails with the following message:
<img width="409" alt="Screenshot 2022-09-14 at 13 51 38" src="https://user-images.githubusercontent.com/28503158/190158935-90809ed0-d9f4-4769-9ed8-a31e9776884f.png">

**Comment by lrapoport-cf** [comment]
running into the same error after the following:
- created a new worker via the dash
- migrated it using `init --from-dash`
- made a text change
- ran `wrangler publish`
