### ISSUE TITLE
🐛 BUG: Preview builds are broken

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#1858]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Mac

### Describe the Bug

When you create a PR, and the bot drops a comment with links to your preview artifacts, `npx` doesn't seem to be able to pick them up:

```bash
% npx https://prerelease-registry.developers.workers.dev/runs/3054372461/npm-package-wrangler-1856 whoami
Need to install the following packages:
  wrangler@0.0.0-b8b0e518
Ok to proceed? (y) y
npm ERR! code ETARGET
npm ERR! notarget No matching version found for wrangler@0.0.0-b8b0e518.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rozenmd/.npm/_logs/2022-09-14T16_22_36_931Z-debug-0.log
```

Which is weird, since that URL resolves with a file...

**Comment by petebacondarwin** [comment]
Yeah I think I have seen this. You have to install it locally first, I think. Then it will work. I.e.

```
npm i -D https://prerelease-registry.developers.workers.dev/runs/3054372461/npm-package-wrangler-1856
npx wrangler whoami
```

**Comment by rozenmd** [comment]
Thing is, it used to work (I have a screencap of it working back in early June) 😬

**Comment by petebacondarwin** [comment]
Different version of npm?

**Comment by rozenmd** [comment]
I installed `nvm` over the top of `volta` and now `npx` works again. Weird.
