### ISSUE TITLE
Enhancement: clean-up logLevel/disableLogs

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#1868]
### What version of `Wrangler` are you using?

2.1.4

### What operating system are you using?

Mac

### Describe the Bug

We don't need to prop-drill.

- `LOGGER_LEVELS` in logger.ts needs two new options: `noRoutes: -2` and `none: -1`
- doLog's messageLevel type becomes `Exclude<LoggerLevel, "none" | "noRoutes">,`
- formatMessage's level type becomes  `Exclude<LoggerLevel, "none" | "noRoutes">`

When logLevel comes in via CLI, set the global logger's logLevel.

When we disable Miniflare's route logger, read the global logger's logLevel, and use that instead of `disableLogs`

**Comment by fubhy** [comment]
Just wondering if this will allow disabling the noisy log output (including all proxied requests) when using `pages dev` with a proxied command?

**Comment by JacobMGEvans** [comment]
> Just wondering if this will allow disabling the noisy log output (including all proxied requests) when using `pages dev` with a proxied command?

Currently there is a new flag that should be available now to help with this `pages dev --log-level none`, this is just a refactoring in the code to improve things.

**Comment by JacobMGEvans** [comment]
> > * `LOGGER_LEVELS` in logger.ts needs two new options: `noRoutes: -2` and `none: -1`
> 
> Yeah I saw that but that doesn't seem to work or I'm missing something.
> 
> ```
> npx wrangler@0.0.0-ba0aed63 pages dev --log-level none --port 3001 --proxy 3000 ...
> ```
> 
> Maybe because I'm using the `--proxy` option?

I can look into that more, can you create a Bug issue and ping me in it please.

**Comment by fubhy** [comment]
Sure thing. Sorry for derailing this one ;-)

**Comment by JacobMGEvans** [comment]
> Sure thing. Sorry for derailing this one ;-)

No need to apologize, we appreciate all involvement.
