### ISSUE TITLE
Local dev server does not start

### ISSUE THREAD

**Issue by kyeotic** [cloudflare/wrangler2#187]
I started [this project](https://github.com/kyeotic/snow-tracker/tree/e56547567006b2cf5c756d54c3064a491aebcef6/client) using the `create-remix` with Cloudflare Pages template. The `npm run dev` script used to start a local server, but now it just builds the files without a server.

```
❯ yarn run dev
yarn run v1.22.17
$ cross-env NODE_ENV=development run-p dev:*
$ remix watch
$ wrangler pages dev ./public --watch ./build --kv snow
(node:37225) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Watching Remix app in development mode...
💿 Built in 193ms
```

I'm not sure when this stopped working, there was a week or so where local dev wouldn't work at all, and now it does this. The deployed version in Cloudflare Pages is still working fine, this is a local-only issue.

Wrangler version: `0.0.0-8ab7d2e`

**Comment by GregBrimble** [comment]
Hi! What operating system are you using?

**Comment by kyeotic** [comment]
MacOS Monterey

**Comment by GregBrimble** [comment]
Successfully reproduced this. Not quite sure what's going on, but upgrading to `node` 16.7.0+ and installing the latest `wrangler@beta` (`0.0.7`) seemed to fix things, so give that a go and let me know if you're still having issues. Thanks!

**Comment by kyeotic** [comment]
@GregBrimble My understanding was that the Pages functionality was in the `pages` tag and not yet merged into `beta`

**Comment by GregBrimble** [comment]
The `pages` tag is just an experimental playground for us testing things out. The `beta` tag does have the `wrangler pages dev` command 😊
