### ISSUE TITLE
🔬 Testing: Conversion to Mock Service Workers

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#1874]
Currently new tests are utilizing Mock Service Workers (MSW) and `r2.test` & `whoami.test` were converted to fully utilize the current MSW implementation. 

This is a tracking ticket anyone is welcome to help in conversion
**Files to evaluate and convert if necessary:**
- [x] access.test.ts
- [x] api-dev.test.ts
- [x] api-devregistry.test.js
- [x] api.test.ts
- [x] config-cache-without-cache-dir.test.ts
- [x] config-cache.test.ts
- [x] configuration.test.ts
- [x] delete.test.ts
- [x] deployments.test.ts
- [x] dev.test.tsx
- [x] dialogs.test.tsx
- [x] generate.test.ts
- [x] guess-worker-format.test.ts
- [x] https-options.test.ts
- [x] index.test.ts
- [x] init.test.ts
- [x] jest.setup.ts (this will need further modifying after test files are converted)
- [x] kv.test.ts
- [x] logger.test.ts
- [x] logout.test.ts
- [x] metrics.test.ts
- [x] middleware.scheduled.test.ts
- [x] middleware.test.ts
- [x] package-manager.test.ts
- [x] pages-deployment-tail.test.ts
- [x] pages.test.ts
- [x] parse.test.ts
- [x] paths.test.ts
- [x] publish.test.ts
- [x] pubsub.test.ts
- [x] queues.test.ts
- [x] r2.test.ts
- [x] route.test.ts
- [x] secret.test.ts
- [x] tail.test.ts
- [x] test-old-node-version.js
- [x] type-generation.test.ts
- [x] user.test.ts
- [x] utils-collectKeyValues.test.ts
- [x] validate-dev-props.test.ts
- [x] version.test.ts
- [x] whoami.test.tsx
- [x] worker-namespace.test.ts

**Comment by cameron-robey** [comment]
`worker-namespace` tests:
https://github.com/cloudflare/wrangler2/pull/1898

**Comment by penalosa** [comment]
Reviewing one of the mocking PRs with @mrbbot, it looks like we're still using `jest-fetch-mock` in `jest.setup.ts`, and so I'm not sure how much of our networking stack is being properly tested (MSW probably won't be going through Undici at all). I wonder if using Undici's `MockAgent` for mocking might give a better coverage of the full network flow?
