### ISSUE TITLE
🐛 BUG: oauth flow with remote server

### ISSUE THREAD

**Issue by Dev2211** [cloudflare/wrangler2#1885]
### What version of `Wrangler` are you using?

2.1.4

### What operating system are you using?

Linode

### Describe the Bug

can't connect to linode server 
auth link goes to localhost:8976

**Comment by penalosa** [comment]
Hi! Would you be able to provide a way for us to replicate this issue? In particular:
- The wrangler command you're running
- The operating system you're using (are you trying to run Wrangler within a Linode server?)

**Comment by cameron-robey** [comment]
I assume this is to do with running an OAuth flow on a remote server.
When going to the auth link from a browser on the local machine, the web server hosted on the remote machine won't receive the callback response as they will be redirected on the local machine.

Possible workaround:
Use API tokens, this is the recommended method if using wrangler for CI/CD (https://developers.cloudflare.com/workers/wrangler/ci-cd/)

**Comment by cameron-robey** [comment]
Closing in favour of https://github.com/cloudflare/wrangler2/issues/884

Please open a new issue @Dev2211 if this is not the same issue
