### ISSUE TITLE
Support .env via miniflare

### ISSUE THREAD

**Issue by marbiano** [cloudflare/wrangler2#190]
Miniflare [automatically supports](https://miniflare.dev/variables-secrets.html#env-files) picking up the content of .env files. This is a very common practice in Node environments and is especially handy when building projects with frameworks like Remix that support multiple deployment targets. I think it would be beneficial and very handy to add support for this on wrangler2.

**Comment by threepointone** [comment]
Yeah, maybe. I'm thinking deeply about vars/secrets lately. It'll likely involve dotenv, or something similar. I'll assign this to myself atm.

**Comment by anonrig** [comment]
This became an issue for me. I'm trying to convert a Remix application running on Vercel to Cloudflare Pages and had to connect to Discord to understand why this does not work (which made me comment this for future reference)

```
"node -r dotenv/config node_modules/.bin/wrangler pages dev ./public --watch ./build ./styles"
```

**Comment by BasixKOR** [comment]
Would you mind if I make a PR implementing this? I think passing `envPath` the detected `.env` file with the `--env` option to override to Miniflare would be enough, but it seems like you have a different idea in mind.

**Comment by motiejunas** [comment]
> Yeah, maybe. I'm thinking deeply about vars/secrets lately. It'll likely involve dotenv, or something similar. I'll assign this to myself atm.

@threepointone so what is on your mind? Can @BasixKOR move forward with `envPath` idea?

**Comment by threepointone** [comment]
We haven't taken a call here yet. It has to apply in both local and edge mode, (and not just pages) and we don't want to create a dependency without understanding it deeply. We may likely go with dotenv, but we just haven't taken a call yet.

**Comment by BasixKOR** [comment]
Ah, I haven't given a thought about edge mode. My thought was that since Miniflare already supports importing a .env file we could pass the path of the file, but this wouldn't work on edge mode.

**Comment by petebacondarwin** [comment]
Perhaps we could add support for two variants of .env files: wrangler.env and runtime.env?

The former would be provided to Wrangler (i.e. for bundling in publish and dev, and for specifying things like CLOUDFLARE_API_TOKEN for many of the commands that need to access the Cloudflare API).
The latter would be provided to the runtime as variable bindings, which should satisfy the scenario of specifying secrets in local mode.

**Comment by marbiano** [comment]
Thank you, folks!
