### ISSUE TITLE
Cleanup: configuration.test has assertions that make no sense

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler2#1922]
Lots of usages of `expect.anything` without calling it as a function (it should be `expect.anything()`)

e.g.

```ts
expect(config).toEqual(
	expect.not.objectContaining({ durable_objects: expect.anything })
);
```

`normalizeAndValidateConfig` actually _doesn't_ strip invalid config lines from the returned object, so either it needs to start doing this, or these expectation lines need to be dropped.

I think everything seems ok right now because if there are any errors, the process exits and the config is never used. But this should be fixed.

**Comment by cameron-robey** [comment]
Is this (and https://github.com/cloudflare/wrangler2/issues/1923) something that you are going to look at, or should dev prod pick this up @geelen ?
