### ISSUE TITLE
🐛 BUG: ✘ [ERROR] Could not resolve "@cloudflare/pages-plugin-sentry"

### ISSUE THREAD

**Issue by aensley** [cloudflare/wrangler2#1925]
### What version of `Wrangler` are you using?

2.1.6

### What operating system are you using?

Windows (Git Bash/MINGW)

### Describe the Bug

# Summary

I am unable to resolve any packages in Cloudflare workers despite them being listed on <https://workers.cloudflare.com/works> and working locally through wrangler.

I followed the [official guide](https://developers.cloudflare.com/pages/platform/functions/plugins/sentry/) to integrate Sentry as middleware.

### Repo/branch

https://github.com/aensley/liturgy-day/tree/add-sentry-2

### Source

https://github.com/aensley/liturgy-day/blob/12f431856ec80533f29ffa5bc08320ad6dd7d464/functions/_middleware.ts#L1-L8

### Build Error

```Shell
09:39:43.463 | Cloning repository...
-- | --
09:39:44.397 | From https://github.com/aensley/liturgy-day
09:39:44.397 | * branch            12f431856ec80533f29ffa5bc08320ad6dd7d464 -> FETCH_HEAD
09:39:44.397 |  
09:39:44.443 | HEAD is now at 12f4318 add wrangler?
09:39:44.443 |  
09:39:44.551 |  
09:39:44.573 | Success: Finished cloning repository files
09:39:45.069 | No build command specified. Skipping build step.
09:39:45.559 | 🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
09:39:45.625 | ✘ [ERROR] Could not resolve "@cloudflare/pages-plugin-sentry"
09:39:45.625 |  
09:39:45.625 | ../../../buildhome/repo/functions/_middleware.ts:1:25:
09:39:45.625 | 1 │ import sentryPlugin from '@cloudflare/pages-plugin-sentry'
09:39:45.626 | ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
09:39:45.626 |  
09:39:45.626 | You can mark the path "@cloudflare/pages-plugin-sentry" as external to exclude it from the bundle, which will remove this error.
09:39:45.627 |  
09:39:45.630 | 1 error(s) and 0 warning(s) when compiling Worker.
09:39:45.631 |  
09:39:45.718 | [31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mBuild failed with 1 error:[0m
09:39:45.718 |  
09:39:45.718 | ../../../buildhome/repo/functions/_middleware.ts:1:25: ERROR: Could not resolve "@cloudflare/pages-plugin-sentry"
09:39:45.718 |  
09:39:45.718 |  
09:39:45.718 | [32mIf you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose[0m
09:39:45.727 | Failed building Pages Functions from /functions.
09:39:46.537 | Failed: an internal error occurred
```

### Local output (successful)

![image](https://user-images.githubusercontent.com/95717/192315914-5b958c7b-47ef-4ab5-8b6e-03a5cc909626.png)

```Shell
me@my-computer MINGW64 ~/Workspaces/liturgy-day (add-sentry-2)
$ npx wrangler pages dev src --binding SENTRY_DSN="https://xxxxxxxxxxxxx@xxxxxxx.ingest.sentry.io/xxxxxxxxx" --binding ENVIRONMENT="local"
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Compiling worker to "C:\Users\me\AppData\Local\Temp\functionsWorker-0.9120506640895183.js"...
Compiled Worker successfully.
▲ [WARNING] Passing --inspect is unnecessary, now you can always connect to devtools.

╭────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit  │
╰────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://0.0.0.0:9229/972d75ea-2273-4625-8023-a5817c6a81ab
For help, see: https://nodejs.org/en/docs/inspector
[pages:wrn] Parsed 2 valid header rules.
[pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[pages:inf] Worker reloaded! (195.16KiB)
[pages:inf] Listening on 0.0.0.0:8788
[pages:inf] Updated `Request.cf` object cache!
GET /api/day/2022-09-26 200 OK (19.75ms)
```

**Comment by aensley** [comment]
Hi @nevikashah, do you have any ideas about what could be causing my issue?

**Comment by davidmurdoch** [comment]
Same issue here, but with `@cloudflare/kv-asset-handler`, but only when using `cloudflare/wrangler-action@2.0.0`

**Comment by thexeos** [comment]
Although unrelated to https://github.com/cloudflare/wrangler2/labels/pages doing `import '@cloudflare/workers-types'` (aka importing worker types locally, rather than globally via tsconfig.json) also triggers this error:

```
  You can mark the path "@cloudflare/workers-types" as external to exclude it from the 
  bundle, which will remove this error.

X [ERROR] Build failed with 1 error:

  src/worker.ts:7:7: ERROR: Could not resolve "@cloudflare/workers-types"
```

**Comment by aensley** [comment]
Hi @nevikashah, any updates?

**Comment by harikrishnan83** [comment]
> Same issue here, but with `@cloudflare/kv-asset-handler`, but only when using `cloudflare/wrangler-action@2.0.0`

I was having the same issue, I have temporarily resolved this by adding a precommand to install `@cloudflare/kv-asset-handler`, is there a better approach?

```yaml
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm install @cloudflare/kv-asset-handler@0.2.0
          command: publish
```

**Comment by jrf0110** [comment]
Hey there, @aensley - did you ever get this resolved? I followed your reproduction repo and it seems like your Github Actions are running smoothly

**Comment by aensley** [comment]
@jrf0110 No, this is not resolved. My actions are working on other branches that exclude this package. Every build that references the cloudflare-maintained Sentry package still fails with the error above. I jave received no help in resolving this.

**Comment by aensley** [comment]
I have finally resolved this issue. The problem was that the build command configuration in Cloudflare Pages did not include `npm install`. I always thought this was run transparently in the background for NPM sites since I never had to explicitly add it before.
