### ISSUE TITLE
🐛 BUG: Cannot access D1 bindings if `no_bundle` is set

### ISSUE THREAD

**Issue by sid405** [cloudflare/wrangler2#1954]
### What version of `Wrangler` are you using?

2.1.9

### What operating system are you using?

macOS

### Describe the Bug

When I set `no_bundle = true` in my `wrangler.toml`, D1 bindings show up as `undefined` in my worker, at runtime (aka after `wrangler publish`), and during `wrangler dev`.

There's an internal thread on the D1 channel where Glen suggested this should work, so I thought I'd document this here.
I'm happy to delete/move this issue wherever y'all think is appropriate, since these are unsupported/beta features.

**Comment by cameron-robey** [comment]
To clarify based on internal discussion:
You cannot use D1 bindings without running through wrangler's bundling. This means that the `--no-bundle` flag or `no_bundle` option `wrangler.toml` mean D1 will not work.

Temporary solution is to throw an error if D1 bindings are used with the `no-bundle`, which is implemented in https://github.com/cloudflare/wrangler2/pull/1955.
