### ISSUE TITLE
🧹 Chore: Update Undici 5.11.0

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#1977]
Update to Undici 5.11.0 and utilize the effort from @cameron-robey in https://github.com/nodejs/undici/pull/1606 to remove the ponyfill we implemented to handle support for multipart/form-data until Undici could support it. 

Undici Release Ref: https://github.com/nodejs/undici/releases/tag/v5.11.0

**Comment by cameron-robey** [comment]
:D
