### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by jihanc** [cloudflare/wrangler2#1995]
### What version of `Wrangler` are you using?

wrangler@2.1.10

### What operating system are you using?

Linux

### Describe the Bug

Total Upload: 15.97 KiB / gzip: 3.92 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/43459a110fd74ca85bf5ab8f68040187/workers/scripts/template) failed.

  Uncaught ReferenceError: reflare is not defined
    at worker.js:472:3
    at worker.js:492:3
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose

**Comment by jihanc** [comment]
I used this project (https://github.com/xiaoyang-sde/reflare) and followed the tutorial and had the above problem.

**Comment by penalosa** [comment]
This is likely an issue with your installation of `reflare`. Have you run `npm install reflare`?

**Comment by jihanc** [comment]
Thanks for the reply. I followed the tutorial and redid what I did before and ran npm install reflare and still had the same problem.

**Comment by jihanc** [comment]
I have solved it, Reflare does not support pan-domains. Thanks!

**Comment by jihanc** [comment]
Resolved
