### ISSUE TITLE
`npx wrangler@beta dev index.js` opens an OAuth login screen, errors on auth callback

### ISSUE THREAD

**Issue by austincrim** [cloudflare/wrangler2#20]
First off, wrangler 2.0 looks incredible! I'm super excited about it and appreciative of everyone's hard work.

I'm trying to follow the [quick start](https://github.com/cloudflare/wrangler2#quick-start) found in the readme and running into some trouble.

After running `npx wrangler@beta dev index.js`, my browser opens the Cloudflare OAuth flow. After clicking "Allow", it fails to callback to `localhost:8976` and I get the following error in my terminal:

```bash
❯ npx wrangler@beta dev index.js
/Users/austincrim/.npm/_npx/dce38835dbc726fc/node_modules/wrangler/wrangler-dist/index_node.js:27064
            throw ex;
            ^

[Error: ENOENT: no such file or directory, open '/Users/austincrim/.wrangler/config/default.toml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/austincrim/.wrangler/config/default.toml'
}

Node.js v17.1.0
```

**Environment**
node: 17.1.0
npm: 8.1.2
macOS Monterrey: 12.0.1
M1 Macbook Pro

**Comment by threepointone** [comment]
Sorry about that! I think I figured out the problem here, will fix tonight. As a workaround, run `mkdir ~/.wrangler/config -p` in your terminal, and try again. I'll leave this issue open till I fix it properly.

**Comment by threepointone** [comment]
This should be fixed in the latest beta, just published.
