### ISSUE TITLE
🐛 BUG: wrangler pages doesn't work with Vite HMR 

### ISSUE THREAD

**Issue by DominicTobias** [cloudflare/wrangler2#2010]
### What version of `Wrangler` are you using?

2.1.11

### What operating system are you using?

Mac

### Describe the Bug

I generated a SolidJS project with `npx degit solidjs/templates/ts my-app`. I've also updated all deps to latest:
```
 solid-js           ^1.5.1  →  ^1.5.7
 typescript         ^4.8.2  →  ^4.8.4
 vite               ^3.0.9  →  ^3.1.7
 vite-plugin-solid  ^2.3.0  →  ^2.3.9
 ```

Add wrangler: `yarn add -D wrangler`

Change the "dev" in "scripts" of `package.json`: `"dev": "wrangler pages dev -- yarn start"`

Run `yarn dev`

Note when visiting http://127.0.0.1:8788/ the HMR websocket has failed to connect.

Setting `hmr.port` or `hmr.clientPort` to the vite one (e.g. `3000`) breaks in other ways.

## However running the two servers separately works:

First for some Vite specific reason need to set the `hmr.port`:

```js
export default defineConfig({
  plugins: [solidPlugin()],
  server: {
    port: 3000,
    hmr: {
      port: 443,
    },
  },
  build: {
    target: "esnext",
  },
});
```

Now add `"local-server": "wrangler pages dev --proxy=3000"` to `package.json` "scripts"

Run `yarn start` + `yarn local-server`. HMR is working at http://localhost:8788/ !

You might think `yarn dev` now works because of the `port: 443` change but actually it's broken in a different way. http://localhost:8788/  now shows "Upgrade Required" in the browser window as if it accidentally intercepted the Websocket handshake response and displayed it.

**Comment by fubhy** [comment]
You can solve this by configuring vite server like this:

```
    server: {
      port: 3000,
      hmr: {
        clientPort: 3000,
      },
```

And then using `wrangler pages dev` like this:

```
npx wrangler pages dev --port 3001 --proxy 3000 -- pnpm vite dev
```

**Comment by DominicTobias** [comment]
Thanks!
