### ISSUE TITLE
🚀 Feature Request: Deprecate `--latest`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#2025]
### Describe the solution

By default, `--latest` is true. The flag itself isn't actually used anywhere. If you specify a `--compatibility-date`, that takes precedence.

Instead, we should probably just deprecate (and eventually remove `--latest`) and default `--compatibility-date` to today?

**Comment by GregBrimble** [comment]
cc @penalosa

**Comment by petebacondarwin** [comment]
It is used in `publish`:

```
		compatibilityDate: args.latest
			? new Date().toISOString().substring(0, 10)
			: args["compatibility-date"],
```

**Comment by GregBrimble** [comment]
Ah, sorry, missed that. Coming from Pages, I was just looking in `dev`. I'll close this out.
