### ISSUE TITLE
Is there a way to watch the file through the `wrangler pages dev` command and update the site whenever the file changes?

### ISSUE THREAD

**Issue by hyunjunian** [cloudflare/wrangler2#203]
Is there a way to watch the file through the wrangler pages command and update the site whenever the file changes?

For example:

`wrangler pages dev ./public --watch ./build`

I saw this command in [remix-cloudflare-pages template](https://github.com/remix-run/remix/blob/1fd70960e4d88740df5bf407a6ba2cd2b9549459/packages/create-remix/templates/cloudflare-pages/package.json#L7).

**Comment by GregBrimble** [comment]
#160 added this functionality, so you no longer need the `--watch ./build` part of that command. Just upgrade to the latest alpha/beta

```sh
npm install --save-dev wrangler@beta
```

And it should just work! 🤞

**Comment by hyunjunian** [comment]
@GregBrimble Thank you for your answer! It works~
