### ISSUE TITLE
🐛 BUG: COMMAND FAILED

### ISSUE THREAD

**Issue by Larrychi101** [cloudflare/wrangler2#2030]
### What version of `Wrangler` are you using?

2.1.11

### What operating system are you using?

Mac

### Describe the Bug

✘ [ERROR] Command failed with exit code 128: git clone --depth 1 https://github.com/Larrychi101/Sologid-app.git.git /var/folders/j0/wm98lqpj62nb1w8gh9jq036w0000gn/T/wrangler-generate-repo-pMO2lM

remote: Repository not found.

**Comment by caass** [comment]
Can you provide the exact command and arguments you passed to wrangler? Something like `wrangler generate my-worker https://github.com/Larrychi101/Sologid-app.git.git`. It looks like somehow there was an extra `.git` extension added to the repository path, which is what caused the clone to fail.

**Comment by caass** [comment]
Hey, I'm going to close this out as we haven't heard back from you. Thanks for opening!
