### ISSUE TITLE
Advanced TypeScript support

### ISSUE THREAD

**Issue by mosch** [cloudflare/wrangler2#2033]
When it comes to typescript we have to manually link the `wrangler.toml` with TypeScript. For me this might look like this:

```ts
interface Env {
  MyKVVariable: KVNamespace
}
```

Some other libraries generate these types for you, so you can't mess up by removing it from the config, but TypeScript still thinks it's there. I think this would be a cool feature for us too!

**Comment by JacobMGEvans** [comment]
> where the magic happens

Permalink: https://github.com/prisma/prisma/blob/c1afd2977ca2cfded5686f923d2ec855e08a0c22/packages/client/src/generation/generateClient.ts
