### ISSUE TITLE
🐛 BUG: environment variables incorrectly pulled when using init --from-dash

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/wrangler2#2048]
### What version of `Wrangler` are you using?

2.1.12

### What operating system are you using?

Mac

### Describe the Bug

- created fresh new worker `init-from-dash-test-3` in the dash
- added two environment variables:
![image](https://user-images.githubusercontent.com/107272160/196845517-d592dde5-881c-471b-a895-420d7414fc6e.png)
- ran `wrangler init --from-dash init-from-dash-test-3`
- checked .toml and observed mismatch with environment variables:
![image](https://user-images.githubusercontent.com/107272160/196845684-14594aa2-f02d-4948-84ac-9d44917a82a5.png)

**Comment by JacobMGEvans** [comment]
Yeah, I think the API changed on us. I will take a look ASAP
