### ISSUE TITLE
Chore: unstable_dev's `script` option is confusing

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#2051]
### What version of `Wrangler` are you using?

latest

### What operating system are you using?

Mac

### Describe the Bug

Currently, `unstable_dev` is using the package.json(?) as a frame of reference for where to look for the Worker script - it should just be relative to whatever is calling `unstable_dev` to avoid confusion.

**Comment by rozenmd** [comment]
@threepointone to avoid needing to ship a breaking change, what if we document this https://github.com/cloudflare/wrangler2/pull/2284/files#diff-948ab151351c5c08b7ed9d36e13487ed37db1ac5f0c5c8992e2e1a16ad5db5c6R15-R20 instead?

Also thinking of potentially adding an option to unstable_dev itself (3rd arg) to let folks change the default behaviour

**Comment by threepointone** [comment]
You can make a breaking change here, it's an unstable api haha. I think it should only always use the file it's being called from as a reference

**Comment by rozenmd** [comment]
Closing this as figuring out where a function is being called from isn't reliable in Node
