### ISSUE TITLE
🚀 Feature Request: Unpublish worker

### ISSUE THREAD

**Issue by polRk** [cloudflare/wrangler2#2087]
### Describe the solution

How can i unpublish my worker via cli? Need for CI/CD (unpublish after pr merged)

**Comment by threepointone** [comment]
`wrangler delete --name <name>` should work

**Comment by JacobMGEvans** [comment]
Hope this helped @polRk, feel free to join the Discord and check out the Wrangler channel for additional help or support https://discord.com/invite/CloudflareDev
