### ISSUE TITLE
🐛 BUG: Route of `*/*` can no longer be deployed with Wrangler

### ISSUE THREAD

**Issue by nathanclevenger** [cloudflare/wrangler2#2095]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Mac and Linux

### Describe the Bug

We have been using the pattern of:
```
route = { pattern = "*/*", zone_name = "decode.do" }
```
for all our workers, which is required for Cloudflare for SaaS so that external custom domains that have a CNAME to the Zone are able to trigger the Worker Route.  This has worked for a long time, but recently it seems that we get an error from Wrangler on deploy: "Invalid URL" if it doesn't include the zone name in the route like this:
```
route = { pattern = "*decode.do/*", zone_name = "decode.do" }
```

But this is not an acceptable solution, as deploying a Worker with this Route breaks on all Cloudflare for SaaS routes.

It appears this was caused by <https://github.com/cloudflare/wrangler2/pull/1946/files>

**Comment by fenos** [comment]
I'm hitting the same exact problem, is there any workaround?

**Comment by fenos** [comment]
@nathanclevenger thanks!

I actually downgraded to 2.1.11 for the time being where the bug is not present, I'll upgrade once fixed and released not a big deal for 2 minor versions

**Comment by ThePaulMcBride** [comment]
This is still an issue right? Should this be closed?
