### ISSUE TITLE
🐛 BUG: Entry-point file at "src/index.ts" was not found

### ISSUE THREAD

**Issue by AmineArif1** [cloudflare/wrangler2#2097]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

wsl2

### Describe the Bug

Hello !
## The error
```
✘ [ERROR] The entry-point file at "src/index.ts" was not found.
```
## how to reproduce
-install Wrangler
- 
```
wrangler init  --from-dash (worker's name)
```
-chose JS instead of TS
-cd "worker's name" (btw idk why it suggested undefined) && npm start
![image](https://user-images.githubusercontent.com/22842587/198825277-a8c31c8b-f7e7-44e7-bf72-3d80ed11e5ab.png)
-
![image](https://user-images.githubusercontent.com/22842587/198825354-0db89abe-9ce5-4951-a969-e8bf3e10f53d.png)

**Comment by JacobMGEvans** [comment]
> (btw idk why it suggested undefined) 
That is another known bug. Thank you for reporting this 😃
