### ISSUE TITLE
🐛 BUG: Unable to publish a worker sometimes

### ISSUE THREAD

**Issue by njlg** [cloudflare/wrangler2#2104]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Linux

### Describe the Bug

I'm getting this trying to publish a worker:

```
✘ [ERROR] Received a malformed response from the API
  <!DOCTYPE html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
  <!--[if I... (length = 4314)
  PUT /accounts/{number}/storage/kv/namespaces/{number}/bulk -> 500 Internal Server Error
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
```

Occasionally, I saw this error last week... and doing the publish again seemed to work. Today I got the error three times in a row.

**Comment by joshgordonsolo** [comment]
https://github.com/cloudflare/wrangler2/pull/2098
Is there a way to verify this did not break things?

**Comment by njlg** [comment]
I tried wrangler version `2.1.10` and had the same problem.

The weird thing -- in my case -- is that this only happens with one environment. I can deploy the same set of files & worker to another environment.

**Comment by joshgordonsolo** [comment]
`Deleting sw.{hash}.js from the asset store...

✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  
  <!--[if I... (length = 4313)

  PUT /accounts/{number}/storage/kv/namespaces/{number}/bulk -> 500 Internal Server Error`

**Comment by joshgordonsolo** [comment]
We're thinking we may be hitting the KV limit of 10,000 or 100MB request size after the addition of some pages/content to our site.
https://developers.cloudflare.com/workers/wrangler/cli-wrangler/commands/#kvbulk

**Comment by JacobMGEvans** [comment]
Internal ticket resolved regarding the KVNamespaces Bulk API failing before size limit is reached.
