### ISSUE TITLE
🐛 BUG: Script with D1 bindings cannot be used as a Queue consumer

### ISSUE THREAD

**Issue by jbw1991** [cloudflare/wrangler2#2131]
### What version of `Wrangler` are you using?

queues

### What operating system are you using?

Linux

### Describe the Bug

Add a Queue consumer to an existing script with D1 bindings and attempt to run `wrangler publish`. The API will reject the script, claiming that it has no "queue" event handler.

Most likely, we simply need to add the `queue()` event handler to the D1 shim here: https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/templates/d1-beta-facade.js#L165-L173

**Comment by rozenmd** [comment]
Closing this as resolved in https://github.com/cloudflare/wrangler2/pull/2194
