### ISSUE TITLE
🐛 BUG: D1 - Unable to use simple database

### ISSUE THREAD

**Issue by marko-simic** [cloudflare/wrangler2#2135]
### What version of `Wrangler` are you using?

2.1.15

### What operating system are you using?

Mac

### Describe the Bug

I keep getting the following error for `npx wrangler d1 execute` command
`
ERROR 9009: SQL prepare error: near "SQLite": syntax error in SQLite format 
`
Databese:
`
CREATE TABLE "users" (
	"id"	INTEGER,
	"first_name"	,
	PRIMARY KEY("id")
);
`
[base.sql.zip](https://github.com/cloudflare/wrangler2/files/9946152/base.sql.zip)

**Comment by rozenmd** [comment]
Hey @marko-simic, sorry that you've run into this issue - does it work if you convert your sql file from `SQLite format` to regular SQL statements in plain text?

**Comment by rozenmd** [comment]
Anyway I've updated the `--file` flag to throw an error in this case, and we have plans to add `wrangler d1 restore` to handle .sqlite files
