### ISSUE TITLE
🐛 BUG: `wrangler logout` attempts to log me back in immediately

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#2141]
### What version of `Wrangler` are you using?

2.1.15

### What operating system are you using?

Mac

### Describe the Bug

```sh
npx wrangler logout
 ⛅️ wrangler 2.1.15
--------------------
Successfully logged out.
Attempting to login via OAuth...
```

**Comment by JacobMGEvans** [comment]
Oh that is weird... Wonder what is causing that.

**Comment by threepointone** [comment]
I can confirm this is happening too. Seems bad.

**Comment by threepointone** [comment]
Hrmm, I can't reproduce this with 2.3.1 either. Odd. I'll keep an eye on it.

**Comment by jspspike** [comment]
Closing for now, likely fixed with ink changes. Feel free to reopen if the error occurs again
