### ISSUE TITLE
🐛 BUG: Response.redirect - showing up as an entirely empty body

### ISSUE THREAD

**Issue by MyNameIsTito** [cloudflare/wrangler2#2145]
### What version of `Wrangler` are you using?

Unknown

### What operating system are you using?

Windows

### Describe the Bug

Having an issue with the `mailchannelsPlugin` as discussed in the [pages-plugins](https://discord.com/channels/595317990191398933/967071916160610344/1039840810499313674) Channel in the [Cloudflare Discord](https://discord.gg/cloudflaredev).

when submitting a form, the page just shows up as an "entirely empty body" the code that I'm using to try and redirect the page is below.

```ts
  respondWith: () => {
    return Response.redirect('https://domain.tld/thank-you/', 302);
  },
})(context);
```

I tried removing the `https://` from the `Response.redirect` but it gave an error of unable to parse the URL.

Not sure if its an isolated issue due to my poor TypeScript knowledge or an actual issue with Wrangler.

Cheers,
Tito

**Comment by MyNameIsTito** [comment]
The location in the Response Header is showing as it should as well.
![Response Headers](https://i.imgur.com/GNoOp0U.png)

**Comment by klaemo** [comment]
Here's a minimal repro: https://github.com/klaemo/cloudflare-functions-status-bug.

I reported this on discord on 2022-10-31 and there's supposed to be an internal ticket for it somewhere.

**Comment by MyNameIsTito** [comment]
Cheers for that @klaemo

**Comment by chescos** [comment]
BTW, I experience this issue due to the [Sentry](https://developers.cloudflare.com/pages/platform/functions/plugins/sentry/) plugin. So it may be all plugins causing this issue, or at least some of them.
