### ISSUE TITLE
🐛 BUG: Startup script exceeded CPU time limit

### ISSUE THREAD

**Issue by callensm** [cloudflare/wrangler2#2152]
### What version of `Wrangler` are you using?

2.1.15

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to publish an update to an existing worker through `wrangler` and running into this error now. The worker is unbounded so it _should_ have a much longer script startup and time limit than the other plan, but it doesn't seem to make a difference.

I saw on the documentation that a worker's size is limited to 1 MB after compression, and if thats the case then this should still work since the gzip size is ~930 KiB.

```
$ wrangler publish
 ⛅️ wrangler 2.1.15 
--------------------
▲ [WARNING] Enabling node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.

Total Upload: 4816.91 KiB / gzip: 929.53 KiB

✘ [ERROR] A request to the Cloudflare API (*******) failed.

  Error: Script startup exceeded CPU time limit.
   [code: 10021]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After trying with `--minify` enabled, the compressed size is even further decreased to ~700 KiB and still fails with the same error.

**Comment by callensm** [comment]
There are no additional scripts, just running via `wrangler publish`

**Wrangler Toml**
```toml
name = "****"
main = "src/index.ts"
compatibility_date = "2022-10-14"
node_compat = true
minify = true

[env.production]
name = "****"
```

**Debug Log**
```
$ wrangler publish
 ⛅️ wrangler 2.1.15 
--------------------
Retrieving cached values for userId from node_modules/.cache/wrangler
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"deploy worker script","properties":{"usesTypeScript":true}}.
-- START CF API REQUEST: GET https://api.cloudflare.com/client/v4/accounts/******/workers/services/******
HEADERS: {
  "Authorization": "Bearer ******",
  "User-Agent": "wrangler/2.1.15"
}
INIT: {}
-- END CF API REQUEST
-- START CF API RESPONSE: OK 200
HEADERS: {}
RESPONSE: {
  "result": {
    "id": "******",
    "default_environment": {
      "environment": "production",
      "created_on": "2022-10-14T03:15:38.369656Z",
      "modified_on": "2022-11-10T15:40:15.24773Z",
      "script": {
        "created_on": "2022-10-14T03:15:38.369656Z",
        "modified_on": "2022-11-10T15:40:15.24773Z",
        "id": "******",
        "tag": "******",
        "tags": [],
        "version_id": "",
        "etag": "******",
        "handlers": [
          "router",
          "strict",
          "_tempPath",
          "path",
          "routes",
          "notFoundHandler",
          "errorHandler",
          "handleEvent",
          "fetch",
          "request",
          "get",
          "post",
          "put",
          "delete",
          "head",
          "options",
          "patch",
          "all"
        ],
        "last_deployed_from": "wrangler",
        "compatibility_date": "2022-10-14",
        "usage_model": "unbound"
      }
    },
    "created_on": "2022-10-14T03:15:38.369656Z",
    "modified_on": "2022-11-10T15:40:15.24773Z",
    "usage_model": "",
    "environments": [
      {
        "environment": "production",
        "created_on": "2022-10-14T03:15:38.369656Z",
        "modified_on": "2022-11-10T15:40:15.24773Z"
      }
    ]
  },
  "success": true,
  "errors": [],
  "messages": []
}

-- END CF API RESPONSE
▲ [WARNING] Enabling node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


-- START CF API REQUEST: PUT https://api.cloudflare.com/client/v4/accounts/******/workers/scripts/******?include_subdomain_availability=true&excludeScript=true
HEADERS: {
  "Authorization": "Bearer ******",
  "User-Agent": "wrangler/2.1.15"
}
INIT: {
  "method": "PUT",
  "body": {}
}
-- END CF API REQUEST
Total Upload: 2350.36 KiB / gzip: 717.17 KiB
-- START CF API RESPONSE: Bad Request 400
HEADERS: {}
RESPONSE: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Error: Script startup exceeded CPU time limit.\n"
    }
  ],
  "messages": []
}

-- END CF API RESPONSE

✘ [ERROR] A request to the Cloudflare API (/accounts/******/workers/scripts/******) failed.

  Error: Script startup exceeded CPU time limit.
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by callensm** [comment]
@JacobMGEvans any ideas for me to try and resolve this?

**Comment by JacobMGEvans** [comment]
Not currently, but will discuss it with the team during our triage meeting.

**Comment by caass** [comment]
The error you're seeing is due to the script's _startup_ taking too long, not the script itself. If there's heavy processing that happens before the `fetch` (or other event) handler is called, that can cause the script to time out. If you have any setup logic, it could be worth moving it inside the event handler and seeing if that fixes your issue.

**Comment by callensm** [comment]
the worker is a rest api using the `hono` library. here is a sample of my `index.ts` entrypoint into the worker code:

```ts
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { logger } from 'hono/logger';
import * as routers from './routers';

const app = new Hono();
app.use('*', logger());
app.use('*', cors());
app.notFound(c => c.json({ error: 'Not Found' }, 404));

app.get('/api/health', c => c.json({ status: 'ok' }, 200));

app.route('/api/curation', routers.curation);
app.route('/api/identity', routers.identity);
app.route('/api/publish', routers.publish);
app.route('/api/storage', routers.storage);

export default app;
```

**Comment by caass** [comment]
maybe the call to `logger()` or `cors()` is hanging for some reason? i'm not sure...we'll investigate further

**Comment by callensm** [comment]
it started after adding a certain dependency for a new feature, but even with the new dependency the compressed bundle size is within the limits.

This is for an unbound worker as well, so shouldn't the time limit for startup scripts be much longer?

**Comment by JacobMGEvans** [comment]
> it started after adding a certain dependency for a new feature, but even with the new dependency the compressed bundle size is within the limits.
> 
> This is for an unbound worker as well, so shouldn't the time limit for startup scripts be much longer?

As @caass had mentioned it's not a size issue. 
> The error you're seeing is due to the script's startup taking too long, not the script itself. If there's heavy processing that happens before the fetch (or other event) handler is called, that can cause the script to time out. If you have any setup logic, it could be worth moving it inside the event handler and seeing if that fixes your issue.

**Comment by clgeoio** [comment]
Hey all!

I'm noticing this issue too, I'm using the Cloudflare worker github action to deploy my worker. I'm using Remix as my "framework" to handle everything

If there's anything I can configure to help, that'd be great.

Thanks

**Comment by JacobMGEvans** [comment]
> Hey all!
> 
> I'm noticing this issue too, I'm using the Cloudflare worker github action to deploy my worker. I'm using Remix as my "framework" to handle everything
> 
> If there's anything I can configure to help, that'd be great.
> 
> Thanks

Thanks for reaching out @clgeoio, so we can help you better, Please create a new issue with:
- Minimal viable repro
- Wrangler Configuration (wrangler.toml)
- Any script information you can provide
- You can also run the command with WRANGLER_LOG=debug npx wrangler publish which should provide A LOT of logging around the command behavior.

**Comment by ssured** [comment]
I hit this issue as well, see #2517 for my logs
