### ISSUE TITLE
🚀 Feature Request: Support imports in _worker.js

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#2153]
### Describe the solution

Support imports in _worker.js

**Comment by dargmuesli** [comment]
Just fyi: this TODO comment still links to this closed issue: https://github.com/cloudflare/workers-sdk/blob/7161785cd69b075d9279b382de30886874e46e81/packages/wrangler/src/deployment-bundle/bundle.ts#L145C26-L145C79
