### ISSUE TITLE
🐛 BUG: `wrangler pages dev [path]` should serve the static content first if there is no `_routes.json`

### ISSUE THREAD

**Issue by zhuhaow** [cloudflare/wrangler2#2160]
### What version of `Wrangler` are you using?

2.2.1

### What operating system are you using?

Mac

### Describe the Bug

According to the doc https://developers.cloudflare.com/pages/platform/functions/function-invocation-routes/

> You can exclude routes such as a static assets directory by creating _routes.json file. This file will be **automatically generated** if a functions directory is detected in your project when you publish your project with Pages CI or Wrangler.

So if no `_routes.json` is provided, it would be better for `wrangler pages dev [path]` to try to serve the static files from `[path]` first before invoking functions. Then the behavior would be consistent when we publish the website.

**Comment by jahands** [comment]
Can you describe the behavior you're seeing that's inconsistent, as well as steps to reproduce?

**Comment by zhuhaow** [comment]
I tried again and everything works just fine.

Not sure what I was doing wrong, probably got some configuration wrong so static files was not served.

Thanks for the help.
