### ISSUE TITLE
Headless Login for Wrangler

### ISSUE THREAD

**Issue by Kronifer** [cloudflare/wrangler2#2174]
### Describe the solution

An option to login to wrangler without a browser for development on remote/headless servers.

**Comment by caass** [comment]
Does the existing solution of authenticating via environment variables not work for your use-case?

**Comment by JacobMGEvans** [comment]
You can find the documentation for Evironment Variables using API Tokens here: https://developers.cloudflare.com/workers/wrangler/cli-wrangler/authentication/#using-environment-variables

**Comment by Kronifer** [comment]
Oh that's perfect, thanks!

**Comment by Kronifer** [comment]
Oh that's perfect, thanks!

**Comment by crstauf** [comment]
> You can find the documentation for Environment Variables using API Tokens here: https://developers.cloudflare.com/workers/wrangler/cli-wrangler/authentication/#using-environment-variables

Broken.

**Comment by WitnessMee** [comment]
This is the working link to the environment variables documentation:
https://developers.cloudflare.com/workers/wrangler/system-environment-variables/
