### ISSUE TITLE
🐛 BUG: "d1 execute" stop executing SQL after query with character ']' in value

### ISSUE THREAD

**Issue by K2Da** [cloudflare/wrangler2#2179]
### What version of `Wrangler` are you using?

2.2.2

### What operating system are you using?

Linux

### Describe the Bug

"wrangler d1 execute" stop executing sql file after line including ']'.

> wrangler d1 execute green --file test.sql
```test.sql
CREATE TABLE IF NOT EXISTS test(str);
DELETE FROM test;
INSERT INTO test VALUES('initial');
UPDATE test SET str = 'update]';
UPDATE test SET str = 'second update';
```

The value in table 'test' is 'update]'.

When I remove ']' from 'updated]', the value is 'second update'.

I confirmed this happen with UPDATE or INSERT statements.

**Comment by xtuc** [comment]
@K2Da  coudl you please try again and confirm the issue is closed?

**Comment by K2Da** [comment]
I tested with v2.6.2 and confirm fixed! Thank you!
