### ISSUE TITLE
🐛 BUG: `generate` tests are fragile

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#2184]
### What version of `Wrangler` are you using?

latest

### What operating system are you using?

All

### Describe the Bug

During Developer Week, some tests started failing in `packages/wrangler/src/__tests__/generate.test.ts` - likely because the underlying repo changed without the tests being updated.

https://github.com/cloudflare/wrangler2/pull/2183 was merged to keep CI running.

Ideally, these tests wouldn't be fetching over the network, or changing the underlying repo shouldn't cause these tests to fail

**Comment by penalosa** [comment]
Closing in favour of #1980
