### ISSUE TITLE
Pages functions hot reload

### ISSUE THREAD

**Issue by leomp12** [cloudflare/wrangler2#219]
Hey,

Is there a way to configure browser hot reload with `wrangler pages dev` when functions (eg.: `/functions/index.ts`) are edited?

I've tried with `--live-reload` arg and _wrangler.toml_:

```toml
[miniflare]
live_reload = true
```

Both no success 😐 

Testing with Node 16 on Windows.

> I'm using miniflare and vite with `wrangler pages dev -- npx vite`, vite HMR works out of the box (👍🏾 ), problem is just with SSR hot reloads.

**Comment by GregBrimble** [comment]
Hi,

Unfortunately, live reload is not currently hooked up, but that's a great feature request, thanks for the suggestion!
