### ISSUE TITLE
🐛 BUG: D1 Inserting ] and ; fails with unrecognized token error

### ISSUE THREAD

**Issue by KennethWussmann** [cloudflare/wrangler2#2227]
### What version of `Wrangler` are you using?

2.4.0

### What operating system are you using?

Mac

### Describe the Bug

The characters `]` and `;` in a SQL insert statement break the SQL parser on D1.

1. Create SQL file:
```SQL
CREATE TABLE IF NOT EXISTS "Test" (
    "text" TEXT NOT NULL
);
INSERT INTO Test (text) VALUES ('];');
```
2. Execute wrangler:
`wrangler d1 execute test-db --file schema.sql`
3. Receive error
```
  ERROR 9009: SQL prepare error: unrecognized token: "'];" in INSERT INTO Test (text) VALUES (']; at
  offset 32 [code: 7500]
```

They don't even need to appear in the same string. Also failing:
```SQL
INSERT INTO Test (text) VALUES (']'), ('Hello'), (';');
```
```SQL
INSERT INTO Test (text) VALUES (']');
INSERT INTO Test (text) VALUES (';');
```

But the order matters. These ones don't fail:
```SQL
INSERT INTO Test (text) VALUES (';]');
```
```SQL
INSERT INTO Test (text) VALUES (';');
INSERT INTO Test (text) VALUES (']');
```

Running it locally using `wrangler d1 execute test-db --local --file schema.sql` does not cause any problems and works as expected. So not a general SQLite issue.

Thank you!

**Comment by Roy-Nelson-Tous** [comment]
i am Having the same issue. any news on how to fix the issue?

**Comment by rozenmd** [comment]
@KennethWussmann / @Roy-Nelson-Tous could you please try again and confirm if the issue is fixed?

**Comment by KennethWussmann** [comment]
I tested on v2.6.2 and can confirm the issue is fixed! Thank you 🙏🏻
