### ISSUE TITLE
🚀 Feature Request: `init --from-dash` should validate the script name before asking questions

### ISSUE THREAD

**Issue by jahands** [cloudflare/wrangler2#2241]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

WSL (Ubuntu 22.04.1 LTS)

### Describe the Bug

Running the following:
```
npx wrangler@latest init --from-dash i-dont-exist
```
will prompt the user to use git/typescript/etc before checking if the Service exists. It'd be nice if `wrangler init` would check for the script first so that you don't have to answer all the questions a second time when you misspell your service name.
![image](https://user-images.githubusercontent.com/10719325/202912127-1ebb3777-2c46-4367-8d43-183e2a2f83ae.png)

**Comment by penalosa** [comment]
Hi—thanks for reporting this! I've added it to our backlog to be implemented.
