### ISSUE TITLE
🐛 BUG: preview_database_id ignored

### ISSUE THREAD

**Issue by jiripospisil** [cloudflare/wrangler2#2263]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Linux

### Describe the Bug

Hello! The following D1 configuration throws an error in the dev mode:

```
d1_databases = [
 { binding = "db", database_name = "...", database_id = "78..." }
]
```

```
D1 bindings require dev --local or preview_database_id for now
```

Fair enough. Adding `preview_database_id` makes the error go away but it doesn't actually use the specified ID.

```
d1_databases = [
 { binding = "db", database_name = "name", database_id = "78...", preview_database_id = "42..." }
]
```

```
Your worker has access to the following bindings:
- D1 Databases:
  - db: name (78...) <---- should be 42...
```

**Comment by rozenmd** [comment]
Just to help me track down this bug @jiripospisil - when you run `wrangler dev`, does the Worker actually hit your preview db though?

**Comment by jiripospisil** [comment]
@rozenmd I don't think it did.

**Comment by Skye-31** [comment]
+1 to this - looks like it actually relies on `database_name` instead of caring about the ID
