### ISSUE TITLE
🐛 BUG: local testing of queues in wrangler dev doesn't work when running with the --test-scheduled flag

### ISSUE THREAD

**Issue by a-robinson** [cloudflare/wrangler2#2273]
### What version of `Wrangler` are you using?

2.4.4 (also tested on 2.3.2)

### What operating system are you using?

Mac

### Describe the Bug

Normally if you have a queue configured in your worker, you can run `wrangler dev` in local mode, send messages to the queue via a queue binding, and receive those messages in the worker's `queue()` handler.

The problem is that this doesn't seem to work when running `wrangler dev` with the `--test-scheduled` flag that's used to enable testing `scheduled()` handlers (as [documented here](https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/)). This is true regardless of whether you're even invoking the `scheduled` handler -- you can have a worker that just defines `fetch` and `queue` handlers and the presence of the `--test-scheduled` flag will prevent messages sent from within the `fetch` handler from properly invoking the `queue` handler.

Example worker code:

```
export default {
    async fetch(request: Requst, env: Env, ctx: ExecutionContext) {
        for (const i of [...Array(10).keys()]) {
            await env.emails.send({foo: 'bar'})
        }
        console.log('sent messages to queue')
        return new Response("OK");
    },
    async queue(batch: any, env: Env, ctx: ExecutionContext): Promise<void> {
      console.log(`received batch of ${batch.messages.length} messages to queue ${batch.queue}`);
    }
}
```

Along with a wrangler.toml like:
```
name = "email-scheduler"
main = "src/index.ts"
compatibility_date = "2022-09-13"

[[queues.producers]]
queue = "emails"
binding = "emails"

[[queues.consumers]]
queue = "emails"
```

When run without the `--test-scheduled` flag, you'll get output like this when you hit the fetch endpoint:

```
sent messages to queue
GET / 200 OK (8.22ms)
received batch of 10 messages to queue emails
[mf:inf] emails (10 Messages) OK
```

When run with the `--test-scheduled flag`, you notably don't get the console output, as shown below. And if you add other code into the `queue()` handler such as `throw new Error ('foo')`, you similarly won't see any of its effects in the output of `wrangler dev`.

```
sent messages to queue
GET / 200 OK (5.46ms)
[mf:inf] emails (10 Messages) OK
```

cc @jbw1991

**Comment by penalosa** [comment]
This is a symptom of a wider issue around how we handle facades and middleware, I think. The specific issue might have a simpler fix—I'll have a look (it probably doesn't work with `email` as well)
