### ISSUE TITLE
🐛 BUG:local testing of r2 in wrangler doesn't work

### ISSUE THREAD

**Issue by bkyerv** [cloudflare/wrangler2#2276]
### What version of `Wrangler` are you using?

2.0.22

### What operating system are you using?

Mac

### Describe the Bug

running `wrangler pages dev . --persist --r2='BUCKET_NAME'` results in an error `Unknown arguments: persist, r2`

**Comment by KianNH** [comment]
> 2.0.22

This is several months old - update Wrangler and you will have the options you're missing.

**Comment by penalosa** [comment]
More recent version of Wrangler should definitely fix this (we're on `2.4.2` right now, I think)
