### ISSUE TITLE
Detect entrypoint when one is not provided

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#229]
When running `wrangler dev`, if no entrypoint is provided, wrangler should check for one in the following places. 
1. `main`/`module` in `package.json`.
2. `build.upload.main` in `wrangler.toml`.

**Comment by threepointone** [comment]
Alternate proposal - we should only have explicit CLI args for entry. Copied from https://github.com/cloudflare/wrangler2/pull/258#issuecomment-1016289886: 

I'm deeply concerned with the ambiguity we've introduced. `wrangler dev` can now point to either something hidden inside a `wrangler.toml` file somewhere, or an `index.js` file locally, or (not implemented yet) the `main` field in a parent `package.json`, or (not implemeted yet) the `entry` field in `wrangler.toml`, and there's no way to tell without running the command. We should resolve this before we ship to GA. 

imo, we should deprecate `build.upload.main`, not implement the proposed `entry` field, and not read from `package.json`. We should only have explicit path in CLI.

**Comment by threepointone** [comment]
This probably deserves a deeper discussion, let's take it up during the meeting.

**Comment by threepointone** [comment]
ping

**Comment by Electroid** [comment]
Deciding against this, for the reasons you outlined.
