### ISSUE TITLE
🐛 BUG: path is required during backup download

### ISSUE THREAD

**Issue by kevinsimper** [cloudflare/wrangler2#2292]
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

Mac

### Describe the Bug

When trying to download a backup I get this error
```
The "path" argument must be of type string. Received undefined
```

But only database and id is required
```
wrangler d1 backup download <name> <backup-id>
```

**Comment by rozenmd** [comment]
Sorry you've run into this @kevinsimper - I'll look into it

**Comment by arne** [comment]
I also encounter this issue, if I add `--output test.sqlite` I get a 500 internal server error.

**Comment by rozenmd** [comment]
Just a heads up @arne - the 500 internal server error was an issue with the API that should be resolved now.
