### ISSUE TITLE
🐛 BUG: consumers don't respect the "max_batch_size" locally

### ISSUE THREAD

**Issue by altryne** [cloudflare/wrangler2#2295]
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

Mac

### Describe the Bug

Given the below (partial) toml:
```
[[queues.producers]]
  queue = "process-videos"
  binding = "PROCESS_VIDEOS"

[[queues.consumers]]
  queue = "process-videos"
  max_batch_size = 10
  max_batch_timeout = 5
```

Expected: sending 150+ messages to the queue, would process them by batches of 10. 

What actually happens locally is something else: 
My consumer gets a batch of 150 messages and tries to process all of them, and then when even 1 fails, it retries all of them, causing even more failures (I get the `FetchError: Too many subrequests. Workers can make up to 50 subrequests per request.\nA subrequest is a call to fetch(), a redirect, or a call to any Cache API method` error) 

Publishing the worker seems to work fine, consumers report batches of 10

**Comment by rozenmd** [comment]
Hey @altryne, sorry you've run into this, I'll get this looked at
CC: @jbw1991 @jbwcloudflare @a-robinson

**Comment by a-robinson** [comment]
Thanks for the bug report! It's fairly likely that we won't be able to take a stab at fixing this until next week, but we will get to it soon.

**Comment by a-robinson** [comment]
I take that back -- I have a fix up at https://github.com/cloudflare/miniflare/pull/450
