### ISSUE TITLE
Verbose logging for API requests

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#230]
There should be a verbose logging mode that ouputs the status, headers, and body of each request and response from the Cloudflare API. This makes it helpful to debug issues or errors.

**Comment by JacobMGEvans** [comment]
Can this be closed after the `useInspector` refactor?

**Comment by threepointone** [comment]
Error logging is much more verbose and helpful now, so I'm closing this. Happy to revisit if there are specific suggestions.
