### ISSUE TITLE
🐛 BUG: Running wrangler dev on Stackblitz fails with the most recent version of Wrangler >2.0.23 

### ISSUE THREAD

**Issue by lauragift21** [cloudflare/wrangler2#2314]
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Mac

### Describe the Bug

Wrangler dev fails with version 2.0.24 and greater when used with some templates in Stackblitz e.g [Stream + Stripe Example ](https://workers.new/stream/auth/stripe)

We had to roll back to 2.0.23 to get it to work. There's a compatibility issue causing this breaking change in 2.0.24 and greater. 

https://github.com/cloudflare/wrangler2/releases/tag/wrangler%402.0.24

**Comment by penalosa** [comment]
How does it fail? Do you have a stack trace or anything like that, by any chance? It's worth noting that Stackblitz isn't really supported—it only works with `--local` mode.

**Comment by lauragift21** [comment]
![Screenshot 2022-11-30 at 15 19 52](https://user-images.githubusercontent.com/17781315/204819952-46c6b2f4-8985-499f-bd57-3f68e37e9964.png)

This is what is the error returned.

**Comment by osaton** [comment]
The opening of the browser does not happen automatically (anymore?). If you press `b` with focus in the terminal it should work.

**Comment by rozenmd** [comment]
As of Wrangler 2.0.24 the fix is to add `--port 6283` or lower in the `dev` script in package.json, as Stackblitz appears to try open the lowest available port in the browser.
