### ISSUE TITLE
🐛 BUG: Vm2 async_hooks failed to build

### ISSUE THREAD

**Issue by gautammd** [cloudflare/wrangler2#2332]
### What version of `Wrangler` are you using?

2.1.15

### What operating system are you using?

Mac

### Describe the Bug

Unable to successfully build when using VM2 package - https://www.npmjs.com/package/vm2

I tried adding a custom webpack config with target set to "node" instead of "webworker" , that didn't work either. any help would be much appreciated.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/16880288/205492036-b307cf14-39dc-4c52-ae56-d270f5b17c0f.png">

**Comment by KianNH** [comment]
That package is never going to work on Workers - 'It uses the internal VM module to create a secure context.'

The `VM` module is a Node built-in and, even if it wasn't, isn't going to run on a platform like Workers that disallows code-generation through things like `eval` or `new Function`.

**Comment by gautammd** [comment]
Thanks @KianNH , I had to indeed try out this package as my code had `new Function` logic, may I ask why can't this library work? I understand that workers disallow `eval` and `new Function` due to security reasons but, this library executes the code in a sandbox environment. isn't that safe enough to allow the execution?

**Comment by KianNH** [comment]
This library is made for Node - and relies on Node's `vm` module. Workers are not Node, and therefore the library will not work on Workers.

The `vm` module is in the realm of modules that you can't really polyfill in Workers, so there is no workaround for this module.
