### ISSUE TITLE
🐛 BUG: Running migrations on local D1 performs backup on production database

### ISSUE THREAD

**Issue by drewschrauf** [cloudflare/wrangler2#2336]
### What version of `Wrangler` are you using?

2.5.0

### What operating system are you using?

Linux

### Describe the Bug

When applying migrations to a D1 database a backup is performed. When migrating a local D1 database with `wrangler d1 migrations apply my-cool-database --local` the backup is not performed on the local database, but on the production database. This requires all developers in a team to be authed against the production account, even if they're otherwise developing against local resources.

**Comment by rozenmd** [comment]
Hey @drewschrauf sorry about that, this is definitely unintentional - will fix shortly

**Comment by drewschrauf** [comment]
So quick! Thanks!
