### ISSUE TITLE
Add esbuild plugins

### ISSUE THREAD

**Issue by huv1k** [cloudflare/wrangler2#234]
Possibility to enhance build step with `esbuild` plugins, for example, https://www.npmjs.com/package/esbuild-plugin-lodash.

This would enable to improve build outputs.

**Comment by threepointone** [comment]
We're thinking about plugin systems, we'll probably do it in v2.1. It may or may not be esbuild plugins.

**Comment by petebacondarwin** [comment]
I think we should keep esbuild as an internal implementation. Enabling esbuild specific plugins would make it harder to switch to an alterntaive build step.

**Comment by threepointone** [comment]
I don't think we'll do this anytime soon. A workaround is to use a custom build using esbuild oneself, and then feed that to wrangler. Closing this.

**Comment by naturecodevoid** [comment]
For any future googlers: I have a fork that you can add using [this git branch](https://github.com/naturecodevoid/wrangler2-esbuild-plugins/tree/wrangler-build) that adds support for esbuild plugins as a wrangler.toml option. You can use it like this:
```toml
# wrangler.toml
esbuild_plugins = ["./esbuild-plugins.js", "esbuild-plugin-glob-import"] # supports local files and installed packages
```
If you need to specify configuration options (or if the plugin export isn’t detected correctly), you can create an `esbuild-plugins.js`:
```js
import globImport from "esbuild-plugin-glob-import";

export default function () {
    return [
        globImport({
            camelCase: false,
            entryPoint: null,
            entryPointMatch: null,
        }),
    ];
}
```
(This is for an ESM project, you might have to change it for commonjs)

I made [a PR](https://github.com/cloudflare/workers-sdk/pull/2500) for it, but I haven’t gotten a response after initial message. I’ve been using the fork for a while with multiple projects using `esbuild-plugin-glob-import`, and I haven’t had any issues.
