### ISSUE TITLE
🐛 BUG: Creating and Downloading D1 Backups Not Possible

### ISSUE THREAD

**Issue by 4dams** [cloudflare/wrangler2#2352]
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

macOS Ventura 13.0.1

### Describe the Bug

It is currently not possible to create and download D1 backups through `wrangler`.

## Reproduce

1. Create a new backup:

```bash
wrangler d1 backup create awesome_database
```

```bash
┌─────────────────────────────┬──────────────────────────────────────┬────────────┬─────────┬───────┐
│ created_at                  │ id                                   │ num_tables │ size    │ state │
├─────────────────────────────┼──────────────────────────────────────┼────────────┼─────────┼───────┤
│ 2022-12-07T12:47:01.802737Z │ f522a065-a429-4b45-bfb5-679eb0476969 │ 18         │ 1.38 MB │ done  │
└─────────────────────────────┴──────────────────────────────────────┴────────────┴─────────┴───────┘
```

2. Download the created backup:

```bash
wrangler d1 backup download awesome_database f522a065-a429-4b45-bfb5-679eb0476969 --output awesome_backup.sqlite
```

```bash
🌀 Downloading backup f522a065-a429-4b45-bfb5-679eb0476969 from 'awesome_database'

✘ [ERROR] Failed to download backup f522a065-a429-4b45-bfb5-679eb0476969 from 'awesome_database' - got 500 from the API
```

(Both the name of the database and the id of the backup have been replaced.)

##

Furthermore, running `wrangler d1 backup download <name> <backup-id>` fails with the following message:

```bash
✘ [ERROR] The "path" argument must be of type string. Received undefined
```

Only when adding `--output` the command runs. This is misleading, as under the `--help` page it states that this option is optional:

<img width="910" alt="CleanShot 2022-12-07 at 13 55 45@2x" src="https://user-images.githubusercontent.com/28960614/206184935-c25146f3-e737-465f-b69a-ec553fc01738.png">

**Comment by rozenmd** [comment]
The creating and downloading backups issue has been resolved - there was an issue with the API

We still need to improve the `--help` in wrangler as per the second part of the issue.

**Comment by 4dams** [comment]
Appreciate the fast feedback and help!

**Comment by YankeeTube** [comment]
same issue

**Comment by rozenmd** [comment]
@YankeeTube can you describe the issue you're having?

**Comment by martindisch** [comment]
Not sure if that's what they meant, but I just noticed that the API is giving me a 500 again. Both in wrangler and the dashboard:
```json
{
  "result": null,
  "result_info": null,
  "success": false,
  "errors": [
    {
      "code": 7500,
      "message": "Internal error"
    }
  ],
  "messages": []
}
```

For my future reference, where is your preferred place to have us report issues that have less to do with the wrangler integration and more with the service (e.g. D1) itself? This repo, the Discord server or the Discourse instance?

**Comment by rozenmd** [comment]
Discord is preferred @martindisch!

Sorry about the API issue over Christmas/New Years - should be resolved now.

**Comment by rozenmd** [comment]
Closing this issue as resolved in https://github.com/cloudflare/wrangler2/pull/2548

**Comment by martindisch** [comment]
Thank you!
