### ISSUE TITLE
Multiple commands in build.command fail on Linux

### ISSUE THREAD

**Issue by tcmal** [cloudflare/wrangler2#236]
For example, with a rust project:

```toml
[build]
command = "cargo install -q worker-build && worker-build --release" # required
```

I get:

```
$ wrangler dev -l build/worker/shim.mjs
running: cargo install -q worker-build && worker-build --release
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ B to open a browser, D to open Devtools, S to turn on (experimental) sharing, L to turn off local mode, X to exit │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
error: Found argument '--release' which wasn't expected, or isn't valid in this context

USAGE:
...
```

Indicating cargo is being passed `worker-build --release` as an argument.

I think this is caused [here](https://github.com/cloudflare/wrangler2/blob/18f8f65424adb8505c7584ae01b1823bb648eb6e/packages/wrangler/src/dev.tsx#L372), and it should be something like `execva('sh', ['-c', commandPieces.join(" ")])`

This looks like it would also affect mac and windows, though I can't test either.

Using `v0.0.7` with node `v16.13.1`

**Comment by threepointone** [comment]
Great catch. Will fix.
