### ISSUE TITLE
UX: Account Selection is not clear as a new user

### ISSUE THREAD

**Issue by Warfields** [cloudflare/wrangler2#237]
# Improve UX for Multiple Accounts
As a first time user I did not realize that wrangler2 was waiting for input. Because of this I pressed enter to see if there was an issue and accidentally deployed to the wrong env

<img width="718" alt="Screen Shot 2022-01-13 at 11 50 47 AM" src="https://user-images.githubusercontent.com/32973228/149413170-6480626a-a4ce-47d8-ba31-f50d0263b46e.png">

This could be fixed by implementing a title header like `Select Account to deploy to`

### Example of what would be helpful
```
# test_wrangler2 % npx wrangler@beta dev index.js
# Select Account to deploy to:
❯ User Account
  User Admin Account
  User Playground account
```

**Comment by threepointone** [comment]
Fixed in https://github.com/cloudflare/wrangler2/pull/239
