### ISSUE TITLE
🐛 BUG: "Unable to preview, dev, or publish"

### ISSUE THREAD

**Issue by crotel** [cloudflare/wrangler2#2382]
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

Mac

### Describe the Bug

"Unable to preview, dev, or publish" till now in China internet. and while I got an VPN which Legal and compliant in China, they told me that, should add some while list, so, how do I know the while list hostname or ip that wrangler use?
Thank you very much!

<img width="1084" alt="Screen Shot 2022-12-10 at 22 10 56" src="https://user-images.githubusercontent.com/4725265/206859902-24c3eded-6384-486e-912e-d8df76f89aae.png">

**Comment by JacobMGEvans** [comment]
We appreciate the report, however, I don't feel this is something we can help or provide support on due to it being a network level issue, outside the control of Wrangler and Cloudflare.

**Comment by rozenmd** [comment]
@crotel - Sorry about that - normally when you get a `10000` error, `wrangler logout` followed by `wrangler login` tends to fix it
