### ISSUE TITLE
🐛 BUG: `wrangler init workername -y` adds "jest" to tsconfig.json, but nothing else

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#2436]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Mac

### Describe the Bug

Like the title says. I'd expect it to install `jest` to my `devDependencies`, and initialise a first test somewhere. Instead, I get this error in my tsconfig. 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/18808/208461836-75650329-ed52-4188-bbcf-cdd34b35bbbc.png">

**Comment by JacobMGEvans** [comment]
Thanks for the report 😃

**Comment by threepointone** [comment]
ps - imo this is a proper bug because the feature doesn't work (and breaks typechecking), not polish.
