### ISSUE TITLE
🐛 BUG: Worker not updating after publish

### ISSUE THREAD

**Issue by VR-Architect** [cloudflare/wrangler2#2442]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Windows

### Describe the Bug

I made a change to an API endpoint and published. The endpoint is a simple return c.json("TEST2"), it was "TEST1". When testing from Postman the returned value didn't change leading me to believe the worker is being cached? 

If I look at the Quick Edit tool, the new value appears fine. 

Is there an issue with workers not getting updated after a wrangler publish? I waited a few minutes and still the same. 

thanks

**Update**: I created a new API endpoint called "/test" and the new endpoint works in the Quick Link tool, but Postman shows 404 not found error.

**Comment by admah** [comment]
@VR-Architect can you please provide a way for us to reproduce this? For example. what does your Wrangler config look like? Can you share your Worker code? We are unable to verify with the info provided. Thanks!

**Comment by VR-Architect** [comment]
The issue was an outage at Cloudflare according to the status website. Closing this ticket.
