### ISSUE TITLE
🐛 BUG: Ensure existing tests fail if an expected prompt|select|confirm fn is never called

### ISSUE THREAD

**Issue by CarmenPopoviciu** [cloudflare/wrangler2#2447]
### What version of `Wrangler` are you using?

latest

### What operating system are you using?

MacOS Ventura

### Describe the Bug

`mockPrompt` | `mockSelect` | `mockConfirm` all return a function that, if executed, will ensure tests fail, if any of the passed expectations was never called. Therefore, the expected usage of these APIs is as follows:
```
mockPrompt(expectations)()
mockSelect(expectations)()
mockConfirm(expectations)()
```

Most of our tests don't call the returned function, possibly resulting in false positive tests. We should ensure that all tests call these APIs as expected

**Comment by petebacondarwin** [comment]
This is not the correct usage. The call of the returned function should be made "after" the tests have run.

E.g.

```ts
			it("should accept and store permission granting to send metrics if the user agrees", async () => {
				const checkConfirmations = mockConfirm({
					text: "Would you like to help improve Wrangler by sending usage metrics to Cloudflare?",
					result: true,
				});
				expect(
					await getMetricsConfig({
						sendMetrics: undefined,
						offline: false,
					})
				).toMatchObject({
					enabled: true,
				});
				checkConfirmations();
				expect((await readMetricsConfig()).permission).toMatchObject({
					enabled: true,
				});
			});
```

**Comment by penalosa** [comment]
Fixed in https://github.com/cloudflare/wrangler2/pull/2283. See https://github.com/cloudflare/wrangler2/pull/2283#issuecomment-1371195344
