### ISSUE TITLE
🐛 BUG: wrangler CLI ignores `NO_D1_WARNING=true` setting

### ISSUE THREAD

**Issue by DataDrivenMD** [cloudflare/wrangler2#2473]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

macOS 13.1 (22C65)

### Steps to reproduce: 
1. Set `NO_D1_WARNING=true` in `wrangler.toml`
2. In command line: `$ wrangler d1 list` or `$ wrangler whoami`

### Observed behavior
Every call to `wrangler` includes the following message:
```
▲ [WARNING] Processing wrangler.toml configuration:

    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
      Note: set NO_D1_WARNING=true to hide this message
```

### Expected behavior
Command-line output should not include warnings about D1 Bindings whenever the project has `NO_D1_WARNING=true` in its `wrangler.toml` file

**Comment by rozenmd** [comment]
Hey @DataDrivenMD - sorry about this, looks more like a bad warning message than a bug.

Wrangler looks for `NO_D1_WARNING=true` in your environment variables - not `wrangler.toml` settings.

I'll update the warning to make that clearer.
