### ISSUE TITLE
🐛 BUG: `wrangler init -y` expects JS for a Typescript test

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#2483]
### What version of `Wrangler` are you using?

beta

### What operating system are you using?

Mac

### Describe the Bug

`wrangler init -y` generates typescript tests, but the entry point its looking for is `src/index.js`
```
Error: The entry-point file at "src/index.js" was not found.
 ❯ getEntry node_modules/wrangler/wrangler-dist/cli.js:142306:11
 ❯ validateDevServerSettings node_modules/wrangler/wrangler-dist/cli.js:165437:17
 ❯ startApiDev node_modules/wrangler/wrangler-dist/cli.js:165318:7

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

**Comment by rozenmd** [comment]
CC: @JacobMGEvans - related to the init typescript/vitest changes

**Comment by JacobMGEvans** [comment]
Ooof, thanks for the report Max
