### ISSUE TITLE
`wrangler delete` (or `wrangler unpublish`?)

### ISSUE THREAD

**Issue by tomkingchen** [cloudflare/wrangler2#25]
To use Wrangler as part of CICD pipeline, we need the ability to remove Workers through code. Currently there is no way to deprovision a worker using `wrangler` command. This feature is requested for Wrangler1, and is still open https://github.com/cloudflare/wrangler/issues/210.

Can this also be included for Wrangler2?

**Comment by threepointone** [comment]
It can indeed. At the very least we'll implement `wrangler delete`. There's some nuance around it re: durable objects and other bindings, but we should be able to do something good. 

Maybe we should land the open PR in v1 as well. I'll bring it up with the team soon.

**Comment by cameron-robey** [comment]
Closing in favour of https://github.com/cloudflare/wrangler2/issues/1065
