### ISSUE TITLE
🐛 BUG: Most D1 Commands require auth even with `--local` flag

### ISSUE THREAD

**Issue by bradenhs** [cloudflare/wrangler2#2515]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler

### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

I've seen the same behavior on Windows, Mac and WSL2

### Describe the Bug

I can run the `wrangler d1 execute` command successfully locally without needing to sign in:

```
npx wrangler d1 execute D1 --file=./migrations/0000_init.sql --local
```

I cannot, however, run other d1 commands locally without signing in e.g.

```
npx wrangler d1 migrations create D1 "init" --local
```

Even with the `--local` flag a `requireAuth({})` function is called most place in the codebase like here: 

https://github.com/cloudflare/wrangler2/blob/e93063e9854059ab4cc9a71fd22362b4ca01d3e9/packages/wrangler/src/d1/migrations/create.tsx#L29

For `execute` it only does `await requireAuth({})` when executing without the `--local` flag as expected. I assume other local d1 commands should behave like `execute`? That would be preferable in my opinion.

**Comment by caass** [comment]
I don't see why this wouldn't be supported -- thanks for reporting!

**Comment by rozenmd** [comment]
Definitely not intentional, will fix
