### ISSUE TITLE
🐛 BUG: Error 10021: Script startup exceeded CPU time limit

### ISSUE THREAD

**Issue by ssured** [cloudflare/wrangler2#2517]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

Mac

### Describe the Bug

Publishing our script triggers a Script startup exceeded CPU time limit error 

```
Your worker has access to the following bindings:
- KV Namespaces:
  - cfkvCMS: ****
Total Upload: 3448.15 KiB / gzip: 766.17 KiB
▲ [WARNING] Here are the 2 largest dependencies included in your script:

  - worker/index.js - 3440.81 KiB
  - node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js - 4.84 KiB
  If these are unnecessary, consider removing them



✘ [ERROR] A request to the Cloudflare API (/accounts/****/workers/scripts/***) failed.

  Error: Script startup exceeded CPU time limit.
   [code: 10021]
```

The source consists of 3mb inlined JSON data and 400kb other script. The JSON data contains a snapshot of the most used data from our CMS system.

In November 2022 we did sometimes hit this error, now it seems much more often. Our script size did not substantially increase in size since November.

As a first measure I moved the preprocessing of the data (building a simple index) into the main "fetch" event listener. This helped in December, but now we are again hitting the limit. 

wrangler.toml
```toml
name = "vanilla"
workers_dev = true
account_id = "21ccff78****"
compatibility_date = "2022-08-29"
main = "./worker/index.js"
send_metrics = true
node_compat = true
usage_model = "unbound"

vars = { WORKER_ENV = "production"}
```

WRANGLER_LOG=debug npx wrangler publish
```
 ⛅️ wrangler 2.6.1 (update available 2.6.2)
-----------------------------------------------------
Retrieving cached values for userId from node_modules/.cache/wrangler
Metrics dispatcher: Posting data {"type":"event","name":"deploy worker script","properties":{"usesTypeScript":false}}
-- START CF API REQUEST: GET https://api.cloudflare.com/client/v4/accounts/21ccff78****/workers/services/vanilla
HEADERS: {
  "Authorization": "Bearer fwnawUWtbXZpgTJus40njYkssa_-nyNZQlAhcd3wIq8.09wPwLcj5w6fwJZV8uXeV9E8Zx-",
  "User-Agent": "wrangler/2.6.1"
}
INIT: {}
-- END CF API REQUEST
-- START CF API RESPONSE: OK 200
HEADERS: {}
RESPONSE: {
  "result": {
    "id": "vanilla",
    "default_environment": {
      "environment": "production",
      "created_on": "2022-08-29T15:05:30.778738Z",
      "modified_on": "2023-01-09T09:35:27.586277Z",
      "script": {
        "created_on": "2022-08-29T15:05:30.778738Z",
        "modified_on": "2023-01-09T09:35:27.586277Z",
        "id": "vanilla",
        "tag": "0b96778132bf498cb2a1fb45ff929df2",
        "tags": [],
        "deployment_id": "",
        "logpush": false,
        "etag": "13ab049dcdd0c401d12f503ef8159815a487661bcb037a333a4610baee2f85d5",
        "handlers": [
          "fetch"
        ],
        "last_deployed_from": "wrangler",
        "compatibility_date": "2022-08-29",
        "usage_model": "unbound"
      }
    },
    "created_on": "2022-08-29T15:05:30.778738Z",
    "modified_on": "2023-01-09T09:35:27.586277Z",
    "usage_model": "",
    "environments": [
      {
        "environment": "production",
        "created_on": "2022-08-29T15:05:30.778738Z",
        "modified_on": "2023-01-09T09:35:27.586277Z"
      }
    ]
  },
  "success": true,
  "errors": [],
  "messages": []
}

-- END CF API RESPONSE
▲ [WARNING] Enabling node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


Your worker has access to the following bindings:
- KV Namespaces:
  - cfkvCMS: ****
-- START CF API REQUEST: PUT https://api.cloudflare.com/client/v4/accounts/21ccff78****/workers/scripts/vanilla?include_subdomain_availability=true&excludeScript=true
HEADERS: {
  "metricsEnabled": "true",
  "Authorization": "Bearer fwnawUWtbXZpgTJus40njYkssa_-nyNZQlAhcd3wIq8.09wPwLcj5w6fwJZV8uXeV9E8Zx-",
  "User-Agent": "wrangler/2.6.1"
}
INIT: {
  "method": "PUT",
  "body": {},
  "headers": {
    "metricsEnabled": "true"
  }
}
-- END CF API REQUEST
Total Upload: 3448.15 KiB / gzip: 766.17 KiB
-- START CF API RESPONSE: Bad Request 400
HEADERS: {}
RESPONSE: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Error: Script startup exceeded CPU time limit.\n"
    }
  ],
  "messages": []
}

-- END CF API RESPONSE
▲ [WARNING] Here are the 2 largest dependencies included in your script:

  - worker/index.js - 3440.81 KiB
  - node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js - 4.84 KiB
  If these are unnecessary, consider removing them



✘ [ERROR] A request to the Cloudflare API (/accounts/21ccff78****/workers/scripts/vanilla) failed.

  Error: Script startup exceeded CPU time limit.
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

**Comment by ssured** [comment]
Currently we cannot deploy which is very limiting. Sometimes (10%) it does work. What are the limits? How can we loosen these limits?

**Comment by caass** [comment]
As @KianNH said, the limiting factor here is script startup time -- meaning how quickly the worker can go from starting the V8 isolate to handling the fetch request. The workers runtime tests your worker when attempting to publish to see how long it'll take to start up, and if it takes longer than 200ms, it'll reject the publish with the error you're seeing here. The reason you're _sometimes_ able to publish is because there's varying amounts of resource contention while the worker is processed, so sometimes you'll be able to just squeak under the 200ms limit.

The best way to solve this issue is to avoid doing heavy preprocessing work -- e.g. loading the 3mb of JSON -- before the `fetch` handler, and try loading it inside the `fetch` handler. Your response to the user will be just as fast, since the worker was doing that work anyway, the timing is just shifted from the startup period to the handler period.

I'm going to close this issue for now and create a new one -- wrangler should be able to explain this with a nice error message, instead of forwarding the (rather opaque) error directly from the server.

**Comment by ssured** [comment]
Hi Caass, I have some more questions.
You talk about doing preprocessing work, this is not something we do. I double checked and cannot find any code paths running outside of the main event handler. This brings me to the hypothesis that current assigned hardware is not fast enough to parse 1mb of gzipped code within the limited execution time of 200ms. 

Furthermore this limit is hard to get any grip onto.  Old codepoints which used to deploy without any problems now structurally hit the init limit. Even code which ran last week now hit the limit. This gives the impression that resource allocation policies changed. How can I measure 200ms if I do not know anything about the hardware performance I am running on?

To me a fair and usable limit would be to limit the initial runtime of the script, excluding parsing.

We have 3.5mb code, because we (at compile time) add our main indexes into the code for speed purposes. Lookup tables are so much faster than DB access. Encoding these indexes and adding those to the source at compile time is a core aspect of our architecture and one of the reasons we chose CF workers. Can we apply for more generous limits, or should we re-assess choosing Cloudflare as our deployment platform?

**Comment by ssured** [comment]
@caass I'm just tagging you in the hope you get an alert or something, as this issue is already closed. I don't want to spam GH issues with a new one, but to me this issue is not done yet. I hope you can answer my questions. Have a nice day!

**Comment by ssured** [comment]
This morning I tried 100 times to deploy but failed. I reduced code from 800kb to 300kb and the deploy worked. Now I test again 1 time with the full 800kb code and it deploys again. This limit is really hard to work with because it feels so non deterministic

**Comment by alexmarmon** [comment]
@ssured sorry to revive this old issue. Were you able to work around this limitation? Even with the new 1s limit it's a pain to work around.
