### ISSUE TITLE
🚀 Feature Request: Explain `Error 10021: Script startup exceeded CPU time limit`

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#2519]
### Describe the solution

Frequently we get issue reports of people hitting this error and not understanding what's happening (https://github.com/cloudflare/wrangler2/issues/2517, https://github.com/cloudflare/wrangler2/issues/2337, https://github.com/cloudflare/wrangler2/issues/2152, https://github.com/cloudflare/wrangler2/issues/1362, https://github.com/cloudflare/wrangler2/issues/771).

We should catch these errors and print a nicer error message. Typically, these errors occur because they're hitting the 200ms hard stop for script startup, but there may be other reasons -- whatever they are, anything is better than an opaque error that means folks will resort to submitting github issues for clarification.

**Comment by yangcheng** [comment]
is there a way for me to get the startup CPU time? I start to see the error more often 2 weeks ago and now I always encounter the error,  it's hard for me to pin-point the broken commit 

Thanks
