### ISSUE TITLE
Improve error message when DO billing is required

### ISSUE THREAD

**Issue by justinnoel** [cloudflare/wrangler2#253]
Wranger Version: 0.0.8

When attempting to do `wrangler publish`, I persistently get this error:

```sh
wrangler publish
running: npm run build

> secret-project-api@1.0.0 build
> node build.js

Failed to fetch /accounts/<MY_ACCOUNT_ID>/workers/scripts/secret-project-api?available_on_subdomain=true - 403: Forbidden
```

Eventually, I gave up and installed the current official version of wrangler and attempted to publish. I got this result:

```sh
wrangler publish
🌀  Running npm run build

> secret-project-api@1.0.0 build
> node build.js

✨  Build completed successfully!
Error: Something went wrong with the request to Cloudflare...
In order to use Durable Objects, you must agree to pricing at https://dash.cloudflare.com/0a71f266bbebd0efde04b0ee74bdb5d1/workers/overview?enable-durable-objects [API code: 10084]
```

The official version of wrangler clearly states what the problem was. I had not previously agreed to the Durable Objects billing.

The new version of wrangler needs to display more information about errors like this.

**Comment by threepointone** [comment]
Good catch. We'll fix this.

**Comment by justinnoel** [comment]
Here's another. If you want it in a different issue, I can create another.

`Failed to fetch /accounts/0a71f266bbebd0efde04b0ee74bdb5d1/workers/scripts/eldrow-api?available_on_subdomain=true - 403: Forbidden`

Here's the equivalent error from the production release of `@cloudflare/wrangler`:

```
Error: Something went wrong with the request to Cloudflare...
Uncaught TypeError: Main module name is not present in bundle.
  at line 0
 [API code: 10021]
```

**Comment by threepointone** [comment]
We now log the pricing message, as well as a better message when we're missing the main entrypoint. I think this can be closed.

**Comment by justinnoel** [comment]
Thanks!
