### ISSUE TITLE
🐛 BUG: When you are creating a table in the Cloudflare dashboard it will crash the website if you try to insert a column that starts with the number

### ISSUE THREAD

**Issue by zigazajc007** [cloudflare/wrangler2#2537]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.7.1

### What operating system are you using?

Linux

### Describe the Bug

When you are creating a table in the Cloudflare dashboard it will crash the website if you try to insert a column that starts with the number.

![image](https://user-images.githubusercontent.com/44822563/212076031-b6a5b566-2ac9-4a39-b498-92e41e66e6bc.png)

Steps to reproduce:
1. Create new table thru Cloudflare Dashboard
2. Use 3test as column name
3. Click on Create button

It should provide a warning to not start column names with numbers instead of a crash.

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings, 
I appreciate the report. This is the repo and issues for Wrangler, Cloudflare Worker CLI, however, I will make sure this gets to the correct people.
