### ISSUE TITLE
🐛 BUG: Removing queue related config from wrangler causes error during publishing

### ISSUE THREAD

**Issue by sertand** [cloudflare/wrangler2#2543]
### Which Cloudflare product(s) does this pertain to?

Queues, Wrangler

### What version of `Wrangler` are you using?

2.7.0

### What operating system are you using?

Mac

### Describe the Bug

I had the following configuration in my wrangle.toml:
```
[[queues.producers]]
  queue = "test-queue"
  binding = "TEST_QUEUE"
[[queues.consumers]]
  queue = "test-queue"
  max_batch_size = 100
  max_batch_timeout = 30
```

And an empty queue handler in worker.js:
```
async queue(batch, env) {....}
```

I then removed the queue handler and the related configs from wrangler. When I try to publish I get:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/005....2b/workers/scripts/test-queues-worker) failed.

  workers.api.error.queue_handler_missing [code: 11001]
```
Adding the queue handler to worker js resolves the issue (without the queue config in wrangler.toml)

**Comment by lrapoport-cf** [comment]
@rts-rob can someone on your team take a look at this?

**Comment by a-robinson** [comment]
Hi @sertand and @hanzlahabib, sorry about the problem. The underlying mismatch here seems to be that you're (quite reasonably) expecting the removal of the `[[queues.consumers]]` section to cause the script to be unregistered as the queue's consumer, but in practice that is not what happens today. Removing the consumer config does not actually change the fact that the script is still registered as the queue's consumer.

If you want to actually unregister the script from the the queue, you can use the `wrangler queues consumer remove` command:

```
wrangler queues consumer remove <queue-name> <script-name>
```

This behavior in wrangler could potentially be changed, of course, but that's how to handle this situation for now.

**Comment by sertand** [comment]
Thank you @hanzlahabib and @a-robinson. @a-robinson you are correct, that was my assumption since the worker was registered as the consumer via `[[queues.consumers]]` section :) 
Thank you for the wrangler command.

**Comment by a-robinson** [comment]
Normally I'd say we should leave this open since it is confusing, but we are at least tracking the work to make this less confusing in our internal issue-tracking system. If anyone else hits this, feel free to chime in :)

**Comment by SamyPesse** [comment]
This is very confusing that removing the `queues.consumers` doesn't actually remove the worker from being a consumer. It's a blocker when deploying multiple times the worker in a team (to different worker name) as it means each dev of the team needs to do a annual action.
