### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by konyilwin** [cloudflare/wrangler2#2549]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.7.1

### What operating system are you using?

Mac Apple chip M2

### Describe the Bug

When I run npx wrangler dev. 
I got the ✘ [ERROR] The entry-point file at "src/index.ts" was not found.
Actually, the project is not typescript.

**Comment by rozenmd** [comment]
@konyilwin this is likely because you have `main = "src/index.ts"` in your wrangler.toml file - did you run `wrangler init` to generate your project?

**Comment by konyilwin** [comment]
I did run the wrangler init. And didn't choose typescript. I choose javascript. 
For quick fix, I changed main= "src/index.ts" to main = "src/index.js".

**Comment by rozenmd** [comment]
@konyilwin did you run `wrangler init` with the --from-dash flag, by any chance?
