### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Jack-R-Long** [cloudflare/wrangler2#2552]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.7.0

### What operating system are you using?

Mac

### Describe the Bug

`wrangler pages dev` is not working with my Vite React project.  It serves the front end correctly but the function does not work.

**Comment by JacobMGEvans** [comment]
Please provide more information on the issue, a minimal viable repro can really give us insights into issues to resolve them 😃

**Comment by JacobMGEvans** [comment]
Please provide a title to the issue as well.

**Comment by Jack-R-Long** [comment]
Figured out a fix.  I was trying to serve my `src` directory instead of my build `dist`🤦‍♂️

My mistake, closing the issue
