### ISSUE TITLE
🐛 BUG: Doing fetch requests in a Worker that is invoked from Service Bindings in Pages Functions throws an internal error

### ISSUE THREAD

**Issue by KianNH** [cloudflare/wrangler2#2589]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

MacOS

## Bound Worker

This Worker is called via Service Bindings.

Worker:

```ts
// src/index.ts
export default <ExportedHandler> {
  async fetch(req) {
    await fetch("https://google.com")
    return new Response("lol")
  },
};
```

## Errors on Functions

Functions:

```ts
// functions/test.ts
interface Environment {
	SERVICE: Fetcher
}

export const onRequest: PagesFunction<Environment> = (context) => {
	return context.env.SERVICE.fetch(context.request);
}
```

Tail logs from Worker:

```sh
GET https://89fdd660.test-functions-7jm.pages.dev/test - Exception Thrown @ 1/23/2023, 4:08:41 PM
✘ [ERROR]   Error: internal error
```

Example URL: https://89fdd660.test-functions-7jm.pages.dev/test

## Works on Workers

```ts
// src/index.ts
interface Environment {
  WORKER: Fetcher
}

export default <ExportedHandler<Environment>> {
  fetch(req, env) {
    return env.WORKER.fetch(req)
  },
};
```

Example URL: https://test-worker.kianorguk.workers.dev

## Additional info

Removing the `fetch` call from the bound Worker stops the error being thrown by Functions.

**Comment by WalshyDev** [comment]
Found the bug and got a fix PR up.

**Comment by WalshyDev** [comment]
This is now resolved, thanks for the report!
