### ISSUE TITLE
Cannot read properties of undefined (reading 'stop')

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#259]
Created an empty `index.ts` file and attempted to run `wrangler dev` resulted in this error:

<img width="451" alt="Screen Shot 2022-01-18 at 11 08 20 AM" src="https://user-images.githubusercontent.com/3238291/150002598-6d5dafa1-0cd0-4881-92bf-2cede90b0714.png">

**Comment by Warfields** [comment]
It appears that this is affecting more than just empty TS files

`export default { fetch() { return new Response('hello world') } }`

worked on beta as TS but not on alpha

**Comment by threepointone** [comment]
fixed in https://github.com/cloudflare/wrangler2/pull/262
