### ISSUE TITLE
🐛 BUG: Pages Functions Request duping might be broken

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#2594]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

-

### Describe the Bug

https://discord.com/channels/595317990191398933/1067095451502907412/1067135729181925486

Haven't verified myself yet, but apparently `const req = new Request(oldReq.url, oldReq)` was working in 2.7.1 and broke in 2.8.0. We should confirm and fix before updating the Wrangler version in prod.

**Comment by DianomiJH** [comment]
Hi, I was the one reporting it on discord, I briefly tried to reproduce the issue, but my first attempt didn't manage it and then my newborn started crying so haven't tried again yet, if I do manage it I'll post a repo here

**Comment by GregBrimble** [comment]
```
export const onRequestPost: PagesFunction = ({ request }) => {
  new Request(request.url, request)
  new Request(request)
  new Request(request, { ...request })
  return new Response("all fine")
}
```

I tried `POST`-ing to this and all seemed okay to me, so I'll close this issue. But if you do hit it again, please do re-open/make another with a set of reproduction steps!

Thanks for the report :)

**Comment by DianomiJH** [comment]
Looks like it was fixed here: https://github.com/cloudflare/wrangler2/pull/2597
