### ISSUE TITLE
remote worker: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#260]
This error occasionally happens, not sure why.

<img width="720" alt="Screen Shot 2022-01-18 at 11 21 59 AM" src="https://user-images.githubusercontent.com/3238291/150004397-8990aa80-268d-4f55-802a-f811e16759f5.png">

**Comment by petebacondarwin** [comment]
I wonder if it is related to this fix: https://github.com/cloudflare/wrangler2/pull/258/files#diff-d79823fe1e90cdc27158bbeaab5f58954e81375f84f4403ca124318c7bccd54fR156-R158

Note that here I had to resolve against the "destination" directory. The current working directory and the wrangler.toml directory did not work.

**Comment by threepointone** [comment]
Can reproduce this by using `npx wrangler publish` from inside `example-worker-app` in our codebase.

**Comment by threepointone** [comment]
I think this should now be fixed in `@alpha`, am closing. Please reopen if you see it again!

**Comment by Electroid** [comment]
Still an issue, happens sporadically with dev.
```
remote worker: [Error: ENOENT: no such file or directory, open '../../../../../var/folders/kv/f6jw8r5d26q9_r6vjvlz87q00000gn/T/tmp-58328-oNNeQQ2mz8WM/chat.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../../../../../var/folders/kv/f6jw8r5d26q9_r6vjvlz87q00000gn/T/tmp-58328-oNNeQQ2mz8WM/chat.js'
}
```

**Comment by threepointone** [comment]
Haven't seen this in a while, probably got fixed with our bundle refactor. Closing for now.
