### ISSUE TITLE
Source map should be inlined when using `wrangler dev`

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#261]
DevTools needs an inlined source map so it can show the original content of a file. Without this, here's what it looks like right now. Instead of `"index.js.map"`, it should be the value of the source map in base64.

<img width="533" alt="Screen Shot 2022-01-18 at 11 34 11 AM" src="https://user-images.githubusercontent.com/3238291/150006768-f6c6f424-500f-4c65-ab5e-18e37c486825.png">

**Comment by threepointone** [comment]
This doesn't fix the issue, needs something else. Closing this issue in favour of #3.
