### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by alihussain575** [cloudflare/wrangler2#2660]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

wrangler 2.8.1

### What operating system are you using?

linux

### Describe the Bug

The package "async_hooks" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

This is the error that i am getting and i have added the platform node but it doesn't works

**Comment by rozenmd** [comment]
@alihussain575 do you mind describing what you're trying to do, and what command you're running?

**Comment by alihussain575** [comment]
I am trying to create a service with that could run my next js application on the edge and run ssr with it.I did added the Next js Edge runtime functionality but apparently it does not gives back the response from the getServerSideprops . So i started creating one using cloudflare workers but get this error I have added the platform but still i get this issue

`platform = "node"
name = "my-worker"
workers_dev = true
type = "webpack"
node_compat = true
account_id = "9a203996171bcf2f8bf9647631470d56"

[site]
bucket = "../dist"
entry-point = "./index.ts"

dependencies = ["next", "async_hooks"]
`
This is my wrangler.toml file


when i run the command `wrangler dev`  or `wrangler publish` i get the error

**Comment by rozenmd** [comment]
You may want to look into https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/ 

CC: @cloudflare/pages

**Comment by GregBrimble** [comment]
Ah, sorry, the latest versions of Next.js are currently unsupported since they've introduced this dependency on `async_hooks`. I'm going through to identify when the change was made and I'll add the supported version range to the docs/README.

**Comment by alihussain575** [comment]
@rozenmd I have read the document but the issue comes the issue is that we don't get the response 
![image](https://user-images.githubusercontent.com/71531323/216084379-5ba34a25-3467-492e-b40b-aee012d5fe53.png)

@GregBrimble Thanks i will try to downgrade it and try

**Comment by GregBrimble** [comment]
Unfortunately, this is a limitation of the Next.js framework, and won't be something we can support until they do.

**Comment by alihussain575** [comment]
@GregBrimble I have downgraded it but still no luck
