### ISSUE TITLE
🐛 BUG: Pages build fails with error accessing file in the build output folder

### ISSUE THREAD

**Issue by likeadeckofcards** [cloudflare/wrangler2#2674]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

version available to Pages UI

### What operating system are you using?

version available to Pages UI

### Describe the Bug

Recently our website hosted on Cloudflare Pages started failing to build because of the following error:

```
Failed: build output directory contains links to files that can't be accessed
```

I originally believed that this was related to an update that I was working on but after pushing a reset version of the main branch I am running into the same error. This is leading me to think that this issue might not be an error with our configuration but rather something in the pipeline causing it.

**Comment by murattufekcioglu** [comment]
One of my Nuxt sites' deployment broke suddenly with this error. Build output directory was configured as "/dist", from the Pages' Nuxt build template. When changed to "./output/public" it begun working again.

**Comment by likeadeckofcards** [comment]
@murattufekcioglu That is what we found out as well. Not sure the exact reason it all of a sudden became an issue. For anyone else running into this issue, the company I work for wrote a quick [step by step blog post](https://gearboxgo.com/articles/web-application-development/nuxt-3-and-cloudflare-pages-failed-build-output-directory-contains-links-to-files-that-can-t-be-accessed/) for updating this and getting the deployments working again.

**Comment by boehs** [comment]
Why was this issue closed? It's still a bug, just one with a workaround. Experiencing with 11ty as well

**Comment by GalacticNetwork** [comment]
I am also getting this problem. Here's the logs:
``` Cloning repository...
-- | --
14:12:03.190 | From https://github.com/GalacticNetwork/jordansmathwork-v5
14:12:03.191 | * branch            2901ac8475468a0904b578afa135701f81e3bc27 -> FETCH_HEAD
14:12:03.191 |  
14:12:04.000 | HEAD is now at 2901ac8 trying to fix deployment
14:12:04.001 |  
14:12:04.084 |  
14:12:04.085 | Using v2 root directory strategy
14:12:04.111 | Success: Finished cloning repository files
14:12:04.738 | No build output detected to cache. Skipping.
14:12:04.739 | No dependencies detected to cache. Skipping.
14:12:04.809 | Detected the following tools from environment:
14:12:04.809 | Executing user command: exit 0
14:12:04.824 | Finished
14:12:04.825 | Note: No functions dir at /functions found. Skipping.
14:12:04.825 | Validating asset output directory
14:12:06.270 | Failed: build output directory contains links to files that can't be accessed```

**Comment by magick93** [comment]
I'm getting this with a Next.js project. 

When I build it locally the files are in the `.next` folder. I'm referencing the same folder int dashboard.  The build succeeds, but for the last step:

```
<pre class="c_mj c_bv c_la c_pz c_px c_py c_dd c_uw c_ux c_uy c_uz c_ju c_jv c_ui c_bx c_va">
07:35:44.368 | builder:build:   └ other shared chunks (total)                                 2.86 kB
-- | --
07:35:44.368 | builder:build:
07:35:44.369 | builder:build: ○  (Static)   prerendered as static content
07:35:44.369 | builder:build: λ  (Dynamic)  server-rendered on demand using Node.js
07:35:44.369 | builder:build:
07:35:44.849 |  
07:35:44.849 | Tasks:    6 successful, 6 total
07:35:44.849 | Cached:    0 cached, 6 total
07:35:44.849 | Time:    3m41.569s
07:35:44.849 |  
07:35:47.122 | Finished
07:35:47.123 | Note: No functions dir at /functions found. Skipping.
07:35:47.123 | Validating asset output directory
07:35:49.218 | Failed: build output directory contains links to files that can't be accessed

```

Does anyone know how to resolve this?

**Comment by garyoberbrunner-gpsw** [comment]
This error seems to be because it's not following a symlink, right? Seems like it ought to be a simple fix...
I just started getting these errors too, with my simple nuxt site.
