### ISSUE TITLE
Improvements to `--public`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#268]
In addition to Sites, wrangler v2 also introduces support for a public folder of static assets. This is similar to Sites, except you don't need to add any code in your worker to serve these files. This is less configurable than Sites, but should come with good defaults (similar to Pages). We'll also eventually add support for features like _headers and _redirects to this, much like Pages. One of the benefits of public is during wrangler dev, we don't need to upload the assets to the edge, making it a lot faster to start up and iterate.

Usage is fairly simple, it's wrangler dev <script> --public path/to/assets for developing, and wrangler publish <script> --name <name> --public path/to/assets when publishing. We'll add the field to wrangler.toml soon.

(Taken from #4)

**Comment by petebacondarwin** [comment]
--public, for consistency with pages, needs to be available on env as ASSETS, and has to be wired manually to the worker. (We should discuss this.)

**Comment by GregBrimble** [comment]
We should switch the execution order around so it matches Pages Functions (i.e. ASSETS last)

**Comment by threepointone** [comment]
Closing this, I'll make a fresh issue for wrangler static assets later.
