### ISSUE TITLE
services / "new" environments

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#27]
This tracks the implementation of [Services](https://blog.cloudflare.com/introducing-worker-services/) in wrangler v2. Of note, we may want to detail the transition story from existing "wrangler v1 style" environments.

**Comment by solaris7x** [comment]
Awesome upgrade to environments , hoping this would be available in wrangler soon .
As of now , Is dashboard the only way to interact with the "new" environments ?

**Comment by threepointone** [comment]
Currently, yes, the dashboard is the only way to interact with the new environments. That said, we're actively thinking about what it looks like in wrangler v2. Will share details when we have something concrete.

**Comment by Electroid** [comment]
This is now being targeted for `2.0` release, work can be followed in #382
