### ISSUE TITLE
Support for mounting/multiple workers

### ISSUE THREAD

**Issue by macaws** [cloudflare/wrangler2#273]
Unless I'm doing something wrong, Wrangler v1 doesn't seem to allow me to run more than one worker at a time, even with setting different ports. It's also not possible to assign local routes to simulate the routing pattern similar to how they will be configured in production.

Miniflare is adopting support for this: https://miniflare.dev/core/mount#mounting-workers

The way that it currently functions, I am able to set up routes on a multi-worker project identical to production but with a local domain and run all the workers at the same time. When you build an API using 6 different workers, this is almost vital to development. 

Is there any planned support for something similar in Wrangler2?

**Comment by threepointone** [comment]
Yes, we will be building support for multi-worker development into wrangler2, however it's planned for after the 2.0 release, very likely 2.1. This ties closely to supporting Services as we announced in November https://blog.cloudflare.com/introducing-worker-services/.

**Comment by rozenmd** [comment]
Hey @macaws, this was released in wrangler@2.0.25! 

(PR here if you're curious: https://github.com/cloudflare/wrangler2/pull/1503)
