### ISSUE TITLE
JavaScript API and configuration

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#285]
We've heard feedback that the wrangler.toml configuration is not the most intuitive format. TOML is uncommon among tools in the JavaScript ecosystem, unlike Rust, so much so that there's a challenge to find a well-maintained library to edit it. We still want to support the wrangler.toml, but we're also considering another configuration format for improvements we're planning in 2.x, such as:
* Support for multiple Workers in the same configuration.
* A plugin/extension system.
* A programmatic API.

A JavaScript (and TypeScript) configuration would accomplish these goals and is similar to tried-and-trusted tools like [esbuild](https://esbuild.github.io/api/#build-api), [jest](https://jestjs.io/docs/configuration), [webpack](https://webpack.js.org/concepts/configuration/#introductory-configuration), [rollup](https://rollupjs.org/guide/en/#configuration-files), also [Miniflare](https://miniflare.dev/get-started/api#usage), etc. (links go to configuration docs)
 
A new configuration would also make it easier to introduce breaking-changes from 1.x to 2.x. If a wrangler.toml is detected, defaults from 1.x are used; otherwise, the 2.x defaults are used. While these differences would need to be prominently documented, it allows new features such as Service environments and bindings to be introduced. 

Here's an example of what the API/configuration could look like. (this is just for demonstration)
```typescript
// worker.config.js

import { uploadWorker, previewWorker } from "wrangler";

await uploadWorker({
  name: "auth-service",
  environment: "production",
  entryPoint: "./worker.js"
});

import { readFile } from "node:fs" 

const server = await previewWorker({
  compatibilityDate: "2020-11-01",
  variables: {
    "MY_VAR": "..."
  },
  entryContent: readFile("./worker.js"),
});
server.listen(8787);
```

Small thoughts:
* Why `import` instead of `default export`? This makes it easier for IDEs to pickup the types of the config.
* An API allows developers to use wrangler to create other tools, like a unit-testing runner.
* What about CLI arguments? Yes, there would be a corresponding CLI arguments for each JavaScript API.

**Comment by petebacondarwin** [comment]
Thanks for kicking off this discussion @Electroid. IMO I think it would be wise to make a decision on this before Wrangler 2.0.0 general release. A few thoughts...

1. It feels like the suggested configuration is actually conflating two separate concepts: configuration and programmable API. While I think it is valuable to have both, I think they should be considered separately.
  I suspect that you are taking the lead from esbuild here, where there are only two options for "configuration":
  a. Use the esbuild command line binary - in this case the only way to configure the build is via command line options
  b. Write a script that uses the esbuld API to execute a build - in this case all the configuration is done within this script programmatically.
  This sort of approach does allow for highly customisable behaviour, but for anything non-trivial, it requires that developers do write such a script and run it directly. I think this goes against the approach we have taken with Wrangler which is more like an interactive development tool.
2. I think that creating an API is a very good idea, especially to support other usages from outside the Wrangler CLI, such as a VS Code plugin. But consider how one would configure a project to be able to accessed from the command line and VS Code? I think having an executable script in this case would be what we want?
3. While an imperative programmable script provides the most flexibility, it is also the most difficult to automate updates.
  We have already talked about automated migrations between versions, but also UI based tooling, such as a VS Code plugin, would want to be able to update the configuration - I envisage adding and removing environments/bindings for a Worker/Service.


So my preference would be to align more with the TypeScript tooling approach:
- provide a programmatic API that can be used to create complex use-cases such as plugins
- provide a declarative (expandable?) configuration syntax with APIs for modifying this - I would still suggest JSONC (or perhaps something YAML related) which is well understood by JS developers and has well supported tooling
- ensure that (almost?) all configuration options can be overridden at the command line

**Comment by lrapoport-cf** [comment]
this is being tracked in https://github.com/cloudflare/wrangler2/issues/1185, closing this out
