### ISSUE TITLE
Propagate `status` and `statusText` from `fetchInternal()`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#290]
See https://github.com/cloudflare/wrangler2/pull/287#issuecomment-1020477379

**Comment by djKooks** [comment]
@petebacondarwin seems it is already sending error with status/statusText
```
throw new Error(
      `Failed to fetch ${resource} - ${response.status}: ${response.statusText}\nInvalid JSON response:\n${jsonText}`
    );
```
is there something more for this issue?

**Comment by petebacondarwin** [comment]
The idea is that rather than throwing a generic error here, we return an object that contains the status information, so that the caller can then choose what to do (and perhaps throw an error if appropriate).

**Comment by threepointone** [comment]
Based on the last few months, looks like the `.code` has been useful and is usually a more refined form of `.status`. When we don't have a `.code`, we throw the error with the `.status` and `.statusText` in the message, which has been sufficient. I think we may not need to do anything else here, so do you suppose we should close this out, and open a fresh issue when we have a specific need?
