### ISSUE TITLE
support `--ip`, `--local-protocol`, `--upstream-protocol` for `dev`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#298]
- [x] `--host`
- [ ] #582
- [ ] #583
- [ ] #584

Related issue: https://github.com/cloudflare/wrangler2/issues/527

**Comment by threepointone** [comment]
Implemented `--host` support in https://github.com/cloudflare/wrangler2/pull/545

**Comment by petebacondarwin** [comment]
Implemented `--local-protocol` support in https://github.com/cloudflare/wrangler2/pull/580

**Comment by petebacondarwin** [comment]
I have split this issue out into separate ones for each feature.
