### ISSUE TITLE
devtools / debugging 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#3]
This tracks the implementation of debugging tools for `wrangler dev`. 

- [x] Hit the `D` hotkey when developing, to open a hosted devtools at `built-devtools.pages.dev` 
- [x] Open `chrome://inspect` on chrome, or `edge://inspect` on edge, and follow the instructions there to open the browser devtools inspector. 
- [ ] Connect vscode debugger to the inspector and debug inside your IDE directly. 

### Features  
- [x] See `console.log(...)`/`console.error(...)` objects in the Console tab
- [ ] Profile your workers following the steps in https://developers.cloudflare.com/workers/learning/profiling-workers
- [x] #1315 
- [ ] Support breakpoints
- [ ] Enable the Network tab, so you'll be able to see and inspect subrequests that your worker makes  
- [ ] Support debugging websockets requests

**Comment by TehShrike** [comment]
Why don't console.log/error/etc log out to the terminal where `wrangler dev` was run?

**Comment by threepointone** [comment]
Yeah, we could probably do that.

**Comment by pleszczy** [comment]
This is a very needed feature, and I'm looking forward to it.

**Comment by jspspike** [comment]
Closing this issue to be tracked in #573
