### ISSUE TITLE
cache some calls in `node_modules/.cache` (specifically - account selection, but maybe more)

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#300]

**Comment by threepointone** [comment]
Assigning to myself so I remember to bring this up in our team meeting

**Comment by petebacondarwin** [comment]
> Assigning to myself so I remember to bring this up in our team meeting

Added to the agenda.

**Comment by threepointone** [comment]
Unassigning now that we discussed it.
