### ISSUE TITLE
UX Bug in `wrangler dev`

### ISSUE THREAD

**Issue by Warfields** [cloudflare/wrangler2#308]
The prompt box for `wrangler dev`'s tools is a bit glitchy as seen below

<img width="1118" alt="Screen Shot 2022-01-25 at 10 06 29 PM" src="https://user-images.githubusercontent.com/32973228/151107172-a17b4524-9427-403f-a6fe-8c2526bddd05.png">

**How to reproduce**
1. `wrangle dev <wrong_path_to_src>`
2.  repeatedly press `L`

[![asciicast](https://asciinema.org/a/3ie4v4pJT8z4DOxJKX51CvCQj.svg)](https://asciinema.org/a/3ie4v4pJT8z4DOxJKX51CvCQj)

**Comment by Warfields** [comment]
This appears to only be an issue when you mistype the path, not sure if we even should care about this now
<img width="321" alt="Screen Shot 2022-01-25 at 10 11 06 PM" src="https://user-images.githubusercontent.com/32973228/151107476-ef39037e-3971-45b0-ae0d-dd7a70463a1e.png">

**Comment by threepointone** [comment]
If we have a wrong path to src, we should simply quit the process with an error message. (We should do the check _after_ `useCustomBuild` returns in `dev`, and after running `config.build.command` in `publish`, because that may be the logic that generates the file).

**Comment by threepointone** [comment]
Ok, I see we fail for publish, but in dev we just catch the error and leave the process running. We should end the process immediately.

**Comment by Warfields** [comment]
I looked into the code and found [this](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/dev.tsx#L506-L510), it appears that we caught the build errors for a reason. I think it's so that when `--watch` is used we don't immediately kill the process, we could add a conditional if watch is not present to kill on line 507.

**Comment by Warfields** [comment]
Further digging, by default the code uses `--watch` on all ESBuilds. So we might want to watch for the not resolving error specifically, but I am not sure if a file with an error in it would raise the same error.

**Comment by petebacondarwin** [comment]
Is an invalid entry-point unrecoverable? I.e. what if we renamed the entry-point (causing the build to break) and then renamed it back again? If so, then perhaps we should not exit but instead just make sure that the UI doesn't get corrupted.

**Comment by Warfields** [comment]
Yeah, that's what I'm thinking about too.

**Comment by threepointone** [comment]
It's very unlikely that an entry point would get renamed. We can work on that usecase, but seems like overkill to design around that. In this scenario, it doesn't exist on the first run itself, and we should probably exit immediately imo.

**Comment by threepointone** [comment]
Fixed by https://github.com/cloudflare/wrangler2/pull/455
