### ISSUE TITLE
npm wrangler vs @cloudflare/wrangler

### ISSUE THREAD

**Issue by chase** [cloudflare/wrangler2#31]
Not sure if this is something that can be easily resolved, but given the recent number of package hijackings that have led to compromised credentials amongst other things, I think it might be good to publish the main tag so that the README doesn't display a 9 year old dead project.

When I realized that [the v2 beta announcement article](https://blog.cloudflare.com/wrangler-v2-beta/) no longer used `@cloudflare/wrangler` for installation and I had already installed via the instructions, I got a little nervous that a typo may have meant that I compromised myself absentmindedly.

Realizing that the collaborators for both packages were the same was the only thing that makes it seem legitimate.

Looking at this, seeing `9 years ago` then `Last publish 13 hours ago` and an unrelated README gives the impression of typo-squatting:

![image](https://user-images.githubusercontent.com/5411/142345126-d9a45c93-9188-45cb-885d-41fbaf40a3ad.png)

**Comment by Electroid** [comment]
Thanks for pointing this out, we'll get this fixed asap.

**Comment by arctome** [comment]
Also in the recent official blog posts, like [Cloudflare Pages Goes Full Stack](https://blog.cloudflare.com/cloudflare-pages-goes-full-stack/) and etc. Please fix them or give a direct link to this repo, thanks !

**Comment by xtuc** [comment]
we took over an old package, since we didn't publish a stable version yet the README didn't update on npm

**Comment by threepointone** [comment]
This is what https://www.npmjs.com/package/wrangler shows now - 
![image](https://user-images.githubusercontent.com/18808/145720118-434b3d54-b64e-4c9d-9539-a3867640efbf.png)

This is what `npm install wrangler` shows now 
![image](https://user-images.githubusercontent.com/18808/145720200-68ade0cf-620b-4ebb-94ce-c1e39f0164e9.png)

This should be fine until we do a proper major release, at which point, we'll just take over the main page of the package, and merge this repo into `@cloudflare/wrangler`.

Marking this issue as closed, thanks for filing it!
