### ISSUE TITLE
Give an actionable error message when running `wrangler publish` without a workers.dev zone defined

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#318]
There are many accounts that don't have a `workers.dev` zone (and some that don't want to enable it as well). We need to make sure `dev`, `publish`, and the other commands that touch the deployment cycle still work without one.

**Comment by petebacondarwin** [comment]
The short term fix is to show an error if they have no workers.dev (subdomain) zone, and describe how they can go create it.
A longer term fix is to ask the user if they would like us to actually create the zone for them, captured in a new issue.

**Comment by threepointone** [comment]
There are two separate issues here 
- folks using wrangler dev but haven't registered a workers.dev subdomain yet. That's https://github.com/cloudflare/wrangler2/issues/535
- folks who will want to use wrangler dev even _without_ having registered a workers.dev subdomain, using their own host/domain. That's what this one is about.

**Comment by petebacondarwin** [comment]
This issue is now about a quick UX improvement to the situation. Currently the error messages are obscure, confusing and not-actionable.
The other issue #535 is to cover the case where a user would like to have a workers.dev subdomain but hasn't yet created one. In that case we should help make it for them automatically.
What I think you are referring to is a third issue, which is to allow `wrangler dev` to work without ever having to provide a route or a worker.dev subdomain.

**Comment by threepointone** [comment]
Pete and I discussed this, and I shared that we haven't yet implemented `wrangler dev` support for zoned workers, and it currently uses the same codepath as `workers.dev` workers (which errors as expected). We should still have better errors/messaging, but I also filed #544 to track actually implementing wrangler dev for zoned workers.

**Comment by threepointone** [comment]
Reopeneing this, we still need to verify whether wrangler2 works on zoned workers for folks who explicitly don't want to register a workers.dev subdomain

**Comment by petebacondarwin** [comment]
I believe that @caass has verified that we can publish to a zoned worker (as long as routes are configured) even if there is no workers.dev subdomain configured.

**Comment by threepointone** [comment]
Dope. Alright, closing this
