### ISSUE TITLE
Warn when wrangler dev is being used on a worker that binds to a durable object class implemented by a different script

### ISSUE THREAD

**Issue by a-robinson** [cloudflare/wrangler2#319]
When a script containing a DO implementation is previewed using wrangler dev, the DO instances accessed in the preview session will have read access to the storage used by real objects in the real version of the namespace, but writes will be kept in memory and won't affect prod data.

However, if a script binds to a DO namespace implemented by a different script (or even if it's in the same script being previewed but the `script_name` is specified in the DO binding), then any requests sent by the preview session to DOs in that namespace will hit the real objects and any writes will modify the real prod data in that namespace. This is how KV works in preview too, but it's more confusing for DOs because of the fact that we do a copy-on-write overlay in the common case where the DO implementation is in the same script.

We should log a warning when `wrangler dev` is used on a script that has a DO binding that will be affected by this, giving the user a chance to acknowledge that they're sure they're ok with their preview session potentially overwriting real live data stored in the DOs.

**Comment by Electroid** [comment]
Is there any technical reason we can't use the same dirty-write mechanic for DOs that are owned by another script? It makes sense for us in the meantime to surface a warning (maybe even a hard error?), but it would also be nice if we didn't need to do that in the first place.

**Comment by a-robinson** [comment]
It's technically plausible, but would be quite a lot of work in both the runtime and the config service to support running the transitive closure of all depended-upon scripts in the preview session for a given script.
