### ISSUE TITLE
[pages] path issue in pages-functions-compiler config on windows

### ISSUE THREAD

**Issue by Xniveres** [cloudflare/wrangler2#32]
under  windows wrangler2  fails due to an incorrect path given in the automatically generated routes.mjs config file from pages-functions-compiler.

to recreate this issue:

cli:

```npx wrangler pages dev -- npx yarn serve```

error:

```
No Instance(s) Available.
Automatically determined the proxy port to be 8080.
Compiling worker to "C:\\Users\\LTGT\\AppData\\Local\\Temp\\functionsWorker.js"
 > ../../AppData/Local/Temp/plinko-DEZGoi/routes.mjs:1:49: error: Could not resolve "C:UsersLTGTWebstormProjectsmgr.moe\functions\time.js" (mark it as external to exclude it from the bundle)
    1 │ import { onRequest as __time_js_onRequest } from "C:\Users\LTGT\WebstormProjects\mgr.moe\functions\time.js"
      ╵                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

the problem is that the path is provided using a single \, however, windows requires either two \ or a /.

to solve this issue i modified plinko.mjs:

in line 98
change:
```js
const resolvedPath = path.resolve(baseDir, filepath);
```
to:
```js
const resolvedPath = path.resolve(baseDir, filepath).replace(/\\/g, '/');
```

**Comment by threepointone** [comment]
cc @geelen for triage

**Comment by fikisipi** [comment]
@Xniveres Reported the same issue (although in the old repo!).

A suggestion regarding your fix: it still wouldn't handle other symbols, like quotes in the folder name. The proper fix is to use a function like `JSON.stringify(filepath)` or an AST->code emitter so that the generated path is always a valid JavaScript string per the spec.

**Comment by GregBrimble** [comment]
This should now be resolved in the latest alpha! Try it out with `npm install wrangler@alpha` :)
