### ISSUE TITLE
Disable persistence locally

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler2#320]
Writing an E2E suite which fires up `wrangler dev --local`, but I want to get a clean slate each time. Atm I can `rm -rf .mf` before each run, but I couldn't find a way to just disable persistence for the current run (in case I had dev data stored in .mf, say).

I tried adding the following to `wrangler.toml` as per https://miniflare.dev/storage/durable-objects#persistence:

```toml
[miniflare]
durable_objects_persist = false
cache_persist = false
```

But it didn't seem to take effect. Ideally, CLI args would be best, since I can invoke them from my test runner easily.

There's not a way to do this already is there? I suppose I'm going to have to send a PR aren't I? :)

**Comment by Electroid** [comment]
We should _always_ disable persistence? Each `wrangler dev` session is fresh on the edge, any downsides to making the same behaviour for local?

**Comment by geelen** [comment]
I can see that, for sure. I'd actually thought the best approach to dev persistence was defining like a `seed.json` file that declares a bunch of data to start a new dev session with. That could be made to work with both edge and local mode...

**Comment by threepointone** [comment]
I'm not certain an CLI flag is the way forward here, because except for tests, this won't be that useful. We do want to figure out how to use wrangler inside tests, and for that usecase this would be perfect.

**Comment by threepointone** [comment]
By the way, we don't disable persistence for `wrangler dev`, except for Durable Objects. KV writes don't use the copy-on-write thing right now. Not sure about `Cache`.

**Comment by threepointone** [comment]
(but I am warming up to the idea of disabling persistence by default...)
