### ISSUE TITLE
Adopt miniflare's `mounts` approach for multi-worker publish

### ISSUE THREAD

**Issue by jed** [cloudflare/wrangler2#323]
Miniflare [uses](https://miniflare.dev/core/mount) `[miniflare.mounts]` in `wrangler.toml` to implement an app from a group of workers. It works great for local development, and seems like a good fit to graduate out of the `miniflare` namespace into Wrangler itself, allowing users to `wrangler publish` the root  `wrangler.toml`, which would in turn publish the nested workers, a la AWS CloudFormation's [Nested Stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html).

**Comment by Electroid** [comment]
It's something we're thinking about! Tracking here: #273

**Comment by jed** [comment]
(Just to clarify, @Electroid, I'm not talking about local development, I'm talking about publishing multiple workers atomically.)
