### ISSUE TITLE
RFC: Serving static assets / The future of Sites

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#346]
Starting an issue to discuss how we should serve static assets, and potentially merge with Pages' implementation. Skip to the end to read suggested plan of action - 

- We currently support Workers Sites (with one breaking deprecation - we don't support the `entry-point` field under `[site]` in `wrangler.toml`). This is fine, but it's super fidgety to integrate (and got even more fidgety with es module workers), is hard to debug, uses up resources limits (specifically, kv resources) even during development, and has been a constant source of frustration with users. That said, it's extremely useful for migrating users over from wrangler 1 (and supporting for a while if they never want to move to whatever we replace it with).

- We announced Pages for static sites in 2020 (and went GA in 2021), and included worker support ("functions") in late 2021, making it a great solution for building apps. Serving static assets is configuration free, _except_ when using the `_worker.js` advanced mode which requires a minimum of one line of code to wire up `env.ASSETS.fetch()` (details - https://developers.cloudflare.com/pages/platform/functions#advanced-mode) The tradeoff are that Pages is by definition a little more prescriptive, and doesn't allow the full range of customisation that a full wrangler project can have. 
  - A nuanced tradeoff of Pages: while local development with `wrangler pages dev` is fully local, (powered by miniflare, and doesn't run on the 'real' edge), if and when we do run it on the edge, it'll share a tradeoff from Sites, which is that it'll use resource limits (since it's powered by KV). Of course, this is completely theoretical, since `wrangler pages dev` is only local right now, and it may change its internal implementation away from kv (to r2?) in the future. 

- wrangler2 has an experimental CLI flag called `--experimental-public <path>` that lets you directly serve a folder of static assets at `<path>` without any code. It's quite nice, tbh. During development, it doesn't consume kv resources _even when in edge mode_, which is quite convenient. Further, it opens up the opportunity to hosting static assets on a different domain in production (to take advantage of multiple domains for saturating network bandwidth much like fbcdn, gstatic) etc, and other possible optimisations. But it lacks some features; namely Pages features like `_redirects` and `_headers` directives, and advanced customisation. It's marked as  `experimental` because I didn't want to introduce a third way of doing the same thing. But, I think I've figured a solution, so here's my suggestions for a way forward. 

## Suggested plan of action

- We rename `--experimental-public` to `--assets`, as well as introducing an `assets` field to `wrangler.toml`. The implementation should probably be powered by Pages' `generateAssetsFetch()` function.
- Additionally, we introduce a flag called `--customise-assets` which is `false` by default. 
  - When `--customise-assets` is `false`, we serve assets much like Pages does in non-advanced mode, i.e., without any additional configuration. In both edge and local mode, this doesn't use kv resources. This is already how `--experimental-public` works today. This also allows optimisations like serving these assets from a completely different domains, etc. 
  - When `--customise-assets` is `true`, we serve assets like Pages does in advanced mode, requiring the developer to wire up `env.ASSETS.fetch()`. When running on the edge, this will use kv resources (much like Sites), but not when running in local mode (much like Pages). This has the tradeoff that static assets will be served from the same domain as the app, but that's the case for both Sites and Pages today. 
- We keep Sites around for a while, not add any new features, and add a terminal message to use `--assets` instead. We may need a flag/config to silence this message for people who never plan on moving away from Sites, but that's ok.

This brings Pages and Wrangler closer in terms of implementation and API, and lets us move forward on converging the two. Thoughts?

(Bonus: Later (and this probably deserves its own issue), we can introduce a `--functions` flag / `functions` config field to consume a folder of filesystem-routed code, bring Pages and Wrangler even closer. ) 

NB: There's a deeper discussion to be had regarding the dashboard's convergence of Pages and Wrangler, but that's separate from this for now.

**Comment by lakano** [comment]
Hi @threepointone

In the new ES Module Workers, it's now possible to join in our bundle others files ( .mjs ) files. 
Since V8/chrome 93, it's possible to also import .css text file like that « import styleSheet from "./styles.css" assert { type: "css" }; » ( https://chromestatus.com/feature/5948572598009856 )

May be later they will also add the possibility for .html files ( import styleSheet from "./template.html" assert { type: "html" }; ), this could be really useful for some kind of projects (eg: templating)

How do you proceed with theses imported files ? Ideally, for performances reasons, it's better to keep them in the same place as the Module Worker and it's others .mjs scripts.

**Comment by threepointone** [comment]
This got no feedback lol. Closing this, will make a fresh issue later with a more focused plan.

**Comment by Wallacy** [comment]
FWIW: The proposal is nice (--assets already exists btw); Today i still use Worker Sites (instead of Pages) because i want to make more customization like serving one diference home page for each different subdomain attached domain. 

Worker Sites feels more like a real "server" that i can do everything. But the KV thing... well... Is we can just use the same `env.ASSETS.fetch()` will be nice (backed by R2 even better);
