### ISSUE TITLE
Add logout command

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#351]
`wrangler logout` should attempt to logout the current user.

- If wrangler has a tty, it should ask "Are you sure?" Otherwise, it should continue.
- If OAuth is used for credentials it should revoke the credentials and remove it from the config.
- If an API token is used, it should ask "Do you want to expire your API token?" If yes, it should make an API request to expire itself. Otherwise, it should just remove it from the config.

**Comment by threepointone** [comment]
`wrangler logout` exists and works, it's simply not shown in the help menu. I'd push back on asking for confirmation, it's not a destructive process and very easy to recover, so we don't want to introduce friction. wrangler 2 only uses oauth tokens when logging in, and api tokens only via `CF_API_TOKEN` passed in as an env var.

**Comment by Electroid** [comment]
Ah gotcha, this is likely outdated feedback.

**Comment by petebacondarwin** [comment]
I think we should show it in the help menu though... ??
