### ISSUE TITLE
wrangler init should support yarn

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#353]
On `wrangler init`, if it detects that `yarn` is present, it should prompt the user and ask if they wish to continue using `yarn` (instead of `npm`)

**Comment by djKooks** [comment]
@Electroid seems it executes by `await execa("npm", ["install"] ...` so I think it can be done by 
- if `yarn.lock` exists, run yarn
- else run `npm install`

How do you think?

**Comment by petebacondarwin** [comment]
Yeah something like that. In this open PR, I partially abstract these operations into helpers: https://github.com/cloudflare/wrangler2/pull/329/commits/d499c4d6cca53702c8d6ba0c5a8a6248b6bdec4d

So we could take that one step further.
