### ISSUE TITLE
wrangler init should populate example code

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#355]
After running `wrangler init`, no example code is provided (`index.js` or `index.ts` depending if they asked for TypeScript or not). It should populate a basic starter file. In the future, we can make this more complex by introducing different templates to choose from.

`src/index.ts`:
```ts
export default {
  async fetch(request: Request, env: Environment, ctx: ExecutionContext): Promise<Response> {
    return new Response("Hello!");
  }
}

export type Environment = {
  // MY_NAMESPACE: KvNamespace;
}

```

`src/index.js`:
```js
export default {
  async fetch(request, env, ctx) {
    return new Response("Hello!");
  }
}
```

Also, should probably have a comment that links to the reference documentation?

**Comment by petebacondarwin** [comment]
Instead of asking `wrangler init` to do this. We should push ahead with implementing the `create-workers-app` package, which could then be run using `npm init workers-app`. See https://www.npmjs.com/package/create-qwik for an example of how this can work.

**Comment by threepointone** [comment]
I'd like to push back on this, it'll become extremely complicated to keep adding features here. But this is what we were planning on doing with create-worker-app, and we should design and plan that separately.

**Comment by Electroid** [comment]
> Instead of asking `wrangler init` to do this. We should push ahead with implementing the `create-workers-app` package, which could then be run using `npm init workers-app`. See https://www.npmjs.com/package/create-qwik for an example of how this can work.

> I'd like to push back on this, it'll become extremely complicated to keep adding features here. But this is what we were planning on doing with create-worker-app, and we should design and plan that separately.

Both great points. I do like the idea that we can just guide folks to `create-workers-app`. In fact, maybe `wrangler init` is just a legacy alias that asks if they want to run it?

My only qualm is leaving `wrangler init` half-baked; the entry point seems like a trivial addition that would make the experience much more useful. I agree the more complicated stuff can be left for a separate tool, but without the entry point, you feel like you got dropped off halfway to your destination.

**Comment by threepointone** [comment]
I like the idea of an entry point. Ok let's try something and see how it feels.

**Comment by threepointone** [comment]
https://github.com/cloudflare/wrangler2/pull/372
