### ISSUE TITLE
A plugin system (for custom file types, etc)

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#367]
Offer a way to allow developers to publish custom file types as part of their Worker.

**Comment by penalosa** [comment]
@petebacondarwin Is this addressed by [module rules](https://developers.cloudflare.com/workers/wrangler/configuration/#bundling)?

**Comment by petebacondarwin** [comment]
Hmm. I'm not sure. Rules support the following type: ESModule, CommonJS, CompiledWasm, Text or Data.
So I guess `Data` could cover custom types?

Honestly I am not sure what the original requirement was.
Let's close this since no one seems to be asking for it.
