### ISSUE TITLE
ReferenceError: req is not defined

### ISSUE THREAD

**Issue by hans-d** [cloudflare/wrangler2#37]
`wrangler pages dev --proxy 8090 -- astro dev --verbose`
results in 
```
[HPM] Proxy created: /  -> http://127.0.0.1:40527
[HPM] Proxy created: /  -> http://127.0.0.1:8090
Serving at http://127.0.0.1:8788/
/blog/node_modules/wrangler/wrangler-dist/index_node.js:27064
            throw ex;
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ReferenceError: req is not defined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Running:
```"node_modules/wrangler": {
      "resolved": "https://registry.npmjs.org/wrangler/-/wrangler-0.0.0-fsw-beta.5.tgz",
``` 
(inside docker nodejs container)

and for `_worker.js`
```
export default {
  async fetch(request, env) {
    if (req.url.startsWith('/api/')) {
      // TODO: Custom /api/* Worker logic
      return new Response('TODO: add logic')
    }

    // Otherwise, serve static asset(s).
    // Without this, Worker will error and no assets will be served.
    return env.ASSETS.fetch(request)
  }
}```

**Comment by WalshyDev** [comment]
```js
export default {
  async fetch(request, env) {
    if (req.url.startsWith('/api/')) {
```

Your parameter is called `request` however you're trying to use it with `req` (`req.url.startsWith('/api')`)

**Comment by threepointone** [comment]
could you try changing line 3 from 
`if (req.url.startsWith('/api/')) {`
to 
`if (request.url.startsWith('/api/')) {`

**Comment by threepointone** [comment]
(we should still do a better job of showing that error outside of the Promise rejection)

**Comment by hans-d** [comment]
ps: _worker.js content from https://developers.cloudflare.com/pages/platform/functions#advanced-mode

**Comment by hans-d** [comment]
> (we should still do a better job of showing that error outside of the Promise rejection)

That would certainly help, as the current message does not trigger review of _worker.js...

**Comment by threepointone** [comment]
Nice catch thanks!

**Comment by threepointone** [comment]
lmao @WalshyDev I beat you to the docs PR https://github.com/cloudflare/cloudflare-docs/pull/2762

**Comment by WalshyDev** [comment]
Yeah, I saw haha. Too quick for me
