### ISSUE TITLE
GitHub action for wrangler

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#381]
[wrangler-action](https://github.com/cloudflare/wrangler-action) is a GitHub action to deploy a Worker using wrangler1. We should either revisit that project, or create a new and improved GitHub action for wrangler2.

**Comment by JacobMGEvans** [comment]
This would be interesting! I think if we approached this again it would be worthwhile doing it in TypeScript, rather than Shell.

The API and docs around creating Actions have also greatly improved.

**Comment by petebacondarwin** [comment]
The wrangler-action has been updated to work with Wrangler 2
