### ISSUE TITLE
Runtime imports differ from esbuild imports

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#386]
When you run the [workers-chat-demo](https://github.com/cloudflare/workers-chat-demo) using wrangler2, you get an esbuild error:

```
✘ [ERROR] Could not resolve "chat.html"

    src/chat.mjs:62:17:
      62 │ import HTML from "chat.html";
         ╵                  ~~~~~~~~~~~
```

Presumably, wrangler1 allowed this where wrangler2 does not allow it. Should we allow this or will this be a breaking change?

**Comment by threepointone** [comment]
huh I thought I'd fixed this. I'll have a look.

**Comment by threepointone** [comment]
Oh, I see what's happening here. Yeah, this is a breaking change. wrangler 2 is doing the "right"/expected thing here, there's no module "named" `chat.html`, it should be a relative path `./chat.html`. We _could_ special case for this, but I think this is actually a bug (rather, unexpected behaviour) with the way we constructed the form upload in wrangler 1.
