### ISSUE TITLE
🐛 BUG: Error Could not resolve "badfilename" doesn't exit back to terminal

### ISSUE THREAD

**Issue by jgentes** [cloudflare/wrangler2#390]
### What version of `Wrangler` are you using?

alpha

### What operating system are you using?

WSL (Ubuntu 20)

### Describe the Bug

Do `wrangler dev badfilename` which results in `Error Could not resolve "badfilename"` but it doesn't exit back to the terminal so you can try again. You have to CTRL-C out or X then you can restart wrangler.

**Comment by Electroid** [comment]
I think this is one of those esbuild errors that should bail, if it's running for the first time. But if this happens during the dev session, we can probably keep it going.
