### ISSUE TITLE
feat: support `[wasm_modules]` 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#392]
We currently support `.wasm` _modules_, so in module-format workers, you can import wasm and instantiate it (like, `import something from './something.wasm';`). 

We should also support "legacy" style wasm, so anything passed to `[wasm_modules]` in `wrangler.toml` is available as a binding in service-worker format workers. 
(I was surprised to learn of this configuration field today. It makes sense that this exists and works, I was just surprised it doesn't appear to be documented at https://developers.cloudflare.com/workers/)

**Comment by Electroid** [comment]
An additional note is this is only accepted in service worker format. The API will reject the script if it attempts to use this in module format.

**Comment by ObsidianMinor** [comment]
I wonder if it makes sense to move fields that only make sense for service worker format to the build upload table (text, blob, and wasm files). That way it's obvious that it only works with that format. Not sure what the migration plan would look like for it though...

**Comment by threepointone** [comment]
We infer the format of the worker now, and there's very little format specific configuration anymore (other than `--public`, and all of Pages, both of which are module format specific.) Importing common text file formats works in service worker format now (html, txt, pem, but we can/should add more, as well as allowing it to be configurable after we figure out our plugin story). Another thing we can do, is make `.wasm` imports work in service worker format as well (I'll send a PR for that soon). With this it becomes easier to write libs and code that work across both formats consistently.

**Comment by threepointone** [comment]
If there's interest/desire, I could probably get `[wasm_modules]` working in modules format(!). Could make migration to module format workers easier.

**Comment by threepointone** [comment]
https://github.com/cloudflare/wrangler2/pull/409

**Comment by threepointone** [comment]
We'll track `import`-ing `.wasm` modules in service-worker workers in https://github.com/cloudflare/wrangler2/issues/416

**Comment by allsey87** [comment]
> We currently support `.wasm` modules, so in module-format workers, you can import wasm and instantiate it (like, `import something from './something.wasm';`).

When I import wasm using `import * as wasm from './backend_bg.wasm';`, I am getting an error that `wasm.fetch` is not a function. I augmented my `fetch` function as follows to check what the type of `wasm` and `fetch` were (as follows) and saw that the types of these variables were respectively `object` and `undefined`
```js
export function fetch(req, env, ctx) {
    console.log('typeof(wasm) is = ' + typeof(wasm))
    console.log('typeof(wasm.fetch) is = ' + typeof(wasm.fetch))
    var ret = wasm.fetch(addHeapObject(req), addHeapObject(env), addHeapObject(ctx));
    return takeObject(ret);
}
```
Is the [declarative import of wasm modules](https://github.com/WebAssembly/esm-integration/tree/main/proposals/esm-integration) supported on Cloudflare workers?

**Comment by threepointone** [comment]
Cloudflare workers does it a little differently at the moment, it's imported as WebAssembly.Module that you can instantiate. Example here https://github.com/cloudflare/wrangler2/blob/main/examples/wasm-app/worker/module/export_wasm.js Here's an older blogpost with some details https://blog.cloudflare.com/webassembly-on-cloudflare-workers/

**Comment by allsey87** [comment]
> Example here https://github.com/cloudflare/wrangler2/blob/main/examples/wasm-app/worker/module/export_wasm.js

Just curious, but why does the [WebAssembly binary in that example](https://github.com/cloudflare/wrangler2/blob/main/examples/wasm-app/worker/index_bg.wasm) contain the string "index_bg.js"? The WebAssembly modules that I have generated using wasm-bindgen do not contain any such references...

**Comment by threepointone** [comment]
I'm not sure, I used the output of the workers-rs base project https://github.com/cloudflare/workers-rs to generate that example folder

**Comment by allsey87** [comment]
My fault: the difference is a result of whether wasm-bindgen is set to build for the `web` target or for the `bundler` target. For the former, the name of the import object is just `wbg` while in the latter it is `./${CRATE_NAME}_bg.js`.
