### ISSUE TITLE
🐛 BUG: pages dev doesn't support live reload

### ISSUE THREAD

**Issue by vladinator1000** [cloudflare/wrangler2#395]
### What version of `Wrangler` are you using?

wrangler@alpha (0.0.0-536c7e5)

### What operating system are you using?

WSL

### Describe the Bug

Hi y'all, I've been trying to get my website to reload on file changes but I got stuck. When you proxy Parcel like that

`wrangler pages dev --script-path dist/_worker.js -- npm run parcel`

the site loads, but hot reloading is broken with the following error
```
GET / 502 Bad Gateway (2.85ms)
[pages:err] TypeError: Web Socket request did not return status 101 Switching Protocols response with Web Socket
```

You can still get the changes if you refresh the page bu it would be great if we had a clear path forward for hot reloading.

I see `pages dev` also supports a `--live-reload` flag, but I'm not sure how that works in practice since it didn't work for me when I compiled manually, pointed it at the dist folder and nothing happened when I changed the files.

I made a little reproduction repo here: https://github.com/vladinator1000/cloudflare-pages-test/tree/0ff085e087fbcaaa514f666609400dfbdb820ce2

**Comment by GregBrimble** [comment]
Thanks for the report. We're already tracking support for WebSockets here: #70
