### ISSUE TITLE
Small improvements to wrangler init

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#399]
- TypeScript configuration seems to be slightly incorrect:
  - [x] `src/index.ts: Cannot find name Promise`
  - [x] `tsconfig.json: Cannot find global type Array`
- [x] `scripts` in package.json should be prepopulated with some defaults, e.g. 
```json
"scripts": {
  "start": "wrangler dev src/index.ts",
  "deploy": "wrangler publish src/index.ts" 
}
```
- [x] `wrangler.toml` is only populated with `compatibility_date`, but should also contain:
   - `name`, matching the name of its directory.
   - ~~`workers_dev = true`, so it's easy to publish.~~

**Comment by JacobMGEvans** [comment]
So, the `name` could be the Worker name that is passed in as an argument of `init` if provided, or should we keep it the name of the directory?

**Comment by JacobMGEvans** [comment]
So `workers_dev` is a default configuration of true in Weangler2, I suppose it could be added to be explicit or rather document the API as implicitly/default true and can be changed to false.

**Comment by threepointone** [comment]
To clarify, we're deprecating the `workers_dev` field altogether in wrangler 2, its value can be inferred by the presence/lack of `routes`. (Unless I'm missing some usecase)

**Comment by Electroid** [comment]
> To clarify, we're deprecating the `workers_dev` field altogether in wrangler 2, its value can be inferred by the presence/lack of `routes`. (Unless I'm missing some usecase)

Right.. forgot about that. So only the `name` would be good to add.

**Comment by JacobMGEvans** [comment]
@threepointone Did you already modify the `tsconfig.json` to fix these issues already?

**Comment by threepointone** [comment]
I'm not aware of whether that fixed the Promise/Array issue. But also, that bug looks highly suspicious, it shouldn't really occur. Might've just needed a vscode restart. If you're not able to reproduce that issue, consider it fixed.
