### ISSUE TITLE
Sites support

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#4]
wrangler v2 has partial support for Workers Sites. This issue tracks the implementation. 

- [x] We need to do some work to make sure the hashes of the files generated when saving to KV are the same as wrangler v1, and we add all the validation that wrangler v1 has. https://github.com/cloudflare/wrangler2/pull/277
- [x] We've added the ability to specify the directory for Sites in the cli, so for example you can do `wrangler dev script.js --site path/to/assets` (You can still specify it in `wrangler.toml`, of course). 
- [x] Error if asset is over 25Mb - 87cbf75
- [x] #282

**Comment by threepointone** [comment]
Things left to do here - 

- `--public`, for consistency with pages, needs to be available on env as `ASSETS`, and has to be wired manually to the worker. (We should discuss this.)
- we need to add validations to Sites; making sure every asset is below 25mb, etc 
- A stretch goal would be to add a command that deletes older, unused assets from the kv namespace.

**Comment by threepointone** [comment]
We should also probably have better defaults in `static-asset-facade.js`.

**Comment by petebacondarwin** [comment]
I believe that checking content is under 25Mb was implemented in https://github.com/cloudflare/wrangler2/commit/87cbf7540bd4fd40983f285ba9ef827dfed3db01

**Comment by petebacondarwin** [comment]
TODO: ensure that `listNamesapces()` (used by Sites to find whether the assets kv namespace exists) searches all the pages of namespaces, if it is not on the first page.

**Comment by petebacondarwin** [comment]
FInd a more efficient way to check whether a KV namespace already exists, rather than listing them all...

**Comment by petebacondarwin** [comment]
First PR: https://github.com/cloudflare/wrangler2/pull/270

**Comment by petebacondarwin** [comment]
Second PR: https://github.com/cloudflare/wrangler2/pull/277

**Comment by petebacondarwin** [comment]
Third PR: #280

**Comment by hkochniss** [comment]
I'm late to the party, but confused; just tried this, but it errors with "there is no KV namespace bound to the script".. I generated a worker site withg the old wrangler, and there is a very simple (just name and compat date) wrangler.toml with [site], but the handler throws using `npx wrangler@beta dev workers-site/index.mjs --site ./dist --local` or `npx wrangler@beta dev workers-site/index.mjs --local`

Is this suppoed to work? What is missing?

**Comment by hkochniss** [comment]
update: in non-local mode, at least manifest works, but env.ASSET_NAMESPACE is not bound, which is the whole issue

**Comment by hkochniss** [comment]
omg figured it out, your example code should be 
```
...
ASSET_NAMESPACE: env.__STATIC_CONTENT,

```
This took me 1,5 hours to figure out.. if there was ONE working example template anywhere for modules worker sites, this wouldn't be an issue, I guess :/
