### ISSUE TITLE
Local mode opens port on too many hosts

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#400]
When running `wrangler dev --local`, Miniflare opens a port on several hosts:
```
[mf:inf] Listening on :8787
[mf:inf] - http://127.0.0.1:8787/
[mf:inf] - http://192.0.2.2:8787/
[mf:inf] - http://192.168.1.5:8787/
[mf:inf] - http://172.16.0.2:8787
```
Instead, it should only open a port on `localhost`.

**Comment by threepointone** [comment]
Appreciate that you filed these, very helpful! We should label these issues with something like "feedback" so it's obvious that they're not tasks from you @Electroid.

**Comment by threepointone** [comment]
The messaging isn't as noisy anymore, closing this for now.
