### ISSUE TITLE
Add deprecation warning when trying to run commands without explicit entrypoint 

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#401]
In wrangler1, you could run `wrangler dev`, `wrangler publish`, etc. without explicitly specifying the entrypoint in the command. Many users will attempt to run these old commands and get confused why they now see the help page. Instead, there should be a deprecation warning that tells them what to do.

**Comment by threepointone** [comment]
Agreed, we should have explicit errors for when people do common mistakes instead of the generic yargs "expect x arguments, got y" message.

**Comment by petebacondarwin** [comment]
One can still run `wrangler publish` with no entry-point in W2, as long as you have defined an entry-point via `build.uploads.main`.

**Comment by Electroid** [comment]
> For `wrangler dev` I think we should also support the `build.upload.main` field exactly the same as `wrangler publish`. I will put together a PR to do that, which will also move the bundling into a helper that both commands use.

If we support something for publish, it should work for dev too. Similar to #396
