### ISSUE TITLE
feat: log bundle size during `dev`/`publish`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#405]
It would be nice if we logged the size of the generated worker (+ modules) in `dev` and `publish`. This would be useful to encourage smaller workers, but also to warn folks who are blowing past the 1mb limit. There's precedent to do this across the ecosystem - webpack, parcel, etc all do some form of this. 

(In the future we could also have a shortcut that shows a visual representation of the bundle and which packages take how much space, á la `source-map-explorer`).

**Comment by Electroid** [comment]
Here are a few notes:
* The script limit is applied after `gzip` compression, so if we show a limit, we would either want to show the compressed size or uncompressed as well.
* `GET /workers/settings` will contain a `allowed_script_size_bytes` value, which can be checked for indicating what the limit is for a particular account (we should *not* hard-code "1mb")

**Comment by JacobMGEvans** [comment]
Vite, uses ESBuild and has a nice implementation of this. Also was recently mentioned in [Discord channel for Wrangler](https://discord.com/channels/595317990191398933/799437470004412476/966018269242884106).

**Comment by JacobMGEvans** [comment]
Tracked down their reporting, could use this as a reference. https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/reporter.ts

**Comment by JacobMGEvans** [comment]
# Bundle Reporter
Given the temporary directory for `publish` and `dev` commands that have the "script" + "modules" we can get the total size that will be uploaded to the edge before and after compression `original size / gzip size` 

- [ ] Implement the helper component for `publish`
- [ ] Implement the helper component for `dev` 
- [ ] Utilize `allowed_script_size_bytes` for color ranges for sizes (green/yellow/red) 
- [ ] Breakout individual files in the message output color code based on ext. (see [Discord example](https://discord.com/channels/595317990191398933/799437470004412476/966018269242884106))
- [ ] Prevent unnecessary API call to `publish` or `dev` if over `allowed_script_size_bytes` limit when compressed. [optional]
