### ISSUE TITLE
🐛 BUG: Disabling workers dev domain doesn't work

### ISSUE THREAD

**Issue by mcfadyeni** [cloudflare/wrangler2#410]
### What version of `Wrangler` are you using?

alpha (14098af)

### What operating system are you using?

MacOS

### Describe the Bug

When adding `workers_dev = false` to `wrangler.toml` and instead using a custom domain with routes, the dev domain is still enabled and able to be used to receive requests. This is not desired behavior.

**Comment by petebacondarwin** [comment]
I concur with this - I noted it also in https://github.com/cloudflare/wrangler2/issues/301
