### ISSUE TITLE
🐛 BUG: `[build.upload.dir]` not respected when resolving `build.upload.main`

### ISSUE THREAD

**Issue by unsafecreds** [cloudflare/wrangler2#413]
### What version of `Wrangler` are you using?

0.0.16

### What operating system are you using?

macOS

### Describe the Bug

Hey there! I have a simple project with a Worker generated using the `workers-rs` template (probably not relevant). This is what the relevant part of my `wrangler.toml` looks like:
```
[build.upload]
dir = "./build/worker"
main = "./shim.mjs"
format = "modules"
rules = [
  { globs = ["**/*.wasm"], type = "CompiledWasm" }
]
```

When I try to `wrangler publish`, I see 
```
✘ [ERROR] Could not resolve "<redacted-cwd>/shim.mjs"
```

The path printed out in here suggests that the `main` is resolved from the current working directory, and it doesn't take the `dir` into account as the docs suggest: https://developers.cloudflare.com/workers/cli-wrangler/configuration#build-2
I can work around this by changing the `main` key to `main = "./build/worker/shim.mjs"`.

`wrangler` v1.19.8 works the way I'd expect (with `main = "./shim.mjs"`)

**Comment by petebacondarwin** [comment]
Thanks for reporting this. The `uploads.main` (and `uploads.dir`) config fields are deprecated. We are moving towards using the top level `entry` config property, which is relative to the current working directory.
But while we still support `uploads.main` we should also honour `uploads.dir`. I'll submit a fix.
