### ISSUE TITLE
feat: implement `[build.upload.rules]` for both service-worker/modules format workers

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#416]
One of wrangler2's highlights is having a first class module system, that brings it closer to runtimes like node/deno/etc. Further, we have pretty decent defaults ootb - common module types (`js`/`jsx`/`ts`/`tsx`/`json`) don't need any configuration, and non-"standard" modules (`wasm`/`txt`/`html`/`pem`) work as expected. There are a few corner cases though, and a little more we can do to make this story feel more complete. 

- importing `.wasm` modules should 'just work' in service-worker format workers. We already do the same for standard and the other non-standard module types, so this would just complete the story. (It would be implemented on top of https://github.com/cloudflare/wrangler2/pull/409) - fixed in https://github.com/cloudflare/wrangler2/pull/432
- wrangler 1 supports  `[build.upload.rules]`for es module workers, and so should wrangler 2, but for both modules and service-worker formats. The most common usecase is to add more extensions to be recognised as `Text`, but I'd imagine some folks will want `Data` as well. 

(This work is _separate_ from the work for plugins (#367), which we'll get to later.)

**Comment by threepointone** [comment]
Most of this was done in https://github.com/cloudflare/wrangler2/pull/530, but some followups before we can close this 
- non-wasm modules don't work in local mode (I think I can fix this)
- `Data` type does not work in service worker format, in either mode (because there isn't an analog to wasm_module/text_blob binding for a Data module, unless I'm missing something)

**Comment by threepointone** [comment]
for `text_blobs`/`Text` modules support in local mode, blocked on https://github.com/cloudflare/miniflare/issues/211. After that, we can land https://github.com/cloudflare/wrangler2/pull/558 and close this. Unassigning from myself.

**Comment by caass** [comment]
Opened https://github.com/cloudflare/miniflare/pull/228 with more hope than tangible code

**Comment by threepointone** [comment]
Deeply grateful to @caass for working on this with @mrbbot to land support in miniflare! Thanks thanks.

**Comment by threepointone** [comment]
importing text and data modules now works in service workers+local mode, but not plain text_blobs/data_blobs. we probably have to copy it here https://github.com/cloudflare/wrangler2/blob/b9336414c3c1ac20ba34d274042886ea802385d9/packages/wrangler/src/dev/local.tsx#L75-L82 I'll fix this tomorrow unless someone else gets to it
