### ISSUE TITLE
feat: support `[build.upload.main]`/`[build.upload.dir]` in `wrangler dev`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#418]
We're currently supporting `[build]` while we transition to possibly phasing out implicit entry points. Looks like we don't read it for `wrangler dev`, and we should.

**Comment by Electroid** [comment]
Seems like we need to refactor/consolidate the build step in `publish` and `dev`. We can't have them be different.

**Comment by threepointone** [comment]
Pete, I'm going to assign this to myself, it intersects with https://github.com/cloudflare/wrangler2/issues/390 and I can solve both together.
