### ISSUE TITLE
[Known issue] Wrangler does not support Yarn 2/3 PnP

### ISSUE THREAD

**Issue by jahands** [cloudflare/wrangler2#420]
Yarn's PnP (Plug'in'Play) [installation strategy](https://yarnpkg.com/features/pnp) changes the way dependencies are stored and how our code can interact with them.

Wrangler 2 does not currently support this feature of Yarn and has no current plans or timeline on supporting it.

## Workaround
Add `nodeLinker: node-modules` to your `.yarnrc.yml` to use `node_modules` instead of `PnP` when using Yarn 2/3 with Wrangler 2.

**Comment by threepointone** [comment]
There's nothing actionable we can do here really, so I'm going to close this issue. Thanks for filing it with a workaround @jahands!

**Comment by Joelasaur** [comment]
I was able to circumvent this error by using the cloudflare [github action](https://github.com/cloudflare/pages-action) instead of running the wrangler CLI through yarn.

**Comment by Kjaer** [comment]
Hey we found the solution by [unplug](https://yarnpkg.com/cli/unplug/)ing wrangler-2. Simply add t
