### ISSUE TITLE
wrangler dev should reload when wrangler.toml is changed

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#439]
When you're in a dev session and change the `wrangler.toml`, say to add an environment variable, the session does not update; though it should.

**Comment by petebacondarwin** [comment]
Yes, I see the pain here when I tested your PR that allows vars to be set in the TOML.
But again, it makes me concerned that now have two ways of defining a Worker, which is interlinked but not consistent: the path passed to `wrangler dev` and the wrangler.toml are both needed for a Worker to be configured correctly.

I think the right thing to do, now, is to wire up the `entry` property in `wrangler.toml` to use by default (properly deprecating the `build.upload.main` and friends. Then allow the command line to override that by passing a script as an arg, while printing a warning if the two do not match.

**Comment by threepointone** [comment]
Yeah, this has been on my mind too. Let's bite the bullet on this.

**Comment by threepointone** [comment]
(we can bikeshed on the name - could be "main", etc)

**Comment by threepointone** [comment]
I added that field haha, it's not a thing in wrangler 1. I suggest `main` because it's familiar, that's all.

**Comment by threepointone** [comment]
We currently load bindings when the toml changes, let's leave this open until we do it for all fields

**Comment by threepointone** [comment]
my mistake, it dos apply for the whole config. neat! closing
