### ISSUE TITLE
Config should be resolved relative to the entrypoint

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#440]
The resolution of the `wrangler.toml` needs to be tweaked, here's an example I ran into:

* `cd home`
* `wrangler dev project/src/index.js`
* Session starts. Ok, but why are my environment variables empty?
* wrangler searched for a `wrangler.toml` starting from the `home` directory, and found nothing. So it assumed no config.
* Instead, it should have started its search at the entrypoint, and traversed up.

**Comment by petebacondarwin** [comment]
I think is a good idea since it would seem strange to have a worker entry point with a wrangler.toml file above it that is not the one you want to use.

**Comment by threepointone** [comment]
^ we discussed this, and decided that that tradeoff is worth it.
