### ISSUE TITLE
feat: implement json bindings for `wrangler dev --local`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#449]
We implemented json bindings in https://github.com/cloudflare/wrangler2/pull/438, but we'll need it for `--local` mode as well. The complication here is that this is actually a proper breaking change, and might require changes in miniflare too, as well as some form of warning/messaging.

**Comment by JacobMGEvans** [comment]
Considering the conversation, implementation of Miniflare API, I would like to consider reducing all the flag to `--bindings` which parses the TOML config still and remove the other flags, to more closely match how remote handles the bindings. 

Cc: @petebacondarwin

**Comment by petebacondarwin** [comment]
@mrbbot suggested an alternative approach, which is to use Miniflare programmatically, where we have full access to set the bindings with the correct types.

**Comment by JacobMGEvans** [comment]
> @mrbbot suggested an alternative approach, which is to use Miniflare programmatically, where we have full access to set the bindings with the correct types.

Correct. I was thinking about removing the extraneous flags and having the Miniflare programmatically (API) handle the TOML file `vars` and other bindings. Rather than always needing to add a flag when features are added, it would just consume the TOML file.

**Comment by petebacondarwin** [comment]
I believe this is now supported as of https://github.com/cloudflare/wrangler2/pull/633

**Comment by threepointone** [comment]
Should we just not have any messaging around the breaking change? Specifically, in wrangler1, `x = 1` would previously have env.x be a string, and now it's a number. It might be fine, but something to remember.
