### ISSUE TITLE
🐛 BUG: SyntaxError, missing ) after argument list

### ISSUE THREAD

**Issue by mcfadyeni** [cloudflare/wrangler2#450]
### What version of `Wrangler` are you using?

0.0.0-bce731a

### What operating system are you using?

MacOS

### Describe the Bug

When running the command:
`node -r dotenv/config node_modules/.bin/wrangler pages dev ./.svelte-kit/cloudflare` (adapted from https://github.com/cloudflare/wrangler2/issues/190#issuecomment-1012486967 for environment variables), Wrangler2 throws a `SyntaxError: missing ) after argument list` error (line 2).

The `./.svelte-kit/cloudflare` directory contains a `_worker.js` and everything works fine if ommiting the `node -r` part.

**Comment by petebacondarwin** [comment]
Ah right! So the file `node_modules/.bin/wrangler` is not a Node.js script. It is a bash script.
So by writing `node -r dotenv/config node_modules/.bin/wrangler` you are trying to run a bash script as a Node.js script, which obviously is not valid JS.

**Comment by petebacondarwin** [comment]
I'm not sure what the requirement for `node -r dotenv/config` is...?

**Comment by mcfadyeni** [comment]
Oh! The comment that I went off of must have been using the original `wrangler`.

The only other option for passing in environment variables from a .env file that I could see was to use `--binding $(cat .env)` but that messes up quotations inside the `.env` file. Is there any options to directly use a `.env` file (I know that was planned at one point?)

**Comment by petebacondarwin** [comment]
I haven't seen any discussion of this other than https://github.com/cloudflare/wrangler2/issues/190, which you already mentioned.

**Comment by petebacondarwin** [comment]
As a workaround you could try using the following:

```bash
node -r dotenv/config node_modules/wrangler/bin/wrangler.js pages dev ./.svelte-kit/cloudflare
```

But that files does some crazy stuff to turn on `--experimental-vm-modules` which I believe is only required for miniflare.
So if that also doesn't work you could go one step further and try:

```bash
node -r dotenv/config node_modules/wrangler/wrangler-dist/cli.js pages dev ./.svelte-kit/cloudflare
```
