### ISSUE TITLE
feat: `wrangler.toml` needs a new field to define custom builds for `wrangler dev`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#453]
Currently, `build.command` is what is used to define a custom build command. It is used for both `wrangler publish` and `wrangler dev`. There are a few reasons why this is inconvenient - 

- frameworks typically have different commands for development and production builds. (eg - `next dev`/`next build`, `react-scripts dev`/`react-scripts build`, etc
- development scripts usually come with their own file watchers, and run "forever", as it were. 
- We support `build.watch_dir` and restart the command whenever anything in it changes, but that's not compatible with what systems expect. Combined with the above other 2 problems, it's not a flexible enough system.  

So we need to introduce a new configuration field that's separate from `build.command`.

**Comment by threepointone** [comment]
Alternately, we deprecate custom builds, and write docs on how to do this on the command line. This may be the better option.

**Comment by petebacondarwin** [comment]
I would be heavily in favour of not supporting custom builds. There are so many ways that it might need to be wired up, and I don't think we should get into wrangler being the orchestration piece in the tool chain. Instead, it should be used within an orchestrator that handles and pre-building steps that are required.

Wrangler should be laser focussed on one (/two) thing(s): publishing workers to the Edge (and providing a nice debugging environment for workers).

**Comment by threepointone** [comment]
Agreed. I'll close this issue, and make a fresh one for deprecating custom builds later.
