### ISSUE TITLE
feat: expire unused assets with `[site]`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#459]
With Sites/`[site]` definitions, we currently don't do anything with unused assets. This can lead to bloated kv stores, and slower upload times (because we iterate through all keys in the sites kv store when uploading). The fix is to detect unused assets during upload, and add expiration tags on them. 

Related, we should probably do this for wrangler 1 as well. 

Related - https://github.com/cloudflare/wrangler/pull/2096

**Comment by threepointone** [comment]
filed https://github.com/cloudflare/wrangler/pull/2214 to revert the change in wrangler1.

**Comment by threepointone** [comment]
This needs to be redone, there's some subtlety with the implementation that's breaking people's deploys https://github.com/cloudflare/wrangler/issues/2224

**Comment by petebacondarwin** [comment]
Urgh! So we can't rely on the current time given in a Docker container to be accurate!!
I think using `expiration_ttl` will solve this.

**Comment by threepointone** [comment]
Distributed systems 🤪
