### ISSUE TITLE
fix: `wrangler dev` doesn't work with `workers-chat-demo`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#477]
The canonical example for durable-objects + websockets doesn't actually work with wrangler2. Clicking to create a new room just fails, no clear error. 

To reproduce - 
```bash
npm run build 
cd packages/workers-chat-demo
npx wrangler dev
```

**Comment by Electroid** [comment]
I actually ran into this too, there's 2 issues:
* in `chat.html`, it's trying to send messages to `wss` and not `ws`
* in `chat.mjs`, it's trying to import `chat.html` instead of `./chat.html`
