### ISSUE TITLE
wranger pages dev --binding

### ISSUE THREAD

**Issue by hans-d** [cloudflare/wrangler2#48]
Having to provide secrets etc via the command line is quite cumbersome, as it seems that is currently the only way for `wranger pages dev`

I would prefer that these can be loaded via a config file (wranger.toml ?) or so.

**Comment by GregBrimble** [comment]
While full-stack Pages and wrangler2 are in beta, we don't have any solid plans for how best to configure bindings in config, but we're thinking a lot about it! Right now, the only way to use bindings are to specify them with flags.
