### ISSUE TITLE
🐛 BUG: render helpstring for incomplete subcommands

### ISSUE THREAD

**Issue by taylorlee** [cloudflare/wrangler2#487]
### What version of `Wrangler` are you using?

0.0.17

### What operating system are you using?

Linux

### Describe the Bug

this isn't a bug, but a UX improvement from wrangler1 that we should bring over to wrangler2.
the happy-path is the same, but wrangler1 prints helptext when a subcommand is incomplete, whereas wrangler2 does nothing.
eg:
```
$ wrangler1 secret list
[]
$ wrangler2 secret list
[]
$ wrangler1 secret 
wrangler-secret 1.19.8
Generate a secret that can be referenced in the worker script

USAGE:
    wrangler secret [FLAGS] [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
        --verbose    Toggle verbose output (when applicable)

OPTIONS:
    -c, --config <config>    Path to configuration file [default: wrangler.toml]
    -e, --env <env>          Environment to perform a command on

SUBCOMMANDS:
    delete    Delete a secret variable from a script
    help      Prints this message or the help of the given subcommand(s)
    list      List all secrets for a script
    put       Create or update a secret variable for a script
$ wrangler2 secret 
$
```

wrangler2 has the helptext though, so we should render it
```
$ wrangler2 secret -h
wrangler secret

🤫 Generate a secret that can be referenced in the worker script

Commands:
  wrangler secret put <key>     Create or update a secret variable for a script
  wrangler secret delete <key>  Delete a secret variable from a script
  wrangler secret list          List all secrets for a script

Flags:
  -c, --config   Path to .toml configuration file  [string]
  -h, --help     Show help  [boolean]
  -v, --version  Show version number  [boolean]

Options:
  -l, --local  Run on my machine  [boolean] [default: false]
```

I can try to fix this when I have time, but feel free to patch it before then if you know how :)

**Comment by petebacondarwin** [comment]
Good spot @taylorlee - thank you for noticing and registering these issues.

**Comment by threepointone** [comment]
I thought we were doing this, must have lost this behaviour a while ago. Thanks for filing!

**Comment by petebacondarwin** [comment]
I have never seen this working specifically for subcommands. When there is an error we run `showHelp()` but this always seems to show the top level help. I once tried fixing it (briefly) but it was not obvious how to solve it simply. I might have missed something obvious.
