### ISSUE TITLE
feature request: `wrangler tail <url-path>`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#492]
Support random url patterns, so you could do wrangler tail xyz.somedomain.com/:user/something and we can intelligently figure out which workers to tail and how to filter it out to that path.

(Captured from https://github.com/cloudflare/wrangler2/issues/5).

**Comment by Electroid** [comment]
I added the "big idea" label, because it would require a substantial change to how the API for `wrangler tail` works. It's totally doable, and I think it's a great idea, but needs more work.

**Comment by caass** [comment]
I was looking with @penalosa and we think this seems doable as a quick win! It looks like it would entail:

1. Checking if the positional argument passed to `wrangler tail <url | name>` resembles a URL
2. Determining the zone ID from the URL (e.g. via [`getZoneForRoute`](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/zones.ts#L29))
3. Calling [`GET zone/:zone_id/workers/routes`](https://api.cloudflare.com/#worker-routes-list-routes)
4. Finding the given URL in the returned routes
5. Using the worker name associated with that route to plug in to the existing `tail` infrastructure

A follow-up question would be: how strict should we be about matching URL's? For example, should `wrangler tail example.com` match a `example.com/*` route? For now, we can print a message like

```
an exact match for "example.com" was not found, but there is a worker "my-worker-name" assigned to "example.com/*".

Try running "wrangler tail example.com/*" or "wrangler tail my-worker-name" if you meant to tail this worker.
```

which would require an exact match, and then we can loosen these requirements as we add logic to more intelligently determine which workers to tail.

For a route that has multiple workers assigned, we should print the names of the workers running on that route and ask the user to tail one individually.

**Comment by penalosa** [comment]
@petebacondarwin Does https://github.com/cloudflare/wrangler2/pull/1700 fully address this issue?
