### ISSUE TITLE
Feature Request: Pages Functions does not support compatibility flags

### ISSUE THREAD

**Issue by mnixry** [cloudflare/wrangler2#495]
### What version of `Wrangler` are you using?

0.0.17

### What operating system are you using?

Linux

### Describe the Bug

I'm trying to use `compatibility_flags` in my [Pages Function](https://developers.cloudflare.com/pages/platform/functions#develop-and-preview-locally), and used some features marked in `compatibility_flags`.

According to [document of Miniflare](https://miniflare.dev/core/compatibility), I can add `compatibility_flags` option in `wrangler.toml`, but it does not work. Although I specify `--config wrangler.toml` in command line, it does not work either.

There is my `wrangler.toml` file:

```toml
compatibility_date = "2022-02-19"
compatibility_flags = [
  "formdata_parser_supports_files",
  "durable_object_fetch_allows_relative_url"
]
```

Did I do something wrong? Is there a way to solve this problem?

**Comment by sidharthachatterjee** [comment]
Hey @mnixry. Pages functions doesn't support this at the moment. Will come eventually. My apologies for the confusion!
