### ISSUE TITLE
`wrangler tail`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#5]
This issue tracks the implementation of `wrangler tail`. 

### Usage 

- [x] as before, you can run `wrangler tail` inside a project and it'll start showing live logs for the worker defined in that project. 
- [x] additionally, you can pass a script name directly to it, like `wrangler tail <name>` and it'll tail the worker from your account with that name. 
  -  [x] Consequently, you won't need to clone the worker's repo, install all dependencies, all just to tail the worker anymore. You should now be able to run `npx wrangler tail <name>` from anywhere. 
- [x] in v2, we only log in the json format, and don't support all the filters yet. We will fix this soon to add pretty mode, and all the filter flags: `--status`, `--header`, `--method`, `--sampling-rate`, `--search`.

**Comment by geelen** [comment]
Just to add one, I made fairly heavy use of the following query in the past:

```
wrangler1 tail | jq --compact-output '.event.request.url,.logs[].message[],.exceptions'
```

With `wrangler1` being entirely config-driven (not interactive), this worked well:

![image](https://user-images.githubusercontent.com/23264/146879383-21f6608b-1097-44d7-a037-e6a8442cf138.png)

I mean, it's not as good as _actually_ presenting the log data in a really nice way. But something to think about. Maybe a `--raw` flag or even a `--jq` one?

**Comment by petebacondarwin** [comment]
Closing as the main task here have been completed!! 🚀
