### ISSUE TITLE
Bug: generated routes on windows are incorrectly escaped (404)

### ISSUE THREAD

**Issue by WalrusSoup** [cloudflare/wrangler2#51]
On windows the routes generated in page functions don't appear to be escaped correctly when compiling:

```
npx @cloudflare/pages-functions-compiler build functions\
```
Outputs:
```
    {
      routePath: "/api\code",
      methods: ["POST"],
      middlewares: [],
      modules: [__api_code_ts_onRequestPost],
    },
```

which should actually be 
`/api/code` or else it simply results in 404's. This happens for all nested routes.

As a temporary fix, I did this:
`node_modules\@cloudflare\pages-function-compiler-bin\plinko.js@5238`

Added the line below the others:
`routePath = routePath.replace(/\\/g, '/');`

and now the routes generate correctly. 

I apologize if this is on the wrong repo, there seems to be a lot of wranglers (alpha, beta, wrangler2, but cloudflare blog references only wrangler@beta) and it took so long to fix this bug I find myself a bit lost in it all.

**Comment by johanndev** [comment]
The problem also occurs when using the `wrangler pages dev` command.

**Comment by petebacondarwin** [comment]
Indeed a string replacement at this point would work. But I think a better solution, across the whole project, is to convert all paths to posix ones (and use the posix `path` functions from Node.js).
