### ISSUE TITLE
API tokens do not work in config/default.toml

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#526]
When an API token (not OAuth token) is added to `~/.wrangler/config/default.toml`, it is rejected and the user is prompted to login. We should accept the API token.

**Comment by threepointone** [comment]
This was a conscious decision iirc, since API tokens can be compromised and have a much longer life. You can use `CF_API_TOKEN=token wrangler ...` to use api tokens, ofc. Want to revisit this decision?

**Comment by petebacondarwin** [comment]
From looking at the logic in the code, this should already work.

The way to do it is to set the `oauth_token` to be the API token but then also to provide a long `expiration_time` such as `"3021-12-31T23:59:59+00:00"`, which is basically all we are doing when we get the API token from the `CLOUDFLARE_API_TOKEN` environment variable.

**Comment by petebacondarwin** [comment]
But as @threepointone said, we don't really want to encourage people to edit the `~/.wrangler/config/default.toml` file, since that is internal...

**Comment by petebacondarwin** [comment]
So we are going to implement `wrangler login --api-token=<API_TOKEN>` which will authenticate them in this way without having to touch that file.
