### ISSUE TITLE
feat: `wrangler dev` should default to `https:localhost:...`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#527]
When we deploy, we default to https. In most cases, code written will work in both http/https. Except when it doesn't, and because we haven't implemented `--local_protocol`, it gets extremely clumsy to work around. (example: `workers-chat-demo`) So - 
- we should implement `--local_protocol` for `wrangler dev`
- we should default `wrangler dev` to `https:localhost:...`, since that's what `publish` defaults to. 

Related to https://github.com/cloudflare/wrangler2/issues/298

**Comment by Electroid** [comment]
Two thoughts:
* Since the edge supports both `http` and `https`, maybe the local default should be both?
* Isn't setting up `https` on localhost a pain (because certificates), would we make that better?

**Comment by threepointone** [comment]
Yes and Yes! It should automatic on our part, we should do the mkcert nonsense etc.

**Comment by petebacondarwin** [comment]
So I think that both upstream and local protocols could be inferred from the URL that is being used locally.
If, after running `wrangler dev` we browse to `http://localhost:8787` then the local and remote protocols should be `http`.
Equally, if we browse to `https://localhost:8787` then both the local and remote protocols should be `https`.
This would effectively make these two options redundant.

In the `wrangler dev` UI we could have two options for opening the browser in http or https mode?

**Comment by threepointone** [comment]
Marking this closed since we now have support for --local-protocol.
