### ISSUE TITLE
🐛 BUG: Image resizing is not supported by `wrangler2 dev`

### ISSUE THREAD

**Issue by ptim** [cloudflare/wrangler2#534]
### What version of `Wrangler` are you using?

0.0.17

### What operating system are you using?

Mac

### Describe the Bug

Any requests for a resized image passes through to the source image (returns "content-type: image/whatever").

This is easily seen when requesting [format='json'](https://developers.cloudflare.com/images/image-resizing/resize-with-workers/#fetch-options)...

Is this due to wrangler2 using miniflare under the hood? I'm accustomed to this behaviour in local dev with miniflare, and have  a "canary fetch" to a known-good image early in my debug handler to remind me of this situation...

I'm expecting that when I run `wrangler2 dev`, live image resizing will occur, as it does with `wrangler1 dev`

(BTW, my wrangler.toml for the env under test points to an enterprise enabled domain with image-resizing activated)

I couldn't find any mention of "image" in the [project](https://github.com/orgs/cloudflare/projects/1/views/1), [2.0 milestone](https://github.com/cloudflare/wrangler2/milestone/1), or issues - hth!

Regards, ptim

**Comment by petebacondarwin** [comment]
Is this using "sites" functionality? If so, I believe the problem is that in Wrangler2, for `dev` we intercept requests for assets and serve them locally rather than asking the Edge for them. This is an optimization to save having to upload all assets every time the code changes and we update the Worker.

**Comment by threepointone** [comment]
@petebacondarwin We still use the edge for Sites, uploads and all, so I don't think that's the issue here. 
@ptim we don't use miniflare by default, unless you've triggered local mode via `--local` or the `L` hotkey (in which case, I don't think we honour the resizing options, but I could be wrong).
This issue may need some investigation. Could you make a sample reproduction repo to help? Thank you!

**Comment by ptim** [comment]
Here we go: https://github.com/ptim/wrangler2-repro-534

> ...unless you've triggered local mode via --local or the L hotkey (in which case, I don't think we honour the resizing options, but I could be wrong).

Nope, confident I haven't done either 👍

BTW - unrelated feedback:

- although wrangler.toml has `workers_dev = false`, hitting `B` opened up https://wrangler2-repro-534.my-org-com.workers.dev/ - not sure if that's expected - I don't really use that functionality
- in my work repo, the keys no longer work (eg have to ctrl+c to quit wrangler2). Seemed to work fine in this toy repo, though. Using iterm2 on mac 11.6.2

HTH!

**Comment by ptim** [comment]
BTW, as a related FR, I'd love to receive warning (maybe a response header?) if image resizing is not enabled - this had me super confused for a while :)

#barrier-to-entry

**Comment by threepointone** [comment]
The latest beta has better support for zoned workers, feel free to give that a spin and let us know if it worked? We'll have a look at the image cache issue in a bit.

**Comment by petebacondarwin** [comment]
@ptim - I just upgraded my account to do image resizing and ran your reproduction (https://workers.bacondarwin.com/wrangler2-repro-534?url=https%3A%2F%2Fi.imgur.com%2FtuJY33L.png).
I could not get it to fail in `wrangler dev`. I see the same result for the URL above and for http://localhost:8787/?url=https://i.imgur.com/tuJY33L.png in `wrangler dev`.

Can you please check with the latest alpha?

**Comment by threepointone** [comment]
This was probably fixed in https://github.com/cloudflare/wrangler2/issues/544, since wrangler dev now uses domain entitlements correctly.

**Comment by ptim** [comment]
> Can you please check with the latest alpha?

Thanks - this is working for me now!

**Comment by petebacondarwin** [comment]
Great! Glad you are unblocked. Thanks @threepointone for the fix.
