### ISSUE TITLE
Help users create a workers.dev zone when running `wrangler publish`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#535]
Following on from https://github.com/cloudflare/wrangler2/issues/318

**Comment by rozenmd** [comment]
Could probably use a bit more detail in this issue - by "help" do we mean, providing a link to the dashboard where they can do this, or actually calling the API on their behalf?

**Comment by threepointone** [comment]
I think we may already be showing the link? I think this issue is about actually having an input prompt and calling the api to create the subdomain

**Comment by threepointone** [comment]
Maybe we can/should do this for them during wrangler dev actually, since that's when they'll see the error first
