### ISSUE TITLE
kv:bulk put/delete error

### ISSUE THREAD

**Issue by motiejunas** [cloudflare/wrangler2#547]
When running:
`wrangler kv:bulk delete --namespace-id=REDACTED keys.json`

I get this error:
```
✘ [ERROR] Received a bad response from the API

  could not parse array of keys from request body: 'invalid character 'a' in literal true (expecting
  'r')' [code: 10012]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new
```

Contents of `keys.json`:
```
[
  "target:foo"
]
```

Similar for `kv:bulk put`.

CLI version: `alpha`

**Comment by petebacondarwin** [comment]
Ah, I think I know the problem.
The Cloudflare API is expecting a JSON encoded string which is the array of keys.
But Wrangler is JSON parsing the contents of the file and then passing that directly as the body of the request to the API.
But the result of parsing an array of strings is not the JSON one should expect.

```
> JSON.parse('[\n  "target:foo"\n]\n').toString()
'target:foo'
```

So what the API is receiving is `target:foo` (no square brackets, no double quotes).

```
> JSON.parse(JSON.parse('[\n  "target:foo"\n]\n').toString())
Uncaught SyntaxError: Unexpected token a in JSON at position 1
```

I'll put a fix together.

**Comment by motiejunas** [comment]
@petebacondarwin thanks for the prompt fix. However, there is one side effect. `null` is printed to the terminal once the command is successfully executed.

**Comment by petebacondarwin** [comment]
Oops! Thanks. I'll resolve that, too.

**Comment by petebacondarwin** [comment]
@motiejunas - fixed in https://github.com/cloudflare/wrangler2/pull/551
