### ISSUE TITLE
Check durable_objects support for `dev` and `publish`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#563]
- [x] https://github.com/cloudflare/wrangler2/issues/319
  - [ ] #509
  - [ ] https://github.com/cloudflare/wrangler2/issues/439
  - missing migrations
    - [x] during `wrangler dev` you get
      `Uncaught (in response) TypeError: Invalid Durable Object ID. The ID does not match this Durable Object class`
      which is not very intuitive.
    - [x] during publish you get a more helpful error:
      `10061: Cannot create binding for class DurableObjectExample2 that is not exported by the script`
  - I note that you still have to export a Durable Object class when you are deleting it (via a migration).
  - Migrations are not sent to the CF API when creating a preview worker for `wrangler dev`. So any new DO bindings must have been created via a publish to the main DO (not sure about environments??)
    -  This was fixed on the backend, so it doesn't error now for new classes. That said, we should still send migrations or renamed classes wouldn't be reflected in wrangler dev. Filed https://github.com/cloudflare/wrangler2/issues/736 to track that

**Comment by threepointone** [comment]
#319 is for 2.0, the rest probably aren't. Let's this to 2.1, or at least to "should have"?

**Comment by threepointone** [comment]
Moving this parent task to 2.1, relevant subtasks are being tracked for 2.0.

**Comment by threepointone** [comment]
Closing out this parent task, we may make a fresh one for 2.1
