### ISSUE TITLE
Support cron triggers using preview and dev

### ISSUE THREAD

**Issue by Kynson** [cloudflare/wrangler2#570]
#### Describe the feature

Currently, there is no way to test scheduled jobs, since we can't fire a `scheduled` during development. I suggest adding support of "cron triggers testing" for `wrangler dev` or `wrangler preview`, which speeds up the development and testing.

**Possible methods of triggering a cron job during development**:

- For `wrangler dev`, wrangler creates a special route (path) during development, and developers can trigger a job by sending a request to the route, eg: `GET http://127.0.0.1:8787/__crons/:cronExpression`
- For `wrangler preview`, a `Test Triggers` tab is available for developers to trigger a cron job.

#### Describe the alternatives

The current work around for this issue is to simply deploy the worker to production. 
Or add the code I want to test to the `fetch` event handler, which is really inconvenient: 

```javascript
addEventListener('scheduled', (event) => {
  event.waitUntil(scheduledJob(event))
});
addEventListener('fetch', (event) => {
  event.respondWith(scheduledJob(event))
})
const scheduledJob = (event) => {
  // Job
}
```

Thanks.

**Comment by threepointone** [comment]
Copy pasting from https://github.com/cloudflare/wrangler2/pull/738#issuecomment-1084590138, where we're landing support for local mode soon. 

---

- We've resisted adding miniflare specific features that don't have edge equivalents, but this seems like a good exception to make. 
- That said, let's consider this experimental, and not make too much noise about it for now. This will definitely change in the future. 
- We could probably make this work on the edge too. For module workers, we could wrap the worker in a facade that exposes a route that triggers the `default.scheduled` export. For service workers, we'd have to override `addEventListener` and wrap the fetch handler with our own thing.
