### ISSUE TITLE
kv:bulk only accepts string values

### ISSUE THREAD

**Issue by nr-goby** [cloudflare/wrangler2#571]
Currently the kv:bulk tool will only upload values that are strings. This is different from the KV web back end when you can upload json values. The behaviour seems to come from cloudflare::endpoints::workerskv::write_bulk::KeyValuePair. Would changing the type of KeyValuePair.value from String to [json::JsonValue](https://docs.rs/json/0.12.4/json/enum.JsonValue.html) be sufficient to fix this? I'm not sure if this library is used for more than wrangler or not so it might be cumbersome to make API changes but it is a cloudflare library. 

Or if there is some workaround that I am unaware of, this request could be quickly closed.

**Comment by petebacondarwin** [comment]
I don't understand this request.

A Workers KV namespace is only able to store string values. The REST API and the dashboard, as far as I can tell, also only allow you to store strings. Of course one can JSON encode data and store it in the KV namespace, but this is the responsibility of the application.

Am I missing something?

**Comment by koeninger** [comment]
KV doesn't have to store strings, it can store arbitrary byte arrays or readable streams, https://developers.cloudflare.com/workers/runtime-apis/kv/#writing-key-value-pairs

The REST api will accept "Content-Type: application/json"

**Comment by petebacondarwin** [comment]
Hmm, it appears that the REST API for bulk uploads does not support non-string values.

when I try uploading the following (or any other non-string value)

```json
[
  {
    "key": "test",
    "value": { "str": "a string", "num": 123 }
  }
]
```

```
✘ [ERROR] Received a bad response from the API

  could not parse array of key/value objects from request body: 'could not unmarshal KVPair into
  intermediate struct: 'json: cannot unmarshal object into Go struct field kvPairJSON.value of type
  string'' [code: 10012]
```

**Comment by petebacondarwin** [comment]
So it looks like Wrangler2 supports this but the Edge Worker Config REST API does not.

**Comment by koeninger** [comment]
Ah, sorry, I was responding to the comment about KV being string only and didn't notice this was about the bulk api specifically.  Yeah the bulk api isn't set up to take nested json for each value.  Not sure what @nr-goby 's original ask was given that.

**Comment by petebacondarwin** [comment]
Since the original poster has not actually commented in almost a year, this is definitely not a high priority. 
And it also appears that the request is at odds with how KV works both in Wrangler and internally.
So let's push this back to the 2.1 milestone and decide later if it is something we should implement.
