### ISSUE TITLE
Deploy worker to multiple zones

### ISSUE THREAD

**Issue by essensx** [cloudflare/wrangler2#574]
### 💡 Feature request

An ability to deploy shared worker to multiple zones (multi domain support).

#### Overview and problem statement

We have hundreds of domains, that need to be deployed on the same account. Our implementation is limited by worker limit and inability to re-use the worker in multiple domains.

Problem more clearly stated here: https://community.cloudflare.com/t/wrangler-deploy-to-multiple-zones-same-worker/156426/8

**Comment by petebacondarwin** [comment]
Closing in favour of https://github.com/cloudflare/wrangler2/issues/669 since we have the feature, just haven't documented it.
