### ISSUE TITLE
Feature: configure Worker entrypoint file for publishing

### ISSUE THREAD

**Issue by jsmrcaga** [cloudflare/wrangler2#575]
#### Describe the feature

Summary: Add an `entrypoint` configuration property on `wrangler.toml` which would allow to specify a file to upload to workers deployment.

I have searched both in the docs and the code of wrangler to see if it was possible to specify a custom js file to `publish` with wrangler, and this does not seem to be the case (although it was my first time reading Rust, sorry if I missed something).

> I also made a quick search of the repo's GitHub issues, so if this is a duplicate you can mark it as so (but please point me to the right issue).

This feature would be perfect for custom building cases, where a file must exist somewhere specific. In my case I can just change the build path to `index.js`, but for diverse reasons (custom checks & organization mostly) it was pointing to `./dist/dist.js`

#### Describe the alternatives

RIght now as I see the only possibility is to bundle the project to `./index.js` (which I also only learned by running wrangler publish and getting the error, I saw no mention of it on CloudFlare docs. If they accept Pull Requests I would be glad to make one to add this information)

**Comment by jsmrcaga** [comment]
@threepointone amazing! Thanks a lot for the fast answer, I'll try it today!

**Comment by threepointone** [comment]
Closing this since we've fixed this in wrangler 2, pending docs.

**Comment by jsmrcaga** [comment]
Sure, thanks again @threepointone
