### ISSUE TITLE
disable error reporting interaction on CI

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#585]
non-tty environments won't be able to acknowledge the multiple choice thing. So we need to take a call on how to proceed here. Disable in CI? use an env var? log a warning?

**Comment by petebacondarwin** [comment]
Actually this is already covered here:

https://github.com/cloudflare/wrangler2/blob/7faf0ebec1aa92f64c1a1d0d702d03f4cfa868cd/packages/wrangler/src/reporting.ts#L72

If Wrangler is being used in non-TTY environment then we do not attempt to report the error.

**Comment by threepointone** [comment]
oh damn, missed this. closing, thanks!
