### ISSUE TITLE
support/deprecate wrangler1 style module specifiers 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#586]
In wrangler1, for module format workers, modules could be referenced with just their file name. For example, in a folder structure like this 
```
project
  - index.js
  - something.js
```
Then in `index.js` you could write 
```
import Something from 'something.js';
```
(note the lack of the `./` prefix.)

In wrangler2, we use 'proper' specifiers, so the above would be `'./something.js'`, which is more like existing runtimes. But on existing projects, we don't explicitly call out the error and suggest an alternative, the build simply fails. Our choices here -
- support it with a warning 
- detect the pattern and throw a proper error 
- leave it as is 

This is low pri and not blocker for 2.0 (imo), but logging this issue so we have visibility and can reference this issue if it comes up.

**Comment by Electroid** [comment]
Related to #386. This doesn't seem like something we should support, since it's technically not compliant with how ES modules work. (that is, a bare import becoming relative)

**Comment by threepointone** [comment]
Yeah, in which case we need to actually detect this usage and throw a proper error. If we "support" it then we can have a warning instead of an error and remove it in a subsequent version with the other deprecations.
