### ISSUE TITLE
`config.build` should be inheritable 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#588]
`config.build` should be inheritable/redefinable across environments (which makes sense, because builds/build commands are typically different across environments; different vars, params, etc.). I think wrangler1 supports this. 
 
This is a bit tricky because this might imply that `main`/`rules` should be inheritable. Maybe it should be. But it would be nice if this combination would work:
 
- top level `main`
- top level `build`
- env specific `build` (that outputs to top level `main`)
- and optionally env specific `main`

I spent a few minutes on this but got confused, so I'm filing this issue instead for now. 

- [x] https://github.com/cloudflare/wrangler2/pull/650
- [ ] https://github.com/cloudflare/wrangler2/pull/673
- [x] https://github.com/cloudflare/wrangler2/pull/668

**Comment by petebacondarwin** [comment]
I think making `main` an inheritable field makes sense. Even without a custom build I could imagine having:

```
src/
  index.dev.ts
  index.prod.ts
```

where various env specific constants etc could be defined.

**Comment by petebacondarwin** [comment]
And we have already agreed for `rules` to be inheritable:

https://github.com/cloudflare/wrangler2/blob/6b44822b1742e2b84e6b38c383e78043db922b67/packages/wrangler/src/config/environment.ts#L126-L134

We have deprecated the `rules` that existed in the `upload` field:

https://github.com/cloudflare/wrangler2/blob/6b44822b1742e2b84e6b38c383e78043db922b67/packages/wrangler/src/config/config.ts#L261-L265
