### ISSUE TITLE
Comparison table between 1.0 and 2.0

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#594]
This is a comparison table between wrangler 1.0 and 2.0. It should serve as a living document -- edits welcome -- until we land something like this in our documentation.

## Commands
| Command | 1.x | 2.0 | Notes |
|-|-|-|-|
| `publish` | ✅  | ✅  |
| `dev` | ✅  | ✅  |
| `preview` | ✅  | ❌  | Removed, use `dev` instead. |
| `init` | ✅ | ✅ |
| `generate` | ✅ | ❌ | Removed, use `wrangler init` or `git clone` instead. |
| `build` | ✅  | ❌ | Removed, invoke your own build script instead. |
| `secret` | ✅  | ✅  |
| `route` | ✅  | ❌  | Removed, use `publish` instead. |
| `tail` | ✅  | ✅  |
| `kv` | ✅  | ✅  |
| `r2` | 🚧  | ✅  | Introduced in wrangler 1.19.8.
| `pages` | ❌ | ✅ | 
| `config` | ✅  | ❔ |
| `login` | ✅  | ✅  |
| `logout` | ✅  | ✅  |
| `whoami` | ✅  | ✅  |
| `subdomain` | ✅  | ❔ |
| `report` | ✅  | ❌  | Removed, error reports are made interactively. |

## Configuration
| Property | 1.x | 2.0 | Notes |
|-|-|-|-|
| `type = "webpack"` | ✅ | ❌ | Removed, look at this guide to migrate.  |
| `type = "rust"` | ✅ | ❌ | Removed, use [`workers-rs`](https://github.com/cloudflare/workers-rs) instead. |
| `type = "javascript"` | ✅ | 🚧  | No longer required, can be omitted. |

## Features
| Feature | 1.x | 2.0 | Notes |
|-|-|-|-|
| TypeScript | ❌ | ✅ | You can give wrangler a TypeScript file, and it will automatically transpile it to JavaScript using [`esbuild`](https://github.com/evanw/esbuild) under-the-hood. |
| Local mode | ❌ | ✅ | `wrangler dev --local` will run your Worker on your local machine instead of on our network. This is powered by [Miniflare](https://github.com/cloudflare/miniflare).

**Comment by petebacondarwin** [comment]
Thanks @Electroid!
Let's land this as a markdown file in this repository. Then we can update it as part of PRs.

**Comment by caass** [comment]
We can also mark off routes #542

**Comment by IgorMinar** [comment]
I think we missed support for "environments" in this table. Where does it fit?

**Comment by threepointone** [comment]
This has landed, and we'll expand the docs soon, including details on environments. Closing this issue.
