### ISSUE TITLE
feat: add Sentry tracing of significant events in Wrangler

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#595]
Currently, we send error reports to Sentry when there is an unexpected error in Wrangler (as long as the user has agreed to this).

To help us monitor the usage of Wrangler it would be good if we sent reports to Sentry when a user runs commands.
It is important to consider the content of what is sent, and also how we engage the user's permission.

**Comment by threepointone** [comment]
closing this since we don't have sentry anymore
