### ISSUE TITLE
New environment logic - publish to custom domain fails

### ISSUE THREAD

**Issue by modestaspruckus** [cloudflare/wrangler2#603]
# Version:
0.0.24
# Config
```js
main = "src/index.js"
legacy_env = false
compatibility_date = "2022-03-08"
name = "image-cropper"

[env.dev]
route = "image-cropper-dev.SECRETDOMAINPLACEHOLDER/*"
```

# Command
`CLOUDFLARE_ACCOUNT_ID=*** CLOUDFLARE_API_TOKEN=*** wrangler publish --env dev` throws error.
Environment is created but no route trigger.

# Error
![image](https://user-images.githubusercontent.com/26200870/162792036-0095b6e6-c19f-4d61-bc91-34d0bc5dc840.png)

**Comment by threepointone** [comment]
What was the value of `route` here? Specifically, what kind of patter did you use? Feel free to replace any secret domain name with a placeholder

**Comment by threepointone** [comment]
Also, the screenshot implies you did `--env staging`, is that right?

**Comment by modestaspruckus** [comment]
Hi, sorry for late reply.
My route pattern is `image-cropper.SECRETDOMAINPLACEHOLDER.com/*`

**Comment by modestaspruckus** [comment]
> Also, the screenshot implies you did `--env staging`, is that right?

Yes, but it doesn't matter which env, publish fails with parameter --env and `legacy_env = false` on configuration file.

**Comment by threepointone** [comment]
Might be related to https://github.com/cloudflare/wrangler2/issues/651 we'll have a look early next week. Can you try not using the token and instead going through the login flow?

**Comment by modestaspruckus** [comment]
Thanks for fast reply!
It works perfectly with login flow, thank you.

Nice to hear that you are gonna look into it next week, because we can't use CI/CD pipeline without API token.

**Comment by threepointone** [comment]
Ok this helps, because it means we can probably fix it internally. I'll update this issue when I have news. Thank you for reporting!

**Comment by modestaspruckus** [comment]
Hi @threepointone 
How is the progress, what's ETA for fix?

**Comment by petebacondarwin** [comment]
No news yet. It is not clear to me why using an API token does not work, if it does work via OAuth login.
Is it possible that the API token that you generated does not have quite the right permissions?

**Comment by modestaspruckus** [comment]
https://community.cloudflare.com/t/cloudflare-put-api-to-set-worker-routes-for-specific-env-not-working/333221
Looks like very simillar issue.

**Comment by modestaspruckus** [comment]
Hey, any updates regarding this?

**Comment by threepointone** [comment]
Please note that legacy_env = false is still experimental, and will very likely change behaviour in the future, so I would not recommend using that in production just yet. 

We've identified a problem with api tokens that are scoped to zones, and are looking at it this week (cc @caass).

**Comment by modestaspruckus** [comment]
Hi,
My API token is not scoped to zone.
![image](https://user-images.githubusercontent.com/26200870/167344650-f68992fb-c3a8-4e77-8d7d-1f5b93e2d304.png)

**Comment by modestaspruckus** [comment]
Hello, 
any progress on this? It still throws `10002` error publishing on service environment.

![image](https://user-images.githubusercontent.com/26200870/171334399-a2dbf218-44ad-41d7-ac8e-64dc7ab5be36.png)

**Comment by modestaspruckus** [comment]
Oh, it seems token was automatically passed by from .env file, thats why even with oauth wasn't working.

**Comment by caass** [comment]
@modestaspruckus i'm unable to reproduce this issue as of this morning -- can you reproduce still on your end? If so, please provide a screenshot of the "token summary" of the token you're using. Thank you!

**Comment by modestaspruckus** [comment]
Hey, it works now. Thank you guys !
