### ISSUE TITLE
Legacy env publish fails if [vars] syntax present in toml

### ISSUE THREAD

**Issue by jcw-** [cloudflare/wrangler2#604]
## Version:
```
wrangler@0.0.19
```

## Config
```
[vars]
FOO = "test"
```

## Command
```
> wrangler publish
```

## Error
```
Cannot use 'in' operator to search for 'zone_id' in test
```

**Comment by threepointone** [comment]
We should give a better error message for this, but - did you mean to use `[vars]` here instead of `[env]`?

**Comment by jcw-** [comment]
Oh whoops, yes I did - edited, thanks.

The workaround is to use `legacy_env = true`.

**Comment by threepointone** [comment]
The new device environments are still experimental so I'd caution against using them in production 

But this scenario should still work. I'll investigate this soon, thanks for filing!

**Comment by threepointone** [comment]
I made a sample repo here https://github.com/threepointone/test-wrangler-publish and it appears to work just fine. Could you make a sample repo that demonstrates the problem?

**Comment by jcw-** [comment]
It might need a route to trigger the zone_id parsing. Will try it out shortly.

**Comment by jcw-** [comment]
I tried to reproduce using your project and adding a bunch of stuff from my other project, but I'm not able to repro it. I'll re-submit with a minimal repro project if I encounter it again, closing for now - thanks for looking into this with me!
