### ISSUE TITLE
Zone inference fails for "all requests" pattern from docs

### ISSUE THREAD

**Issue by jcw-** [cloudflare/wrangler2#605]
The zone inference logic introduced in https://github.com/cloudflare/wrangler2/pull/545 fails to infer the zone from the example [from the docs](https://developers.cloudflare.com/workers/platform/routes/#matching-behavior) for "matching all routes":

> A pattern to match all requests looks like this:
> ```
>*example.com/*
>```

## Version
```
wrangler@0.0.19
```

## Command
```
wrangler publish
```

## Error
```
✘ [ERROR] Received a bad response from the API

  workers.api.error.zone_not_specified - Can't infer zone from route, please specify zone for
  "*example.com/*" [code: 10082]
```

## Workaround

I was unable to make this work by specifying `zone_id`. This worked for me though...

Use the following config:
```
routes = ["*.example.com/*", "example.com/*"]
```

**Comment by threepointone** [comment]
Good catch, I missed checking for patterns like this. I'll fix it. Thank you very much for filing this!

**Comment by threepointone** [comment]
There are 2 workarounds here - 
- Use the patterns as you showed 
- add an optional `zone_id` like so: `routes = [{pattern = "*example.com/*", zone_id ="<the zone id>"}]` (we recently landed support for this.) 
We should document this better, which we'll get to very soon.

Closing this issue, thanks for filing it!
