### ISSUE TITLE
Fix network tab in DevTools

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#63]
The runtime supports the Network tab, but for some reason, it does not work. For instance, it works on https://cloudflareworkers.com

**Comment by lrapoport-cf** [comment]
@Electroid is this still an issue? if so, can you clarify what is not working and add repro steps?

**Comment by penalosa** [comment]
Closing for now, since this will be fixed with the Devtools convergence work happening this quarter (tracked internally)
