### ISSUE TITLE
🐛 BUG: Miniflare configuration 

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#643]
### What version of `Wrangler` are you using?

0.0.19

### What operating system are you using?

Mac

### Describe the Bug

When running Wrangler 2 on a old Workers project that used Wrangler 1, it will prompt the user with fields that are deprecated i.e. `build_upload` 

In that deprecation message which gives suggestions/fixes, `miniflare`  in TOML will throw an error after those suggestions/fixes. There should be a message for `miniflare` deprecation in TOML and suggest removing from TOML, then use `wrangler dev --local`

**Comment by threepointone** [comment]
I think the solution here is to add these fields to miniflare too.

**Comment by threepointone** [comment]
Or do you mean having the "miniflare" field itself? https://github.com/cloudflare/wrangler2/pull/627 should've fixed that

**Comment by threepointone** [comment]
A bigger task is all the module system work (and other features) that'll have to be replicated there, and getting more miniflare features into w2 (like the test environment, dotenv, and of course a broader story about mounts/multiple workers). Might have to wait till 2.1 but we should start planning soon.
