### ISSUE TITLE
🐛 BUG: Routes do not work with `--env`

### ISSUE THREAD

**Issue by skirsten** [cloudflare/wrangler2#652]
### What version of `Wrangler` are you using?

0.0.0-21ee93e

### What operating system are you using?

Linux

### Describe the Bug

In
https://github.com/cloudflare/wrangler2/blob/c75cfb83df4c98d6f678535439483948ce9fff5b/packages/wrangler/src/publish.ts#L208-L212

when `notProd` is true and routes are specified, the request to
```
PUT /accounts/${accountId}/workers/services/${scriptName}/environments/${envName}/routes
```
https://github.com/cloudflare/wrangler2/blob/c75cfb83df4c98d6f678535439483948ce9fff5b/packages/wrangler/src/publish.ts#L273

fails with
```
✘ [ERROR] Received a bad response from the API

  workers.api.error.internal_server [code: 10002]
```

I could not find any api documentation for the "environment / env routes" to check if its a issue with the payload.

**Comment by threepointone** [comment]
Have you set legacy_env to be false? The newer service environments are experimental at the moment. (But this issue still looks like a bug, thanks for filing!)

**Comment by skirsten** [comment]
Yes, `legacy_env` is false.

**Comment by threepointone** [comment]
Could you check if this is still a problem with the latest version? If so, can you share your wrangler.toml? 
Of note, `legacy_env = false` is still not _supported_, and we expect it's behaviour to change.

**Comment by skirsten** [comment]
It still does not work with `legacy_env = false` (on latest alpha) as far as I can tell:

```
✘ [ERROR] Received a bad response from the API

  workers.api.error.internal_server [code: 10002]
```

wrangler.toml
```toml
name = "..."
main = "..."
compatibility_date = "2022-04-16"
legacy_env = false

[env.main]
# ...
workers_dev = false
routes = ["https://example.com/*"]
```

I understand that `legacy_env = false` is still in development. I can manually configure this on the dashboard so its not critical.

**Comment by threepointone** [comment]
Are you using an api token that's scoped to zone to deploy?

**Comment by skirsten** [comment]
No, I removed the token restriction because it triggered this (different) bug: https://github.com/cloudflare/wrangler2/issues/651

![image](https://user-images.githubusercontent.com/1972314/163697307-1421ff6f-6500-43c3-b518-5e32893e95c8.png)

**Comment by modestaspruckus** [comment]
Related https://github.com/cloudflare/wrangler2/issues/603

**Comment by caass** [comment]
Hey, I'm looking into this and having trouble reproducing the issue. Can you provide the steps you took when you encountered this issue?

**Comment by skirsten** [comment]
Hi, I just checked this again and I also cannot reproduce it anymore.
It seems to be fixed now. Thanks :smiley:
