### ISSUE TITLE
We should deprecate being able to pass every config value as `CF_` env vars (which is possible in wrangler 1!!)

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#657]

**Comment by threepointone** [comment]
This one might just be a case of ignoring it till (and if!) people complain and we point them to config docs.

**Comment by threepointone** [comment]
no flag, and they shouldn't be able to silence the warning either. 
thing is, this is also undocumented behaviour. maybe we shouldn't even acknowledge its existence.

**Comment by threepointone** [comment]
yeah, maaaybe we shouldn't even do this.

**Comment by caass** [comment]
mm ok. Feel free to close the issue if you've made up your mind
