### ISSUE TITLE
All the binding names should be distinct, no repeats (since they'll all be hanging off the same `env` object)

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#658]
We should verify that users don't use the same binding names for 
- Durable Objects
- Service Bindings
- KV Namespaces
- R2 Buckets

**Comment by caass** [comment]
Is there a list of the properties whose bindings should be checked for uniqueness? Off the top of my head, like
- Durable Objects
- Service Bindings
- Environment variables

But I feel like there's more that i'm missing

**Comment by threepointone** [comment]
R2
Also secrets, but there's no good way to validate against that without a network call

**Comment by petebacondarwin** [comment]
Something that came up yesterday in our attempt to upgrade one of the Pages Workers to W2 was the approach of setting a var binding in wrangler.toml but then overriding it with a secret in the dashboard. I don't know how prevalent this practice is, but I think we should not attempt to ensure uniqueness between vars and secrets.

**Comment by caass** [comment]
That makes sense. What about unsafe bindings as well?

**Comment by caass** [comment]
And `wasm_modules` and `text_blobs`?

**Comment by caass** [comment]
> Something that came up yesterday in our attempt to upgrade one of the Pages Workers to W2 was the approach of setting a var binding in wrangler.toml but then overriding it with a secret in the dashboard. I don't know how prevalent this practice is, but I think we should not attempt to ensure uniqueness between vars and secrets.

We could do a warning, maybe, instead of a full error
