### ISSUE TITLE
generate a compiled version of miniflare

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#66]
We currently install miniflare as a dependency. However, it makes the install much slower, and bloats up the bundle a little bigger than it has to be. Instead, we should generate a bundled version of it (much like we already do for wrangler) and ship that. This would make installs a lot faster, and the dependency tree much smaller.

**Comment by cameron-robey** [comment]
Going to wait until open source runtime implemented
https://github.com/cloudflare/wrangler2/issues/1637

**Comment by penalosa** [comment]
Closing this for now, as local development is undergoing changes related to the open-sourcing of the Workers runtime. We'll revisit this in the future, and consider whether this is a direction we want to go in for Miniflare v3 (especially considering how required `workerd` as a dependency will affect the bundle size)
