### ISSUE TITLE
🐛 BUG: bulk put: could not base64 decode value for key

### ISSUE THREAD

**Issue by fcomrqz** [cloudflare/wrangler2#666]
### What version of `Wrangler` are you using?

0.0.22

### What operating system are you using?

Mac

### Describe the Bug

Logs show propers readings, skippings and uploadings.

Then start to expiring unused assets and after do a few throw next error:

✘ [ERROR] Received a bad response from the API

  bulk put: 'could not base64 decode value for key: "dist/client/assets/404.cdfafd35.2ee828c209.js",
  err: 'illegal base64 data at input byte 6'' [code: 10012]

I suspect is related with your new feature for expire unused assets  #587.

Upload works properly with a clean new KV Store.

**Comment by petebacondarwin** [comment]
What is the command you are running? `wrangler kv:bulk put` or `wrangler publish` (with assets)?
Can you provide more information about the specific scenario?
This may be relevant since Wrangler 2 has the same problem: https://github.com/cloudflare/wrangler/issues/2224#issuecomment-1075010201

**Comment by fcomrqz** [comment]
I am running `wrangler publish` and I have `site = { bucket = "./dist/client" }` in my `wrangler.toml`.

**Comment by threepointone** [comment]
I'll send a PR that removes the site expiry logic.

**Comment by petebacondarwin** [comment]
OK, so this could well be the same problem. We should have a fix and a release later today or tomorrow

**Comment by fcomrqz** [comment]
Maybe this video has a hint about how to fix this. 😉 
https://www.youtube.com/watch?v=WxnN05vOuSM

**Comment by threepointone** [comment]
😈

**Comment by threepointone** [comment]
would you like to try with a prerelease version (https://github.com/cloudflare/wrangler2/pull/667#issuecomment-1075060013) and see if it fixes your problem?

**Comment by fcomrqz** [comment]
@threepointone I tried your prerelease and is working. Thank you for your quick response.

**Comment by petebacondarwin** [comment]
Rock on!
