### ISSUE TITLE
document how to deploy to multiple zones

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#669]
This was a feature request in Wrangler 1, which is now supported in Wrangler 2.
We just need to add documentation around it.
See https://github.com/cloudflare/wrangler2/issues/574

**Comment by ptim** [comment]
FYI, I couldn't find the actual documentation for this (it got raised in discord), but found this related mention:

> The `zone_id` field is deprecated, and will be removed in a future release. It is now inferred from `route`/`routes`, and optionally from dev.host when using wrangler dev. This also makes it simpler to deploy a single Worker to multiple domains.

https://github.com/cloudflare/wrangler2/blob/main/docs/deprecations.md
