### ISSUE TITLE
🐛 BUG: Environment variables have undefined values when passed through with --binding

### ISSUE THREAD

**Issue by AF111** [cloudflare/wrangler2#674]
### What version of `Wrangler` are you using?

0.0.22

### What operating system are you using?

Windows 11 with WSL 2

### Describe the Bug

I'm trying to load environment variables using the ``--binding`` flag, It worked when I 
was using version 0.0.19 but when I tried to re-run the same command again today with the latest version of wrangler2 v0.0.22
all the environment variables get added but the values are all ``undefined``

![image](https://user-images.githubusercontent.com/30418824/159572500-94b313e7-d371-421f-becd-e6d4f068ecfc.png)

And here's the repo to reproduce.
https://github.com/AF111/wrangler2-env

**Comment by JacobMGEvans** [comment]
related issue: #648
