### ISSUE TITLE
Deprecation/Migration messaging 

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#681]
During a migration of a fairly complex project there was a large amount of messaging to read through that was all the same color with no distinction of importance or priority. 

This can provide priority implications, colorizing or emoji: 
1. High/Breaking (🚨, 🚫, 🔴 , or red text would indicate high priority).
2. Deprecation/non-blocking should fix (📜, 🧹 , ⚒️ , 🛠️, 🟠   or orange/burnt orange text)  
3. Warning/behavior may be needed for old projects, but not Wrangler2 convention/best practice (⚠️, 🟡, 🦺 or dark/mild yellow text)

**Comment by lauragift21** [comment]
I like the idea of showing emojis or highlighting important information with colors. There's been an instance where it took a few looking over the output to understand what it is. 

An example from a recent migration:

```sh
 ⛅️ wrangler 0.0.23
--------------------
Processing wrangler.toml configuration:
  - DEPRECATION: "type":
    DO NOT USE THIS. Most common features now work out of the box with wrangler, including modules, jsx, typescript, etc. If you need anything more, use a custom build.
  - DEPRECATION: "zone_id":
    This is unnecessary since we can deduce this from routes directly.
  - Unexpected fields found in site field: "entry-point"
Processing wrangler.toml configuration:
  - DEPRECATION: "site.entry-point":
    The `site.entry-point` config field is no longer used.
    The entry-point should be specified via the command line or the `main` config field.
   ```

In order to improve the DX going through these messages I think we can highly benefit from making it clear and intuitive.

**Comment by JacobMGEvans** [comment]
@petebacondarwin made a huge leap in message layout, formatting and communication with #848 

Closing this issue, if future improvements are to be made a new issue can be made.
