### ISSUE TITLE
🐛 BUG: Pages subcommand `--help`

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#686]
### What version of `Wrangler` are you using?

0.0.23

### What operating system are you using?

Mac

### Describe the Bug
`wrangler pages --help` or the help message default `wrangler pages` shows the help message for 
`wrangler pages dev` 

Currently commands with multiple subcommands will list their subcommands in the default help message. 
Example:
```shell
wrangler secret

🤫 Generate a secret that can be referenced in the worker script

Commands:
  wrangler secret put <key>     Create or update a secret variable for a script
  wrangler secret delete <key>  Delete a secret variable from a script
  wrangler secret list          List all secrets for a script

Flags:
  -c, --config      Path to .toml configuration file  [string]
  -h, --help        Show help  [boolean]
  -v, --version     Show version number  [boolean]
      --legacy-env  Use legacy environments  [boolean]
```

**Comment by JacobMGEvans** [comment]
This is possibly a Yargs default behavior, when there is only one subcommand available.

**Comment by GregBrimble** [comment]
Nope, confirmed as a bug now that we've got additional commands. I'll take a look. Thanks for catching!
