### ISSUE TITLE
🐛 BUG: wrangler publishes to workers.dev if there's no top level route, but does have one in an environment

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#690]
### What version of `Wrangler` are you using?

0.0.23

### What operating system are you using?

Mac

### Describe the Bug

Given this wrangler.toml 
```
name = "worker-name"
main = "src/index.js"

[env.production]
routes = ["https://some=domain.com/*"]
```
and run the command `wrangler publish --env production`, wrangler will attempt to publish to both worker-name.threepointone.workers.dev and https://some=domain.com/. 

I investigated it a little, and noticed that this section https://github.com/cloudflare/wrangler2/blob/82ec7c2c65b1515cf081420499091cd0878fed8d/packages/wrangler/src/config/validation.ts#L101-L105 marks `workers_dev` as `true` (since there aren't any routes there), and then passes `topLevelEnv` to the next call at https://github.com/cloudflare/wrangler2/blob/82ec7c2c65b1515cf081420499091cd0878fed8d/packages/wrangler/src/config/validation.ts#L114-L121 which assumes that the top level value doesn't get overridden by the `defaultValue` passed at https://github.com/cloudflare/wrangler2/blob/82ec7c2c65b1515cf081420499091cd0878fed8d/packages/wrangler/src/config/validation.ts#L531. I'm not sure what a fix for this is, hence filing the issue. @petebacondarwin do you have any ideas?

--- 

Also question, is there a scenario where folks will want to publish to both workers.dev and a route? I ask this, because I'm not actually sure how to publish to a plain route on Workers 🤪. I just setup a CNAME to proxy from the workers.dev deploy to my domain's route.
![image](https://user-images.githubusercontent.com/18808/160061290-db0d9a90-8403-4fd2-826e-6ec8e586bb29.png)

**Comment by threepointone** [comment]
Ok, we're already setup ti publish to both if workers_dev = true and if routes are defined, so I guess there's no cod changes to make for the latter scenario.

**Comment by petebacondarwin** [comment]
Let's make `workers_dev` default to `undefined` in the config, and then move the logic for the "actual" default into the publish command.

**Comment by threepointone** [comment]
Ok good shout. I'll send a PR.
