### ISSUE TITLE
🐛 BUG: `wrangler init` should not turn on skipLibCheck by default

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/wrangler2#704]
### What version of `Wrangler` are you using?

0.0.0-52ea60f

### What operating system are you using?

Mac

### Describe the Bug

wrangler init generates a project with tsconfig that has `skipLibCheck` turned on:
```
"skipLibCheck": true /* Skip type checking all .d.ts files. */
```

This is dangerous for reasons discussed here: https://github.com/angular/angular-cli/issues/16696#issuecomment-579450895

Can we please turn this off?

**Comment by threepointone** [comment]
I don't believe this is true anymore, the typescript default is now to turn it on. https://twitter.com/orta/status/1260583041740812288?s=21 iiuc, It doesn't check _non referenced `@types` d.ts files_, which is different.

**Comment by threepointone** [comment]
(The tsconfig we now generate is from `tsc --init`)

**Comment by threepointone** [comment]
Closing this since it's the recommend configuration now, and can be easily edited when needed.

**Comment by IgorMinar** [comment]
Interesting! Today I learned something new.

I agree that we should stick with the tsc defaults. Thanks for pointing me to the tweet.

I am however shocked that tsc changed this recommendation (they have not changed the default though), as this will make writing `.d.ts` files within your project very error-prone.
