### ISSUE TITLE
🐛 BUG: insufficient command line param checking -`wrangler tail --pretty` doesn't fail

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/wrangler2#706]
### What version of `Wrangler` are you using?

0.0.0-52ea60f

### What operating system are you using?

mac

### Describe the Bug

I accidentally ran the following:

```sh
$ wrangler tail --pretty
```

and to my surprise it behave in the same way as `wrangler tail`. I'd expect the command to fail because `--pretty` is no a valid flag. Could we tighten up the param checks and error when in valid flag is passed in?

This seems to be a wrangler-wide issue because other commands don't mind bogus flags either:

```sh
$ wrangler whoami --pretty
 ⛅️ wrangler 0.0.0-52ea60f 
---------------------------
Getting User settings...
👋 You are logged in with an OAuth Token, associated with the email '...'!
```

**Comment by threepointone** [comment]
Missed this, I'll fix it

**Comment by threepointone** [comment]
Fix in https://github.com/cloudflare/wrangler2/pull/708
