### ISSUE TITLE
🐛 BUG: crypto.subtle.sign works locally but not in deployment

### ISSUE THREAD

**Issue by ardislu** [cloudflare/wrangler2#710]
### What version of `Wrangler` are you using?

0.0.23

### What operating system are you using?

Windows

### Describe the Bug

1. Clone the example repo: https://github.com/ardislu/cloudflare-pages-env-test
2. Run: `npx wrangler pages dev .`
3. Visit `http://localhost:8788/` and see that the local site is working as expected, returning the signed message `G3LiJGjMWZJ2gh9xMMUt-mrXDEXdc5w_eGpaqM4cTLQ0k3OF73rWJqkc99yuzlKwzluXNjxG7O5jxBxEqS7vqw`
4. Deploy the repo to a Cloudflare Pages site. I've deployed my example repo to: https://cloudflare-pages-env-test.pages.dev/
5. The deployed Worker (`/api`) returns an error instead of the expected signed message

**Comment by Electroid** [comment]
This is possibly an inconsistency with the Node.js polyfill in Miniflare.

- Workers: `Failed to execute 'sign' on 'SubtleCrypto': parameter 3 is not of type 'Array'.`
- Deno:  `Failed to execute 'sign' on 'SubtleCrypto': Argument 3 is not an ArrayBuffer or a view on one`

- Node.js: works

**Comment by ardislu** [comment]
Thank you! I think you're exactly right.

I updated from:
```
crypto.subtle.sign('RSASSA-PKCS1-V1_5', signingKey, message)
```
to:
```
crypto.subtle.sign('RSASSA-PKCS1-V1_5', signingKey, new TextEncoder().encode(message))
```
and now both the local and the deployed sites are showing the signed message as desired.

I also read [MDN](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign) more closely and saw the `data` parameter should indeed only accept `ArrayBuffer` or `ArrayBufferView`, not `string`:
> `data` is an [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) or [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView) object containing the data to be signed.

**Comment by threepointone** [comment]
Closing since there's not much we can do here, probably deserves an issue on the miniflare repo.
