### ISSUE TITLE
🐛 BUG: adding environment variables locally not work

### ISSUE THREAD

**Issue by supachaidev** [cloudflare/wrangler2#714]
### What version of `Wrangler` are you using?

0.0.23

### What operating system are you using?

Mac

### Describe the Bug

Using `-b ENV_NAME=value` with `wrangler pages dev` to bind an environment variable locally does not work like before.

It binds the `ENV_NAME` with `undefined` instead of `value`.

The 0.0.19 version works well with Remix (CF Pages template).

**Comment by threepointone** [comment]
Could you try with `wrangler@alpha`? This was fixed in https://github.com/cloudflare/wrangler2/pull/684 but we haven't done a beta release yet, which we'll do soon this coming week.

**Comment by threepointone** [comment]
We just did a beta release, so I'm closing this issue. But please let us know if it doesn't work as expected. Thank you!
