### ISSUE TITLE
bug: Leaving wrangler dev running for an extended period of time results in terminal spam

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#730]
Reported internally, but I've seen this too. I think it appears on the inspector websocket.

**Comment by petebacondarwin** [comment]
It would be good to see what messages are being spammed to the terminal in order to identify the cause.
And how long is an extended period? One minute, an hour, a day?

**Comment by petebacondarwin** [comment]
I left `wrangler dev` running for over 30 mins and saw no messages. So closing for now, unless someone can provide a reproduction.
