### ISSUE TITLE
Feature: Schedule tasks from http://localhost:8787/cdn-cgi/mf/scheduled

### ISSUE THREAD

**Issue by mattbdc** [cloudflare/wrangler2#737]
### What version of `Wrangler` are you using?

0.0.24

### What operating system are you using?

Linux

### Describe the Bug

Would be nice to have support for manually triggering crontab tasks via a curl get request, similar to how wrangler1 (iirc) and miniflare support

https://miniflare.dev/core/scheduled

**Comment by threepointone** [comment]
Admittedly we haven't put much work into the dx for scheduled workers in wrangler2, but we definitely want to do this soon. Thanks for filing this issue!

**Comment by petebacondarwin** [comment]
Added support for this in local dev mode via #738

**Comment by Electroid** [comment]
@threepointone We don't have an API to trigger a cron trigger preview using `wrangler dev`. We'll need to engage with Runtime to conjure up something. wrangler1 can't preview a cron trigger.

**Comment by threepointone** [comment]
Dropped some notes here for how we could potentially support it without runtime support https://github.com/cloudflare/wrangler2/issues/570#issuecomment-1084654222

**Comment by mattbdc** [comment]
> @mattbdc could you share how wrangler1 does this? I'm actually not familiar with it and haven't heard so.

Sorry I was probably getting confused - exhausted - as I had looked at Wrangler1, Wranger2 via wrlanger@beta with a lower semver than Wranger1, Miniflare ootb, Miniflare with Wrangler 1 config, Miniflare breaking with Wrangler2 config....  And no solid story on what to use and when. Flashbacks to 1password versioning during the transition to unify everything, or finding the right google sku for chat 🤣 

Thanks for the addition, I hope it all comes together
