### ISSUE TITLE
🐛 BUG: Functions Routing returns 404

### ISSUE THREAD

**Issue by motiejunas** [cloudflare/wrangler2#760]
### What version of `Wrangler` are you using?

latest

### What operating system are you using?

mac

### Describe the Bug

Hello,

There is no way to report CF bug on a free plan. Just want to let you know, that a few hours back Functions Routing (https://developers.cloudflare.com/pages/platform/functions/#functions-routing) stopped working and routed functions now returns 404 HTTP code. I believe this is a critical bug on CF side, because the last time I deployed my personal project was a week ago. Since then everything was working fine till today.

**Comment by motiejunas** [comment]
Deployed routes:
```
{
  "routes": {
    "GET /ping": {
      "module": [
        "ping.js:onRequestGet"
      ]
    },
    "POST /collect": {
      "module": [
        "collect.js:onRequestPost"
      ]
    },
    "POST /perf": {
      "module": [
        "perf.js:onRequestPost"
      ]
    }
  },
  "baseURL": "/"
}
```

404 page (defined in public/404.html) is returned when going to `/ping`.

**Comment by GregBrimble** [comment]
I just successfully deployed Functions on a project of mine, and the routing seems to be working as expected. Can you please provide example reproduction steps for this?

**Comment by motiejunas** [comment]
Interesting. Could you please tell me what happens when "Functions requests today" (known limitation of 100k/daily) limit is reached? Is 404 status code returned for function routes?

**Comment by GregBrimble** [comment]
Ah, yes, Functions be disabled until midnight UTC (when your daily limits reset). The static assets of your project will continue to be served as normal.

**Comment by motiejunas** [comment]
> Ah, yes, Functions be disabled until midnight UTC (when your daily limits reset). The static assets of your project will continue to be served as normal.

Okay let's see if that's the issue. It is interesting that the "Functions requests today" counter in the dashboard stuck at 79,109 / 100,000.

**Comment by motiejunas** [comment]
@GregBrimble okay, so after the limits reset everything works fine again. Anyways, could anyone create a ticket internally for this? 429 HTTP status code should be returned instead of 404. Super confusing, this could save me hours...

Moreover, "Functions requests today" counter in the dashboard is not working properly in this case.
