### ISSUE TITLE
🐛 BUG: [ERROR] Transforming const to the configured target environment ("es5") is not supported yet

### ISSUE THREAD

**Issue by santsys** [cloudflare/wrangler2#764]
### What version of `Wrangler` are you using?

Unknown

### What operating system are you using?

Cloudflare Pages

### Describe the Bug

Started getting the below error in Cloudflare Pages today... (same code would build and deploy 2 days ago).

```
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
[ERROR] Transforming const to the configured target environment ("es5") is not supported yet
```

This seems like something that may block most Cloudflare Pages builds that are using functions.

**Comment by 0x8a** [comment]
Also started getting the same error on Pages this afternoon. Was seeing the same error locally since [wrangler@0.0.19](https://github.com/cloudflare/wrangler2/releases/tag/wrangler%400.0.19), so it looks like Pages started using a more recent version of Wrangler internally.

Adding a `functions/tsconfig.json` file with following fixed builds for us:

```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "lib": ["ES2020"],
    "types": ["@cloudflare/workers-types"]
  }
}
```

**Comment by threepointone** [comment]
Thanks for reporting this, we'll look at it soon! 

// @GregBrimble

**Comment by GregBrimble** [comment]
Sounds like we're accidentally picking up a `tsconfig.json` that you have for your front-end code. Sorry about that!

I'll file an internal issue to build Functions with our fixed TypeScript config.

**Comment by santsys** [comment]
> Sounds like we're accidentally picking up a `tsconfig.json` that you have for your front-end code. Sorry about that!
> 
> I'll file an internal issue to build Functions with our fixed TypeScript config.

Having the ability to define some custom config for functions may be a good feature to have, but it should probably be isolated to the functions directory (or, require an override config in the functions folder if there are breaking settings in the root config).

**Comment by GregBrimble** [comment]
@santsys , you've changed my mind. @0x8a 's approach of adding a `tsconfig.json` to the `functions` folder is the 'correct' way, so we'll document that better. But if a tsconfig isn't present, we'll continue to look up as `tsc` and `esbuild` do today.
