### ISSUE TITLE
Script startup timed out. [code: 10021] on `wrangler publish`

### ISSUE THREAD

**Issue by konsumer** [cloudflare/wrangler2#771]
I am using `@alpha` (`0.0.0-7d4ea43`, which seems to be the only config-version working with remix/miniflare, in my local testing.)

Everything builds and runs locally, and was working up until recently, which is confusing because I locked the npm version (to prevent auto-updates which were breaking things in other ways.)

**package.json**
```json
{
"private": true,
  "sideEffects": false,
  "scripts": {
    "prebuild": "node node_modules/remix-esbuild-override/dist/bin/index.js",
    "build": "remix build",
    "start:frontend": "remix watch",
    "start:backend": "NODE_OPTIONS='--experimental-vm-modules --no-warnings' node tools/dev.mjs",
    "start": "npm run build && run-p start:*",
    "postinstall": "remix setup cloudflare-workers",
    "predeploy": "rm -rf build public/build && npm run build",
    "deploy": "wrangler publish build/index.js"
  }
}
```

**tools/dev.mjs**
This is a local miniflare thing, and is working and I think unrelated to deploy:

```js
// this is the dev-server, which uses local KV and remote DO

import { Miniflare } from "miniflare"
import { CrossKV, CrossDO } from 'cross-cf'
import fetch from 'cross-fetch'

global.fetch = fetch

const globals = {
  // ... DO and KV setup work on local
}

const mf = new Miniflare({
  envPath: true,
  packagePath: true,
  wranglerConfigPath: false,
  scriptPath: 'build/index.js',
  buildCommand: "npm run build",
  globals,
  sitePath: "./public",
  name: 'XXX',
  port: 3000,
  watch: true,
  liveReload: true,
  sourceMap: true
})

await mf.startServer()
console.log("Listening on http://localhost:3000")
```

**wrangler.toml**
```toml
name = ""

compatibility_date = "2022-01-31"
account_id = "XXX"

[build]
command = "npm run build"

[site]
bucket = "./public"

[[kv_namespaces]]
# ...

[[durable_objects.bindings]]
# ...
```

It builds & uploads site ok, but at end it says this:

```
✘ [ERROR] Received a bad response from the API

  Script startup timed out.
   [code: 10021]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new
```
It returns really fast (doesn't hit 5 minute limit)

**Comment by threepointone** [comment]
Oh hmm, that's weird. I think that usually means there's an infinite loop when starting up, but I can't say. Lemme ask internally.

**Comment by MatousKundrik** [comment]
I'm seeing the same thing on my end with a similar remix+cloudflare-workers application. It works when running under miniflare 2.4.0 but fails to publish to Cloudflare where the script times out after ~5s.

```
Error: Something went wrong with the request to Cloudflare...
Script startup timed out.
 [API code: 10021]
```

Any updates @threepointone 👀

**Comment by MatousKundrik** [comment]
> Could y'all share your account ids and the workers' names? I'll pass it on to the backend folks

Since the worker is never successfully uploaded it isn't present in my cloudflare dashboard. My account id is : `3c922ba2f38f303dbab57cfac4211cec` if that's still of any help 😁

**Comment by MatousKundrik** [comment]
Bumping remix to `1.4.0` and setting `serverBuildTarget: "cloudflare-workers"` inside `remix.config.js` seems to have fixed this for me 👍

**Comment by konsumer** [comment]
@threepointone `cd9c418c2f482d1d4b6616d040bd48e5` is ID, but I also can't publish, so it's not in dash.

I am troubleshooting other issues (with not being able to override esbuid config in remix) so I can't currently build at all, which is a whole other thing. Once I get this building, I will try out your suggestion, @MatousKundrik thanks!

**Comment by threepointone** [comment]
The solution here is as @MatousKundrik describes, looks like there was a bug. I'll close this for now.
