### ISSUE TITLE
`local-mode-tests` blows up the CI logs with `waiting for connection...` on windows

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#776]
[Here's an example](https://github.com/cloudflare/wrangler2/runs/5892640735?check_suite_focus=true#step:7:803).

This makes it really annoying to debug CI failures since you have to scroll through, no exaggeration, seventeen thousand lines of `waiting for connection...`.

This might have to do with my own tests (#759) not exiting properly, so if it gets fixed when i patch my stuff i'll close this

**Comment by threepointone** [comment]
Can this be closed? Looks like it doesn't cause that spam anymore?

**Comment by petebacondarwin** [comment]
Closing. Please re-open @caass if it is still a problem.

**Comment by threepointone** [comment]
This is still happening, reopening. It's not related to the webpack stuff since we disabled those tests.

**Comment by threepointone** [comment]
assigning to myself. might just disable those tests on windows.
