### ISSUE TITLE
Support PNPM?

### ISSUE THREAD

**Issue by michaelmerrill** [cloudflare/wrangler2#777]
Any chance wrangler2 can support PNPM? It's much faster and has better support for workspaces which pairs nicely with workers using a micro-service approach. Currently, `npx wrangler@beta init` fails as it defaults to npm.

**Comment by threepointone** [comment]
Yeah, I think we can/should do this. Our yarn integration could also use some work. Thanks for filing this, it had slipped my mind!

**Comment by michaelmerrill** [comment]
I'm interested in working on this. Is [this file](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/package-manager.ts) the only one that needs updating?

One approach could be updating this file to support `hasPnpmLock`, but I don't think this logic currently supports monorepos as the lock file will often be in a parent directory.

Another approach could be to allow passing in the package manager as a flag and setting `npm` as the default using yargs. This file could be simplified to do a check to see if the system `supports('<package_manager>')` and a conditional to use the right package manager object (eg. `YarnPackageManager`, `PnpmPackageManager`).

What do you think @threepointone ?

**Comment by threepointone** [comment]
There's some nuance here we might want to revisit. For example, if you use `pnpm dlx wrangler init <name>` we want to make sure it sets up a pnpm project. (This is separate from looking for the lockfile, which won't exist when the above command is called.). yarn doesn't have a direct executor like npx and pnpm dlx, so maybe that's ok. 

I don't think we should add any new flags, we should be able to detect what's executing the command and take a call from there.
