### ISSUE TITLE
TypeError while launching Wrangler without file extension, ie "./index"

### ISSUE THREAD

**Issue by jgentes** [cloudflare/wrangler2#78]
While using `wrangler dev ./index` I get
```
TypeError: Cannot read properties of undefined (reading '0')
    at null.build (/home/jgentes/workers/wrangler2/packages/wrangler/src/dev.tsx:411:15)
```

This is caused due to the `entry` value being verbatim what was used as a command line argument, ie. `./index`, whereas the `entryPoint` value in `result.metafile.outputs` has the extension added to the file, ie `./index.js`.

I'm going to submit a PR that uses what esBuild recognizes as the input value in `result.metafile.inputs` instead of the `entry` value:

```
const chunks = Object.entries(result.metafile.outputs).find(
        ([_path, { entryPoint }]) =>
          entryPoint === Object.keys(result.metafile.inputs)[0]
      ) // assumedly only one entry point
```

**Comment by jgentes** [comment]
Fixed in https://github.com/cloudflare/wrangler2/pull/196

**Comment by threepointone** [comment]
reopening this since it got reverted in https://github.com/cloudflare/wrangler2/pull/262

**Comment by threepointone** [comment]
Fixed in https://github.com/cloudflare/wrangler2/pull/258
