### ISSUE TITLE
🐛 BUG: Package jest-environment-wrangler is empty

### ISSUE THREAD

**Issue by eugene1g** [cloudflare/wrangler2#781]
### What version of `Wrangler` are you using?

0.0.25

### What operating system are you using?

Mac

### Describe the Bug

The recently added `jest-environment-wrangler` package is [missing](https://unpkg.com/browse/jest-environment-wrangler@0.0.24/) the `dist/` folder from NPM in both `1.0.0` and `0.0.24`, so Jest fails with 

```
● Validation Error:

  Test environment wrangler cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

/cc @threepointone

**Comment by threepointone** [comment]
Good catch, thanks for filing! I'll fix this, but please note that it's still not usable (it doesn't do compilation, etc at the moment)

Also you don't have to cc me, I get notifications for everything on this repo already :)

**Comment by threepointone** [comment]
Moving this to 2.1, just as well that it doesn't work right now.

**Comment by threepointone** [comment]
Going to close this, we'll probably make a new umbrella task for a proper testing story.
