### ISSUE TITLE
feat: implement `minify` config in wrangler.toml

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#785]
I've now seen multiple projects that reach for custom builds because they need smaller bundles (exacerbated by our 1 mb limit). We should just leverage esbuild's minify here.

**Comment by threepointone** [comment]
A complication here is some folks want sourcemaps too to upload to sentry and such. I don't have a good answer for that yet

**Comment by petebacondarwin** [comment]
I don't think we can upload source-maps since that would count towards the 1Mb limit.
For `wrangler dev` we could do the source mapping inside the `wrangler` client - i.e. as part of the DevTools proxy.

But not sure what the best solution for Sentry and similar production stuff would be.
Perhaps an option to push source-maps to an Asset store, and then reference them from the minified source somehow??

**Comment by JacobMGEvans** [comment]
> Asset store, and then reference them from the minified source somehow

That's definitely what I was driving at. Some sort of external place that could be referenced after the fact.

**Comment by threepointone** [comment]
Tempted to have folks optionally pass `--outdir` for `publish` to enable superusers do whatever they want with the assets. They still won't be able to modify it when we publish, but they can introspect and upload sourcemaps separately if they want.

**Comment by threepointone** [comment]
Well I guess the superuser case is they setup a custom build by themselves, since they already have a level of complexity where they have to upload the sourcemaps and such. So maybe we don't have to worry about that here, and can just implement `minify` for folks who want smaller bundles. 

Related, we should work on factoring out our esbuild work so folks can use it in their custom build pipelines, but that's a bunch of work for later, probably 2.1.

**Comment by JacobMGEvans** [comment]
> Well I guess the superuser case is they setup a custom build by themselves, since they already have a level of complexity where they have to upload the sourcemaps and such. So maybe we don't have to worry about that here, and can just implement `minify` for folks who want smaller bundles. 

That's a great point and agree with minify implementation.

**Comment by JacobMGEvans** [comment]
I started working on this a bit, first thing we will need to modify `mockUploadWorkerRequest` to be able to assert minified code, likely rewind the minification. 

Something else to consider is when minifying what ECMAScript version can the edge handle, we can target specific ES if necessary. https://esbuild.github.io/api/#minify-considerations

**Comment by threepointone** [comment]
How about an extremely simple worker, and just check that the white space got removed?

**Comment by JacobMGEvans** [comment]
> How about an extremely simple worker, and just check that the white space got removed?

You meaning something like this? 
```ts
if (expectedEntry !== undefined) {
        expect(await (formBody.get("index.js") as File).text()).not.toContain(
          `\n`
        );
      }
```

**Comment by threepointone** [comment]
something like 
```js
// script.js 

export 

     default {

   fetch() {
 
       return new Response(     "hello jacob"     )
   
                 }
}
            
```

and 
expectedEntry: `fetch(){return new Response("hello jacob")}`
