### ISSUE TITLE
feat: Yargs Commands Directory

### ISSUE THREAD

**Issue by michaelmerrill** [cloudflare/wrangler2#792]
The wrangler cli is getting [unwieldily](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/index.tsx). Is there interest in adopting the [yargs commands directory feature](http://yargs.js.org/docs/#api-reference-commanddirdirectory-opts)? I believe this will help other developers contributing and can be done incrementally.

An example of a command file: 

```
// packages/wrangler/src/cmds/<command>

exports.command = 'remote <command>'
exports.description = 'Manage set of tracked repos'
exports.builder = function (yargs) {
  return yargs.commandDir('remote_cmds')
}
exports.handler = function (argv) {}
```

**Comment by threepointone** [comment]
I don't agree that it's unwieldy, it's pretty straightforward. We could probably add some comments and make it easier to search through, but it's fine. I don't think we want to do this refactor just yet.
