### ISSUE TITLE
🐛 BUG: wrangler throws a ParseError when script name contains uppercase characters in wrangler.toml

### ISSUE THREAD

**Issue by 25thhour** [cloudflare/wrangler2#795]
### What version of `Wrangler` are you using?

0.0.25

### What operating system are you using?

Mac

### Describe the Bug

When using uppercase characters for the script name in `wrangler.toml`, e.g. `name = "Test"`, wrangler throws a "_ParseError: Received a bad response from the API_" when running `npx wrangler dev`.

### Steps to Reproduce
```
➜ npx wrangler@beta init
 ⛅️ wrangler 0.0.25
--------------------
…
Would you like to create a Worker at src/index.ts? (y/n)
✨ Created src/index.ts
```

**index.ts**
```
export default {
  async fetch(request: Request): Promise<Response> {
    return new Response("Hello World!");
  },
};
```

**wrangler.toml**
```
name = "Test"
main = "src/index.ts"
compatibility_date = "2022-04-14"
```

**Terminal output**
```
➜ npx wrangler dev
 ⛅️ wrangler 0.0.25 
--------------------
Select an account from below:
❯ 25thhour
⬣ Listening at http://localhost:8787
remote worker: ParseError: Received a bad response from the API
    at throwFetchError (/Users/jdeane/dev/demos/vidAEo/node_modules/wrangler/wrangler-dist/cli.js:137650:17)
    at fetchResult (/Users/jdeane/dev/demos/vidAEo/node_modules/wrangler/wrangler-dist/cli.js:137623:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createPreviewToken (/Users/jdeane/dev/demos/vidAEo/node_modules/wrangler/wrangler-dist/cli.js:139904:29)
    at async createWorkerPreview (/Users/jdeane/dev/demos/vidAEo/node_modules/wrangler/wrangler-dist/cli.js:139919:17)
    at async start (/Users/jdeane/dev/demos/vidAEo/node_modules/wrangler/wrangler-dist/cli.js:140357:16) {
  text: 'Received a bad response from the API',
  notes: [ { text: 'workers.api.error.invalid_script_name [code: 10016]' } ],
  location: undefined,
  kind: 'error',
  code: 10016
}
```

**Comment by threepointone** [comment]
related to https://github.com/cloudflare/wrangler2/issues/775, we should generate valid worker names, and add validation for the same.

**Comment by threepointone** [comment]
The PR didn't solve the original problem, either disallowing capitals when generating a wrangler project, or lowercasing the name automatically. Reopening.

**Comment by JacobMGEvans** [comment]
> The PR didn't solve the original problem, either disallowing capitals when generating a wrangler project, or lowercasing the name automatically. Reopening.

This is if the name is inferred from the directory rather than the TOML?

**Comment by threepointone** [comment]
fixed by https://github.com/cloudflare/wrangler2/pull/877
