### ISSUE TITLE
warn if `[miniflare]` is used in wrangler.toml

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#799]
We currently ignore the `[miniflare]` key in wrangler.toml, but that's actually confusing because folks think we support its configuration values. We should probably throw a warning here. Separately we should implement features similar to the ones miniflare provides (with additional edge equivalents) incl. mounts and testing environment, but that's for 2.1

**Comment by petebacondarwin** [comment]
LOL - I specifically removed the warning here - https://github.com/cloudflare/wrangler2/pull/627

**Comment by threepointone** [comment]
lmao oh right

**Comment by JacobMGEvans** [comment]
> LOL - I specifically removed the warning here - #627 - and you approved it @threepointone 😆

I can put this back (maybe try to improve the format and UI), or are we leaving it as is?

**Comment by threepointone** [comment]
We need a custom message explaining why exactly we don't support miniflare configuration
