### ISSUE TITLE
fix: add a warning when using the newer service environments

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#809]
Service environments aren't ready for widespread usage, and the behaviour is guaranteed to change. So we should have a warning if anyone tries to use it.

**Comment by JacobMGEvans** [comment]
I can add messaging Monday.

**Comment by threepointone** [comment]
I'll do this one myself, I want to land it soon and do a release this weekend.

**Comment by eugene1g** [comment]
Just saw the new message come up in our stack. Do you have any guesses on when Services might become stable or go GA? Even if as broad as "next quarter / next year".

**Comment by threepointone** [comment]
Probably next quarter, but I can't guarantee tbh, it's a cross functional effort.
