### ISSUE TITLE
`wrangler init .` name inheritance

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#828]
When running `wrangler init .` the expected behavior should be to find the parent directory inherit the directories name as the script `name` in TOML configuration.

> That's indeed it.

> I thought wrangler init takes the dir as a parameter so I did `wrangler init .` but that was definitely wrong.
Thanks :upside_down_face:

> _Originally posted by @Leptopoda in https://github.com/cloudflare/wrangler2/issues/775#issuecomment-1094331309_

**Comment by petebacondarwin** [comment]
> When running wrangler init . the expected behavior should be to find the parent directory with package.json or another means to determine project root and inherit the directories name as the script name in TOML configuration.

Is that correct? This is certainly the behaviour when no name argument is passed to the `wrangler init` command. But if the `.` argument is passed, I would suggest that the user is specifically requesting that the initialisation happens at the current directory, ignoring any higher level wrangler.toml/package.json files.

**Comment by threepointone** [comment]
^ pete's right.

**Comment by JacobMGEvans** [comment]
> > When running wrangler init . the expected behavior should be to find the parent directory with package.json or another means to determine project root and inherit the directories name as the script name in TOML configuration.
> 
> Is that correct? This is certainly the behaviour when no name argument is passed to the `wrangler init` command. But if the `.` argument is passed, I would suggest that the user is specifically requesting that the initialisation happens at the current directory, ignoring any higher level wrangler.toml/package.json files.

Edited original to be aligned with this.

**Comment by threepointone** [comment]
fixed in https://github.com/cloudflare/wrangler2/pull/877
