### ISSUE TITLE
Messaging during `wrangler publish` with underscores

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler2#833]
If the `workers_dev` prevent `wrangler publish` from pushing up the script and provide a message detailing why underscores cannot be used with `workers.dev` 

> Removing `_` eligibility would be a breaking change and prevent people from using Wrangler 2 for Workers with underscores.

> As I understand it, the only constraint is that we cannot use underscores with `workers.dev` subdomains. So I propose that we do allow `_` in the Worker name, but do not attempt to publish to `workers.dev` if there is an underscore in the name, displaying a suitable warning when that happens.

> _Originally posted by @petebacondarwin in https://github.com/cloudflare/wrangler2/pull/829#discussion_r854906620_

**Comment by JacobMGEvans** [comment]
Discussed, and we will be handling this slightly differently than mentioned in the issue body, however, we will still be providing messaging during this scenario.

**Comment by petebacondarwin** [comment]
Since SSL certificates for workers.dev are of the form `*.subdomain.workers.dev`, which is valid for Workers that have underscores, we don't need to constrain this here. What is important is that `subdomain` has no underscores, but this is already prevented in the dashboard.
