### ISSUE TITLE
🐛 BUG: Better Error Message for when Wrangler Login Fails when using Cloudflare Warp

### ISSUE THREAD

**Issue by lauragift21** [cloudflare/wrangler2#850]
### What version of `Wrangler` are you using?

0.0.19

### What operating system are you using?

Mac

### Describe the Bug

I tried running the  `wrangler login` command but it timed out with this error message.

<img width="974" alt="Screenshot 2022-04-26 at 15 23 28" src="https://user-images.githubusercontent.com/17781315/165314558-854fc225-aac0-404e-9c5f-777ccaa65f0c.png">

I was able to fix it by turning off WARP and retying the login process and it worked. We should include a better error message instead that tell me what the issue is and catch the error returned.

**Comment by threepointone** [comment]
Fixed properly in https://github.com/cloudflare/wrangler2/pull/963, we don't need to have an error anymore
