### ISSUE TITLE
🐛 BUG: Add a flag to not auto-open the browser

### ISSUE THREAD

**Issue by miniBill** [cloudflare/wrangler2#856]
### What version of `Wrangler` are you using?

0.0.27

### What operating system are you using?

Linux

### Describe the Bug

Please add a flag to prevent auto-opening the browser for the `pages` subcommand

**Comment by GregBrimble** [comment]
If you set a `BROWSER=none` env var (just like CRA), we won't open the browser automatically.

**Comment by miniBill** [comment]
Thanks, works perfectly
