### ISSUE TITLE
Things I wish 2.0 had 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#858]
I know we're already talking about all the new things we want to do in 2.x, but I wanted to just note down some misses, so that we'll hopefully prioritise it soon - 

- [ ] #1143
- [ ] #1144
- [ ] #285
- [ ] #66
- [ ] #3
- [ ] #1145

There's plenty more, but these came to mind for me.

**Comment by IanMitchell** [comment]
I asked about this on Twitter a day ago, but huge plus one to `wrangler as an api, so folks could build their own tooling on top`! 

For context, I'm writing a library that needs to update the state in a third party service after a developer updates metadata in their code. Being able to hook into the hot reload flow and run some functions as a callback for a new build would be extraordinary (Miniflare's style of `addEventListener` worked great!)

**Comment by petebacondarwin** [comment]
Linked to or created issues for all these items.
