### ISSUE TITLE
🐛 BUG: `wrangler init foo` should stop looking for tsconfig.json and package.json at `./foo`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#859]
### What version of `Wrangler` are you using?

0.027

### What operating system are you using?

Mac

### Describe the Bug

If you run `wrangler init foo` inside a directory that contains a tsconfig.json, then Wrangler automatically assumes you are in a TypeScript project. I would argue that if you have specified a new directory (e.g. `foo`) for this Worker, then we should not treat it as part of a wider project.

**Comment by threepointone** [comment]
Yeah I can agree with this. Especially because: 

- we usually need to setup workers-types anyway 
- or we need to extend from a higher tsconfig 

Both scenarios require a new tsconfig file. And it's easier to delete/modify a generated tsconfig than it is to create one.

**Comment by rozenmd** [comment]
I think this might be two issues:
1. Should we *always* create a package.json, even if one exists in a higher directory
2. Should we *always* create a tsconfig.json, even if one exists in a higher directory

I would argue (at least for my own uses, maybe I'm the edge case?) in both cases, we should completely ignore what's in the current directory - if I run `wrangler init newWorkerPls` in `projectRoot/` I expect `/projectRoot/newWorkerPls/` to be a self-contained worker with a package.json, and if I asked for typescript, I'd like a tsconfig.json too

**Comment by petebacondarwin** [comment]
I agree that if you specify a path in the `init` command, then we should be assuming that the new directory is self contained and do not look up the tree for package.json or tsconfig.json.

If you do not specify a path then Wrangler defaults to initialising the current directory. In this case then I think we should be willing to look up the directory-tree for package.json and tsconfig.json.
