### ISSUE TITLE
Browser-Based Editor Compatibility

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#861]
This is a meta-issue for tracking progress on getting wrangler working in browser-based editor sandboxes such as [StackBlitz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/), [GitHub Codespaces](https://github.com/features/codespaces), etc.

- [x] #863
- [x] #862
- [ ] #865
- [x] #864

**Comment by coding-to-music** [comment]
I use a chromebook to develop using a DigitalOcean droplet, this bug affected me, CORS error, could not login.
Good news, per one of the comments in one of these listed issues, I then did this:
```java
npm install -g wrangler@beta
```
and it worked, authenticated

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/wrangler2/milestone/7
