### ISSUE TITLE
CORS fails when running wrangler inside a browser context

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#864]
The APIs that wrangler interacts with do not allow Cross-Origin requests, which causes requests that originate from e.g. `stackblitz.com` to get rejected. This is not currently something that we can solve from the wrangler side, but I'm creating an issue to track progress.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/wrangler2/issues/1796 (TLDR we'll autodetect CORs failures and fall back to a CORs API proxy)
