### ISSUE TITLE
🐛 BUG: unknown arguments: publish, on `$ wrangler pages publish dist/client`

### ISSUE THREAD

**Issue by TurboTobias** [cloudflare/wrangler2#878]
### What version of `Wrangler` are you using?

0.0.27

### What operating system are you using?

Mac OS 12.2.1

### Describe the Bug

When I run `$ wrangler pages project create asdasd`, I get:
✨ Successfully created the 'asdasd' project. It will be available at https://asdasd.pages.dev/ once you create your first deployment.
To deploy a folder of assets, run 'wrangler pages publish [directory]'.

But when I run`$ wrangler pages publish dist/client`, I get:
Unknown arguments: publish, dist/client

When I check `$ wrangler pages --help`, I get:
Commands:
  wrangler pages dev [directory] [-- command]  🧑‍💻 Develop your full-stack Pages application locally
  wrangler pages project                       ⚡️ Interact with your Pages projects
  wrangler pages deployment                    🚀 Interact with the deployments of a project

**Comment by threepointone** [comment]
Could you try with `wrangler@alpha`? The command was introduced in https://github.com/cloudflare/wrangler2/pull/790/, which hasn't gone out to `@beta` yet.

**Comment by GregBrimble** [comment]
The API isn't fully released for everyone on production yet, so I'd hold off on using this until we've officially announced this feature anyway.

**Comment by TurboTobias** [comment]
@threepointone I see. Alpha works 👌

@GregBrimble absolutely just wanted to inform. The CLI says `🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose`

**Comment by GregBrimble** [comment]
Great, thank you! :)
