### ISSUE TITLE
Formalize devtools

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler2#881]
We should formalize [built-devtools](https://github.com/threepointone/built-devtools/) as a part of the wrangler repo

- [x] #1416
- [ ] Automatically deploy the built output somewhere
- [ ] Related: make that "somewhere" something official looking (e.g. not pages.dev)
- [x] #607

**Comment by admah** [comment]
@penalosa will this work be taken care of in the upcoming devtools consolidation work?

**Comment by penalosa** [comment]
> @penalosa will this work be taken care of in the upcoming devtools consolidation work?
Yes, it will

**Comment by penalosa** [comment]
Closing in favour of #2550
