### ISSUE TITLE
🐛 BUG: Passing in --site flag with no value results in unexpected behavior

### ISSUE THREAD

**Issue by jkup** [cloudflare/wrangler2#883]
### What version of `Wrangler` are you using?

0.0.27

### What operating system are you using?

Mac

### Describe the Bug

A teammate cloned down https://github.com/cloudflare/worker-sites-template and was trying to run `wrangler dev --site` thinking that was the syntax for running a workers-site. I noticed that if you pass in --site with no value, it seems to pass `undefined` in to Miniflare as the `sitePath`. The TL;DR was instead of getting an error like 'You must pass in a value when calling `wrangler dev` with `--site` or something it just ran the dev build and errored with `__STATIC_CONTENT is not defined` which was confusing.

I'm not sure if there is a real bug here with passing undefined to Miniflare or maybe we could just, in Wrangler, check to make sure you pass something in when calling --site?

**Comment by threepointone** [comment]
bleh, this should have been caught by yargs strict mode, but looks like it doesn't.

**Comment by threepointone** [comment]
btw, In 0.0.28, we landed some backward compat support, so calling `wrangler dev` in the linked repo now works (after calling npm install inside the `workers-site` directory to install dependencies)

**Comment by threepointone** [comment]
This has nothing to do with miniflare btw, it happens in both remote/local modes.
