### ISSUE TITLE
Support `.proto` modules

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#885]
Many developers use [ProtocolBuffers](https://developers.google.com/protocol-buffers) as a wire format for APIs. The problem is that it's challenging to get it to work on Workers, since most libraries either require `eval` or access to a file system.

[`protobufjs`](https://www.npmjs.com/package/protobufjs) offers a way to "pre-compile" a `.proto` file into a "static" standalone parser, that also works on Workers. This way, there is no `eval` or file system needed.

Here's how it would work:
1. Import a `.proto` module.
```proto
message Person {
  required string name = 1;
  required int32 id = 2;
  optional string email = 3;
}
```
2. `wrangler` uses `protobufjs` to compile it to a "static" file, then writes its TypeScript definition to the file system so developers can access its types.
```typescript
// types/proto-generated/person.d.ts
export interface Person {
  get name(): string;
  get id(): number;
  get email(): string | null;

  static decode(buffer: BufferSource): Person;
}
```
3. Developers can use the `.proto` module from their Worker.
```typescript
import { Person } from "./src/person.proto";

export default {
  async fetch(request: Request): Promise<Response> {
    const { body } = request;
    const person = Person.decode(body);
    const json = JSON.stringify(person);
    return new Response(json);
  }
}
```

**Comment by threepointone** [comment]
This sounds like a solid usecase for custom builds, any reason we should support it natively?

**Comment by threepointone** [comment]
Closing since this is covered by custom builds, and I don't think we're plannong on "natively" doing this.
