### ISSUE TITLE
Update the CLI arg descriptions for wrangler pages publish

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#895]
![image](https://user-images.githubusercontent.com/8484333/166713459-166959a4-3d44-4075-9ca4-e95a88dba23a.png)

**Comment by threepointone** [comment]
This appears to be fixed, closing 

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/18808/168623263-71eb6d07-eb25-47d1-b103-6c8e3e51e4a4.png">
