### ISSUE TITLE
.dev.vars support for on 'wrangler pages dev'

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#898]
Still need to figure out exactly what this looks like, but part of the local env vars story was solved with #879.

**Comment by maraisr** [comment]
I tired something similar with https://github.com/cloudflare/wrangler2/pull/818

**Comment by dt-chris** [comment]
this would be useful. as i understand it currently, none of the wrangler.toml config or dotenv stuff applies to 'wrangler pages dev', is that correct?
