### ISSUE TITLE
[DEPRECATION] `wrangler preview`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#9]
We're considering deprecating the `wrangler preview` command. It's not as powerful as `wrangler dev`, and it usually lags in features that we're implementing in workers. That said, we recognise that it makes development on Workers accessible to folks, so we can't simply rip it away without a strong story. Perhaps we should make sure we have great development stories with tools like codesandbox / stackblitz / codepen / etc (and perhaps directly in our docs too).  This issue looks to collect feedback and describe alternative strategies for when we do actually deprecate it.

**Comment by threepointone** [comment]
via @Electroid, just run `wrangler dev` instead. good idea!

**Comment by petebacondarwin** [comment]
- For working/developing a Worker (without officially publishing it) then `wrangler dev` definitely seems like the obvious alternative to `preview`.
- Is there an additional use-case where a developer wants to share a draft Worker with a colleague or client without officially publishing it?
  - Does that even make sense?
  - Could we make use of environments instead?

**Comment by Electroid** [comment]
I think we would want to leverage environments for sharing a preview. It's something we should definitely support with `dev`. It might need some API work though, because if we publish to a `workers.dev` subdomain, I think we loose access to the DevTools inspector. (There's no technical limitation here, we just need to implement it in the back)

**Comment by GregBrimble** [comment]
I use it in Discord sometimes when I want to show someone a quick script (e.g. "how do I add a header to a response?"). For simple questions, cloudflareworkers.com is pretty handy. But, I've never used wrangler to use it.

If it's complex enough to require wrangler (e.g. it needs a KV binding or similar), then it's roughly complex enough to require a repo.

**Comment by TrySound** [comment]
We do some domain parsing in our workers and it's really easy to check things with wrangler preview.

**Comment by petebacondarwin** [comment]
@TrySound - would the `--host` flag in `wrangler dev` help you here?
For example if I go to the `examples/worker-app` project in our repository and run the following
(assuming that I have attached the `my-zone.com` to my account):

```bash
$ npx wrangler dev --host=www.my-zone.com
```

Then when I browse to `http://localhost:8787/foo/bar` I see the following in the dev-tools:

```
GET
"https://www.my-zone.com/foo/bar"
Map(22) {
  [[Entries]]: {
    ...
    { "host": "www.my-zone.com" }
    ...
  }
}
```

**Comment by TrySound** [comment]
Thanks, this is very helpful!
