### ISSUE TITLE
🐛 BUG: Profiling doesn't work as expected 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#907]
### What version of `Wrangler` are you using?

0.0.30

### What operating system are you using?

Mac

### Describe the Bug

Profiling as described in https://developers.cloudflare.com/workers/learning/profiling-workers/ doesn't work with wrangler v2. The button to start profiling is disabled in devtools. (Whether opened via chrome://inspect, or the standalone tools on hitting D).

**Comment by threepointone** [comment]
More info: 

In chrome://inspect, the button gets enabled after visiting the worker at least once. Dug in a little, and it looks like the prewarm logic isn't working . This code - https://github.com/cloudflare/wrangler2/blob/f2b6cd94b354d44a88298388ccd9ccec710ed093/packages/wrangler/src/create-worker-preview.ts#L169-L171 is always erroring. 

In the standalone/hotkey tools, the button gets enabled, but doesn't look to ever stop after clicking Stop.

**Comment by threepointone** [comment]
Reopening this since it looks like the Profiling itself isn't working, it doesn't. Via Discord: 

Also the cpu profiler doesn't seem to work in devtools. I click record/start, then make a request to my worker (which completes normally), then I stop the profiling. Then it shows that my worker been idle for the whole time. I've tried it a few times now and I'm 100% sure that I'm making a request to my worker (I see console logs in my terminal and devtools) while it's recording. I only see idle in the profiler 

![image](https://user-images.githubusercontent.com/18808/168227262-abecac9f-e5b2-429c-9785-21743c06364c.png)

**Comment by petebacondarwin** [comment]
@threepointone to double check whether this even works in the dashboard.

**Comment by threepointone** [comment]
I can confirm that profiling is broken at an api/edge level. I verified that profiling doesn't "work" with wrangler 1 as well, so there's nothing to fix here, and we should follow up internally.  I'll leave this assigned to me, but marking as blocked for now.

**Comment by petebacondarwin** [comment]
Related (sort of) to #3

**Comment by Warfields** [comment]
@threepointone I've taken a look at this. The spec indicates that the runtime will only send CPU Stats in local fiddle, apparently there were concerns about timing data and Spector. I'll be bridging a discussion of if it is ok to open this up on the edge.

**Comment by Warfields** [comment]
@petebacondarwin @threepointone I'm asking the Runtime team on Wednesday

**Comment by Warfields** [comment]
Update, found the bug in the runtime. V8 changed how it returns somethings from the profiler.

**Comment by threepointone** [comment]
assigning to @Warfields

**Comment by Warfields** [comment]
@threepointone A fix has been merged to the runtime and is awaiting release. As soon as the next release this bug can be closed

CC: @JacobMGEvans As Sunil is out

**Comment by ObsidianMinor** [comment]
The fix has been released
