### ISSUE TITLE
`wrangler pages dev` 404s some functions/routes

### ISSUE THREAD

**Issue by Mexican-Man** [cloudflare/wrangler2#92]
`functions/index.ts` and `functions/*/index.ts` , `functions/_middleware.ts` and `functions/*/_middleware.ts` work, but nothing else. For example, `functions/*/*/index.ts` does not work. Parameterized paths also don't work.

I'm on Windows. To repro, open new folder, `npm init`, `npm i wrangler@alpha`, create `functions` folder, create `index.ts`, insert:
```typescript
export const onRequestGet: PagesFunction<{}> = async ({ request, env }): Promise<Response> => {
    return new Response("hello1", { status: 200 })
}
```
Run `npx wrangler pages dev ./`. Move it to `functions/index.ts`, http://localhost:8788/ works fine. Move it to `functions/test/test/index.ts`, http://localhost:8788/test/test/ returns a 404.

The other day, this was happening both when building on Cf and when I tried using `wrangler pages dev`. Now it's just happening with wrangler. This seems like an isolated case, so let me know if there's any more info I can provide.

**Comment by threepointone** [comment]
Feels like a bug, we'll investigate this.

**Comment by Mexican-Man** [comment]
I tried the latest `wrangler@alpha`, and behaviour has changed. Before, one of the bad routes would respond with my `404.html`, now there's nothing at all.

To make sure my project is set up properly, I tried it on WSL and it seems to work fine, but esbuild watch does not work there :(

**Comment by threepointone** [comment]
@GregBrimble

**Comment by elemental-mind** [comment]
Should have put my comment here. It's a bug in the code generator:

https://github.com/cloudflare/wrangler2/issues/50#issuecomment-997289714

**Comment by Mexican-Man** [comment]
Last night, I kept getting burned by this bug, so this afternoon, I decided I would take some time to finally fix it. Spent a good 30 minutes setting up the environment, reading the contrib doc, and running my first build, etc.

> "Wait, why is it working?"

The build, the one that came out this morning 🤣

Can someone, like @elemental-mind, `npm i -g wrangler@beta` and confirm it's working now?

**Comment by GregBrimble** [comment]
I think this has likely been closed by #331 . Can you confirm @Mexican-Man ?

**Comment by Mexican-Man** [comment]
Thanks @GregBrimble. I thought that commit would fix it, but it doesn't seem to work. I pulled `@alpha` and `@0.0.16` with no luck. Pulled my PR just to make sure, and it's still working.

I will try to merge and redo a PR when I get more time.

**Comment by Mexican-Man** [comment]
It seems as though that PR (or another one from 0.0.16) introduced a bug where the "route deduplication" is disregarding methods. This doesn't seem like it would be a Windows exclusive issue, but I've gone ahead and made another PR #465.
