### ISSUE TITLE
🐛 BUG: Different workers created for different environments

### ISSUE THREAD

**Issue by gijo-varghese** [cloudflare/wrangler2#921]
### What version of `Wrangler` are you using?

1.19.12

### What operating system are you using?

MacOS 12.3.1

### Describe the Bug

Wrangler is adding the environment name to the worker while publishing, which creates separate workers for each environment.

For example, I have a worker named "foo". `wrangler publish --env production` creates a new worker `foo-production` and `wrangler publish --env staging`  creates a new worker `foo-staging`.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create a new project `wrangler generate foo`.
2. Add `production` and `staging` environments to `wrangler.toml` (as below).
3. Run `wrangler publish --env production`.
4. Run `wrangler publish --env staging`.
5. Notice the newly created workers "foo-production" and "foo-staging" both with the production environment.

```wrangler.toml
name = "foo"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-05-07"

[env.production]
route = "*/*"

[env.staging]
route = "*/*"
```

#### Expected behavior

Only a single worker will be created named "foo" with two environments "production" and "staging". Instead, it's creating two workers with both of them having a production environment.

**Comment by threepointone** [comment]
This is working as designed https://developers.cloudflare.com/workers/platform/environments/#naming. 

We also have newer service environments https://developers.cloudflare.com/workers/learning/using-services/ which is a first class abstraction that succeeds the existing environments and would work as you desire, but we'll enable them by default in wrangler only after they become generally available, which should happen soon later this year.

**Comment by gijo-varghese** [comment]
@threepointone so what's the point of "environments" in the dashboard? We can create environments in the dashboard, but can't deploy to them?!

**Comment by threepointone** [comment]
Sorry for the frustration. We probably jumped the gun by enabling them in the dashboard as early as we did before we had proper wrangler support. 

If you're interested, we have _experimental_ support for service environments in wrangler, which you can enable by passing `legacy_env = false` in your `wrangler.toml` but CAUTION that the behaviour isn't well defined and may change soon, so I wouldn't recommend using that for production software just yet. 

Again, sorry about this, we're actively working on fixing this.

**Comment by gijo-varghese** [comment]
@threepointone understood, thanks.

**Comment by ignoramous** [comment]
> Again, sorry about this, we're actively working on fixing this.

Can you pls point to the gh-issue that tracks this effort for wrangler2?
