### ISSUE TITLE
🐛 BUG: confusing/misrepresented HTTP status output in CLI

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/wrangler2#931]
### What version of `Wrangler` are you using?

2.0.0.

### What operating system are you using?

MacOS 12.3.1

### Describe the Bug

When using `wrangler` CLI, there is a disconnect between what the `wrangler` connection receives as the HTTP status and what the Worker returns. The distinction is important yet confusing to most. Here is a simple reproduction demonstrating the behaviour.

```
$ echo "export default { fetch() { return new Response('hello world', { status: 419 }) } }" > index.js

$ npx wrangler dev index.js

⬣ Listening at http://localhost:8787
```

Now, make a request to the endpoint using `curl` (in another terminal) or a browser.

```
$ curl -so /dev/null http://localhost:8787 --write-out '%{http_code}'
419
```

Flip back to the wrangler CLI, and you'll see the wrangler output says the HTTP status was  HTTP 200.

```
9:49:52 am GET / 200
Script modified; context reset.
```

Now, this isn't really a bug but a misrepresentation of what is actually happening (and to be clear, the issue is present in the UI but shown differently so slightly less confusing but still not great).

Under the covers, the log entry isn't actually getting HTTP 200; it is getting `{"outcome":"ok", ...}` which is being displayed as the HTTP 200. What I'd be proposing here is updating the log line to something like this:

```
9:49:52 am GET / 419 [outcome=ok]
```

I'm not married to the syntax so happy to yield to whatever however, the intent would be that the CLI makes the subtle differences a little clearer to avoid people debugging HTTP status confusion.

**Comment by threepointone** [comment]
Good catch, yeah we need to fix this, it's clearly just wrong.

**Comment by jacobbednarz** [comment]
nice! you beat me to it. thanks!
