### ISSUE TITLE
🐛 BUG: named exports will crash

### ISSUE THREAD

**Issue by thepassle** [cloudflare/wrangler2#937]
### What version of `Wrangler` are you using?

2.0.0

### What operating system are you using?

mac

### Describe the Bug

```
⚡ echo "const a = () => {};export {a};" > index.js && wrangler dev index.js 
```

will result in:
```
  {
    text: 'Received a bad response from the API',
    notes: [
      {
        text: "Uncaught SyntaxError: Unexpected token 'export'\n" +
          '  at line 4\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

Ideally, in a modern module system named exports wouldnt throw an error even if they are unused

**Comment by threepointone** [comment]
Good catch. In this scenario, wrangler is detecting that you're developing a service-worker format worker, since you don't have a `default` export. Our runtime throws an error when those workers have named exports. We do log a warning when you do this, which would look like: 
```
▲ [WARNING] The entrypoint index.js has exports like an ES Module, but hasn't defined a 
default export like a module worker normally would. Building the worker using "service-worker" format...
```

The workaround here is to remove any exports. As a long term fix, wrangler could do better and simply remove those exports itself, which we'll do soon. Thanks for reporting this issue!

**Comment by thepassle** [comment]
> Actually, I don't think Wrangler should patch these exports. Instead this should be a hard error, rather than just the warning it is now.

Why?

To elaborate on my usecase: I'm creating an [Astro](https://astro.build) integration for cloudflare. This means that I dont have complete control over the build output. The build output in this case includes some exports. In a modern module system environment, this would be fine, and the exports would just be ignored, however, in cloudflare this would then apparently be a hard error? This means I now have to write extra code and run an additional build to post-process my already modern es module

**Comment by petebacondarwin** [comment]
Hmm. As I understood it, the named exports should not cause the error. It is the lack of default export that is the problem.
That is because without it, this is not a Worker.

**Comment by thepassle** [comment]
> It is the lack of default export that is the problem.

Interesting, using wrangler 1 this didnt seem to be a problem

**Comment by petebacondarwin** [comment]
@thepassle - could you provide a reproduction of the error that I could try out?

**Comment by petebacondarwin** [comment]
```ts
const a = () => {};
export {a};
```

This is not a valid Cloudflare Worker.

**Comment by thepassle** [comment]
Thats the most minimal repro I could make that highlights the error

**Comment by threepointone** [comment]
I think wrangler2 could do a better job here, I'll chat with @petebacondarwin and we'll come up with something

**Comment by petebacondarwin** [comment]
Oh! I see. Sorry if I was coming across as argumentative. I was trying to work out why you would get the error.

You are actually creating a "service worker" style Worker, but happen to also have exports, which causes Wrangler 2 to think it is a "ES module worker" style Worker.

So in that case, we should improve our "format sniffing". I.E. if there is no default export (that contains a `fetch` method) and there is a call to `addEventListener()` then we should consider that a "service worker" style format.

**Comment by threepointone** [comment]
We landed a fix that shouldn't throw the error anymore in https://github.com/cloudflare/wrangler2/pull/941, you can try it with wrangler@beta. We'll do a proper release in a few days. Thanks for filing this issue!
