### ISSUE TITLE
🐛 BUG: `npx wrangler publish` cannot resolve root npm packages

### ISSUE THREAD

**Issue by tomkingchen** [cloudflare/wrangler2#946]
### What version of `Wrangler` are you using?

2.0.1

### What operating system are you using?

Mac

### Describe the Bug

I have an existing project was published using Wrangler 1. The `wrangler.toml` file looks like below.
```
name = "my-project-name"
main = "./"
account_id = "abc12345..."
route = "foo.bar.com/*"
workers_dev = true

[env]
compatibility_date = "2022-04-01"

[build]
command = "npm install && npm run build"
```
After installed wrangler2 package using `npm install wrangler --save-dev` and run `npx wrangler publish` I got the error below.
```
...
webpack 5.38.1 compiled successfully in 764 ms

✘ [ERROR] Could not resolve "" after running custom build: npm install && npm run build

```
Same project can be published without problem using wrangler1 though `wrangler publish` command.

Publish also works if I run `npm install && npm run build` directly.

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue.

The problem appears to be that Wrangler 2 expects the `main` property to be the path to the output from the custom build.

Let's assume that your webpack build is outputting to `dist/index.js`, then in wrangler.toml your would need

```toml
main = "dist/index.js"
```

**Comment by petebacondarwin** [comment]
If you are not doing anything special in your webpack build, you could actually just remove the custom `build` step altogether and point `main` at the source entry-point of your Worker.

**Comment by tomkingchen** [comment]
Thanks @petebacondarwin, after set `main` to `dist/worker.js`, I was able to publish the worker using `npx wrangler publish`.

**Comment by petebacondarwin** [comment]
One last thing. Can you tell me if you added the `main` field as part of your upgrade to Wrangler 2? Or was it already there from Wrangler 1? I believe that Wrangler 1 would not use this field, and that our deprecation warning ought to have told you to use `dist`. For example:

````
Delete the `build.upload.main` and `build.upload.dir` fields.
Then add the top level `main` field to your configuration file:
```
main = "dist/index.js"
```
````
