### ISSUE TITLE
🐛 BUG: wrangler dev still sometimes fails to exit cleanly after Ctl-C

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#958]
### What version of `Wrangler` are you using?

2.0.2

### What operating system are you using?

Mac

### Describe the Bug

Occasionally, hitting Ctrl-C when running `wrangler dev` does not result in the process exiting. Instead it just hangs.
Previously we had this problem but thought we had fixed it with #732. But it seems to have reappeared.

**Comment by petebacondarwin** [comment]
cc @d3lm

**Comment by JacobMGEvans** [comment]
Oh no, how often does it still happen?

**Comment by petebacondarwin** [comment]
I think it only happens if you have made a request to the Worker and there is a connection being held open somewhere.
