### ISSUE TITLE
🐛 BUG: KV keys that begin with slash aren't setting correctly

### ISSUE THREAD

**Issue by jkup** [cloudflare/wrangler2#961]
### What version of `Wrangler` are you using?

2.0.2

### What operating system are you using?

Mac

### Describe the Bug

```bash
☁  delete [master] ⚡  wrangler kv:key --namespace-id "123" put "/twitter" "https://twitter.com/jkup"
Writing the value "https://twitter.com/jkup" to key "/twitter" on namespace 123.

☁  delete [master] ⚡  wrangler kv:key list --namespace-id "123"
[
  {
    "name": "twitter"
  }
]
```

It says it writes "/twitter" but it seems to write "twitter". The dashboard works correctly.

**Comment by threepointone** [comment]
Ugh that looks bad, sorry. Will look into this today.
