### ISSUE TITLE
Unable to run dev or publish after upgrade to v2

### ISSUE THREAD

**Issue by ookangzheng** [cloudflare/wrangler2#966]
#### Describe the bug

I use pure JavaScript
Run `wrangler dev` and it shows this error

```
❯ wrangler login
 ⛅️ wrangler 2.0.2 
-------------------
Attempting to login via OAuth...
Successfully logged in.
❯ wrangler dev
 ⛅️ wrangler 2.0.2 
-------------------
▲ [WARNING] Processing wrangler.toml configuration:

    - Deprecation: "zone_id":
      This is unnecessary since we can deduce this from routes directly.


⬣ Listening at http://localhost:8787
✘ [ERROR] Error on remote worker: ParseError: Received a bad response from the API

      at throwFetchError
  (/Users/loll/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/wrangler/wrangler-dist/cli.js:105919:17)
      at fetchResult
  (/Users/loll/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/wrangler/wrangler-dist/cli.js:105892:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/Users/loll/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/wrangler/wrangler-dist/cli.js:108261:29)
      at async createWorkerPreview
  (/Users/loll/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/wrangler/wrangler-dist/cli.js:108276:17)
      at async start
  (/Users/loll/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/wrangler/wrangler-dist/cli.js:108722:16)
  {
    text: 'Received a bad response from the API',
    notes: [
      {
        text: 'Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and
  generating random values, can only be performed while handling a request.\n' +
          '  at line 0\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

#### Environment and versions

Fill out the following information about your environment.

* operating system: Mac OSX 12.3.1 (Arm)
* output of `wrangler -V`: 2.0.2
* output of `node -v`: v16.13.2
* content of `wrangler.toml`:

```
## Wrangler.toml

account_id = "asdfasdf"
workers_dev = true
zone_id = "asdfasdf"
compatibility_date = "2022-05-11"
main = "dist/index.js"

[env.sandbox]
name = "www-sandbox"
vars = { ENVIRONMENT = "sandbox" }
route = "*www.xxx.io/*"

[env.dev]
name = "www-dev"
vars = { ENVIRONMENT = "dev" }
route = "*www.xxx.io/*"

```

`package.json`

```
{
  "private": true,
  "name": "www",
  "version": "1.0.0",
  "main": "./dist/index.js",
  "scripts": {
    "format": "prettier --write '**/*.{ts,js,css,json,md}'",
    "eslint-fix": "eslint --fix **/*.ts",
    "set-env": "./env.sh $ENV",
    "build": "webpack"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/eslint-parser": "^7.14.3",
    "@babel/preset-env": "^7.14.2",
    "babel-loader": "^8.2.2",
    "dotenv-webpack": "^7.0.3",
    "eslint": "^7.27.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-webpack-plugin": "^2.5.4",
    "prettier": "^2.2.0",
    "source-map-loader": "^3.0.0"
  },
  "dependencies": {
    "@cloudflare/workers-types": "^3.10.0",
    "typescript": "^4.6.4",
    "dotenv": "^9.0.2",
    "wrangler": "^2.0.2",
    "eslint-plugin-babel": "^5.3.1",
    "webpack": "^5.60.0",
    "webpack-cli": "^4.9.1"
  }
}
```

**Comment by petebacondarwin** [comment]
Can you try running in "local" mode - we might get a more helpful error message...

```
wrangler dev --local
```

**Comment by petebacondarwin** [comment]
Oh! I see that you have no custom `build` section in your `wrangler.toml` file, even though it appears that your Worker code is being generated by `webpack` and outputting to `dist/index.js`. I don't suppose that this file has not yet been generated?
If you add the `build.command` setting to `wrangler.toml` then `wrangler dev` will run this command before trying to preview the Worker.

**Comment by igorbelikov** [comment]
@petebacondarwin I have the same problem and I have:
```
[build]
command = ""
```

also I tried:
```
[build]
command = "yarn build"
```

**Comment by threepointone** [comment]
@igorbelikov could you please file a separate issue? It looks to be a different error. Please share a small reproducible demo. From the look of the error, it appears you're not exporting a `default { fetch ()... }` handler? Are you using addEventListener instead? Please share logs and as many details as you can in a new issue.

**Comment by threepointone** [comment]
@petebacondarwin this doesn't appear to be a problem with finding an entry point. This kind of error usually happens when you call something like setTimeout outside the scope of a request. 

@ookangzheng It's concerning that you're saying this code was working on wrangler 1 and not wrangler 2. Could you share a repo with a minmal reproducible example? Remove as much code as possible that still leaves this error and we'd be happy to investigate further.

**Comment by ookangzheng** [comment]
Hi,

This issue has been resolved by removing webpack and switch to Parceljs v2 😅 

Cuz webpack obfs and minify javascript cuz that issue.

**Comment by petebacondarwin** [comment]
Thanks for the update. Did you know that as of 2.0.0 Wrangler will do bundling for you (using esbuild). So unless you are doing something custom, you could just point `main` at the actual source entry-point file.

**Comment by petebacondarwin** [comment]
It would be good to know what aspect of the webpack output made the code invalid as a Worker.

**Comment by petebacondarwin** [comment]
Closing as this issue appears to be resolved.
