### ISSUE TITLE
Error messages while importing node modules

### ISSUE THREAD

**Issue by Rauno56** [cloudflare/wrangler2#969]
### What version of `Wrangler` are you using?

2.0.2

### What operating system are you using?

Linux

### Describe the Bug

Importing native node modules is probably a mistake any newcomer is bound to do. The current error message:

```
The package "assert" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.`
```

Could tell how the user can set the `platform` option.

**Comment by threepointone** [comment]
Could add `node_compat = true` in your wrangler.toml and try? (Alternately, pass `--node-compat` as a CLI argument)

**Comment by threepointone** [comment]
We should add a better message for this, ofc.

**Comment by Rauno56** [comment]
Changes nothing for me. I guess it has to do with the fact that I'm running a Pages app?

My command: `npx wrangler pages dev public/`

**Comment by threepointone** [comment]
Oops that's right, we don't have node-compat for pages yet, sorry! Tracking here https://github.com/cloudflare/wrangler2/issues/890

**Comment by threepointone** [comment]
A workaround _for now_ would be to install polyfills, so you can install https://www.npmjs.com/package/assert into your package.json and it _should_ just work.

**Comment by petebacondarwin** [comment]
Closing as this is tracked at #890.

**Comment by Rauno56** [comment]
@threepointone, those specific polyfills(`assert`, `util`, `process`) have their problems and are outdated. With some edits they do work though. I'll wait for the flag, thanks!
