### ISSUE TITLE
🐛 BUG: Login doesn't work in WebContainers

### ISSUE THREAD

**Issue by d3lm** [cloudflare/wrangler2#971]
### What version of `Wrangler` are you using?

beta

### What operating system are you using?

Browser (Chrome Version 101.0.4951.54)

### Describe the Bug

I have tried to test the login after I have implemented a host specific callback URL (#952) and noticed that the callback URL doesn't work. It seems that the request is invalid. The URL in the address bar gets changed to:
```
https://dash.cloudflare.com/oauth/error?error=invalid_request&error_description=The+request+is+missing+a+required+parameter%2C+includes+an+invalid+parameter+value%2C+includes+a+parameter+more+than+once%2C+or+is+otherwise+malformed&error_hint=The+%22redirect_uri%22+parameter+does+not+match+any+of+the+OAuth+2.0+Client%27s+pre-registered+redirect+urls.
```
And the page shows `404 | We can't find the page you're looking for.`.

**Reproduction**
1. Visit https://stackblitz.com/edit/cloudflare-worker-examples-jca5ck?file=package.json
2. Wait for the install to finish
3. Type `wrangler login`

Could it be that Cloudflare does not accept this new redirect URL?

CC @threepointone

**Comment by threepointone** [comment]
@eidam said he'd have a look at this internally

**Comment by jahands** [comment]
Seeing the same issue in stackblitz :(

**Comment by penalosa** [comment]
Moving forward, we've decided internally that authentication from environments like Stackblitz will be purely through the use of API tokens, and the OAuth flow will explicitly not be supported. With that in mind, I'm closing this as `wontfix`
