### ISSUE TITLE
🐛 BUG: `wrangler publish` overwrites routes setup in Cloudflare Dashboard UI

### ISSUE THREAD

**Issue by tjclifton** [cloudflare/wrangler2#972]
### What version of `Wrangler` are you using?

2.0.3

### What operating system are you using?

macOS Monterey (12.1)

### Describe the Bug

Hello,

I have just migrated to wrangler 2 for one of my workers, and now whenever I publish the worker via `wrangler publish`, any routes I have created via the Cloudflare Dashboard under the "Workers" section for a given zone are overwritten by whatever I have in my `wrangler.toml` file. I deploy my worker to multiple different domains in Cloudflare, and have found doing it through the dashboard is the easiest way as opposed to adding many different domain patterns in the `routes` key in the `wrangler.toml` file (the worker serves a generic purpose for many websites I manage). I'm not sure if this is a supported use-case, but it seems like a bug if the dashboard UI supports this functionality, but it is overwritten the next time the worker is published. This was not the case with Wrangler v.1, just FYI.

Thank-you!

**Comment by threepointone** [comment]
Extremely sorry you had to face this, we should have communicated this breaking change better. You can achieve this by marking `workers_dev = false`, and also having no `routes`/`route` keys in `wrangler.toml` when you publish (You should then see `No publish targets for <name> (0.00 sec)` logged into your terminal). This won't overwrite any routes that you setup in the dashboard, and you're free to edit them there.

**Comment by threepointone** [comment]
I'm going to close this issue. We should work on making a breaking changes/workarounds doc, tracking here #973. Sorry again for the trouble.

**Comment by ajwootto** [comment]
Just ran into this and nearly caused production downtime by wrangler attempting to delete our custom-defined routes. If this is supposed to be the correct behaviour it should be called out very loudly in the migration documentation because it's a super dangerous behaviour change.
