### ISSUE TITLE
docs: Create Wrangler 1 -> Wrangler 2 breaking changes document

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#973]

**Comment by ajwootto** [comment]
I think this is an important thing to publish, it would have saved us from at least one production incident related to the behaviour change in the linked issue. After updating to wrangler 2, it tried to delete all of the routes we had defined manually in the dashboard which were left alone by wrangler 1, which would have left our worker unreachable in production. This is a major behavioural difference which is very dangerous to not have documented.

**Comment by KianNH** [comment]
Created https://github.com/cloudflare/cloudflare-docs/pull/5482 to address the previous comment, referencing https://github.com/cloudflare/wrangler2/issues/972#issuecomment-1125359729

**Comment by penalosa** [comment]
@petebacondarwin Is this covered by https://github.com/cloudflare/wrangler2/issues/973?

**Comment by petebacondarwin** [comment]
Yeah I think that doc is good enough.
