### ISSUE TITLE
🐛 BUG: non-standard ports are allowed in local and preview mode

### ISSUE THREAD

**Issue by eidam** [cloudflare/wrangler2#975]
### What version of `Wrangler` are you using?

2.x

### What operating system are you using?

Mac

### Describe the Bug

we should match the Workers runtime and throw an error/warning when fetch is used with non 443/80 port

related issue https://github.com/cloudflare/cloudflare-docs/issues/4299

**Comment by jfsiii** [comment]
I wonder if https://github.com/cloudflare/wrangler2/pull/992 addresses this

**Comment by petebacondarwin** [comment]
Yes I think that this has been addressed as far as we plan, with the only next step being to fix the actual bug in the runtime, which is outside of the scope of Wrangler but is being tracked in https://github.com/cloudflare/wrangler2/issues/1320
