### ISSUE TITLE
The package "stream" wasn't found on the file system but is built into node.

### ISSUE THREAD

**Issue by leadream** [cloudflare/wrangler2#985]
I need to use `jsonwebtoken` to generate access token in my worker. I got this error after importing this package.

> The package "stream" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

Here is my core code:

```js
import jwt from 'jsonwebtoken';

const secret = '*******'

export function generateToken () {
  let rawToken = {
    "sub": "*****",
    "name": "Hal Vimes",
    "iat": 1716239022,
    "exp": 1816239022
  }
  
  // sign the token
  let token = jwt.sign(rawToken, secret);
  console.log('token: ', token, '\n')
  return token
}
```

Where should I add "platform: 'node'" in my project?

**Comment by threepointone** [comment]
Could you try adding `node_compat = true` to your `wrangler.toml` and trying again?

**Comment by leadream** [comment]
@threepointone Not working for me. Got this error:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/12868055/168426687-00cbd1bd-dfe9-4c1f-ba20-9367f0b6651e.png">

Finally, I use `@tsndr/cloudflare-worker-jwt` instead of `jsonwebtoken` and it worked. Thanks anyway.

**Comment by threepointone** [comment]
Nice! The crypto polyfill isn't complete, and is likely to stay that way for a while. The workaround, as you discovered, is to use a library that's built for runtimes like Workers. Closing this issue, have a great weekend!
