### ISSUE TITLE
🐛 BUG: the value read from stdin should be trimmed

### ISSUE THREAD

**Issue by dhcmrlchtdj** [cloudflare/wrangler2#993]
### What version of `Wrangler` are you using?

2.0.3

### What operating system are you using?

linux

### Describe the Bug

I use wrangler on github action and set secrets in a non-interactive way
like this
```
$  echo 'some_value' | wrangler secret put 'TOKEN'
``` 

When I update from `@cloudflare/wrangler` to `wrangler2`, the TOKEN no longer what I expected.

expected: `TOKEN === "some_value"`
actual: `TOKEN === "some_value\n"`

---

`@cloudflare/wrangler` will strip all trailing whitespace ([code](https://github.com/cloudflare/wrangler/blob/v1.19.12/src/terminal/interactive.rs#L24)
but `wrangler2` return the stdin directly ([code](https://github.com/cloudflare/wrangler2/blob/wrangler%402.0.3/packages/wrangler/src/index.tsx#L172)

**Comment by threepointone** [comment]
Nice catch, we should fix this soon!
