### ISSUE TITLE
Error when trying to add a secret using wrangler 

### ISSUE THREAD

**Issue by dearcodes** [cloudflare/wrangler2#994]
`wrangler secret put PRIVATE_KEY ` 

Yields;
```
 ⛅️ wrangler 2.0.3 
-------------------

✘ [ERROR] Missing script name
```

**Comment by threepointone** [comment]
secrets have to be associated with a Worker. This is usually read from a `wrangler.toml` file in a project (which wrangler will look for either in the directory you call it, or any parent directory). Like @ecchochan pointed out, you can also pass a path to a custom config file), or can be explicitly passed with `--name <worker name>`.

**Comment by threepointone** [comment]
Closing this, but happy to discuss if there's a problem.

**Comment by petebacondarwin** [comment]
@allsey87 - created an issue to track that https://github.com/cloudflare/cloudflare-docs/issues/4892. I am sure that a PR would be welcome.
